### ISSUE TITLE
DecentDelegate application

### ISSUE THREAD

**Issue by hozzjss** [stacksgov/Stacks-Grant-Launchpad#120]
Background
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Trust

Delegators must trust the delegate to do the right thing and distribute rewards, with a contract you might alleviate a great deal of that trust, through a collateral paid in advance, and even with multisig wallets, you could get to total trustless stacking.

A delegate might have a reputation token for each cycle they complete with full transparency of each cycle.

App Stacking
small stacks locked in the contract from hundreds of stackers could mean a monthly payout to app developer, but with a contract you can easily down vote an app for being dishonest and not delivering, and might change the pox address without needing to first revoke the stx, and then delegate to somebody else, the process would be a simple election over the new pox address

Locked STX Liquidity

Since the contract would virtually lock the STX by taking it, and stacking it while logging how much a stacker is owed, a stacker might change the owner of that stake and in theory you might even use a fungible token just like stx-futures through it, then when distributing rewards (in STX) the contract would give that new stacker their new rewards according to their stake or how much fungible tokens they have

Project Overview
What solution are you providing? Who will it serve?
The contract code is almost complete for the first case study: DecentDelegate: a decentralized solution for stacking through collateral STX

decent-delgate.clar

Using this contract with a web app that interacts with it, deploys different contracts

Scope
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

A really big contract that handles each case study

A front end app that deploys different versions and interacts with it.

Budget and Milestones
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 9000$

I don't need money I might however need some STX that are to be locked into the contract, I am sure the foundation can inspect the contract first before depositing any STX, but that's my grant request, I'd be more comfortable using my contract than actual payment, even the minimum stacking for the next cycle is enough, I might also go to community stacking, if anybody wanted to support the project

M1: Case study collateral STX for stacking with a constant pox address

Delivery: April 1st

M2: App chains

Delivery: April 7th

M3: Locked STX liquidity

Delivery: April 14th

Team
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.
Just me
I am a front end and clarity hacker I have built large scale apps led teams, at Koinz and Pravica

Risks
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
actual stacks to go live with the project, this is a passion project of mine, whether I'm paid or not I'm gonna do it, you can take the contract and do with it what you want, if you wanna contribute please do, I could need some help building the app as I'm not free most of the time
I could absolutely use guidance or reviews from @jcnelson and @lgalabru

Community and Supporting Materials
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

This project might be incorporated later or at the same time with the evangelist stacking pool project with @friedger, @dantrevino, and @jennymith

**Comment by RaffiSapire** [comment]
Hey @hozzjss when you closed this it was removed by our system, so Jonathon is going in to try to retrieve the info you already input.

**Comment by hozzjss** [comment]
I was really confused by the closed label here and then the payment label on the old grant, so had weird signals tbh, but yeah I'll keep my hands off this time, and if you think we need to do a different issue I'm comfortable to do that

**Comment by hozzjss** [comment]
!m1_complete

**Comment by RaffiSapire** [comment]
Hi @hozzjss  please share M1 deliverables here?

**Comment by hozzjss** [comment]
I'm not sure that it has all the required stuff, but I think that's enough for us to go to milestone 2, [Contract code](https://github.com/hozzjss/cooperative-stacking/blob/master/contracts/decent-delegate.clar), I hope you take a look at it and let me know what you think and the missing parts that I should fill
[Testnet version](https://explorer.stacks.co/txid/ST22HQ6YT0NAHB42F6X8PGZVA70S2XNB7KF03ZABX.ddx-v1?chain=testnet)

In this milestone these problems are solved:

liquid stacked stx (DDX token) inspired by @jcnelson's stx-futures contract, that is used as a proof of hodl for the percentage of rewards a delegator is eligible to, and as a utility for these hodlers to distribute their rewards between peers so that those peers can redeem part of that reward, and as a way for exchanges to trade actual stx futures if they could tap into sip-10 which the contract implements.
Trust minimization mechanism or a collateral based stacking in which a stacker can just pay everyone upfront or with a fraction or something of that reward, the total reward is defined as part of the pool meta data, and the pool would be completed if and only if the stacker deposits the full rewards during the period of the cycle, when they do, they receive a reputation token that is not transferrable and only marks the accomplishment of the cycle being complete.
Reward distribution is now a responsibility of the DDX holder to redeem their rewards through calling a function on the contract, not only could they redeem their rewards once but multiple times as they come in when the stacker makes deposits, the first time the rewards are available are when stacking begins, then the hodlers can redeem the deposited collateral right away, stacking starts once the pool reaches its delegation goal of how much stx is needed that would be defined as part of the pool's metadata.

**Comment by jennymith** [comment]
Hey @hozzjss, quick clarifying question: Were you able to talk to other pool providers and find out if this contract is something they would want to implement for their own pools? If not, we recommend talking to at least 2 pool providers and sharing your learnings from your conversations with them before moving on to M2.

**Comment by hozzjss** [comment]
Got it!

**Comment by jennymith** [comment]
Hey @hozzjss checking in to see how progress on M2 is coming along. Let us know if you need any support in getting this milestone over the finish line!

**Comment by hozzjss** [comment]
!m2_complete

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
