### ISSUE TITLE
On-chain Accounting for Stacking Pools (Take 2b)

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#121]
**Background**
Users of stacking pools have to trust the pool admin to manage their rewards correctly. Transparency can help to increase the trust. Therefore, income and expenses should be collected on-chain. This will create transparency as well as help to automate stacking pool operation in the future. This is the next step to make stacking pools more autonomous. Friedger Pool and other community stacking pools should benefit from it.

**Project Overview**
The project is about writing a smart contract and a web interface that allows users and pool admins to submit and view tx of stacking pools that payout rewards in stx as well as perform some pool admin tasks. Users and pool admins have the same privileges because the submitted data is verified on-chain.

The project will collaborate and use results from related work by the following projects:
* [decent delegate](https://github.com/hozzjss/cooperative-stacking)
* [stacks-open-oracle](https://github.com/psq/stacks-open-oracle)
* [bitcoin library](https://github.com/jcnelson/clarity-bitcoin)
* [pool tools](https://gitlab.com/riot.ai/clarity-pool-registry)
* [boomboxes](https://explorer.stacks.co/txid/ST314JC8J24YWNVAEJJHQXS5Q4S9DX1FW5Z9DK9NT.boomboxes-v1?chain=testnet)
* [xverse](https://explorer.stacks.co/txid/SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33.xverse-pool-v1?chain=mainnet)
* [stacking.club](https://github.com/stacksgov/Stacks-Grants/issues/88)

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
Components:
* There will be two smart contracts
    * Auditing contract
        * submit btc tx for rewards received by the pool's btc reward address, the corresponding stx value of the reward will be determined by an oracle, the value is stored both in stx and btc.
        * submit btc tx for btc withdraw from pool's btc reward address, the corresponding stx value of the withdraw will be determined by an oracle, the value is stored both in stx and btc.
    * Admin contract
        * delegate stx that are immediately locked by the users themselves
        * aggregate commit the pool 50 blocks before the start of the next cycle
        * request stx rewards payouts proportionally to their delegated stacked stxs, the total reward amount is retrieved from the auditing contract
* The web app will focus on functionality and reuse design and app architecture of Speed Spend/Pool Registry/Send Many
    * uses `connect` library for tx signing (requires users to use Stacks Wallet for Web)
    * show btc and stx of the submitted txs
    * provide UI to call the smart contract functions
    * provide UI to allow the smart contract to manage the users' delegation
* User education
   * update pool.friedger.de and include information how to use the smart contract
   * answer questions via email, discord, twitter (and occasionally other social media)
* Test on Testnet 
* Operate Friedger Pool until it runs autonomous. This includes customer services, maintaining the website, trading BTC/STX, accounting, legal advice.

The project will be successful when 
1. users participate in delegated stacking through the smart contract in cycle #11.
2. the pool contract meets the static stacking minimum (min_increment_ustx) and can join Friedger Pool's btc reward address.
3. rewards are claimed and received by users through the smart contract.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $12000 

M1: Smart contract for submitting btc transactions + web app to submit and view txs (1 week)
$1500  development clarity + web
$1500 operating costs Friedger Pool

M2: Extended smart contract with pool operations + web app + testnet test (1 week)
$5369
* development clarity + web
* community management for testing
* operating costs Friedger Pool

M3: Extended smart contract with pool operations + web app + testnet test (1 week)
$3631
* development clarity + web
* community management for testing
* operating costs Friedger Pool

M4: Invite pool members to use the contract for the next cycle. (1 week)
$3000
* user education
* operating costs Friedger Pool

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Friedger Müffke,  pool administrator of [Friedger Pool](https://pool.friedger.de),

I have one open grant (https://github.com/stacksgov/Stacks-Grants/issues/84) that only requires a bit of communication with other pool admins over the next weeks.

I am looking for 
* community manager
* testers
* smart contract testers

**Risks**

The project depends on the successful submission of the Stacks Wallet for Web through the Hiro team. The project can only be successful once the wallet is published on the corresponding browser extension sites.

The verification of btc tx is not yet well tested in production. It can be too difficult or impossible to do it on-chain. Therefore, M1 focus on this part of the proposal.

**Community and Supporting Materials**
This is continued work for Friedger Pool and related community stacking pools, following #52 and #84 

This grant is a duplicate of #92 for easy accounting :-)

**Comment by friedger** [comment]
The first bitcoin transaction has been verified on the stacks testnet. I wrote a summary here: https://app.sigle.io/friedger.id/zwmiYGAH1TvqQnoiKGqSV
The web app is part of [Speed Spend](https://speed-spend.org/pool-audit).
This complete m1

**Comment by friedger** [comment]
!m1_complete

**Comment by friedger** [comment]
!m1_complete

**Comment by jennymith** [comment]
Congratulations @friedger! Looking forward to M2. Just keep us posted on your work involving the price oracle.

**Comment by friedger** [comment]
Update M2 - week 1

Bitcoin Testnet suffered from a Blockstorm and therefore, our testing was postponed.

Price finding via oracle has been improved to fall back to previous blocks (up to 3) in case of flash blocks or as a last resort to the last known price. The contract is deployed with a call to the price oracle such that there will always be a last known price. - With the launch of .btc domains we saw that the oracle couldn't register prices for more than 5 days.

Discord server for testing community is ready,  @OmurCataltepe joined to support community during testing.

Next steps:
- improve web ui
- prepare educational material

**Comment by friedger** [comment]
Update M2 - week 2

Bitcoin Testnet is working better.

More testing happened, UI has been improved.

As part of testing, a trustless BTC/STX swap has been implemented and tested:
https://twitter.com/fmdroid/status/1410018264982470663

Next steps:
* invite testers to discord server
* prepare educational material

**Comment by friedger** [comment]
!m2_complete

**Comment by friedger** [comment]
Milestone 2 has been split into 2 milestones to reflect the two payments for it. The previous Milestone 3 has been renamed to Milestone 4.

Looking forward to the new testnet!

**Comment by friedger** [comment]
Testnet is running, but we still don't have the possibility to test stacking (https://github.com/blockstack/stacks-blockchain-api/issues/664)

I tested the bitcoin clarity library on mainnet with BTC-NFT catamaran swap: https://twitter.com/fmdroid/status/1418533936498724874

**Comment by friedger** [comment]
I hit a road blocker. I am missing a way in clarity to find out and verify during which reward cycle a bitcoin transaction happened. 

This is needed for the payout of rewards. As it looks to me, that a solution can only happen with Stacks 2.1 (see https://github.com/blockstack/stacks-blockchain/issues/2784)

**Comment by friedger** [comment]
!m3_complete

With the current blocker, here is a review from the scope and what I have achieved.

## Contracts
>    There will be two smart contracts
>        Auditing contract
>           submit btc tx for rewards received by the pool's btc reward address, the corresponding stx value of the reward will be determined by an oracle, the value is stored both in stx and btc.
>            submit btc tx for btc withdraw from pool's btc reward address, the corresponding stx value of the withdraw will be determined by an oracle, the value is stored both in stx and btc.

There are two auditing contracts in https://github.com/friedger/clarity-friedger-pool/tree/main/contracts:
* friedger-pool-audit.clar 
* friedger-pool-wrew.clar
The first contract verifies rewards txs and reports the value of the rewards together with the price received from an oracle.
The second contract verifies rewards txs and reports the value of rewards together with the price received from an oracle and mints wrapped rewards token, sending them into a depot/vault contract for later payouts.

The withdraw txs from the pool were too large (500+ ins) to verify them on-chain. Therefore, I decided to use the wrapped rewards token and audit these tokens instead of bitcoins directly. They map 1 sat to 1 reward token.

>   Admin contract
>            delegate stx that are immediately locked by the users themselves
>            aggregate commit the pool 50 blocks before the start of the next cycle
>            request stx rewards payouts proportionally to their delegated stacked stxs, the total reward amount is retrieved from the auditing contract

This is implemented in the Boombox contract https://gitlab.com/riot.ai/clarity-boom-pool/-/blob/master/contracts/boomboxes-12.clar. The contract allows to delegate stx with immediate locking and to do the aggregate commit by any user, no interaction by the pool admin.

The payout can't be done trustless for now due to the blocker about cycle to reward mapping.

## Web UI

>    The web app will focus on functionality and reuse design and app architecture of Speed Spend/Pool Registry/Send Many
>        uses connect library for tx signing (requires users to use Stacks Wallet for Web)
>        show btc and stx of the submitted txs
>        provide UI to call the smart contract functions
>        provide UI to allow the smart contract to manage the users' delegation

The UI for auditing with price oracle is implemented as part of Friedger Pool on https://pool.friedger.de/members
The UI for managing the user' delegation is implemented in https://boom.money

Speed Spend has also some UI for verifying btc transactions and doing stack aggregation commit transactions: https://www.speed-spend.org/pool-audit

I contributed to stacks-blockchain-api to simplify the auditing process (https://github.com/blockstack/stacks-blockchain-api/issues/675)

>    User education
>        update pool.friedger.de and include information how to use the smart contract
>        answer questions via email, discord, twitter (and occasionally other social media)

The details about how to use the smart contracts are described in these articles:
* Instructions on Testing APF (https://app.sigle.io/friedger.id/dAZao4q9C22DL76zHsF5-)
* Trustless Swap: NFT vs $BTC (https://app.sigle.io/friedger.id/A-l0d8h0Bq7uEGTWl004B)
* Boomboxes and Friedger Pool (https://app.sigle.io/friedger.id/q-UHdutKP7wxrQm72QtUy)
* An Application of Clarity Bitcoin Library (https://app.sigle.io/friedger.id/zwmiYGAH1TvqQnoiKGqSV)

I run a discord server for testing and answer emails, twitter, discord, reddits daily.

## Testing
>    Test on Testnet

I did a few tests on testnet to verify the clarity-bitcoin-library before the testnet reset. Since then, it is not possible to test stacking.

I did more tests on mainnet with the 3 Catamaran swaps and 1 Catamaran mint that all use the clarity-bitcoin-library.

## Operation
>    Operate Friedger Pool until it runs autonomous. This includes customer services, maintaining the website, trading BTC/STX, accounting, legal advice.

Friedger Pool is successfully participating in stacking since cycle #3 without any missed cycles. In cycle 13, we stacked 12,2m STXs for 1138 members (see details https://pool.friedger.de/cycles/)
https://app.sigle.io/friedger.id/dAZao4q9C22DL76zHsF5-

##  What is left to do?
> M4 user education

During cycle 13, I will assist users to use the smart contract, to report btc tx and claim their rewards in wrapped reward tokens at the end.

## What was not achieved?
The fully automated stacking pool could not yet be realized. It is not possible to support btc transactions that happen during flash block. Furthmore, btc transactions can't be linked to the reward cycle trustlessly.  

The relevant issues are:
* get burn block height in clarity - problem to identify reward cycles: https://github.com/blockstack/stacks-blockchain/issues/2784
* get any burn block in clarity - problem flash blocks: https://github.com/blockstack/stacks-blockchain/issues/2663

## The future (new grant maybe)
Friedger Pool will release a wrapped reward token that can be swapped against STX trustlessly.

**Comment by friedger** [comment]
!m3_complete

**Comment by friedger** [comment]
The first tx is not listed on https://pool.friedger.de/members (https://github.com/friedger/stacking)
![Screenshot from 2021-07-30 22-37-23](https://user-images.githubusercontent.com/1449049/127729415-a8172831-b4ec-4380-b433-47491297ba51.png)

**Comment by friedger** [comment]
Update: 
* all possible BTC reward transactions have been verified on the stacks chain. 
* payouts for cycle #14 can now be claimed by users. 

Full report here: https://app.sigle.io/friedger.id/MA3mBt0f-fwK2GxxG4JWY

I am still continuing to educate users about the impact.

**Comment by RaffiSapire** [comment]
Thanks @friedger we reviewed M3, great work! will disburse for M4 today.

**Comment by friedger** [comment]
Until today 0.5% of the reserved wrapped rewards have been claimed by 12 users. Considering that there is no use case for the wrapped rewards so far and that users with hardware wallets can't claim the tokens, we could at least show that it works.

As the final part of M4, I published an article about using the wrapped rewards for accounting and for other services like catamaranswaps.org:

https://app.sigle.io/friedger.id/sJuX84nlvLYEGfUTZVfZA

This completes M4. 

Nevertheless, I will continue to help users using the wrapped rewards and running the pool of course.
I am in contact with Hiro about the oracle for block heights, ideally this will run on my threefold node.

**Comment by friedger** [comment]
!m4_complete

**Comment by jennymith** [comment]
Hi @friedger thanks for your hard work on getting this grant over the finish line, especially considering all the challenges you ran into! We can mark this as complete cc: @RaffiSapire @jhammond2012.

**Some feedback for continued/future work:**

It seems that the low redemption rate for wrapped rewards stems from the difficulty of the process. We understand that you won't be able to reasonably improve this process until Hiro pushes certain upgrades to its wallet. In the meantime though, perhaps you could consider the following:

- Hosting regular live demos on how to claim rewards for your community
- Looking into sponsored transactions

We also encourage you to share the tools you've built with other pool operator/third parties. The tools you've developed have really advanced the decentralization of Stacking pools--all operators and Stackers could really benefit from implementing and using them.
