### ISSUE TITLE
Wise - Stacks tools for mobile dapps

### ISSUE THREAD

**Issue by Pravica-Inc** [stacksgov/Stacks-Grant-Launchpad#134]
**What problems do you aim to solve? How does it serve the mission of a user owned internet?**

There is a problem with building DApps on mobile iOS/Android native or cross-platform on top of Stacks infrastructure and the current unsupported community SDKs are outdated, and would not have the stacks 2.0 support unless much much work is put into these SDKs (almost a revamp) closing that process into an open source app for auth/payments/contract interactions would make it much much easier to integrate through experiences the likes of Metamask and TrustWallet.

**Project Overview**

We came with a solution to ease the user’s journey authenticating through Stacks BNS. With a single tap the users and dApp developers could access the plethora of potential stacks blockchain features and services, the idea of this authenticator is, The user will login with his wallet one time using WISE, and every time any other apps try to authenticate it will ask the user’s permission to generate the identity for the current usage app, so basically, the flow is:

- The DApp requests the appPrivateKey from WISE
- The user will review the app data within WISE interface and then decide to either grant or reject access request by that app to use any of his currently set up identities on WISE.
 - WISE will generate appPrivateKey for the app, once it’s generated it will redirect the user to the app with the required data.

![image](https://user-images.githubusercontent.com/61974592/121220611-0a10a280-c885-11eb-8b52-ef4bfc965214.png)

**Scope**

Basically, developers who are building dApps will no longer need to use deprecated SDKs, to build their apps on top of Stacks, they will focus on their app journey and not the hassle of creating a better UX for their authentication, and STX transfers and contract interactions in the future.

We will not stop from here, we’re looking further to implement more features for this product, our vision is to make life easier for developers, the second phase of this app is to provide the identities real information which is not found in the current connect ux, such as avatar, full name, social media and more personal information the user will decide what are the information the app asking takes.

Also, we’re planning to implement STX transfer where users will be able to transfer STX from other apps through Wise.
And more features.

Why Wise?
- W > Wallet: Fully wallet functionality, with a better UX and usage, users will be able to transfer/receive STX, NFTs and so on
- I > Identities: Users will be able to generate new identities, and authenticate with these identities to other apps
- S > Stacks: We'll implement Stacks functionalities such as Stacking pool, Delegations, etc..
- E > Encryption

[WISE](https://wiseapp.id/)

**Budget and Milestones**

The total requested budget is $17,500 for the next milestones
Applying for a grant. We expect to spend more than that on development efforts over the next couple of months. Milestone would be to be able to have a basic working version of the project. The project will be split over the following milestones.

**M0: (2 months / March 2021) (DONE)**

- Designing architecture for the app workflow 
- Designing UI/UX for WISE
- Rebranding from Pravica authenticator to WISE
- Initiate Android/iOS projects for developing WISE
- Implement UI design through both iOS and Android
- Implementation of authenticating wallet logic (iOS/Android)
- Implementation of redirecting and giving permission logic (iOS/Android)
- Handling testing and secure apps from dangerous URL schemes and re-routing apps frauds
- PIN code for securing WISE
- Go to open source for the community

**M1: (June 2021) grant -  $1,000**
- Implementation of JS library for (Cross-platform and PWA apps) to access WISE
- Go to open source for the community

**M2:  (Aug 2021) grant -  $4,000**
- Wallet Research and Validation.
- Designing Wallet UI/UX.
- Wallet Implementations(Send/Receive/NFTs) 
- Go to open source for the community

**M3: (Jan 2022) grant $4,500**
- Utilizing Stacks tools and research
- Stacking through contract call
- Stacking through delegated pools
- Go to open source for the community

**M4: (Apr 2022) grant $6,000**
- iOS Native SDK for native apps that accessing WISE
- Android Native SDK for native apps that accessing WISE
- Go to open source for the community

**M5: (Jun 2022) grant $2,000**
- Code cleanup and JS docs
- Docs

NOTE: WISE will be compatible with Stack JS.

From here we can start asking the community what features and requirements they would like to implement next, we will not stop from here, we’re targeting Wise to be the standard tool for mobile apps for Stacks apps

**Team**

Pravica team

**Risks**

None was found till now according to these milestones.

**Comment by Pravica-Inc** [comment]
We published this grant 3 month ago [Authenticator](https://github.com/stacksgov/Stacks-Grants/issues/134).
We continued the plan and kept working on it, and rebranding Pravica Authenticator to WISE.

Since 15 May we published Wise on the stores and we got 250+ users download and more than 400+ id.stx created using Wise

We're looking forward to collaborate with Stacks and fast the development in the mobile apps

**Comment by RaffiSapire** [comment]
Hi @Pravica-Inc 

1.  We did pass on the Authenticator previously. What changed since then and why would it be more useful now?
2. You mention you have an app thats done in this application, but its just not open source. Making something built previously open isn’t a fit for the grant program. It's important that we are funding future work. Can you clarify?

**Comment by Pravica-Inc** [comment]
Hi @RaffiSapire 

The answers to your questions are included already in our proposal, it seems that you didn't have enough time (despite replying after about 10 days of our proposal) to read our proposal carefully and review the previous one and do a quick comparison to extract the main differences in order to build a good vision that may lead you to the proper decision. [end of text]

Here is a sample proof of what I am saying, I will get the answer to one of your questions from inside of our proposal.

Your question:

"You mention you have an app thats done in this application, but its just not open source. "

If you can review our proposal carefully, you can get the following information that can help you to clarify this concern.

We didn't ask to fund the M1 that already DONE, because we know exactly the rules of the grant program, you can note that M2 is the first one to be funded and the main purpose of this milestone is to put the work done in open source, and there is a huge difference between completing a task and putting this task in an open-source format which requires a proper work of code cleaning, documentation and many other sub-tasks to care about.
We just mentioned the sub-tasks that already done in M1 as a kind of "proof-of-work" to help you evaluate the amount of work.

WISE is the ONLY Mobile app solution available now in both (iOS and Android) on Stack to allow users to create/restore their Stacks ID to use these IDs to authenticate in a mobile app built on Stacks easily and securely.

**Comment by RaffiSapire** [comment]
Hi @Pravica-Inc - why don't you join one of the open office hours to discuss your grant, it seems like there has been some miscommunication on the back and forth here. Let’s get on a call to clarify. The office hours are Tuesday 3:30-4pm EST or Thursday at 9 am EST, on discord. Or you can ping Jenny if she hasn't reached out to talk if those times don't work this week.

**Comment by Pravica-Inc** [comment]
Thanks @jennymith and Marvin for arranging the following up call, we discussed all related topics about the proposal and we did clarify the concerns. 

We have updated the proposal to reflect the approved points related to the open-source timing and Stacks tools (Stacks JS) that is being used in the development process for the final WISE product.

Looking forward!

**Comment by jennymith** [comment]
Hi @Pravica-Inc, this grant is approved cc: @RaffiSapire

**Comment by Pravica-Inc** [comment]
Thanks @jennymith, @RaffiSapire and Marvin ... Let's build!

**Comment by Pravica-Inc** [comment]
Milestones names and timing has been updated after grant approval ... working in M1 now

**Comment by Pravica-Inc** [comment]
!m1_complete 

https://github.com/PravicaInc/wise-js
https://github.com/PravicaInc/Wise

**Comment by RaffiSapire** [comment]
Thanks! We are disbursing your payment for M2 this week.

**Comment by jennymith** [comment]
I see this grant was updated on 08/16 in Total Funding Ledger but just want to confirm that M2 was indeed disbursed @RaffiSapire @jhammond2012.

**Comment by jhammond2012** [comment]
> I see this grant was updated on 08/16 in Total Funding Ledger but just want to confirm that M2 was indeed disbursed @RaffiSapire @jhammond2012.

@jennymith I had a check and it is funded.

**Comment by jennymith** [comment]
> !m1_complete
> 
> https://github.com/PravicaInc/wise-js https://github.com/PravicaInc/Wise

Hi there @Pravica-Inc, how is M2 coming along? I see that M2 was original planned for completion in September. Do you need any support moving your grant forward?

**Comment by Pravica-Inc** [comment]
Hi @jennymith , M2 is almost done but we still need to solve a technical issue ([here](https://github.com/blockstack/stacks.js/pull/1151)). Once solved, we will close M2 and update the roadmap accordingly

**Comment by Pravica-Inc** [comment]
!m2_complete

The identity retrieval issue has been solved temporarily 

WISE new UX/UI

https://www.figma.com/file/9sYiwYKCFmASav7tHFlSd5/WISE-UI?node-id=729%3A69

Roadmap has been updated!

**Comment by Pravica-Inc** [comment]
!m2_complete

**Comment by Pravica-Inc** [comment]
> Thank you for completing M2. The grant committee will review and confirm completion or send feedback within a week

Hello @jhammond2012 and @RaffiSapire 

Looking forward to your help to close the M2 and start the M3  .. we submitted the closing for M2 23 days ago.

**Comment by jhammond2012** [comment]
Hi @Pravica-Inc I will forward this to the correct individuals. Sorry for the delay.

**Comment by Pravica-Inc** [comment]
> Hi @Pravica-Inc I will forward this to the correct individuals. Sorry for the delay.

Thanks @jhammond2012  .. Looking forward!

**Comment by Pravica-Inc** [comment]
> > Hi @Pravica-Inc I will forward this to the correct individuals. Sorry for the delay.
> 
> Thanks @jhammond2012 .. Looking forward!

Hello @jhammond2012  .. can you help us to accelerate the reviewing and closing for M2 ? we are on hold since Jan 14th .. Thanks for your support

**Comment by vanesvibes** [comment]
@Pravica-Inc Vane here! I am supporting the Grants in updated information. Could you let us know your discord username?

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
