### ISSUE TITLE
Enable User choice of Gaia hub to the current Web Wallet based onboarding of users to apps

### ISSUE THREAD

**Issue by HariniRajan397** [stacksgov/Stacks-Grant-Launchpad#139]
**Background**
What problems do you aim to solve? How does it serve the mission of a user-owned internet?
Currently, during onboarding of new users to apps,  they are assigned a default storage through Gaia hub hosted by Hiro PBC. This enables devs and users to use Stacks apps without worrying about storage. 

However,  one of the important parts of Stack’s mission is to empower users to make their own choice regarding where to store their data.  By this ownership of storage, users are in control of their data - not by an app developer or a platform provider. 

In Blockstack Browser, this problem was solved by enabling application developers to include a prompt for users to select their own storage. Refer to the[ forum post here](https://forum.stacks.org/t/user-choice-of-gaia-hub-now-available-during-onboarding/7026), Currently, this part is not available in the current Web Wallet-based onboarding of users to apps. 

This grant request is to bring back the user-selected storage to the Web Wallet extension. By this, the user-owned Internet is available to end-users. 

**Project Overview**
What solution are you providing? Who will it serve?
We are proposing a solution similar to the one implemented during the Blockstack Browser period. This solution is aimed to provide an option to application developers to enable a user-selected storage prompt in Gaia similar to the below snapshots but in web wallet extension. 

![image](https://user-images.githubusercontent.com/65052776/122291224-96911580-cec2-11eb-8b79-43d75178a59f.png)

Bringing back this feature in the latest connect and web wallet helps the new users to the Stacks environment to select their own storage, which puts them in complete control of their data. Also, this helps the application developers to enable the user-selected storage for their users. 

**Note:** This will be currently applicable only for new users. Migrating existing user's data to the new hub is not covered as part of this grant. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
This project is aiming to bring back the functionality of user-selectable storage. Reference [Github issue here](https://github.com/blockstack/stacks-wallet-web/issues/1145). 

The changes have to be made in the below packages.

- @stacks/auth 
- @stacks/storage 
- **@stacks/profile**
- @stacks/common 
- connect /web-wallet .

Steps involved: 

1. Once the user logs in, the auth request gets constructed , currently, this is being passed to the default Gaiahub. This has to be updated to include the user-selectable Gaia hub.
2. The connect/web wallet has to be enabled to parse this value. 
3. The authresponse should include the Gaia hub URL. 

From the UI end, the user should be able to enter the details of their own Gaia hub. This has to be enabled in the web wallet extension UI as well. 

Note: The users can set up their Gaia hub in AWS referencing the [Stacks doc](https://docs.stacks.co/storage-hubs/amazon-ec2-deploy). 

The final deliverable will be an updated web wallet that allows users to select their own storage. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.
**Total Grant Request:**  5000$

**M1: 3 weeks starting July 6th** - 500$

Wrap up the design and get the approval from Hiro UI/UX team 
Deliverable : Design analysis doc including the package and file change

**M2:  3 weeks** - Implement the changes in Stacks.js -2000$

Deliverable: Update the related packages @stacks/auth , @stacks/storage, @stacks/common, @stacks/profile, @stacks/keychain . Also, do sanity test around  the dependent packages. 

**M3:  3 weeks** -  Make the corresponding UI changes and provide a beta build for testing - 2000$

- create UI mockup
- Get approval from Stacks UI/UX team 
- Implement UI changes in stacks web-wallet 

Deliverable : Build for beta testing . 

**M4 : 2 weeks** - Release the final update (fixing issues from beta testing(if any) and also provide the corresponding updates to the Stacks doc. - 500 $

Deliverable :

-  Final Pull Request incorporating this feature
-  Update the stacks doc corresponding to the same changes. 
            
**Team**
Who is building this? What relevant experience do you bring to this project? Are there skill sets you are missing that you are seeking from the community? Please share links to previous work. 

BlockSurvey team - https://blocksurvey.io

1. Raja Ilayaperumal
2. Harini Anantha Rajan

Note: UI/ UX Design guidance is given by the Hiro Team ( UI/UX team). 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
No Risks as of now predicted. 

**Some limitations to this feature**

1. This will be tested with AWS storage for now. 
2. This grant will enable only the new users to select their storage. 
3. This grant is not focused on the enterprise use cases. This is focused on end-user selection.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan with the community over time and as the final deliverable?
There are active Github issues related to the same given below:

1. https://github.com/blockstack/stacks-wallet-web/issues/1145

 2. https://github.com/blockstack/connect/issues/82 
 
 Community interests are surrounding the same . Active apps interested in this implementation include, Team Risidio, XorDrive.
 
 Attaching Discord references for community interest :
 https://discord.com/channels/621759717756370964/750467085720617031/854702543417245756
 https://discord.com/channels/621759717756370964/621759718192447502/851562573198786591
 https://discord.com/channels/621759717756370964/623217767356694547/838475130723893329
 https://discord.com/channels/621759717756370964/623217767356694547/837643387208335390
 
 We will be actively updating our developments as per Milestones in the grant as well as in the GitHub issue https://github.com/blockstack/stacks-wallet-web/issues/1145.

**Comment by Deliver88** [comment]
Hello, thanks for the proposal @HariniRajan397 ,

I totally agree with this.  Evaluating using Stacks instead of classical approaches the argument of the user data ownership plays a decisive role. Moreover, this is also a selling argument looking to use Stacks for commercial purposes to increase the trust. In contrast to that, the integrity and confidentiality of the user profiles are given through the blockchain; therefore the user choice of Gaia hub will ensure and increase the data ownership and thus the acceptance from the user side.

**Comment by SmartMirlo** [comment]
This is an important piece for users to decide about their data management. I would like to see it implemented: it provides an original feature that enhances the Stack's mission of a user owned Internet.

**Comment by Deliver88** [comment]
I would like to add one more thing. The Gaia hub choice opportunity will relax the situation in case having a huge amount of data, for e.g. from a dApp relies on Stacks with millions of users. It could give the dApp operator the ability to deploy its own Gaia hub infrastructure, for sure when the users would like to use it.  

One additional use case enabled through own/distributed Gaia hubs might be edge-computing and edge-intelligence. Process the data there where it arises and resides to enhance the user experience.

**Comment by markmhx** [comment]
I'd love to see the BlockSurvey team work on this with the support of a grant 👍

**Comment by RaffiSapire** [comment]
Hi @HariniRajan397 this is approved and we are excited to see it built! 

Would love to see if hosting/provisioning hubs could be explored as part of this.

**Comment by HariniRajan397** [comment]
Thank you @RaffiSapire ! Regarding hosting/ provisioning hubs, I would like to discuss this with you or another member of the grants team to understand the proper expectations/scope. Kindly let me know if we can have a discussion tomorrow during the Stacks grants office hours. Thank you very much!

**Comment by HariniRajan397** [comment]
No worries, and thanks for keeping me updated, @RaffiSapire! Meanwhile, Alex contacted me yesterday, and we're meeting today to talk about hub configuration and provisioning.  Thank you kindly for your assistance! !

**Comment by RaffiSapire** [comment]
Hi @HariniRajan397  - can you try the onboarding flow here and let us know if you are able to sign up and then receive email with docusign?

**Comment by HariniRajan397** [comment]
@RaffiSapire, sure! Thank you very much. We had a question about the form, so we contacted Jenny! Once our query is resolved, we will complete the onboarding flow.                                                                                                                                                 Meanwhile, I would like to provide an update on my meeting with Alex. We both agreed to proceed with the grants as-is. At the application level, we envision hub provisioning to be done on a need basis and that will be taken as the next step post the completion of the grant. Please let me know if you require anything further from my end.  Thank you very much for the assistance.

**Comment by HariniRajan397** [comment]
@RaffiSapire Wilson has signed the contract, and please note that, as part of the initial grant update, we will begin Milestone 1 on July 6th. Please let me know if you have any concerns. Thank you kindly.

**Comment by RaffiSapire** [comment]
Hi @HariniRajan397 I've sent you an invite to be added to bill.com, where I'll disburse payment.

**Comment by wilsonbright** [comment]
Hi @RaffiSapire, I'm not able to add India to a location in Bill.com. It looks like it is only for the US. Let me know if there is an alternative way.

**Comment by HariniRajan397** [comment]
Dear Team, A couple of updates. Please note that M1 has been extended to three weeks due to the wallet analysis taking longer than anticipated. We've also been in touch with the UX team, and we'll be meeting with them on Monday to explain the findings, get their feedback, and finalize the scope. Thank you.

**Comment by HariniRajan397** [comment]
Dear Team, A couple of updates. Please note that we are wrapping up M1 today. We have created the rough design analysis doc  that includes finalized scope details ,proposed design changes and open questions which we've submitted to the UX team for approval here https://github.com/blockstack/stacks-wallet-web/issues/1145#issuecomment-887786359.
We intend to validate the proposed changes and address the unknowns/open questions with the help of the UX team. We'll move on to M2 after that's done. We'll keep you informed as things progress. Thank you very much.

**Comment by RaffiSapire** [comment]
When you are done with M1 type !M1_Complete

**Comment by HariniRajan397** [comment]
> 
> 
> When you are done with M1 type !M1_Complete

Sure, @RaffiSapire! On Wednesday, we'll evaluate the design analysis with the UX team. I'll mark M1 as finished once that's done. I'll let you know as soon as I have further information. Thank you.

**Comment by HariniRajan397** [comment]
!M1_Complete

**Comment by jennymith** [comment]
Hi @HariniRajan397, hope this grant is going well! Any updates to share on M2?

**Comment by HariniRajan397** [comment]
> Hi @HariniRajan397, hope this grant is going well! Any updates to share on M2?

Dear Jenny & team ! Please accept my sincere apologies for the delay in the update. I've been unwell, so it's taking a little longer than planned. I'm currently reviewing the codebase's most recent updates and re-evaluating the changes that are required. We'll be able to provide a more detailed update and an improved timeline by the end of next week. I appreciate the entire team's excellent support thus far, and I greatly appreciate your understanding. Thank you very much.

**Comment by HariniRajan397** [comment]
Dear Team! Please find below the most recent M2 update. I've been re-evaluating the Stacks.js package updates and beginning work on a new "enable Gaia selection" parameter. Because changes must be made across multiple packages such as 1)@stacks/wallet-SDK, 2)@stacks/auth, 3)@stacks/common 4)@stacks/storage, the current updated completion estimate for M2 is 4 weeks, based on a thorough consideration of buffer time. As things progress and if anything changes due to unanticipated circumstances, we'll keep the team informed. Thank you so much for your help and encouragement. Kind Regards.

**Comment by HariniRajan397** [comment]
Dear All,

I'm taking a break for a few months due to personal health difficulties. As a result, I will no longer be able to continue with the grants, unfortunately. Hence, as discussed with Jenny,I am handing over all grant-related activities to Blocksurvey's tech-head/co-founder Raja Ilayaperumal (raja@blocksurvey.org). Raja will take it forward.

 Please accept my heartfelt apologies for the delay, and thank you for your tremendous support and patience. I really appreciate it. cc @jennymith @wilsonbright @markmhx 

Regards,
Harini

**Comment by will-at-stacks** [comment]
@HariniRajan397 we are very sorry to hear you are confronted with a personal health issue.  We wish you all the best.  I will contact Raja and see what the next steps are.  Please take care of yourself.  Best, Will

**Comment by ilayaperumalraja** [comment]
Hi @will-at-stacks, I have started to work on this. I will keep update as i make progress. Thanks.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will

**Comment by Deliver88** [comment]
Hello @will-at-stacks , where can I find this grant at [grants](https://grants.stacks.org/)? What is the current state of this work? Thank you.
