### ISSUE TITLE
A simple way to set royalties for NFTs 

### ISSUE THREAD

**Issue by grigerny** [stacksgov/Stacks-Grant-Launchpad#140]
**Background**
Our platform for minting and manage NFT businesses requires us the ability to set various royalty percentages and create unique tokenomics when NFTs are sold 2, 3, 4 times etc
As NFTs become more and more popular, the ideal scenario is that the best art is propped to the top. In order to do that, we believe that royalties are an immensely important part of rewarding great artwork. We want to give control over royalties back to the creators in a way that is easy to manage using a frontend admin panel.  

**Project Overview**
We are providing a platform for galleries, digital agencies and owners of multiple digital art to mint and manage NFTs. Our technology has a similar user interface as a common cloud storage system where users can upload and mint NFTs by simply Right Clicking a file. 

- It serves any content creator who is interested in minting NFTs but does not know how. 
- It serves artists with large libraries of work who want to schedule their mints over time
- It serves collectors who can organize their NFTs 
- It serves marketing companies who can manage multiple artists and their artwork
- It serves ad agencies who can create NFTs for their campaigns and set unique royalty distributions.
- It serves artists who can share their NFTs on social media without losing control of ownership

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

We've laid out the technical diagrams here: https://docs.google.com/document/d/1fdO197-oEyh_AwcG0q-LDOaorPq_43qwMuE-rd2pDhI/edit?usp=sharing

**Deliverable**
On the frontend, the final deliverable will be an NFT sales flow that automatically distributes royalties to the original NFT creator. 

For example:
Assuming, individual A is the creator of the NFT, individual B is the current NFT holder and seller.

Individual B will see:

Pay to NFT Creator:  95 % 
Pay to Me (upon sale): 5% 

Button -> [ SET ROYALTIES ] 

Upon NFT sale, the royalties are paid out to the respective wallets instantly. 

**Budget and Milestones**

Milestone 1: 
 
1. Development Engineer

20 hours Research & Clarity Fundamentals
30 hours implementation of Smart Contracts, running experiments and working with existing engineers on making sure smart contracts will work with our current application. 

Total: $6,250

2. Project Management
11 hours Outline the project scope and create projections for a month weekly deliverables 
Weekly progress updates check ins with Senior engineer and CTO
Support with miscellaneous tasks  

Total: $880

Total Grant Request:  $7,130

**Team**
The team will be engineers hired by Gary Riger, our CTO who has developed blockchain enabled applications for startups including Layer’s storage and minting platform. Engineers are mostly javascript focused who have interest in Blockchain technology and smart contract engineering. 

**Risks**
Some learning curves into clarity unless the engineer we find already has clarity experience. 
Ability to get community feedback in time so we can have a good cadence for hitting milestones. 

**Community and Supporting Materials**
Royalties seems to be a need by many in the stacks community. As NFTs become more commonplace and the needs evolve, we need a common standard for royalties that is instant and trustless. By making these run with a flick of a switch on the front end we can create a useful interface for developers and users alike to create the NFT economics they feel will fit their individual use cases.

**Comment by RaffiSapire** [comment]
Hi @grigerny, this grant is approved! 

We have some questions to think about: 

1. Would like a better idea of what concrete implementation will be. 
2. How do we make sure that creator gets the royalties? 
3. If you’re making NFTs for sale, then why wouldn’t you go through an NFT exchange that gave you royalties?
4. What if the buyer of the NFT simply sells the NFT on a different platform?

**Comment by RaffiSapire** [comment]
Hi @grigerny - We're having an issue with the new grant bot, but we're fixing it and a sign up form will be posted here likely tomorrow. Sorry for the delay on the onboarding!

**Comment by RaffiSapire** [comment]
Hi @grigerny  - can you try the onboarding flow here and let us know if you are able to sign up and then receive email with docusign?

**Comment by grigerny** [comment]
An update on progress:
- ability to select a royalty percentage and NFT is distributed accordingly. 

Right now we are showing 300 because clarity doesn’t allow for decimals but this will be improved.

Demo: 
https://youtu.be/quKL2YdoWmk

**Comment by grigerny** [comment]
!m1_complete

**Comment by jennymith** [comment]
Hey @RaffiSapire, this grant had only one milestone so it can be marked as complete now cc: @jhammond2012.

**Comment by RaffiSapire** [comment]
Great. @grigerny are there any other outputs, or maybe a link to the repo you can share here?

**Comment by grigerny** [comment]
`(impl-trait 'ST4WC7XV46Y2M6SDD5G31H8BHK8GMJX13XGEYNS8.nft-trait.nft-trait)
(define-non-fungible-token NFT-layer uint)
(define-data-var last-id uint u0)
(define-map token-data 
  {token-id: uint} 
  {price: uint, for-sale: bool, name: (string-ascii 64)})
(define-map token-royalties {token-id: uint} 
  {royalties: (list 5 {address: principal, percentage: uint})})
(define-constant locker-base-uri "https://heylayer.com/")
(define-constant gallery-base-uri "https://layer-abe5c.web.app/")

;; Internal - Mint new NFT
(define-private (mint (owner principal) (token-id uint))
  (match (nft-mint? NFT-layer token-id owner)
    success
      (begin
        (var-set last-id token-id)
        (ok true))
    error (err error)))


(define-public (mint-nft 
  (asset-hash uint) (price uint) (for-sale bool) (name (string-ascii 64)) 
  (royalties (optional (list 5 {address: principal, percentage: uint})))  
  )

  (if 
    (unwrap! (mint tx-sender asset-hash) (err u1))
      (begin 
        (print gallery-base-uri)
        (ok 
          (and 
              (map-set token-data {token-id: asset-hash} {price: price, for-sale: for-sale, name: name})
              (map-set token-royalties {token-id: asset-hash} 
              {royalties: (default-to (list ) royalties)})
          )
        )
      )
      (err u2)
  )
)

(define-read-only (get-all-token-data (token-id uint))
  (ok
    {
      token-id: token-id, 
      token-data: (unwrap! 
                    (map-get? token-data {token-id: token-id} )
                    (err u3)
                  ),
      token-royalties: (unwrap! 
                    (map-get? token-royalties {token-id: token-id} )
                    (err u4)
                  ),
      token-owner: (unwrap! (nft-get-owner? NFT-layer token-id) (err u5))
    }
  )
)


(define-read-only (get-token-data (token-id uint))
  (ok 
    (unwrap! 
      (map-get? token-data {token-id: token-id} )
      (err u6)
    )
  )
)


(define-read-only (get-token-price (token-id uint))
  (ok 
    (unwrap! 
      (get price (map-get? token-data {token-id: token-id} ))
      (err u7)
    )
  )
)

(define-read-only (get-token-name (token-id uint))
  (ok 
    (unwrap! 
      (get name (map-get? token-data {token-id: token-id} ))
      (err u8)
    )
  )
)

(define-read-only (get-is-token-for-sale (token-id uint))
  (ok 
    (unwrap! 
      (get for-sale (map-get? token-data {token-id: token-id} ))
      (err u9)
    )
  )
)

(define-public (set-token-price-data (token-id uint) (price uint) (for-sale bool))
  (if (is-eq (unwrap! (unwrap! (get-owner token-id) (err u10)) (err u11)) tx-sender)
  (let 
    (
      (token-name (unwrap! (get-token-name token-id) (err u12)))
    )
  
    (ok (map-set 
    token-data {token-id: token-id} {price: price, for-sale: for-sale, name: token-name})))
    (err u13)
    
  )
)

(define-public (set-token-royalties (token-id uint) (royalties (optional (list 5 {address: principal, percentage: uint}))))
  (if (is-eq (unwrap! (unwrap! (get-owner token-id) (err u10)) (err u11)) tx-sender)
    (ok (map-set token-royalties {token-id: token-id} 
              {royalties: (default-to (list ) royalties)}))

    (err u13)
    
  )
)

(define-public (purchase (token-id uint))
  (let 
    (
      (is-token-for-sale (unwrap! (get-is-token-for-sale token-id) (err u14)))
      (token-name (default-to "default name" (get name (map-get? token-data {token-id: token-id}))))
      (token-price (unwrap! (get-token-price token-id) (err u15)))
      (token-owner (unwrap! (nft-get-owner? NFT-layer token-id) (err u16)))
      (token-buyer tx-sender)
    )
    (if 
      (and 
        is-token-for-sale
        (unwrap! (payment-split token-id token-price token-buyer token-owner) (err u17))
        (unwrap! (nft-transfer? NFT-layer token-id token-owner token-buyer) (err u18))
      )
      (ok (map-set token-data {token-id: token-id} {name: token-name, for-sale: false, price: token-price}))
      (err u19)
    )
  )
)

(define-private (pay-royalty-helper (royalty-info {address: principal, percentage: uint}) (price uint))
  (if 
    (is-ok 
       (pay-royalty tx-sender price (get address royalty-info) (get percentage royalty-info))
    )
    price
    price
  )
)

(define-private (percentage-to-owner-helper 
                  (royalty-info {address: principal, percentage: uint}) 
                  (remaining-percentage uint))
  (- remaining-percentage (get percentage royalty-info))
)

(define-private (payment-split (token-id uint) (sale-amount uint) (payer principal) (owner principal))
  (let 
    (
      (royalties (get royalties (map-get? token-royalties {token-id: token-id})))
      (percentage-to-owner (fold percentage-to-owner-helper (default-to (list ) (get royalties (map-get? token-royalties {token-id: token-id}))) u10000))
    )
    (begin 
      (fold pay-royalty-helper (default-to (list ) royalties) sale-amount)
      (ok (is-ok (pay-royalty tx-sender sale-amount owner percentage-to-owner)))
    )
  )
)

(define-private (pay-royalty (payer principal) (sale-amount uint) (payee principal) (percentage uint))
  (begin 
    (if (> percentage u0)
      (let 
        (
          (split (/ (* sale-amount percentage) u10000))
        )
        (if (unwrap! (stx-transfer? split payer payee) (ok u778)) (ok u2) (ok u777))
      )
      (ok u222)
    )
  )
)

(define-private (is-owner (token-id uint ) (user principal))
  (is-eq user (unwrap! (nft-get-owner? NFT-layer token-id) false))  
) 

(define-public (transfer (token-id uint) (owner principal) (recipient principal))
  (if 
    (and 
      (is-owner token-id tx-sender)
      (is-eq owner tx-sender)
    )
    (nft-transfer? NFT-layer token-id owner recipient)
    (err u37)
  )
)

(define-public (delete-token (token-id uint))
  (if (is-owner token-id tx-sender)
    (if
      (and
        (is-ok (nft-burn? NFT-layer token-id tx-sender))
        (map-delete token-data {token-id: token-id})
        (map-delete token-royalties {token-id: token-id})
      )
      (ok true)
      (err u999)
    )
    (err u998)
  )
)


;; SIP009: Get the owner of the specified token ID
(define-read-only (get-owner (token-id uint))
  (ok (nft-get-owner? NFT-layer token-id)))

;; SIP009: Get the last token ID
(define-read-only (get-last-token-id)
  (ok (var-get last-id)))

;; SIP009: Get the token URI. You can set it to any other URI
(define-read-only (get-token-uri (token-id uint))
  ;; (ok (some (concat base-uri token-id)))
    (ok (some (concat locker-base-uri "hmmmm")))
)`

**Comment by grigerny** [comment]
Here is a recent TESTNET deployment of the smart contract which includes the source code. Please let me know if you require anything else and I'd be happy to provide. 
[Contract deploy - Stacks Explorer by Hiro [TESTNET MODE]](https://explorer.stacks.co/txid/ST4WC7XV46Y2M6SDD5G31H8BHK8GMJX13XGEYNS8.outdoor-silver-spider?chain=testnet)
