### ISSUE TITLE
ALEX - Launchpad, helping founders fairly distribute tokens with minimal capital investments

### ISSUE THREAD

**Issue by fiftyeightandeight** [stacksgov/Stacks-Grant-Launchpad#193]
### The Problem
Many projects want to distribute tokens in a fair way among the community, with the tokens remaining in the hands of those that are invested in the project for the long term, instead of speculators looking for quick profits. At the same time, the projects need their projects to build deep liquidity with efficient price discovery of their tokens, without requiring heavy capital investments from the team.

### The Solution
"ALEX Launchpad" helps founders solve these problems: projects are able to fairly distribute tokens with minimal capital investments. "ALEX Launchpad" develops a simple UI powered by ALEX's core technology. 

ALEX's core technology is an application of the Liquidity Bootstrapping Pool ("LBP") pioneered by Balancer, but applied to Stacks. LBPs allow projects to launch tokens with custom capital requirements--including very low capital requirements. 

ALEX's LBP will consist, at first, of pool with exactly 2 assets or tokens. One token will be the project's token. The other token will be chosen by the project, such as STX, or BTC. The ratio, or weight of the tokens, can be determined by each project themselves. 

To minimize capital requirements in terms of the collateral token, a project may choose to start with a 90:10 ratio of Project_Token:Collateral_Token for example. People may put collateral tokens into the pool in exchange for the project's tokens. 

To promote price discovery while preventing malicious behaviors from bots or front-running, LBPs can evolve in specific ways over time. For example, over time, the pools token weights may gradually change. Typically, the weights will change such that the project token's relative weight in the pool decreases, while the collateral token's relative weight increases until the end of the token distribution. 

The relative weights of a project's token to collateral tokens can be held constant, it can increase, or it can decrease. ALEX Launchpad offers projects the full range of possibilities, allowing projects to customize the evolution of their token distribution in ways that best fit their intentions. 

Should a project want to maximize the number of collateral tokens received in exchange for the project's tokens, they could hold the relative weights constant over time. In turn, should a project want to maximize the speed at which the tokens are distributed, they may choose to decrease the weight of the collateral token over time. 

Should a project want to maximize fair distribution while minimizing price speculation, then the project may choose to increase the weight of the collateral token over time. This approach prevents "whales" from performing a “rug pull” or a similar technique that leads to instant price volatility and allows for more fluid price discovery for the token. This is because tokens are released slowly with changing weights, whales are forced to split their trades into separate, small, trades over a longer period of time.

LBPs were first offered by Balancer in 2020 and have been used as an alternative to ICOs, IDOs or IEOs.

### Comparables
There does not currently exist a launchpad for IDOs on Stacks. ALEX is uniquely positioned to build an IDO launchpad on Stacks because ALEX is building technology that builds upon and extends technology pioneered by Balancer as well as Compound and Aave. We are not aware of other efforts even attempting to build a decentralized launchpad solution on Stacks that solves the problems above.

### Expected Impact
Would it matter if ALEX launchpad, as a decentralized token issuing platform, does not exist? We believe it would. With ALEX launchpad, we expect that it becomes much easier for new projects to issue tokens. The expected outcome should be a) a greater number of projects joining Stacks because it's become easier to issue tokens, b) a greater number of projects issuing tokens on Stacks than would otherwise be the case, b) a less concentrated distribution of tokens across tokenholders than would otherwise exist.

### Milestone 1
**Deliverable**: A smart contract on mainnet implementing a functional version of the two-token Liquidity Bootstrapping Pool described above, released under a MIT License.
**Requested grant**: 30,000 USD
**Deliverable deadline**: Dec 31

Upon completion of Milestone 1, we would like to review and expand the scope of grant. To provide some examples for extensions, one potential next milestone would be to upgrade the LBP from two token pools to pools with more than two tokens. For example, instead of a pool with a 50:50 ratio of a project's token with some collateral token, we could enable a pool with a 33:33:33 ratio of a project's token, some collateral token, as well as another collateral token. Another option is to allow projects to issue NFTs for buyers from an LBP, as a type of badge that they were there when a project first launched.

### Community and Supporting Materials
Four projects of Stacks Accelerator Cohort 1 agreed to launching their tokens on our Launchpad. We would be happy to share more details with the Foundation.

**Comment by jennymith** [comment]
Hi @fiftyeightandeight, thanks for resubmitting this grant with more information on the community support you've received! It seems that there is clear demand for a platform like this and that it has the potential to really improve token management within the ecosystem (well done 😄). 

Before we approve this, we'd just like to clarify the deliverable. Will it just be a smart contract or will you be building an accompanying UI? Given the size of this grant and the alleged urgent demand for this launchpad, we believe it would be appropriate to include a comprehensive and accessible UI that founders, users, and auditors can use to explore funding and verify that the terms of each token issuance are, indeed, fair.

**Comment by fiftyeightandeight** [comment]
Hi @jennymith, thank you for your feedbacks. Yes, the milestone will include a basic, yet, comprehensive, UI that will provide all the relevant/important information to the stakeholders that you mentioned.

**Comment by jennymith** [comment]
Thank you for your response @fiftyeightandeight! This grant has been approved cc: @RaffiSapire @jhammond2012.

**Comment by jennymith** [comment]
Hi @fiftyeightandeight, just checking in to see how this grant is going. Let us know if you need any help getting things off the ground!

**Comment by fiftyeightandeight** [comment]
Hi Jenny, we are on track to release some initial preview of the LBP in action in the next two weeks (we probably want to push the deadline by one week). Many community members are already helping (with base contract code base etc) and will come back to you if we need more time and/or need help!

**Comment by jennymith** [comment]
Hi @fiftyeightandeight checking in to see how this grant is coming along! Do you have an estimate on a new deadline (I see the original deadline was October 30th)?

**Comment by fiftyeightandeight** [comment]
Hi @jennymith , the smart contract is now available. It has also been audited by CoinFabrik.
The relevant code is available at https://github.com/alexgo-io/alex-v1/blob/main/clarity/contracts/pool/liquidity-bootstrapping-pool.clar.

We are currently working on the UI and could I please suggest to update the deadline to Dec 30?

Thank you.

**Comment by jennymith** [comment]
Sure @fiftyeightandeight! Feel free to update your application to reflect the new deadline of Dec 30th.

**Comment by fiftyeightandeight** [comment]
Hi @jennymith , we think we can complete the basic UI in the next two weeks. I will keep the group updated.
Thank you.
