### ISSUE TITLE
Stacks - Lightning Network Bridge #2

### ISSUE THREAD

**Issue by pseudozach** [stacksgov/Stacks-Grant-Launchpad#204]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

This is a follow-up grant request to https://github.com/stacksgov/Stacks-Grants/issues/172 where a non-custodial submarine swap implementation is successfully developed, open sourced and deployed. This service is currently live at https://LNSwap.org

Target of this follow-up grant is 3-fold building on the potential of the previous deliverables: 
- Expand the reach (include tokens)
- Increase liquidity (enable bitcoin onchain)
- Decentralize (allow anyone to easily run this app)

**Project Overview**
What solution are you providing? Who will it serve?

* By the end of this grant when all deliverables are provided, any internet user will be able to deploy a non-custodial exchange with 1-click. They'll be able to select which pairs they would like to enable, select what fee they'd like to charge, provide required liquidity and serve others in a non-custodial way.

* Another highlight will be to enable [millions of people currently on Lightning](https://twitter.com/ArcaneResearch/status/1445749299703205894) access to USD stablecoins within seconds in a trustless way.

* Similarly, access to STX and all tokens/NFTs on Stacks will increase as there will be a new KYC-free, noncustodial way to go from onchain Bitcoin (the most liquid asset) to any token on Stacks within minutes.

* A new type of Stacking pool will be possible. One that allows Bitcoin returns from Bitcoin investment (and another very exciting application I'd rather not reveal at the moment) in a trustless way without users even touching STX.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

* [Previously developed clarity contract](https://github.com/pseudozach/lnstxbridge/blob/main/contracts/stxswap_v7.clar) will be updated to enable SIP9 and SIP10 swaps.
* Backend will be updated to support any token pairs.
* Frontend will be updated to fetch rates and service any token pairs.

After receiving [very positive feedback on lnstxbridge](https://github.com/stacksgov/Stacks-Grants/issues/172#issuecomment-921282162) from the community, I'll keep sharing usage numbers and most popular swap pairs on LNSwap.org. I'll also be available to add support for other requested tokens as per milestone-3.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

M1 - SIP9/SIP10 support
SoW: 
* Update Clarity contract to support tokens. 
* Update backend to track token activity and complete submarine swaps. 
* Update frontend to query token prices and fees.

Deliverables: All code pushed to github. As a sample integration [USDA (Arkadiko)](https://github.com/stacksgov/Stacks-Grants/issues/172#issuecomment-896603985) will be integrated to LNSwap.org mainnet.
Approx. Timeline: 2 weeks
Grant Amount: $4000

M2 - Better liquidity/Faster Swaps
SoW: 
* Update backend to support bitcoin onchain swaps between STX or any SIP9/SIP10 token. 
* Update backend to utilize microblocks, cutting down swap time from ~10minute to seconds.
* Optimize the backend API and publish documentation and guides for easier integration by any developer.
* Offer integration support/guidance to any LN/Stacks app developer 

Note: Part of the grant funds (Up to %50) will be used to provide liquidity on LNSwap.org.
Deliverables: All code pushed to github. Publish demo of first trustless USD stablecoin <-> Lightning swap in under 1 minute.
Approx. Timeline: 1 month
Grant Amount: $8000

M3 - Decentralize/Integrate/Maintain
SoW: 
* Package the app and all the components into a Docker container.
* Enable 1-click deploy to popular platforms. Backend to Heroku/AWS, frontend to vercel)
* Provide a fully dockerized version to enable users to deploy and easily configure all components to their self-hosted nodes such as [Umbrel](https://getumbrel.com).
* Maintain the repos, follow-up with [issues](https://github.com/pseudozach/lnstxbridge/issues)/feature/token requests for at least 1 year.  

Deliverables: All code pushed to github. 1-click deploy buttons on github repo with detailed instructions and videos. 
Approx. Timeline: 1 month
Grant Amount: $8000

Total Grant Request: 20k$

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I'll continue working on this. Over the past months, I've become very familiar with all the codebases and clarity contract. With continued great guidance from Hiro/Stacks Foundation teams I'll keep delivering working, innovative applications that has real utility. As with previous grant, I'm hoping to deliver the results even earlier than planned barring any major issues.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Running a bitcoin node and stacks node in parallel may have high system requirements and increase the barrier to running this app, if this turns out to be the case, I'll think about running a separate service that provides Stacks Node websocket as a service and provide it to the community.

Depending on demand, the offer to help other devs for API integration can become overwhelming but I can use the feedback to build better guides/documentation/video instructions to provide others with tools so they can integrate independently.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

https://github.com/stacksgov/Stacks-Grants/issues/172
https://github.com/pseudozach/lnstxbridge
https://github.com/pseudozach/lnstxbridge-frontend
https://github.com/pseudozach/stxoracle
https://github.com/pseudozach/stxpredict

* I continue to collect feedback on this [comment](https://github.com/stacksgov/Stacks-Grants/issues/172#issuecomment-921282162) so far all very positive. I've recently also done a podcast interview on this subject which I'll share once published.
* I will keep utilizing discord community channels but I'm also open to creating a dedicated channel on discord.

**Comment by pseudozach** [comment]
Hi @jennymith,
Thanks for the response. No worries, I'll look forward to the decision, obviously I'm open to suggestions. 

I've used this off-time to build scaffolding for the 'new type of stacking pool' I've mentioned in the proposal.
https://stacktogether.org will be a no-loss, non-custodial Bitcoin lottery. Users will be able to convert BTC to STX (via LNSwap.org) and join the lottery without even needing to install a stacks wallet. 1 lucky winner will win all of the stacking rewards and other participants will be able to withdraw their initial capital with no loss. 

I've also discussed with Jamil from stxnft.com and he's interested in using the deliverables from this grant (M2 onchain BTC - STX swaps) to enable purchase of Stacks NFTs with Bitcoin. We're planning to integrate LNSwap.org and stxnft.com to do a follow-up to my NFT project (self-plug 😅) https://www.stacksroots.com and sell the new NFT drop exclusively with Bitcoin!

**Comment by dantrevino** [comment]
I'm especially looking forward to M2 and M3.  M1 is necessary, but M2 and M3 could really fill a need for the development community in Stacks.  +1

**Comment by jennymith** [comment]
Sharing this here for documentation purposes: We'll be discussing feedback from the review committee as well as plans to re-scope this grant tomorrow, during office hours with Marvin.

**Comment by pseudozach** [comment]
One additional note to discuss in the meeting from my side: 
- Currently LNSwap as it is, lacks the `initial onboarding` support for a user with no STX at all, because in order to claim funds from the contract they still have to have a small amount of STX. 
- I think this may be a good idea to add to M3, where the contract can be improved so a small amount of funds are sent to user during the lockup process. This way once they're ready to claim funds from the contract they'll have STX to use as gas.

**Comment by pseudozach** [comment]
As discussed in the meeting with Jenny & Marvin, here are the updates to the milestones:
- Microblock support will be optional with tradeoffs to be communicated to the users.
- M3 maintenance support will not be provided as it's open ended, instead documentation and video guides will be published.
- M3 Future token support requests will be handled with follow up grants with relevant scope.

Thanks,

**Comment by jennymith** [comment]
Hi @pseudozach looks like we're still waiting on a thumbs-up from the committee on M2 and M3 but I can get you started on M1 for now. Will disburse that soon, thanks!

**Comment by jennymith** [comment]
Hey @pseudozach please comment '!m1_complete' so that we can get you started on milestones 3 and 4 :).

**Comment by pseudozach** [comment]
Hi,
I'm happy to announce Milestone-1 is complete. BTC Lightning <-> USDA swaps are live on https://lnswap.org.
There's limited liquidity but hopefully we can scale it as people use it. 
As usual all relevant code is pushed to  repos: 
https://github.com/pseudozach/lnstxbridge
https://github.com/pseudozach/lnstxbridge-frontend
Thanks,

!m1_complete

**Comment by jennymith** [comment]
Hi @pseudozach, any updates to share on M2 and M3? Also, https://lnswap.org/ is not loading at the moment.

**Comment by pseudozach** [comment]
Hi @jennymith 
I'm mostly blocked due to issues dealing with 2.05 node upgrade. Node migration failed and I've been waiting for the node to sync for ~1 week. It's currently syncing from beginning at chain height `35672` so hopefully lnswap will be back up in 1-2 days and then I expect to progress a lot faster.

**Comment by txpost** [comment]
Any progress on this? Just attempted a swap using Blue Wallet on iOS to complete the lightning invoice and got the error "API error: Payment failed. Does the receiver have enough inbound capacity? (code 10)"

**Comment by pseudozach** [comment]
Latest update:
- lnswap stacks node synced and upgrade to 2.05 is completed successfully.
- lnswap.org Lightning node is re-launched but currently connectivity is low so it's expected to see payment failures like this. I'm trying to increase inbound Lightning channels. Feel free to open a channel if your swap fails and you are running a node.
https://1ml.com/node/023d1009e449f1f88f97731844d446d788bd70fd051f1ccca16542553e02e14d62
- grant milestone is progressing nicely, chain to chain atomic swaps are `almost` done. Hoping to have a simple demo pretty soon. 
https://github.com/pseudozach/lnstxbridge/commits/onchain

**Comment by pseudozach** [comment]
Hi,
I'm proud to finally share atomic swap demo between stx and onchain btc: https://www.youtube.com/watch?v=siAFpWxB9MY

There's still some work left to cleanup the front-end UI and cover some edge cases but overall I feel like this was the most challenging part (and took a bit longer than anticipated) and it's complete. I should be able to merge the changes into main branch in the next few days and enable atomic swaps in production on https://lnswap.org.

!M2_complete

**Comment by pseudozach** [comment]
Atomic Swaps between onchain BTC and STX is live on mainnet on https://lnswap.org.

Here's the first atomic swap demo video: https://www.youtube.com/watch?v=3B1LNnuFI-A
And here's a refund video where user can retrieve their onchain BTC funds from the HTLC if swap fails: https://www.youtube.com/watch?v=tY5EEhIkkpI

Regarding other goals of Milestone-2:
- Microblock support is ready from my side but unfortunately, progress is blocked pending stacks-blockchain-api team to merge support for socket.io `address-transaction` events. I've discussed this with Rafael and opened this issue to track: https://github.com/hirosystems/stacks-blockchain-api/issues/952
Once this feature is available, I can integrate it and accomplish slight improvement in UX using microblocks.

- Swap integration for Stacks Apps:
As per feedback from other Stacks apps (e.g. Arkadiko, stxnft.com, boom) developer integration will be done via an embeddable widget. Stacks apps can show a simple button and user will be able to swap BTC for STX without leaving their app.
For this I've added a new page here: https://www.lnswap.org/developers
And the widget is available for a demo at: https://lnswap-widget.vercel.app

Let me know any feedback,
Thanks,

**Comment by pseudozach** [comment]
Some exciting news to share about M-2 Part-2:
Together with stxnft.com we launched the initial integration for `Buy NFT with Lightning` which is enabled by lnswap.org API. 
Very positive reaction by the community: https://twitter.com/stxnft/status/1479227407030800385?s=20

Of course at the moment it's a trusted setup but with learnings from this experiment I want to continue building on this codebase to make it fully non-custodial and extend beyond NFTs. Outline for how to proceed after M3 is shaping up very nicely.

**Comment by devinshoemaker** [comment]
This is incredible work, thank you for this. Has there been any thought into integrating this technology directly in a wallet (users wouldn't even have to know they are swapping to make an STX transaction)?

**Comment by pseudozach** [comment]
@devinshoemaker thanks. Yes, this is definitely one of the potential paths to take next. API and widget are the first steps to enable a wallet that can scan either an STX address or LN invoice (or BTC address) and send/receive/do contract call by abstracting everything and swapping trustlessly in the background. 
Wallet balance could be kept in any combination of btc/usda as well, per user's needs. 

However there's still some work to do on the lnstxbridge decentralization & tooling. But we'll get there.

**Comment by pseudozach** [comment]
quick update:
I've opened a discord: https://discord.gg/Gt45nMYPCM with channels for both support and developers.
and I've deployed a gitbook documentation page: https://docs.lnswap.org
With these I think there are plenty of information for Stacks app developers to simply embed this tool. I've already received requests to integrate into NFT marketplaces and will work with them.

**Comment by pseudozach** [comment]
Hi,
I'd like to announce that I've finalized and pushed the final features that were planned as part of Milestone-3 and this grant.

Dockerization of LNSwap: https://github.com/pseudozach/lnstxbridge/pull/16
This feature packages the app for easy deployment by anyone via docker. Build and deploy instructions are added to the repo along with docker-compose files. Every new release is built and pushed to docker hub automatically via github actions:
https://hub.docker.com/r/pseudozach/lnstxbridge/tags

Sponsored tx: https://github.com/pseudozach/lnstxbridge/pull/17
This feature is different but `better` than what was planned. Instead of forwarding funds from the contract, there's now an option to select if a user is onboarding to STX for the first time so if they enable this feature their claimStx contract call will be sponsored by the lnswap signer account. 

![Screen Shot 2022-01-14 at 11 53 48 PM](https://user-images.githubusercontent.com/3731591/149614305-a60a0fcd-7892-483d-b40e-df1cb0e9fa0c.png)

This feature is a great baseline and will prove very convenient to have for new use cases involving other stacks apps where potential users do not have any STX in their wallets. It enables a smooth onboarding experience and will be heavily utilized in lnswap-widget interactions as well.

I look forward to feedback/approval from the grant committee and continuing working on this app to build it to its full potential. 

Thanks,
!M3_Complete

**Comment by jhammond2012** [comment]
M2 and M3 got processed at the same time so there was a strange issue where it set both of them as active. When @pseudozach tried to market it as complete it wouldn't allow it because two were active. Anyways, I have corrected this and set M3 as ready for review.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
