### ISSUE TITLE
Specification for auth protocol

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#207]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Stacks connect and Hiro Wallet uses the stacks auth protocol to authenticate users in web apps. The documentation of the protocol is small. This proposal is about creating a specification that helps projects like Circle, Wise, Ryder to be interoperable. Web application should not worry about users having different authenticators.

**Project Overview**
What solution are you providing? Who will it serve?

The specification will be a ~~written document~~ a SIP proposal with at least one visual element. It should help to support custom authenticators (reference required) and to help solve bugs in implementations.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The SIP contains specification of the protocol including used cryptographic methods, transport protocols and message formats.

The proposal includes interaction with @larrysalibra @markmhx @0xAsteria and other interested community members.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 2,000$

M1: SIP outline document
1 week

M2: Accepted SIP
3 weeks

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Friedger (specified [sip-9](https://github.com/stacksgov/sips/blob/main/sips/sip-009/sip-009-nft-standard.md), pull request to fix auth issue: https://github.com/blockstack/stacks.js/pull/1117) 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

A previous diagram was not integrated in the official documentation due to design differences (https://github.com/blockstack/docs/issues/446), this can happen again.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

There is a general overview of the authflow here: https://docs.stacks.co/build-apps/guides/authentication 

Earlier work from 2018 [forum post](https://forum.stacks.org/t/review-spec-creation-for-blockstack-authentication/4034) by @larrysalibra et al.

[Specification for OAuth2](https://datatracker.ietf.org/doc/html/rfc6749)
[Documentation for Unstoppabledomain login](https://docs.unstoppabledomains.com/login-with-unstoppable/high-level-overview)

**Comment by friedger** [comment]
Not really, identity foundation maybe.

If the SIP repo is also intended for these kind of documentations, I am happy to write it down as a SIP.

For the milestones, I would like to start with a draft as M1, and a SIP as M2. Ratification is probably out of scope and a community effort.

**Comment by 0xAsteria** [comment]
> I would like to start with a draft as M1, and a SIP as M2. Ratification is probably out of scope and a community effort.

Agreed, this sounds good. Have to agree with @jcnelson that authentication is directly linked to the chain and therefore should be a SIP. SIPs will be easier to normalise, too.

I think this should come out as algorithm-agnostic like how Hiro's Web Wallet implementation is now.

**Comment by jennymith** [comment]
> Not really, identity foundation maybe.
> 
> If the SIP repo is also intended for these kind of documentations, I am happy to write it down as a SIP.
> 
> For the milestones, I would like to start with a draft as M1, and a SIP as M2. Ratification is probably out of scope and a community effort.

Thanks for all the discussion here, everyone. @friedger Happy to get you started on this grant but want to confirm the amount first. Since you'd rather not include ratification in this proposal, should the amount still be $2,000?

**Comment by friedger** [comment]
@jennymith Yes.
M1: outline: 1 week - 500$
M2: final version as sip including discussion on sip proposal: 3 weeks - $1500

**Comment by jennymith** [comment]
Sounds good @friedger. This grant has been approved! I'll get started on disbursing M1. In the meantime, can you please update your grant to show that this will be a SIP? Thanks!

**Comment by friedger** [comment]
Updated the description!

**Comment by jennymith** [comment]
Hey @friedger just checking that you've filled out the onboarding form?

**Comment by MarvinJanssen** [comment]
Following this and happy to be part of the conversation.

**Comment by friedger** [comment]
!completes_m1

Here is the start of the SIP: https://github.com/stacksgov/sips/pull/50

This completes M1. Currently, I am involved in the discussions about 
* authentication on mobile 
* fixing profile lookup
* BNS in general (BNS working group)

**Comment by friedger** [comment]
!m1_complete

**Comment by friedger** [comment]
Could you please check why the status still says "sign contract"?

**Comment by jennymith** [comment]
@friedger Did you receive and sign an agreement on Docusign yet? Let me know! We can still review your M1 in the meantime though.

**Comment by friedger** [comment]
@jennymith I submitted a signed contract.

**Comment by will-at-stacks** [comment]
Hi @friedger, thanks for submitting M1. You've gotten off to a good start outlining the various components of this SIP. However, we recommend adding a little more content to make this outline more accessible. Someone who doesn't understand BNS initially should be able to read the outline and at least get a sense of what they would need to do to implement this authentication protocol. Specifically, can you please add more information to the first three sections: "Specification," "Authentication Flow," and "Transport Protocol"?

**Comment by friedger** [comment]
Thank you for reviewing the outline. I understand that more work is needed. However, your comments do not say that the outline is incomplete. Instead of arguing about the outline I prefer to continue to work on the sip. My goal for M1 was to prove 
a) that I have a good understanding of the topic, 
b) that we now have a place to discuss aspects of the sip and 
c) that I have an understanding of the sip process.

**Comment by will-at-stacks** [comment]
@friedger Sounds good.  We agree you should keep moving.  Please include completing the three sections noted above in your next milestone review - in addition to continued, overall development of the SIP.  Thanks, Will

**Comment by friedger** [comment]
The SIP document is ready for review: https://github.com/stacksgov/sips/pull/50 

It describes mainly the current implementation of the Hiro Wallet/stacks.js

Next steps are improving the protocol/format and getting more feedback.

**Comment by friedger** [comment]
!m1_complete

**Comment by friedger** [comment]
The SIP https://github.com/stacksgov/sips/pull/50 has been updated.

It now specifies that the public profile is a verifiable credential.

The transport protocol section has been moved to a [new sip](https://github.com/stacksgov/sips/pull/59).

I think this completes this grant. It would require a new grant to upgrade Hiro Wallet to this spec.

**Comment by friedger** [comment]
!m2_complete

**Comment by friedger** [comment]
! m2_complete

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
