### ISSUE TITLE
Stacks Russia Chapter Grant - November 2021

### ISSUE THREAD

**Issue by jennymith** [stacksgov/Stacks-Grant-Launchpad#224]

**Comment by AslanyanM** [comment]
> Congratulations. Your grant is now approved. Please complete the on-boarding link here: https://stacks-grant.netlify.app/onboard?q=8faaad84f1dde97ea77a9cbaba1bb135

No Pending Grants
We’re sorry, no onboarding is ready for you.
Please comment on the Github issue
if experiencing issues.

**Comment by jennymith** [comment]
Hi @AslanyanM you can ignore this. I created this issue on your behalf so that we could pay out your Chapter grant.
