### ISSUE TITLE
STX NFT Data Aggregator - STACKTISTICS

### ISSUE THREAD

**Issue by teflonmusk** [stacksgov/Stacks-Grant-Launchpad#232]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

In an increasingly digital world, digital communities are becoming increasingly more important than geographic ones. What we're seeing with NFTs is how we're going to decentralize the trading of assets across the board - real estate, equity, debt, tickets, collectibles, and - of course - art. NFTs will be the means we subscribe to software (like Sigle is doing). NFTs will be how a smart contract recognizes participants in a complex, smart-contract business agreement.

While NFTs originated on Bitcoin (e.g., Rare Pepe), the Bitcoin community is still largely disconnected from the modern NFT platforms and activity. This is now changing. Modern Bitcoin NFTs are seeing an explosive revival on the Stacks blockchain, enabling smart contracts secured on Bitcoin’s security layer. 

This growth is maturing the capabilities and expanding the ecosystem but there is concern that there may be more recycling of STX NFT capital rather than new capital flowing into the ecosystem. As existing participants in this space, it is our duty to continue to educate the newcomers about Stacks and NFTs on Stacks to help this ecosystem grow and thrive.

As the Stacks NFT ecosystem and marketplaces continue to grow at exponential rates, it’s becoming increasingly time-consuming and painstaking for NFT collectors and traders to view information related to all the new, innovative projects and collections. Our solution will enable the future of a user-owned internet by making NFT’s on Stacks to be more accessible and discoverable through tools and dashboards that provide accurate, reliable information to NFT collectors, traders, and communities. 

Other L1 ecosystems have platforms like [solanafloor ](https://solanafloor.com/), [icy.tools](https://icy.tools/), and [solanalysis](https://solanalysis.com/) for their NFT communities. Stacks needs STACKTISTICS.

**Project Overview**
What solution are you providing? Who will it serve?

_**Overview:**_ A community-led platform that provides NFT market data and intel including a leaderboard with floor prices, the volume traded, number of owners, and other insights related to the STX ecosystem.  

_**Mission:**_  Our mission is to make NFT’s on Stacks more accessible and discoverable through accurate, reliable information that will empower NFT collectors, traders, and communities to make informed decisions. 

_**Vision:**_  The long-term vision is to be the most trusted source of insights and data for the NFT and collectible markets secured on Bitcoin. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
Key components of MVP:

Leadership Board: Landing page of the site, would display information of NFTs being minted and traded on the Stacks blockchain.  The displayed information would include:
Name of an NFT collection
Unique Owners 
All-Time-Traded Volume
Weekly Volume Percentage +/-
Average Price (last 14 days)
Largest Sale 
Floor Price 
Market Cap (%+/-) 
Links (Twitter, Secondary Market Link)

API Access for NFT Creators and Developers: Access for projects within the Stacks ecosystems to pull data related to specific projects for use on their site or elsewhere and a dashboard to enable this. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 

M1: Scope of work, deliverables, and grant amount of total.

**Phase 1** - Website UX prototyping and MVP development

Create MVP prototype including leaderboard of verified NFT projects with variable filters and accessible APIs for top projects. 
-Floor prices with percentage change in price over time  
-Volume ranking in STX transacted over time
-Ranking by market cap indicating total STX invested in individual verified NFT projects.
-The number of unique NFTs per collectible class in verified NFT projects. 
-Ranking by most recently deployed. 
-Community beta testing/bug-fixing before public launch. 

Time to complete = 50 hrs.
Total Cost: 1,500 STX 

Successful Completion: Interactive leaderboard and functioning site designed and deployed

Cost Components:
-Figma and other licenses = 100 STX.
-Funds to incentivize community devs for bug fixes and functionality testing= 1400 STX

**Phase 2** (Ongoing) - Community Development and Roll-out

Roll-out MVP to Stacks community with promos. 
-Grow community through campaigns with NFT giveaways and a Stacksboard slot.
-Ongoing promotions and partnerships with new STX ecosystem projects to raise awareness of STACKTISTICS and STX NFTs.

Time to complete = 100 hrs. 
Cost: 2,500 STX

Successful completion: Deploy functioning MVP to the community and jump-start engagement 

Cost Components: 
-STX / STX NFTs to fuel community adoption for promotions/giveaways= 2000 STX
-Stacksboard slot rental or other STX ecosystem partnership~500 STX 

Total Cost: **4,000 STX**

M2: Etc.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

@themariaverse is an experienced front-end developer who began collecting NFTs on Stacks at the start of the summer. She brings a background in React working professionally on a variety of projects from SPAs to more complex Electron applications, a penchant for building seamless and intuitive UI, and a drive to take part in creating a free and decentralized future. Her interest in blockchain development led her to Stacks which she is thrilled to be building for and looks forward to more contributions to projects on Web3 and the Stacks ecosystem.

@KenTheRogers has been a full-stack developer for 8+ years working on everything from intricate data-heavy UIs in React and Vue to building complex APIs in Laravel and Node. A generalist at heart, he brings to the emerging Web3 economy a desire and ability to quickly learn new technologies to build useful products. Over the past 6 months, he’s been focusing on growing his Web3 chops by learning Solidity and building out full-stack applications on Ethereum. A closet Bitcoin maxi, he recently found Stacks and is eager to learn Clarity and begin contributing to the emerging Stacks ecosystem by building full-stack Web3 applications using JavaScript and Clarity.

@ dulb26 has been working in the IT industry for 15+ years, from hardware skills to quality assurance and more recently, data engineer. Early this year became more curious about programming in the blockchain and found Stacks, rapidly became an enthusiast of the ecosystem and community. Bringing to the table data skills as: python, data manipulation, modeling, database management, ETL or ELT pipelines, databases as elastic search, cassandra, postgresql, mysql and sql server. As QA participated in a lot of projects with big players in Brazil across sectors from telecom to finance and mining, doing test cases for functional testing and also automated tests. Haa been practicing reading Clarity code and wants to adventure further in this world - helping the Bitcoin world expand along with Stacks

@teflon_musk has been a member of the Stacks community pre-mainnet launch with Freehold and experienced as a FinTech product marketer, enabling start-ups and enterprises alike to position next-gen platforms and drive differentiation. He’s found a niche in growing online audiences through memes(e.g. teflon_musk on IG) and most recently with a data/insights platform that tracks real-time option order flow, stocks and cryptocurrency trends, etc.  

@lean_sowry is a recent graduate from CU Boulder with a bachelor’s degree in computer science and a business minor. While there, he was involved in the creation and deployment of a user-driven activity posting site whose front-end was designed with HTML/CSS, EJS, and JavaScript; middle-layer server communication took place via NodeJS, and stored user data and content on a PostgreSQL database; all of which were hosted on Heroku. He also has familiarity with Python for the purpose of data manipulation, modeling, and basic implementations of machine learning and AI algorithms. This will be his first experience with development in the realm of DeFi, and he is excited to explore the possibilities therein as well as contribute where he may to the growth of the Stacks community.

@ Carl is an avid NFT collector on multiple blockchains including Stacks, Ethereum, and Tezos. A believer in the potential of Web 3.0, he is passionate about contributing to the Stacks ecosystem and resonates with the Stacks vision of a user-owned internet. As an NFT collector, he recognizes that the services Stacktistics will provide are necessary and is eager to help develop and maintain them. Bringing a background in the law, he has assisted various entities with legal and regulatory website compliance. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

**Market Risks and Obstacles**
Our product will rely on open-source data in the Stacks’ NFT ecosystem. While this is a powerful and beneficial feature of the user-owned internet, it also means there is nothing to prevent competing products from being developed that could pull users from Stacktistics. Without a “moat” to protect the data aggregated and displayed, Stacktistics could fail to generate user growth and engagement or quickly lose any growth obtained. 

To mitigate the above risk, we will focus on social engagement by leveraging Twitter. To differentiate from other NFT floor price projects, Stacktistics will create differentiation and a competitive edge from community engagement strategy that will drive adoption and fuel growth. This strategy includes using a Build in Public approach, actively engaging daily on Twitter, sharing Sigle blogs, and partnering with ecosystem projects and community members to onboard new NFTs users to the Stacks community. This content will focus on updating Stacktistics’ progress as well as being a resource for Stacks NFT ecosystem updates. 

Broader risks include the overall failure of the Stacks NFT markets to generate user or artist engagement and growth. This could occur for a number of reasons including government regulation and taxation. While unlikely, this risk would significantly undercut the value of Stacktistics and make moving forward untenable. Our prophylactic plan to address this risk includes weekly twitter updates highlighting Stacks’ innovations, updates, and improvements. These posts will positively portray Stacks as the innovative decentralized network that it is; fueling user interest and mitigating the risk of stunted adoption. We plan to additionally use Stacktistics’ Twitter account to promote blog posts, infographics, and other thought leadership to increase viewership potential and benefit the Stacks ecosystem.  

**Tech**
With the growing number of NFT collections being minted and different marketplaces also being developed, we can expect to have increased prices for data hosting as more computational and storage power are required. This amount is expected to be relatively mitigable considering that most platforms like AWS or Heroku offer tier-based pricing systems based on the necessitated requirements.  

We also do not plan on storing user data on the initial implementation which would have required a much greater storage demand. This may evolve in future versions of the site with the integration of user wallets and the possible option of displaying personal projects that are not listed on the current marketplaces. This development would also require greater focus being placed on security and appropriate handling of precious user information and materials.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

[STACKTISTICS Twitter](https://twitter.com/STACKTISTIC_btc)

[Overview Deck ](https://docs.google.com/presentation/d/1kng8FGIouatR_80GHxnQqnELbT4WMDsLAizpuoClOfY/edit#slide=id.p)

The team has the necessary expertise and experience across UX/front-end development, back-end/data, middleware/integrations, and marketing/growth to develop and deploy this solution for the community.

Stacktistics has performed preliminary market research using Blocksurvey from 47 community members shared on Twitter. The results from the survey indicate the majority of respondents believe Stacktistics would be a beneficial and valuable addition to the Stacks ecosystem, of these, 89% already participated in Stacks NFT markets. 95.8% of survey respondents believe there is a need for this product. 91.4% of survey respondents stated they would use Stacktistics at least once a week if deployed. 

See below for additional feedback from the community gathered from the survey:

“This is a great project and I’ll be following. I’ve purchased nearly every NFT over the last couple months with no intent to sell for years.”

“Really excited about this and definitely a much-needed resource in the community” -founder of STX NFT Marketplace (STXNFT.Com)

“Great idea. Differentiate the product by offering more fine-grained metrics like highest sale, avg. sale price, graphs tracking prices over time, and categorically breakdowns (for example gamefi projects often involve multiple NFT subcategories that have different valuations, like land vs. wearables). “

“Need more of an open sea site. Cleaner, crisper and comprehensive to compete with Eth. I also think we need more users with stx.”

 “I think Stacks NFT should provide sales history and price charts. Those are crucial info for collectors to make purchasing decisions.”

[STX NFT Community Survey - Blocksurvey Results ](https://drive.google.com/file/d/1lkFfBNr8TXVp-_Hmi1HoL7z5vQVsCPgY/view)

**Comment by thesaintgeist** [comment]
As an early NFT collector on STX, I feel like Stacktistics is a really important project to the evolution and maturation of the STX NFT market. I have been following their Twitter updates and have gotten to know the team, which is comprised of collectors themselves who are very active and engaged with the community. This has led them to a have very deep understanding of the current market and the issues they are working to solve. Cannot wait to see what this team can do!!

**Comment by tycho1212** [comment]
This is cool!

**Comment by will-at-stacks** [comment]
Hi @teflonmusk, we generally support the idea of making more detailed stats and analytics of Stacks NFTs more accessible to the community. 

However, instead of the Twitter bot and "how to" page, we recommend devloping an API alongside the dashboard that enables other NFT developers and creators to pull your data onto their sites. 

We think this could be extremely useful for community members navigating all the different NFT platforms across the ecosystem. It could also drive more traffic to your own dashboard. Let us know what you think!

**Comment by teflonmusk** [comment]
> Hi @teflonmusk, we generally support the idea of making more detailed stats and analytics of Stacks NFTs more accessible to the community.
> 
> However, instead of the Twitter bot and "how to" page, we recommend devloping an API alongside the dashboard that enables other NFT developers and creators to pull your data onto their sites.
> 
> We think this could be extremely useful for community members navigating all the different NFT platforms across the ecosystem. It could also drive more traffic to your own dashboard. Let us know what you think!


Thanks for the comment! We agree that adding this would be beneficial for the community and should be able to make it happen.

**Comment by louiseivan** [comment]
As a person who's been in the community for so long, this proposal is very much needed. We need more developer tools to better visualize the NFT ecosystem in Stacks. NFT aggregators such as Stacktistics are vital for having a better infrastructure for an ecosystem. Think of it as a building block. We need it now more than ever, especially before we open the floodgates.

At the moment, this tool is actually helpful with various stakeholders of the ecosystem such as the following: 

**Users:** onboarding and educating new them about STX and its NFT landscape. 

**Growth:** People like me who do a BDs with various possible integration partners always need an update to metric what's happening, and we need tools like this. 

**Engineers:** Their API could be the central repository of the entire NFT landscape of the Stacks. 

There's a whole lot more to unwrap here but these are the things on top of my mind.

**Comment by will-at-stacks** [comment]
Hey @teflonmusk if you could revise your application to address the API in lieu of the twitter bot and 'how to' - AND - make any resulting revisions to the budget / milestone roadmap - and resubmit we will get things reviewed and processed for you.  Thanks, Will

**Comment by teflonmusk** [comment]
> Hey @teflonmusk if you could revise your application to address the API in lieu of the twitter bot and 'how to' - AND - make any resulting revisions to the budget / milestone roadmap - and resubmit we will get things reviewed and processed for you. Thanks, Will

Consider it done. Just updated it.

**Comment by ventzbtc** [comment]
As someone who has entered the NFT market recently, and has already seen a multitude of rug pull projects, but also enthusiastic, successful community driven ones, this "NFT Storefront" seems almost paramount for new user onboarding and organic ecosystem growth.

NFTs likely being the entry door, and first steps, into the crypto world for most people, providing the kind of information that can assist newcomers selecting community-led projects, with long term value - assuming this project will work to maintain this _ethos_, instead of promoting only profitable ones - can only create the fertile ground where these new users feel welcome to continue to participate instead of driven away due to what can be perceived as a "bad investment".

I'll shy away from the technical capacities of this project, since I don't have an engineer/dev. background, but providing the kind of API endpoints it is promising can also only help better ecosystem integration and growth.

**Comment by dcsan** [comment]
Stacktistics twitter feed is a great source of info! 

echoing the above if you were able to provide APIs for sub graph queries it would be really helpful to dApp devs that don't want to deal with the whole hassle of setting up a node instance.

This seems a bit similar to the https://thegraph.com that allow you to setup queries aka "subgraphs" and then listen to events there and also publish these subgraphs for others to build on.

Question: would there be any open source coming out of this project?

**Comment by teflonmusk** [comment]
> https://thegraph.com

Thank you for the feedback!! We totally agree that providing APIs for sub graph queries will be extremely beneficial for the community - especially as witnessed in the past week. 

Re your question: yes, in the spirit of decentralization and transparency we plan on publishing the code and documentation to Github.

**Comment by teflonmusk** [comment]
Hey @will-at-stacks - Is there anything else you need from our team regarding this application?

**Comment by will-at-stacks** [comment]
@teflonmusk apologies for the delay!  I lost track of this over the holiday break.  Thanks for nudging me.  This is approved!

Excited to see this completed and see what is next for this incredible team!

Best,
Will

**Comment by teflonmusk** [comment]
> @teflonmusk apologies for the delay! I lost track of this over the holiday break. Thanks for nudging me. This is approved!
> 
> Excited to see this completed and see what is next for this incredible team!
> 
> Best, Will

Fantastic! Let us know what you need from us to move it forward.

Tef

**Comment by will-at-stacks** [comment]
@teflonmusk can you please provide an update on this grant?  did you sign the contract and onboard OK?
cc: @jhammond2012

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
