### ISSUE TITLE
ESSIF and Blockstack

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#25]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

The countries of the Europe Union have agreed on interoperability of eIDs between nations some time ago. Now, the attributes of the eID should be leveraged as a self-sovereign identity (European Self-Sovereign Identity Framework (ESSIF)): https://ec.europa.eu/cefdigital/wiki/pages/viewpage.action?pageId=262505360

While ESSIF and SSI in general solve a different problem than Blockstack IDs (human identities vs digital profiles), bringing Blockstack IDs and verified user data together is an important step to cover more use cases like age verification or representation/signature rights in a company.

ESSIF will likely be a separate blockchain. Therefore, interoperability between the stacks chain and other chains is an issue that might be also applicable to other areas.

## Project Overview

> What solution are you providing? Who will it serve?

This project is about exploring opportunities how to bring Blockstack IDs/profiles together with ESSIF. A solution that bridges ESSIF and Blockstack IDs will enable a new class of applications that deals with private user data and verified user data.

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

This proposal is about collecting information and doing research about opportunities and finally creating a report about the findings that can be used by evangelist and app developers to integrate SSI solutions with Blockstack. More precisely:

- interview 3 members of the Blockstack community and 3 members of the ESSIF community about possible opportunities and challenges to bridge SSI and Blockstack usernames
- research projects that try to bridge SSI and digital profiles like handshake
- write a document presenting the findings (~4 pages)

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

6 Interviews
1 day research
1 day writing
= $1000 

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

to be defined

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Blockstack IDs (non-public profiles) and Blockstack usernames (public profiles) solves the problem of digital profiles. A human can have more than one while they only have one SSI. There is a risk that the profile and the SSI can be linked and private data can be unwillingly become public. The research findings should highlight this aspect and propose a solution or guidelines.  

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

None yet.

**Comment by friedger** [comment]
Before specing out the details, I would like to get early feedback...

**Comment by dantrevino** [comment]
Even though I'm not in the EU, I think this would be super valuable.

**Comment by ryanarndtcm** [comment]
Hi Friedger, we are interested in this application but would want to ensure it was something that was started after completion of[ the other grant (OpenRiff](https://github.com/stacksgov/Stacks-Grants/issues/5)) that you are working on. I will leave this open for this time and check back in once we get closer to OpenRiff's final milestone.

**Comment by RaffiSapire** [comment]
Hi there, we're pleased to approve this research grant for $667 given the scope of the work proposed above and the previous incompleted Open Riff grant. The next step here, is to deliver on the proposed outputs. We'd love to have you share what you learned at an upcoming demo day.
