### ISSUE TITLE
Managed Stacks API Nodes

### ISSUE THREAD

**Issue by rswol** [stacksgov/Stacks-Grant-Launchpad#250]
**Background**
As more Stacks projects are getting off the ground the pressure on https://stacks-node-api.mainnet.stacks.co increases. Projects in distributed ecosystem cannot rely on centralized service and required to run own API nodes for getting an access to Stacks blockchain information. Unfortunately, running your own API node is not trivial - it requires developers time, resources, and domain knowledge dedicated to the service that is not core focus of the business. stacksdata.info runs a cluster of API nodes already as underlying source of analytics, and it makes a perfect sense to open it up to Stacks community as a managed service.

**Project Overview**
What solution are you providing? Who will it serve?
Stacksdata.info already has a runnning cluster stacks API nodes exposed as http://stacks-api.stacksdata.info:3999/extended/v1/status. The solution will be to allow any customer to get access to a dedicated or shared instance of stacks API node on demand. The target audience would be current users of https://stacks-node-api.mainnet.stacks.co who need guaranteed performance and availability of stacks API.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The basic service is already up and running. It is a cluster of several API nodes running behind flexible load balancer (http://stacks-api.stacksdata.info:3999). There is a healthcheck which is integrated with load balancer that makes sure underlying nodes are healthy.
 
The following new components for stacksdata.info needs to be developed:
* front end website allowing customers to register for the service, pick a plan, pay for the service, and get an endpoint and token for the service. 
* proxy service with auth component to allow access and provide throttling based on agreed rate limits
* expand existing scripts to provision more nodes based on demand
* implement HTTPS endpoint for http://stacks-api.stacksdata.info:3999

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $9,000

M1: Frontend website with Hiro wallet authentication. On the website a customer can pick a level of service, generate an endpoint, generate a token which later will be included in all requests to the service. 2 weeks
M2:  Proxy service. The Proxy accepts Stacks API request, checks the standing by inspecting the provided token and base on the level of service for identified customer (by querying blockchain data through stacksdata.info) passes the request further or rejects the request. 2 weeks
M3: Implement operational dashboards for the whole service (load balancer, stacks api nodes, proxy, etc) to identify the service quality for making decision if spinning up new nodes is necessary. 3 days
M4: Expand existing scripts to spin up new stacks api nodes. 2 days.
M5: provision more bitcoin nodes to provide resiliency (currently running 1 node per VPC). 1 day

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

* Stacksdata.info currently has the most accurate data due to expertise gained during running Stacks API nodes for few months now.  I have a lot of experience building of high availability cloud services from scratch (Amazon and Oracle OCI). I will work on all these project components exclusively with some UI help from StacksOnChain. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
The most challenging part is pretty much done, there are few risks that might derail this project.
* the demand might overwhelm the service since provisioning a new stacks api node takes some time (1-2 days to fully sync). Can be mitigating by throttling of existing users and careful onboarding strategy
* Oracle Cloud is still in active development and some services are not stable yet. Can be mitigated to relying only on rock solid services such as Compute, LBAAS, Object Storage.

Running backbone services is hard and this is just a first step. Another risk for this project would be a single developer not be able to provide a support 24/7 especially during non-USA business hours. This can be mitigated later based on demand with hiring operational developers from other time zones.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

* The community feedback for stacksdata.info is overwhelming. It is not just providing its own frontend for some important dashboards it is an most accurate source of analytics right now. StackOnChain is using api.stacksdata.info as a backend. If you need more specific feedback please refer to https://twitter.com/anononchain, https://twitter.com/BowTiedFellow or https://twitter.com/BowTiedMooneeb

**Comment by dcsan** [comment]
hiya - 

just to understand a bit better:

- you're proposing to deal with the devops hassle of setting up a node? possibly to provide paid plans for guaranteed access to read-only APIs? 
- would there be any extended APIs available?

- Are you [running a full node](https://github.com/hirosystems/stacks-blockchain-api) that provides a blockchain instance and will this take load off the core stacks infrastructure?

- would there be any open source code provided by this process?

just to confirm this is the same team as www.Stacksdata.info ? It's like the infrastructure component for #232 ?

**Comment by BowTiedArcticWolf** [comment]
>  you're proposing to deal with the devops hassle of setting up a node? possibly to provide paid plans for guaranteed access to read-only APIs? (a bit like infura/alchemy ?)
Yes, exactly. 
> would there be any extended APIs available?
Yes, there is already an extended API provided which customers will have access to: https://stacksdata.info/api.html
> Are you running a full node that provides a blockchain instance and will this take load off the core stacks infrastructure?
Yes, in fact, it is a cluster of full nodes behind a load balancer. 
> would there be any open source code provided by this process?
I can opensource the Proxy component if needed, the rest of infrastructure is closed sourced since it is part of stacksdata.info (which is closed sourced for now)
> just to confirm this is the same team as www.Stacksdata.info ? It's like the infrastructure component for #232 ?
Yes, this is the stacksdata.info team. #232 STACKTISTICS might use our API, I am not sure about that - right now the API is fully open to everyone.

**Comment by will-at-stacks** [comment]
Hey @BowTiedArcticWolf -

Thanks for your application.  This sounds really cool!  I am just waiting for a technical review of your application.  Wondering if you might be available to join this Twitter Space tomorrow: https://twitter.com/SyAsteria/status/1477305339745902598?s=20

I also asked @dcsan since you are both exploring API related topics.  Figure it would be cool to have a roundtable and touch on your studies in conjunction to what Asteria has been working on.  We really want to support as many explorations as possible.  It would be great to get a rich dialog going.  Sorry for the short notice!

Best,
Will

**Comment by BowTiedArcticWolf** [comment]
Hi @will-at-stacks,
Absolutely, I will try to make it

**Comment by wileyj** [comment]
An interesting proposal - is the idea around the service model based around subscriptions via smart contract?
I'd also like to see the proxy component not be tied to the API backend (particularly if your current API is not open source).

**Comment by BowTiedArcticWolf** [comment]
Smart contract is useful but not necessary, we can always get payments info
directly from Blockchain - for the first iteration we most likely look at
this approach

Proxy will be open source and independent from the stacksdata API, this is
for sure - we can get all necessary information from stacks open source API


An interesting proposal - is the idea around the service model based around

**Comment by will-at-stacks** [comment]
@BowTiedArcticWolf this is approved!  We look forward to reviewing the work this grant yields and can't wait to see it out in the wild!

**Comment by rusabd1** [comment]
Fantastic, @will-at-stacks

I will keep the community updated

**Comment by BowTiedArcticWolf** [comment]
The proxy is ready: https://github.com/BowTiedArcticWolf/stacks-api-proxy
It can monitor underlying Stacks API Nodes and include/exclude them automatically based on latest block their are processing.
It has a support for authentication, so the service can be gated if needed

**Comment by will-at-stacks** [comment]
@BowTiedArcticWolf thanks for the update.  Can you please give us an update on M3-M5?

**Comment by BowTiedArcticWolf** [comment]
@will-at-stacks 
> M3: Implement operational dashboards for the whole service (load balancer, stacks api nodes, proxy, etc) to identify the service quality for making decision if spinning up new nodes is necessary. 3 days

This is will take little bit more time since I am not a frontend developer, going to offload this job to someone soon

> M4: Expand existing scripts to spin up new stacks api nodes. 2 days.
in progress, need to polish and publish

> M5: provision more bitcoin nodes to provide resiliency (currently running 1 node per VPC). 1 day
in progress, will be part of M4 script for API node bootstrap

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
