### ISSUE TITLE
Songs To Radio Grant Application

### ISSUE THREAD

**Issue by JacobRyan258** [stacksgov/Stacks-Grant-Launchpad#252]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

The problem Songs To Radio Protocol aims to solve is decentralizing the music industry. The initial roll out of the application will be for musicians, industry experts, and engineers to have a platform of ownership with the NFTs that are already available. SongsToRadioDAO will launch by mid 2022 with the NFT being the governance token of the DAO and the access token for admission to networking events, live shows, etc. The protocol may apply for a 2nd grant when the DAO is ready to be formed, but that is to be determined at this point. 

The protocol will allow for STR (Songs To Radio - STR for short) tokens to be used in several different ways. The PoX consensus will allow for the token to be stacked to earn STX rewards, and this will also allow for DeFi of music ownership to come to fruition for the first time. 

A user owned music and internet is created by allowing the protocol/DAO to fund musicians and receive benefits that royalties produce over long periods of time. The protocol will be paying close attention to subnets and appchains to enhance the protocol and allow the users to create their own communities on top of the protocol. The protocol will pay for musicians' who have track records, followings, and music ready to be produced to record their music, license, and provide legal protection for some of the royalties to go back to the protocol/DAO. The amount will be far less than the amounts record labels currently take, which will allow for higher income achievements for artists and for their fans to share in their successes.

This grant application is for the initial smart contract development of the protocol, enhancements to the UI/UX of Songs To Radio, content creation, and for marketing. 

**Project Overview**
What solution are you providing? Who will it serve?
This is providing a solution to the music creation, ownership, and distribution from the ancient ways of the past/present to a more decentralized, permission less, and innovative environment. The protocol aims to benefit token stackers and NFT owners from the PoX built in functionality that The Stacks Blockchain provides and with the security of The Bitcoin Network. The protocol will serve individuals who want to own a passive form of income like music royalties from successful artists of the protocol. This will also benefit hundreds and thousands of musical artists, managers, and agents who are being blocked by centralized members of the established industry. Large corporations and insurance companies invest into music royalties, so why not allow the same for the direct fans of their favorite artists and allow for a DeFi protocol to be built around that? 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
Components include the smart contract for the protocol, the token development, and marketing to build out the community.
Success will be measured by community growth, the initial functionality of the Songs To Radio Protocol which is authenticating with Stacks wallet, users being able to mine, purchase, or be airdropped STR tokens, and a community of industry experts and musicians ready to implement the mission! "The Songs To Radio Protocol allows music industry experts to join forces to create music in a decentralized, permission less, and trustless environment."

The protocol will look to work with the first 3-4 musicians as milestone #1. This includes getting the musicians studio time to record their music, licensing music, and marketing.  

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

**M1: Minimum Viable Product - time to complete = (Jan. 7th - Jan. 25th) - MVP to be completed so that can apply to the accelerator program once we have community, and market fit.** 

There is a lot of innovation happening right now in the NFT, music, and DAO space. I am currently working in the community to develop DAO tooling, clarity universe 2nd cohort, and with other projects within the community. The MVP of this project will allow for the users to use the application to attain STR tokens, and we will have the first round of musician backers by Jan. 25th 2021.   

**Funds will be used for**
1. User Testing/Initial Design. $2500

- Deliverables - A solid testing flow with the smart contract live on the testnet. We will have user flow mapped - complete first iterations able to be modified as suggested by testers from the Stacks Foundation. Testers will be able to act as up and coming musicians ready to implement the Songs To Radio Protocol.

2. Content creation $3500
3. UX/ Front end $5000
4. Engineer $8000
5. Allowing Jacob Ryan to spend full time working on the protocol over next few weeks. $6000

**Total Budget** - $25,000

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
At this point it is just me. I will be actively looking for a co-founder who is savvy in marketing- since I am in Clarity Universe, I think it would be nice to connect with another cohort member, but not required at this time. I have experience with React/Javascript development so implementing the MVP by myself won't be an issue. I have been able to learn a lot about clarity development over the last few weeks in the cohort. My github account is here https://github.com/JacobRyan258. I will be looking to add another engineer to the team help with development efficiency. 
Prior to blockchain and web development, I owned a local light construction business. I spent 4 years running and operating a business so I now look forward to bringing all the skills that I learned there into the tech and blockchain space. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
The obstacles I may face is users not understanding the value the protocol will bring initially which is why there are funds allocated to content creation. If there is content created around how it works, information about Stacks Blockchain, and security of the Bitcoin Network, I think the education provided by the content will ease any tension as it relates to understanding. Content is the way people on the internet learn these days, so we will create videos about how the protocol works, how stacks works, and all the value that is being created in the ecosystem, not just about STR.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

I am currently working with a team that I won't name here who has gone through the Stacks Accelerator program. I have been working on DAO tooling with community members, and I believe the skills and abilities I possess show that I am capable of completing this project. I am over half way through the content in CodeCademy for the 2nd Clarity Universe Cohort. 

I plan to post this application in the Grants section of the Stacks Discord channel, I have discussed with some community members about the vision for this project, and have received plenty of positive feedback. I also am happy to be a part of the Stacks Grant Ambassador program and be interviewed about my process and provide written and video content of the process/community.

I am very open to community feedback, you can email me at jacobryan258@gmail.com or you can dm me on twitter here : @JacobRyanMedia

**Comment by will-at-stacks** [comment]
Hi Jacob, thanks for the application!

This is a really exciting project and we always welcome the opportunity to support builders making the leap from Clarity Universe to Stacks Accelerator.  We have a couple of items we would like you to consider and, then revise your application accordingly:
- We can assist with the smart contract audit with internal devs and/or contractors we have on retainer that can be utilized for this line item.
- We would like you to consider incorporating some user testing into the UX/Front end portion of your project.  Either a v1 build or a Figma prototype (or something similar).  We can help facilitate a user group.  We feel this will help you ensure product fit.
- Lastly, (these items do not need to be in your application, but we want you to be aware) the Grants Program is about to rollout some process revisions including having Grant Ambassadors (mentors) assist with the review of grants.  The details are still being worked out, but we would like you to consider being a part of this group.  We are also working to produce content inspired by grant work.  We would like to engage you in assisting with either writing a blog post or being interviewed at the conclusion of your grant.  
We hope this all sounds agreeable.  We look forward to reviewing your revised application.
Best,
Will

**Comment by JacobRyan258** [comment]
Will,

Thank you for your feedback. I have updated the grant application to reflect everything mentioned and am ready to proceed. What are next steps?

Thank you,
Jacob

**Comment by will-at-stacks** [comment]
Jacob - 

Thanks for the revision.  This is approved!  I will communicate with others internally to get funds disbursed.  We realize you are trying to keep a deadline.  

Please reach out when you are ready for user testing.  Give me a weeks heads up and I will work to get some users pulled together and a BlockSurvey or something for feedback - unless you have your own methodology.

Best of luck and can't wait to see how things come together!

Will

**Comment by JacobRyan258** [comment]
> Jacob -
> 
> Thanks for the revision. This is approved! I will communicate with others internally to get funds disbursed. We realize you are trying to keep a deadline.
> 
> Please reach out when you are ready for user testing. Give me a weeks heads up and I will work to get some users pulled together and a BlockSurvey or something for feedback - unless you have your own methodology.
> 
> Best of luck and can't wait to see how things come together!
> 
> Will

We will be in touch when we are ready for user testing. I am already in communication with 2 UX designers who have massive followings. The team that will be built for this application is going to be a cohesive team that will both bring more people to the community as well as add massive value. 

Thank you again Will and The Stacks Foundation for this amazing support and opportunity, much gratitude,
Jacob

**Comment by JacobRyan258** [comment]
!m1_complete

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
