### ISSUE TITLE
The Stacks No Code Plugin

### ISSUE THREAD

**Issue by perceptforminc** [stacksgov/Stacks-Grant-Launchpad#263]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Cryptocurrency has changed the world and the world is beginning to take notice after 10+ years. Can we blame them? This is a highly technical space with layers as deep as the ocean. In many cases, we are still learning as we are building the new world of tomorrow with where blockchain technology is today. There is a new emerging tool that is empowering many developers all over the world and that is No Code / Low Code technology. According to Redhat, No Code / Low Code solutions have the potential to reduce the development time by 90% and also have potential to grow to a $20 billion dollar industry by 2025. Enterprise level scalability with front ends that can operate at a high level yet are designed as easy as a Canva file is something to marvel at. This is the time where I ask a question regarding this. Where is blockchain technology in this new wave of development? No Code / Low Code solutions often are centralized and are beefed up to be powerful through the use of plugins. These plugins are created through coding languages so plugins can serve as the bridge to more power. I believe that Stacks needs to be accessible in the No Code / Low Code space to expand its reach as a top tier cryptocurrency / blockchain / platform but also to create the opportunity for powerful introductions, interactions and impact from the standpoint of ownership.

My name is [Christopher Perceptions](https://www.crunchbase.com/person/christopher-perceptions) and I am the founder of [PerceptForm](perceptform.tech). My company’s vision is unique in that we wish to be a bridge company in the grand industry of cryptocurrency and blockchain technology. PerceptForm has chosen the Stacks ecosystem as the place as home and we have a myriad of plans in the realm of finance, education, art and real estate but we wish to start first with this: a No Code plugin. Why is this important? As a company that aims to be a bridge, we understand that not every who enters this space within the next 10 years will ever desire to learn Rust but they will desire a better experience with development as we are seeing the world become hyper digitized on a global scale. This means that people will have less time and more to do. Low hanging fruit would be to create access points for people to interact with decentralized platforms such as Stacks because they will grow in knowledge and gain through use. No such solution exists now but we aim to create a Stacks No Code Plugin. 

**Project Overview**
What solution are you providing? Who will it serve?

We aim to create the Stacks No Code Plugin. What will the plugin do? It will allow for No Code / Low Code developers to access the power of the Stacks blockchain and connect to the Hiro Wallet, interact with Clarity smart contracts and even pay for goods or services with Stacks. The plugin is one step of two within the realm of bringing Stacks to No Code / Low Code platforms like Bubble. We have a vision of creating a Clarity smart contract deployer called NoCodeClarity which will have a series of smart contract templates that can be customized and launched, increasing the amount of Dapps developed on Stacks but the plugin in step 1. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The technological side of the Stacks No Code Plugin will include the use of Javascript and Clarity. 

Our deliverables consist of rapid development, testing, auditing, integration and launching by end of March 2022. 

Success will be measured in downloads, Dapps launched on Stacks as well as sales. We will have a period where a plugin will be available for free then we will create a more powerful plugin that will be available to those who purchase it. PerceptForm believes that No Code / Low Code platform stores will be like the Chrome Browser extension store. There are billion dollar products waiting to be developed and those who create the tools to do so will gain tremendously. After the success of the Stacks No Code Plugin, our next focus is the launch NoCodeClarity smart contract template deployer. We anticipate applying for this grant by April or May 2022 and it will require a larger grant to ensure that it is launched properly. Truly, the success of the Stacks No Code Plugin will open the door for PerceptForm to develop more solutions bridging Stacks to No Code / Low Code.    

The Stacks No Code Plugin will be developed and launched on Bubble. Upon greater demand, we will expand to opening the plugin to other platforms. Bubble is the platform of choice due to my personal history with it as a Bubble Immerse Cohort founder and the fact that Bubble raised $100 million in their Series A due to the explosive growth of the platform, upwards of 1.5 million users.  

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

PerceptForm anticipates that it will take a full time commitment to take this from vision to reality. 

The full time commitment would be 100 hours spread over the course of two months, specifically February and March. 

Our roadmap and timeline are as follows: 

February 2022

Rapid Development
- Assessment & Strategizing (10 Hours) 
- Development of Plugin Framework (10 Hours) 
- Development via Clarity Integration (10 Hours) 

Testing
- Plugin Test I: Hiro Wallet Connection (10 Hours) 
- Plugin Test II: Smart Contract Interaction (10 Hours) 
- Plugin Test III: Pay With Stacks (10 Hours) 

March 2022

Integration
- Load to Bubble Plugin Marketplace (10 Hours) 
- Create Test Bubble Apps with the Stacks No Code Plugin (10 Hours) 

Launching
- Publishing of Plugin (5 Hours) 
- Marketing & Outreach (5 Hours) 

Total Grant Request: $15,000

A follow up grant will be created upon the successful launch of the Stacks No Code Plugin so that we can build out our Clarity smart contract template platform called NoCodeClarity. 

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I have personal history with No Code as I was one of a few chosen from a national pool of applicants to be a [Bubble Immerse Cohort founder](https://bubble.io/blog/bubble-immerse-cohort-2021/). This armed me with a great experience with Bubble and showed me its power as well as its potential. I have been in the cryptocurrency space since mid 2016 and have committed myself to this industry as I know it has the power to change lives. As an African American founder who has a Hispanic developer as a long term partner, I understand more than many why cryptocurrency and blockchain technology as a whole needs to be accessible on all levels. The dream of Dr. Martin Luther King Jr. is being celebrated on this January 17 in the year 2022 but we have something that Dr. King did not and that's the ability to globally scale effort through decentralized technology. I believe that Stacks, like Bitcoin, has the power to empower more than other cryptocurrencies and it’s why I aim to only develop in Stacks ecosystem. I am an active participant within Clarity Cohort 2 and also have applied for the Stacks accelerator. My long term goal is to develop a myriad of solutions within the Stacks ecosystem to achieve the Partnership tier for grants. I am here for the long term and this is only the beginning of my involvement with Stacks. 

PerceptForm's developer is Sergio Gorgona who is a Bubble.io developer with over 3+ years, several developed projects and complex problem-solving plugins with different features such as API, elements, actions (both server and local side). With a strong passion for resolving complex problems in a no-code environment. In the last 3 years, Sergio has developed over 5+ projects and over 21+ plugins in Bubble. He is an experienced web developer with over 5+ years doing several projects with different tools such as traditional code (HTML, CSS, JavaScript), WordPress, and Bubble.io. In WordPress, he has experience with building informative and e-commerce websites. With 5+ years of working on this platform on different project solutions. Our developer Sergio has [code commits](https://github.com/segongora) and [history within the No Code world as well regarding plugin development](https://plugins.gongora.me/). PerceptForm is grateful to have Sergio as a long term developing partner.  

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

When doing a new thing, you run into new obstacles and we have the resilience to overcome any issue that comes before us. We do not wish to be lax on any aspect of the process. The opportunity with No Code / Low Code technology is to create frictionless opportunities. With this, we may find complexities arise as we aim to marry the highly technical world of blockchain in the form of a plugin. This is why we are aiming to create the plugin within the timeframe of two months to ensure that ample testing can take place for security sake, experience sake and for the sake of process. 

Making the plugin interact with pre made STX wallets is one thing but we are going after a demographic that may not have ever heard of Stacks which will require educational content as people learn about private keys, public keys, seed phrases, where to acquire Stacks from, stacking and the like. Along with the technical, this will also require education which I am more than ready to speak about to a new group of people as I have done so with a campaign on TikTok called [#100DaysOfBTC which organically got over 100,000 views](https://www.tiktok.com/tag/100daysofbtc).

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

PerceptForm has committed to leveraging No Code technology for the foreseeable future and is committed to building in the Stacks ecosystem. Every aspect of our company uses No Code technology. Our developer Sergio has code commits and history within the No Code world as well regarding plugin development as spoken on. 

We are the team to do this as we are passionate as well as qualified to bring this to life and scale it. Regarding community buy in, there is a huge need for a No Code / Low Code bridge and its been heard from many, including Marvin Janssen who I spoke with during the beginning of Clarity Cohort 2 about connecting Stacks to No Code. PerceptForm aims to contribute to the entire Stacks ecosystem with creating bridges to No Code. 

PerceptForm will keep an open line of communication regarding our developments and will leverage [GitHub](https://github.com/perceptforminc/nocodeclairty) and Twitter ([personal](https://twitter.com/CMPGFB) and [business](https://twitter.com/perceptforminc)) as we are very excited about what the future holds!

**Comment by JakeBlockchain** [comment]
I love this idea.

Having used Bubble in small bursts, It's a powerful tool for building out an MVP quickly.
With Bubble's recent round of funding, I imagine it's still early and they will bring a wealth of functionality in the next couple years that can be leveraged as Stacks grows.

**Comment by perceptforminc** [comment]
@JakeBlockchain Thank you so much! We are excited to bridge No Code to Stacks via Clarity. It's beyond important as developers may want to spin up Dapps quickly. We wish to create tools that add value to developers, companies and users so we are excited for what the future holds as we build on Bitcoin through Stacks!

**Comment by will-at-stacks** [comment]
@perceptforminc Hey Christopher.  This is a very exciting proposal.  Thanks for the email.  Just a bit backed up with several applicants right now - good problem to have, I suppose.  Just letting you know, I have reviewed this and now I am just waiting on a technical review.  I hope to have some feedback for you by the end of the week.  Best, Will

**Comment by will-at-stacks** [comment]
@perceptforminc A quick note.  I would anticipate the Foundation providing the smart contract auditing.  Also, the vast majority of our grants for similar work tend to work out to $100/hr - whereas yours is working out to $300-250/hr.  If you could give this some thought and consideration that would be helpful.  Thanks, Will

**Comment by perceptforminc** [comment]
Will,

Based on your recommendation and confirmation regarding smart contract auditing, I will revise the total grant request amount. Thank you and I look forward to the response by end of week.

**Comment by will-at-stacks** [comment]
Hi @perceptforminc  - Thanks for the amazing application!  We are pleased to approve this.  Our only concern is that your schedule seems very aggressive and we would like you to give yourself an extra 30-45 days to ensure you have the time to really knock this out of the park.  We feel it could add a lot of value to the community.  Please engage with Kennny (Developer Advocate) so we can be support you along the way.  Best, Will

**Comment by perceptforminc** [comment]
@will-at-stacks Thank you so much! We will add an additional 45 days to the timeline. Looking forward to adding value to the Stacks ecosystem!

**Comment by perceptforminc** [comment]
@will-at-stacks I will be speaking with Kennny during the first week of February.

**Comment by perceptforminc** [comment]
To update the community, we are seeing success with wallet creation and authentication through a No Code front end while the plugin is being tested on the backend! 

<img width="300" alt="Screen Shot 2022-02-26 at 2 28 02 AM" src="https://user-images.githubusercontent.com/66108558/155834512-d66416d5-80ac-47d4-8b25-7b3fc70f6430.png">

**Comment by will-at-stacks** [comment]
gm @perceptforminc  just checking in.  Can you please provide us with an update on this grant?  Thanks, Will

**Comment by perceptforminc** [comment]
> gm @perceptforminc  just checking in.  Can you please provide us with an update on this grant?  Thanks, Will

@will-at-stacks Good morning! The plug-in is almost ready to deploy no later than April! Our [social media presence](www.Twitter.com/NoCodeClarity) for the plug-in & No Code tools is growing in interest. Bitcoin Zay, who is working on an academy in Miami, stated that he's interested in the Stacks No Code plug-in and retweeted it to his thousands of followers. 

After the tool is deployed, we have a desire to continue to iterate on the Bubble plug-in as needed as well as expand to other No Code platforms like Webflow, Zapier, Carrd, Adalo & more. We aim to create the best No Code resource for developers interested in Stacks. After successful deploying of the Stacks No Code plug-in on Bubble, no later than April, we would be interested in contacting the foundation for an additional grant to build out more No Code tools for Stacks. 

Lastly, when the first plug-in is launched, I will be sure to comment with the direct link for people to see it. Thank you.

**Comment by perceptforminc** [comment]
The No Code Stacks Plug-in will go live by next week! Once live, we will continue to perfect it based off of feedback, requests and bugs that need to be fixed.

![image](https://user-images.githubusercontent.com/66108558/164112534-ae40f363-0a9f-4431-a38d-42c8138980c6.jpeg)

(define-WAGMI NoCodeClarity)

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
