### ISSUE TITLE
Zero Authority DAO & Creator Hub

### ISSUE THREAD

**Issue by zeroauthority** [stacksgov/Stacks-Grant-Launchpad#264]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

🔗 zero authority is a community of people who believe in open source and permissionless systems built on stacks and secured by bitcoin. 🔗

Zero Authority was started as a way to educate and encourage people in the transition to a user owned internet, also known as Web3… by setting up a Web3 wallet, learning to use decentralized applications, and buying/minting NFTs. Since our first video in February of 2021, we have had 37,000 views and 1,100 hours watched for our intro to Web3 series, “Built on Stacks” builder series, CityCoin tutorials, and other stacks related content. Each person in the DAO averages 10,000 to 60,000 impressions on Twitter from the content shared monthly. We have really strong and passionate contributors in the community who joined Zero Authority to produce helpful content and tutorials for people who want to use applications built on Stacks. 

We help people learn how to use applications on Stacks. We want to build a Creator Hub for people who want to become contributors and for members who want learning content in the Stacks ecosystem. Our mission is to educate, encourage people to use decentralized applications, and promote a user owned internet. 

**Project Overview**
What solution are you providing? Who will it serve?

Zero Authority has added dedicated Stackers who want to make a difference and contribute to building a user-owned internet. This project began as a passion that we do in our spare time, and we felt the time was right to use the momentum and construct a self-sufficient organization. 
With this grant we will expand content creation, video, and written content, create more playlist, and weekly updates on stacks ecosystem and dynamic trends. More interviews with people and locals who support CityCoins mission. More conversations with builders in the Stacks ecosystem. More connections with builders and developers who can encourage others looking to build decentralized apps. The Creator Hub will be a place where learning happens and eventually where people can become contributors and earn potential rewards by creating content so others may learn and grow. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

M1: Weekly Live Streams & Twitter Spaces

![zero authority live stream](https://user-images.githubusercontent.com/16929732/149858799-8969e192-b132-4624-88a3-07eec53a30c0.png)

Live streams will include topics related to CityCoins, Gaming, stacking, earning Bitcoin, writing, NFT marketplace (trends, artwork, artist profiles). 

- Keep the community engaged. Offering live streams elevates audience experience by giving the community more access to us and more educational content.
- Gain a wider audience. We can get more people who are interested in smart contracts for Bitcoin into educational and informative content. Creates an additional way for community engagement.
- Monday’s & Wednesday’s

Key Performance Indicators: 
- Viewership
- Repeat traffic
- Duration of views
- Unique visitors to site
- Measure & Improve Net Promoter Score 

Budget for M1: Weekly Live Streams & Twitter Spaces
- 10 hours per week
- Canva & Ecamm subscription = $100
- Total Cost: $8,500

Deliverables for M1: Weekly Live Streams & Twitter Spaces
- Weekly live stream - Monday & Wednesday 
- Twitter Space - Thursday 

M2: Builder Series & Newsletters
We want to expand the builder series and writing where we talk to people building the next generation of dapps, protocols, infrastructure, NFTS, bridges, independent entities, developers and community members working to build a user-owned internet on Bitcoin. 

![Zero Authority Shows](https://user-images.githubusercontent.com/16929732/149858970-ef766e84-f0ad-4fa4-b8d1-8e0428892456.gif)

We would like to produce illustrative content and tutorials for the following: 
- What is Web3 series (tutorials, user wallets, build with clarity)
- Clarinet, Stacks.js tutorials
- Security basics and secure coding using OWASP 
- Emerging data marketplaces for a user owned internet (@stacktistic_btc; @trubit_tech)
- Stacks PoX & energy consumption 
- Stacks anchored to Bitcoin
- STX mining 
- CityCoin mining and city activation
- DeFi lending, borrowing, liquidity mining, staking 
- NFT marketplace, trends, new projects, community updates
- Moonray metaverse (start with PvP battles and behind the scenes) 
- Blockchain gaming and trends 
- Partner with Stacks Chapters to promote dapps and user owned internet 
- Blockchain Naming System (BNS) review

Key Performance Indicators: 
- Viewership
- Repeat traffic
- Duration of views
- Unique visitors to site
- Measure & Improve Net Promoter Score 
- Total Views
- Signups
- Subscriptions
- Shares
- Email Recipients
- Open Rate

Budget for M2: Builder Series & Newsletters
- 15 hours per week
- Total Cost: $10,800

M3: Creator Hub 
Create MVP website including links to social content, NFT projects, hackathons, bug bounties, hiring, and other content in stacks ecosystem. In preparation of integrating stacks hiro login, Phase 2 of the Creator Hub will allow us to develop a decentralized creator marketplace where projects, applications, and core teams can use STX (or token) for micro-task opportunities for creators and be rewarded for contributions to the community. 

<img width="991" alt="zero authority creator hub" src="https://user-images.githubusercontent.com/16929732/149859403-e38909b7-b1b0-4130-82b8-8dbde25bbc41.png">

- Create a template and customize design to link content
- Adding new pages for navigation
- Hiro Web3 Login Preparation 
- Optimize SEO 
- Optimize for mobile web 
- Changing the size, colors, and fonts of buttons
- Adding new elements like contact forms and menus
- Editing the images on your homepage gallery
- Choosing a different color palette
- Linking/embedding social media channels

Budget for M3: Creator Hub 
- Time to complete = 300 hrs.
- Total Cost: $6,500

Deliverables M3: Creator Hub 

2 to 4 weeks
- UI/UX design, requirements analysis, architecture, design
- Layout content and images following design style guides.
- Assist in creating user personas and evaluating requirements
- Assist in creating mind maps, customer journey maps, sitemaps, wireframes, and prototypes to guide the overall product flow and design
- Assist with building and maintaining complex design systems that are shared across multiple products

4 to 8 weeks
- Prepare detailed specifications from which programs will be written and designed, coded, tested, debugged and document those programs. Design, code, and test applications and user interfaces.
- Convert Sketch files into fully functioning e-commerce sites.
- Perform project planning, organizing and implementation until the application is commissioned in a production environment.

8 to 10 weeks
- Perform thorough QA testing including cross-browser/platform compatibility with a design point of view in mind.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Mariaverse is an experienced front-end developer who began collecting NFTs on Stacks at the start of the summer. She brings a background in React working professionally on a variety of projects from SPAs to more complex Electron applications, a penchant for building seamless and intuitive UI, and a drive to take part in creating a free and decentralized future. Her interest in blockchain development led her to Stacks which she is thrilled to be building for and looks forward to more contributions to projects on Web3 and the Stacks ecosystem.

KenTheRogers has been a full-stack developer for 8+ years working on everything from intricate data-heavy UIs in React and Vue to building complex APIs in Laravel and Node. Over the past year he’s been focusing his efforts on web3 and recently joined the Stacks Foundation as Developer Advocate. Now he spends his time building things on Stacks and helping other developers do the same.

James (Hodlstx) professional background is in engineering, technical writing and intellectual property. He is working on learning software development right now and planning to develop with clarity in 2022. James is very involved all around the stacks ecosystem, mainly Discord and Twitter. 

Kurtg has experience providing feedback on CityCoins data and analytics. He provided feedback on the early versions of MIA Mining and the new MIA dashboard at Stacks on Chain.  He has also helped CityCoins with updating MiamiCoin’s profile on CoinMarketCap and CoinGecko. His background is in data analytics, project management, backlog prioritization, coordinating with stakeholders such as features and testing, and agile software development. He has a studio where he will start creating more video content, long-form, and short-form with software to create videos.

Spartan has experience in sales. His skills are in sales, marketing, project management. He’s also very well versed in NFTs, as well as how to launch a project from start to finish in the Stacks ecosystem.

Algorithm is very involved in the stacks ecosystem and he is the community manager for Stacks Telegram, Bitfari, Bitcoin Pizza NFT, and Stacks Advocates. He has experience in developing online communities, marketing, and exceptional analytical skills with a data-driven mindset. He is comfortable with engaging with people from all backgrounds and optimizing content so it is clear and concise. 

Crypto Nub is very involved in the stacks ecosystem and he has a pulse on all things blockchain gaming and Moonray RPG, battle, and metaverse. He has experience in developing online communities, marketing, and exceptional analytical skills with a data-driven mindset. 

Zero has 10+ experience in cybersecurity, application security, cyber risk management. He would like to continue developing skills related to project management, video production, and technical writing, newsletter and blogging. He would like to learn more about data analytics using R in 2022. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

COVID-19 
Adverse macroeconomic conditions, including COVID-19 and its effects on the global economy, have impacted the lives of many across the world and within the stacks community. If someone falls ill, it could delay expected delivery by days; however, we do not expect significant delay for months. 

Strategic Risk
Strategic risks can occur at any time and we will need to remain steadfast about our mission at Zero Authority: educating, engaging the community, and promoting a user owned internet. We will continue to obtain feedback from our socials and online channels so we know what value we need to deliver to our community and continuously improve over time. 
 
Financial Risk
We do not have any person who receives a salary or wages. Since we all have day jobs and family responsibilities, it would be a great incentive to be able to reward our contributions in $STX for these projects. 
 
Natural Disaster Risk
If the internet connection or living conditions are negatively impacted from a natural disaster, it will adversely impact each person’s ability to have a stable environment in which to work and provide value to the group. Project deliverables regarding weekly updates and builder series would still be on track for expected dates. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

The team has the necessary expertise and experience across UI/UX development and marketing, growth, and community involvement to develop and deploy this solution for the community. Zero Authority core contributors have reached out to members in the community and found that people want more topics on how to start in Web3, how to use decentralized applications, how to secure your wallet, how to buy and mint NFTs, etc. etc. 
Discord: https://discord.gg/kRQrWMBw 
Twitter: https://www.instagram.com/0zeroauthority/ 
Instagram: https://www.instagram.com/0zeroauthority/

**Comment by will-at-stacks** [comment]
@zeroauthority thanks for the proposal.  this sounds really cool and has some fantastic potential overlap with some changes we have in mind for the grants program.  curious if you could do a zoom call this week so we can discuss and make sure efforts compliment each other?  email me at will@stacks.org so we can organize a time + day.  thanks!

**Comment by zeroauthority** [comment]
thank you @will-at-stacks ! excited to see if we can compliment and grow stacks together. 
appreciate it.

**Comment by will-at-stacks** [comment]
hey @zeroauthority can you revise this ASAP to be in USD?

**Comment by zeroauthority** [comment]
yes, I will get it done today @will-at-stacks, thank you

**Comment by zeroauthority** [comment]
revised in USD. thank you @will-at-stacks

**Comment by will-at-stacks** [comment]
Hi @zeroauthority - Thank you for the great application.  We are pleased to approved this grant!  The portion of the grant we are excited about hope you take the most time with is the DAO.  There are a lot of people in the ecosystem that have done some great work on this and we want you to collaborate with them.  Please connect with @jennymith  so she can engage you in the process as a mentor.  Lastly, please keep in mind our conversation regarding the Grants Dashboard Knowledge Base as you develop your Creator Hub.  We really hope to work together and maximize both efforts.  Thanks, Will

**Comment by zeroauthority** [comment]
@will-at-stacks thank you for the trust and faith you put in us. 
back to building.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
