### ISSUE TITLE
Stacksgov Grant Proposal: Voting Mechanism and Code of Conduct

### ISSUE THREAD

**Issue by joberding** [stacksgov/Stacks-Grant-Launchpad#27]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

The goal of this grant proposal is to secure support for the Stacks community’s Governance Working Group for the remainder of Q4 2020 to Q1 2021. The Governance Working Group aims to solve pressing issues that hinder Stacks community members from making meaningful contributions to the mission of building a user-owned internet, such as insufficient community tools and educational material. The general objective of this working group is to advocate for the needs of the Stacks community, and empowering them with better tools and governance upon the launch of Stacks 2.0 is one major way to do that. Based on discussions with community members, we have identified and prioritized a couple of key issues to address starting this quarter:

1. There is currently no voting mechanism in place that community members can utilize to come to a consensus/make decisions on matters impacting the Stacks Ecosystem.
2. Although much of the community supports the “Can’t Be Evil” ethos, there is no official code of conduct or manifesto to enforce and unify the Stacks community around that ethos. 

Should we secure support from the Grants Program, the Governance Working Group would take the lead on the research and project management required to solve the above issues, but work closely with the wider Stacks community to execute on their solutions. It’s worth noting that this proposal is meant to kickstart several important projects ahead of the launch of Stacks 2.0. If the Governance Working Group is successful in delivering on these projects over the next two quarters, we hope to renew our support from the Grants Program in upcoming quarters to continue serving the Stacks community.

## Project Overview

> What solution are you providing? Who will it serve?

The proposed solutions to the aforementioned issues are:

1. Test, evaluate, and select an official voting mechanism for decision-making within the Stacks community. This is a longer term project that will likely take up to six months. For the purposes of this proposal, we aim to test, evaluate, and report on at least 4 different voting mechanisms by the end of Q4 of 2020. If our efforts in Q4 are successful, we would continue testing into the following quarter and aim to select and implement a voting mechanism for the Stacks community by the end of Q1 of 2021.

2. Develop and publish a draft code of conduct that will have been reviewed, contributed to, and qualitatively approved by the Stacks community by the end of Q4. Get the code of conduct officially approved by the Stacks community (via the voting mechanism determined above) by the end of Q1 2021.

These solutions will primarily serve Stacks community members focused on educating their local communities about a user-owned internet, and community members seeking a more structured governance model for community participation and decision-making. 

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Stacks Community Voting Mechanism

- A representative of the Governance Working Group, with the help of Jude Nelson at the Stacks Foundation, will lead testing of different voting mechanisms via focus groups. Community members will be polled on relevant issues within the Stacks ecosystem (e.g. “Based on the designs that you have seen so far, should we move forward with the Stacks logo?”), using each of the different mechanisms.

- Testing 4 mechanisms: a formula that endows longer-term community members with more voting power (increases log linearly with time; based on age of BNS names), quadratic voting, and 2 mechanisms chosen by the community. (Community members to submit voting mechanism proposals for consideration within the first week of testing.)

- Testing will be conducted simply, using a combination of Blocksurvey and spreadsheets.

- We will ensure that at least 50 community members participate across (not in each) the focus groups in order to gather sufficient data; results of each test will be publicly accessible throughout the process.

- By the end of Q4 of 2020: Once all mechanisms have been tested, we will release a report analyzing and comparing the accuracy and efficacy of each voting mechanism, all of which will be open for discussion within the Stacks community.

- ^If successful, by the end of Q1 of 2021: These tests and evaluations should ultimately result in the final product: open source voting software, specially designed for the Stacks community and easy to integrate into various platforms.

“Can’t Be Evil” Code of Conduct

- A representative of the Governance Working Group, with the help of Jenny Mith at Blockstack PBC, will develop a comprehensive code of conduct that not only covers the values of the Stacks community, but also outlines best practices for contributing to the Stacks Ecosystem

- Would address different stakeholders in the Stacks community, from investors to developers. I.e. For developers, the code of conduct might enforce strict privacy-preserving practices when it comes to building tools and applications. For investors, the code of conduct might encourage and endorse behaviors that help grow the Stacks Ecosystem, e.g. hodling. 

- We will conduct broad research of existing codes of conduct and take inspiration from the most effective ones (such as the [Contributor Covenant](https://www.contributor-covenant.org/) before outlining a Can’t Be Evil Code of Conduct and crowdsourcing content from the Stacks community. 

- By the end of Q4 of 2020: A working draft of the code of conduct that has been qualitatively deemed functional by the Stacks community (through feedback across platforms such as the Forum, Discord, Twitter) will be published on the Stacks Foundation website, GitHub, etc.

- ^If successful, by the end of Q1 of 2021: We will work on getting the code of conduct officially approved by the Stacks community using the voting mechanism selected from the above project.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

We are seeking $2,500, broken down into the following milestones:

Can’t Be Evil Code of Conduct (30 hours / $900)

- M1: develop initial draft based on research ($360)
- M2: solicit and incorporate feedback from Stacks ecosystem ($90)
- M3: develop revised / working draft based on feedback ($360)
- M4: publish working draft across relevant outlets ($90)

Stacks Community Voting Mechanism (40 hours / $1,200)

- M1: create focus group and solicit Stacks ecosystem input for voting mechanisms ($120)
- M2: test voting mechanisms using a combination of Blocksurvey and spreadsheets ($450)
    - Note: data will be publicly available throughout the process
- M3: compile and release analysis of selected voting mechanisms, again soliciting Stacks ecosystem input ($120)
- M4: implement selected voting mechanism as open source software for the Stacks ecosystem ($450)
- M5: use selected voting mechanism / software to ratify Can’t Be Evil Code of Conduct ($60)

An additional reserve of $400 is requested for miscellaneous tasks in support of both goals above, including but not limited to: small bounties for completing research tasks, configuration and tracking of project management, etc.

The timeline on delivery is based on an estimated 2-3 hours per week over 12 weeks, with more details listed under the project Scope. It’s worth noting that the scope of work has been broken down into milestones and hourly rates in order to calculate fair compensation for those who take ownership of these projects. This should not be viewed as transactional or contract work; the individuals who end up managing these projects will be dedicated Stacks community members. Anticipating that much of this work may be challenging and rather abstract, we just want to make sure that these projects leads are appropriately compensated for their time and effort.

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

- Representatives of the Governance Working Group will be taking the lead on each of these projects but all Stacks community members are welcome and encouraged to participate.

- The Governance Working Group is broadly educated on governance but needs the technical, educational, and community skills/expertise from Stacks community members to move forward on these projects in a meaningful way.

- Each of these projects may be treated as a “work stream” or “subcommittee” in which Stacks community members can and should get involved.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Given all the work going on with Stacks 2.0 in the background, the biggest obstacle we anticipate running into is insufficient time. Although there is obvious community demand for each of these projects, the timelines that we have set may be ambitious. That being said, we are committed to holding ourselves accountable by consistently tracking and evaluating our work in a publicly accessible GitHub project board. We will also review our work during public working group calls on a semi-monthly basis. We will set very specific, concrete, and time-sensitive key results that show progress toward larger deliverables. If we fall behind on progress for any of the deliverables two weeks in a row, we will re-evaluate the scope of the deliverables and explore revised goals with the community.

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

- Brainstorming [document](https://paper.dropbox.com/doc/Gov-Group-Grant-Proposal--A402pAn8MQVQPIikglkCKxXXAQ-RN1efxJdptsRGVrJIbwou) of high priority community projects

- Forum [thread](https://forum.blockstack.org/t/community-feedback-needed-by-08-13-how-can-the-governance-working-group-better-support-the-stacks-community/11089) on how the Governance Working Group could support the Stacks Community

- Several discussions on voting/evaluation mechanisms for the Stacks community [here](https://forum.blockstack.org/t/app-mining-feedback-de-and-token-holders-voting/7692), [here](https://forum.blockstack.org/t/building-a-voting-dapp/5375), and [here](https://forum.blockstack.org/t/appmining-scoring-a-thoughtful-proposal-for-how-applications-should-be-scored/10146)

- Please see project Scope for details on how we plan to share our work with the community.

**Comment by ryanarndtcm** [comment]
Thanks @joberding ! We will review it in the Grants Committee Meeting on Tuesday and should have feedback for you by EOD Thursday.

**Comment by blocks8** [comment]
**Review Committee Feedback from 10/27/2020: We'd like more information on your proposal.**

Thank you for your submission! We'd like to learn more about the team. Can you please update to include the team members names and roles who will be responsible for the delivery of the grant? 2-3 grant leads are fine, we just want to make sure there is clear accountability for the work here. 

Voting Proposal
- M1 of the Community Voting Mechanism might start with a handful of voting mechanisms they want to consider. 
- M4 of making it open source software - who will be building that?  I see that Foundation Research Scientist Jude Nelson is listed here as a technical contributor, has he agreed to a set number of hours for this project? I know he is very busy and want to make sure there is a technical reviewer included in this grant who can commit the necessary time to the deliverables outlined above. If he is not available, would you be able to scope with someone else? Or remove the technical components of the proposal? It’s a lot of work to build - so could it start as non-software first? Especially for $450.

Code of Conduct 
- Who will be leading this from the governance working group? 

Thanks and we look forward to the updates!

**Comment by joberding** [comment]
Thanks for the feedback @blocks8. The Governance group will discuss tomorrow and provide further information.

**Comment by joberding** [comment]
Update: 
@blocks8 I will lead the COC project. @HaroldDavis3 will lead the voting mechanism project. Further info to come.

**Comment by RaffiSapire** [comment]
Hi there, is there an update here?

**Comment by joberding** [comment]
The Governance group is currently working on an update regarding the issues
raised on the voting mechanism side of the project. The code of conduct is
good to go unless there are further questions. As mentioned previously I
will be leading the code of conduct development

**Comment by jennymith** [comment]
Update: 

The governance group has decided to remove the technical component of M4 (build open source voting software) and instead, explore existing tools for implementation, such as PolicyKit. By the end of Q1 2021, we aim to implement a low tech, beta version of the selected voting mechanism that the community can sufficiently test throughout Q2.

Assuming that testing of the beta version is successful, and that community members want a more custom solution, we can consider renewing this grant to build out open source voting software. The revised milestones are as follows:

M4: Implement a beta version of the voting mechanism using existing open source tools ($450)
M5: Use selected voting mechanism / tools to ratify Can’t Be Evil Code of Conduct ($60)

And, as Juliet has mentioned, she and Harold will be leading each of the projects outlined in this grant.

**Comment by RaffiSapire** [comment]
Great, thank you @jennymith ! This is approved. The next step is to email grants@stacks.org and we'll send over a contract so we can disburse funds. We are so stoked to see this come to life, thank you for spending time on it.

**Comment by jennymith** [comment]
Amazing!! Thanks so much @RaffiSapire. I'll coordinate with the governance group to figure out the best person to coordinate on funds.

**Comment by joberding** [comment]
@RaffiSapire I sent an email as requested on Thursday, December 3. Please advise if you need any further information.

**Comment by joberding** [comment]
The current project management of this grant proposal resides [here](https://github.com/stacksgov/pm/issues/119).

**Comment by joberding** [comment]
@RaffiSapire  I have not received an invite from Bill.com
@jennymith contract was executed on 8 December 2020

**Comment by RaffiSapire** [comment]
Hello! Thank you for all your hard work this year. We would love to send you a holiday note and some custom stacks stickers. Please email me at Raffi@stacks.org with you and your name/address if you'd like to receive one. We really appreciate all your help and contributions. Stacks is what it is because of you!

**Comment by RaffiSapire** [comment]
Hi @joberding , wanted to check in and see if there are any updates here?

**Comment by joberding** [comment]
Hi Raffi, 
Our most recent updates from last week (as well as all previous updates) live here: https://github.com/stacksgov/pm/issues/119
Both Harold and I regularly post our updates on issue 119. Let me know if you need a different method for reporting.

I am currently using a working open approach with regularly updates to the documents in the links.
Working Documents

Project Overview
https://docs.google.com/document/d/1eYJhrZhmqt9RcTJ-PkzRlzgt0Yl1d2tgjDj24SN2Mfs/edit?usp=sharing

RFC
https://docs.google.com/document/d/1e0bgdpHfhdc5LYIaW1koyFtlFAGpw0LN8qjgZez0zl0/edit?usp=sharing 

I will be presenting the COC to the Governance group on Feb 4 and releasing it to the community for comment (RFC) that same day.  On Feb 11, I will present the COC on the Stacks demo day.

**Comment by RaffiSapire** [comment]
Hi there! I wanted to see if this grant has been completed, or if M2 is in the works currently?

**Comment by joberding** [comment]
Hi Raffi, 

On the Code of Conduct, We have completed M1, M2 and will soon complete M3 and M4. This project has taken longer than expected on M1 and M2. It was very important to us to encourage significant community feedback.  I am super proud that we had over 130 views on the forum. Thanks to the community for participating.

@HaroldDavis3 will report on the voting mechanism shortly.

**Comment by HaroldDavis3** [comment]
Will give detailed update on where we are with Metagov & Policykit combinations for community decision making testing 💯 Ty kindly for reaching out Juliet & Raffi.

**Comment by RaffiSapire** [comment]
Hi @joberding , wanted to check in on the status of this grant!

**Comment by RaffiSapire** [comment]
Hi @joberding , wanted to check in and see how this was going, if you could share the output deliverable if you're completed here? Anything we can support you on? thank you!

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
