### ISSUE TITLE
Clarity language logo design

### ISSUE THREAD

**Issue by fluidvoice** [stacksgov/Stacks-Grant-Launchpad#277]
**Background**
Hire a logo designer to design a logo for Clarity.
I made a simple one as an idea starter, that some on Discord liked..., Friedger, Dan, etc.

**Project Overview**
Self explanatory - the Clarity language should have a logo
Total Grant Request:  $1200

**Team**  [Fiverr.com](https://www.fiverr.com) site?
**Community and Supporting Materials**
Discord discussion [thread](https://discord.com/channels/621759717756370964/713087894260023377/937324152568807484)
Twitter discussion [thread](https://twitter.com/fmdroid/status/1488128552050515972). 
My idea for the logo (example in lower right below) is to have it resemble an (eye) since Clarity is **"what you see is what you get"** on-chain interpreted lang and an eye can easily encorporate a "C" shape in it.  It could be done with the Stacks purple color and with or without the Stacks nexus logo in the iris of the eye. Other chains/projects that use clarity could put their logo in the iris if it's left white/blank. Just some ideas.  
![clarity-x-logo](https://user-images.githubusercontent.com/373038/151718284-1d076203-daaa-46b1-920f-cad23862af87.png)

![lang-logos](https://user-images.githubusercontent.com/373038/151718030-a8b0602b-92e1-4862-820e-dac3a01e037b.png)

**Comment by fluidvoice** [comment]
example logo without the nexus:

![clarity-x-logo-no-nexus](https://user-images.githubusercontent.com/373038/151795426-874631da-2c5b-4ba0-9cbb-997981a37bf8.png)

**Comment by jhammond2012** [comment]
You should check out 99 Designs: https://99designs.com/logo-design

**Comment by jhammond2012** [comment]
Pricing info here: https://99designs.com/pricing/logo-design

**Comment by fluidvoice** [comment]
Another starting point for a designer could be something like the top of this coffee cup 
where the "C" is enclosed in parenthesis... **(C)** which is a focus on how the Clarity language looks visually with lots of parens.

![attachment_132305328](https://user-images.githubusercontent.com/373038/152156336-8f8703f9-dc81-47d1-a5dd-493b19beb65e.jpeg)

**Comment by Armando1Designer** [comment]
Hi @fluidvoice do you still need this job? I could do it.

**Comment by fluidvoice** [comment]
> Hi @fluidvoice do you still need this job? I could do it.

Hi Armando, Can you post a link to some of your previous designs? and your design fee is?

**Comment by Armando1Designer** [comment]
> > Hi @fluidvoice do you still need this job? I could do it.
> 
> Hi Armando, Can you post a link to some of your previous designs? and your design fee is?

Sure, you can see anyone [here](https://www.armandotorraco.it/loghi/). I can create for 250€ or 250$ or crypto.

**Comment by will-at-stacks** [comment]
Hi @fluidvoice -
Thanks for your leadership on this.  We would like the Clarity community to be included in the selection of the design - even if this means increasing the budget.  Please consider the following:
- Solicit initial designs from (3) designers
- Post them for initial review and twitter survey (we can promote or host the survey)
- The winning design would then get another round of development -> community feedback -> final revisions
- After the final design is agreed upon, the designer would need to provide industry standard size / file / color variations so that the design will work in different formats and be available for download from the Clarity website / repository.

Please give this some thought and revise your budget to reflect this increase scope and associated management on your behalf.

Thanks
Will

**Comment by fluidvoice** [comment]
Hi Will. sounds OK to me at first read. Will give it more thought and take a look at online design sites, n seek to identify 3 designers that look good to me.

**Comment by fluidvoice** [comment]
without spending an inordinate amount of time on the subject since we will be putting designs up on Discord for the community to eval, just some possible criteria to think about I found in a quick search...

- Memorable – highest recognition and recall 
- Including recognition at maximum distances 
- Aesthetically pleasing
- Timeless quality – the logo will not become dated
- Appropriate for the product/service category
- Has “breakthrough” quality, that is, it stands out in the midst of other logos 
- Reinforces the brand name or tagline or both
- Evokes positive emotions
- Has positive brand associations
- The icon does not evoke negative or unintended associations among the target audiences
- Fits in the spaces in which it will most likely appear – has the most advantageous (vertical/horizontal) orientation
- Including, is recognizable in small spaces
- A version of it looks good in black and white
- Works well with sub-brand or endorsed brand identities

**Comment by fluidvoice** [comment]
Investigating if these three can meet requirements (all about $400):

**99Designs** [Logo & Social media contest](https://en.99designs.com.br/social-media-pack) 
**Fiverr** [Logo design](https://www.fiverr.com/categories/graphics-design/creative-logo-design?source=visual_filters&ref=style%3Aflat_minimalist) 
**The Logo Company** [Logo + Social Media Pack + Headers](https://thelogocompany.net/services/logo-design/)

**Comment by fluidvoice** [comment]
@will-at-stacks I updated with details in the post above and updated the total Grant request amount in the original post Project Overview.

**Comment by fluidvoice** [comment]
@will-at-stacks I updated with details in the post above and updated the total Grant request amount in the original post Project Overview.

**Comment by will-at-stacks** [comment]
@fluidvoice thanks for revising.  I am approving now for $1200.  Best, Will

**Comment by fluidvoice** [comment]
> @fluidvoice thanks for revising. I am approving now for $1200. Best, Will

@will-at-stacks How do you deal with stacks to fiat conversion slippage?  
I just converted the STX received at the current USDT price on Binance of $1.193 which resulted in ~10% ($128) **less** total USD than the approved grant amount.  It's not a big deal in this case, but how do you deal with this with larger grant amounts?
maybe this was in the grant docs somewhere and I just didn't see it?

**Comment by fluidvoice** [comment]
Logo contest was paid/submitted to 99Designs. Awaiting publication.

**Comment by fluidvoice** [comment]
9 designers submitted designs in the design contest. 2 days left for phase 1 submittals.

**Comment by fluidvoice** [comment]
First phase has ended. Here are 4 designs from 3 designers. The better designs IMO with a bit different takes on the primary ideas.  @will-at-stacks you want to send out a twitter poll, or how do you want to get community feedback?

![#36](https://user-images.githubusercontent.com/373038/156191124-73c597c4-e170-497b-becd-f776ed6adf9e.png)
![#82](https://user-images.githubusercontent.com/373038/156191134-6d7c9dcf-a1ab-466b-875d-33e5b061ac2b.png)
![#83](https://user-images.githubusercontent.com/373038/156191138-88d0343b-1ed5-4e61-95f3-44a9b74902fb.png)
![#91](https://user-images.githubusercontent.com/373038/156191141-8c071a92-41d4-4e29-aee2-6431f2026be1.png)

**Comment by cuevasm** [comment]
I think we need to draw more attention to this before trimming it down to finalists. I just found out this was happening, I suspect many throughout the ecosystem will not have seen this either and we're missing out on a lot of great possible submissions/input. 

Would love to support you all in creating a clear plan to better amplify this throughout the network (and maybe include a prize) so everyone who might be interested is aware of and has time to submit suggestions and concepts.

**Comment by LNow** [comment]
@fluidvoice can you post somewhere all submissions?

**Comment by fluidvoice** [comment]
> I think we need to draw more attention to this before trimming it down to finalists. I just found out this was happening, I suspect many throughout the ecosystem will not have seen this either and we're missing out on a lot of great possible submissions/input.
> 
> Would love to support you all in creating a clear plan to better amplify this throughout the network (and maybe include a prize) so everyone who might be interested is aware of and has time to submit suggestions and concepts.

I was thinking the same thing when I was trying to pair down the huge number of submissions.
I was just going by the directions given by Will who wanted only 3 designers.  I'm not sure if I can reverse selection of the finalists let me see.

**Comment by fluidvoice** [comment]
> @fluidvoice can you post somewhere all submissions?

I don't know.  I could have before today when I chose 3 finalists. But now I'm not sure.
Will's direction was "Solicit initial designs from (3) designers"

**Comment by fluidvoice** [comment]
> I think we need to draw more attention to this before trimming it down to finalists. I just found out this was happening, I suspect many throughout the ecosystem will not have seen this either and we're missing out on a lot of great possible submissions/input.
> 
> Would love to support you all in creating a clear plan to better amplify this throughout the network (and maybe include a prize) so everyone who might be interested is aware of and has time to submit suggestions and concepts.

They have an option to extend the contest for $60 per day so that's a likely way to go back. I will try to extend it for another 2 days.

**Comment by will-at-stacks** [comment]
@cuevasm for context - the initial proposal was to just 'create a logo for clarity' for a set fee.  My goal was to increase the process so as to involve the community more.  I did not want to over-inflate the budget so I suggested the following process so that @fluidvoice could feel empowered and we could also get a fair amount of community feedback.  

- Solicit initial designs from (3) designers
- Post them for initial review and twitter survey (we can promote or host the survey)
- The winning design would then get another round of development -> community feedback -> final revisions
- After the final design is agreed upon, the designer would need to provide industry standard size / file / color variations so that the design will work in different formats and be available for download from the Clarity website / repository.

If you have thoughts on how to proceed please let us know @cuevasm 

@fluidvoice lets just pause now until we get some direction from Mitchell.  Thanks, Will

**Comment by fluidvoice** [comment]
> @fluidvoice lets just pause now until we get some direction from Mitchell. Thanks, Will

@will-at-stacks I opened a ticket with their support to find out if I can move back to the qualifying phase.  I already paid for 2 extra days to extend the contest thinking that would do it but no. Awaiting support's reply.

**Comment by will-at-stacks** [comment]
@cuevasm yes, happy to support.  || @fluidvoice please let me know what you have paid out from the approved $1200 and we can conclude grant without completing it - and then work with you on submitting a fresh grant once we get feedback from Ginny and have a plan of attack that includes feedback from her and Mitchell.

**Comment by cuevasm** [comment]
I'm more than happy to increase the budget here to get this all done to the best of our collective ability. Mainly I want to optimize for more participation from the community for something like this, so let's start with building awareness for the opportunity to submit logos. 

We can have the social team put some comms together out on the main handle and make sure the word gets out. Before we do so, @fluidvoice what's the ideal way for people to submit logos? Do you want them to do that here on this thread or post elsewhere? Maybe we can start a fresh issue that's just submission files so people can quickly scroll through and comment?

**Comment by fluidvoice** [comment]
> please let me know what you have paid out from the approved $1200

$677

![image](https://user-images.githubusercontent.com/373038/156207355-bdb6da41-4439-4f27-b585-94a99a1898b7.png)

**Comment by will-at-stacks** [comment]
@fluidvoice thanks for the transparency.  Since the full $1200 was already disbursed, we will just apply the $523 credit to the grant we issue once this process resumes.  Does that sound agreeable?

**Comment by fluidvoice** [comment]
> @fluidvoice what's the ideal way for people to submit logos? Do you want them to do that here on this thread or post elsewhere? Maybe we can start a fresh issue that's just submission files so people can quickly scroll through and comment?

@cuevasm I think 99Designs site might work well for managing this as they allow [requesting designers to join a design contest](https://support.99designs.com/hc/en-us/articles/204761975) and they have a [polling tool](https://support.99designs.com/hc/en-us/articles/204109499-What-s-the-poll-tool-for-) built in that can be used to gather feedback.  Overall [how the contest works](https://support.99designs.com/hc/en-us/sections/201001515-How-contests-work) docs.

**Comment by fluidvoice** [comment]
> 

@will-at-stacks  I think we should wait until we have decided how we want to run another contest.  If we do it again on 99Designs while inviting other (outside) designers, we may want to increase the contest award amount to get more and higher quality designers.  @cuevasm thoughts?

**Comment by eugeniadigon** [comment]
Hi everyone,
If I can chime in, one of the issues in my opinion with delegating this to an outsider designer is that there's lack of context and hence there could be a lack of understanding of what this logo needs. Are we providing them with a brief? Do they know in which context / platforms / supports will this logo probably be used? I think these are important questions to raise since this is not a typical company/startup logo, which is the biggest market of sites like Fiverr or 99designs.

I think it could be much more interesting to open/focus this more in our community and make community-efforts improvements to proposals. I'm planning on submitting some proposals soon btw!

**Comment by fluidvoice** [comment]
> Hi everyone, If I can chime in, one of the issues in my opinion with delegating this to an outsider designer is that there's lack of context and hence there could be a lack of understanding of what this logo needs. Are we providing them with a brief? Do they know in which context / platforms / supports will this logo probably be used? I think these are important questions to raise since this is not a typical company/startup logo, which is the biggest market of sites like Fiverr or 99designs.
> 
> I think it could be much more interesting to open/focus this more in our community and make community-efforts improvements to proposals. I'm planning on submitting some proposals soon btw!

Hi @eugeniadigon thanks for the feedback. It's not being delegated to any one outside designer.  
I'm a Stacks OG community member helping manage this.
I gave this short brief and the following inputs (images).
I'm open to suggestions on how this brief can be improved, thanks.

```
Existing site: https://clarity-lang.org
Primary things that set's it apart:
* it's predictable and secure (no surprises)
* it's "what you see is what you get" open and transparent.
* it visually has a lot of parenthesis characters... "(" and ")"
so starting points might be an eye and the letter "C" - see attached images.
* Logo should be easily recognized in a browser tab (see attached image)
* A color (non black and white) version of the logo should use primarily the purple color of stacks.co and stacks.org
news: https://www.hiro.so/blog/clarity-making-it-github-official
```

![image](https://user-images.githubusercontent.com/373038/156214680-5859dac6-5f4d-46d3-b1aa-dd79d8302888.png)
![image](https://user-images.githubusercontent.com/373038/156214787-da569f23-7ae0-4892-872d-9d65b0a56285.png)
![image](https://user-images.githubusercontent.com/373038/156215065-4214741b-a1c5-42e7-8774-5b0627989b9c.png)

**Comment by fluidvoice** [comment]
> @fluidvoice thanks for the transparency. Since the full $1200 was already disbursed, we will just apply the $523 credit to the grant we issue once this process resumes. Does that sound agreeable?

@will-at-stacks , @cuevasm  Here's how we can proceed. **Please comment asap.**  -Brad-

I will chose a winner out of the 3 in the current contest and close it out. 
That winning design can serve as a starter idea for the **new competition** which will be performed as follows:

### Design Brief
I will post the design brief on the discord Clarity channel to solicit feedback from dev's to improve the initial brief I created. The brief is what the product/brand stands for, style, etc., directions for look n feel given to designers for guidance.
We can include the winning design from the previous contest as an example.
### New Contest 
(on 99Designs again)
**Outside designers:** the community can refer other designers and we can invite them to the 99Designs contest.
**Reward:** we can increase the contest winner reward to any value we want.  (note previous contest was around $500)
Six finalists are chosen from submitted designs during the qualifying round. 
**Feedback:** we can solicit feedback from the community on twitter during both the qualifying round and after the six finalists have refined their designs based on feedback given.

### Previous Design Brief
```
Primary things that set's Clarity apart:
* it's predictable and secure (no surprises)
* it's "what you see is what you get" open and transparent.
* it visually has a lot of parenthesis characters... "(" and ")"
so starting points might be an eye and the letter "C" - see attached images.
* Logo should be easily recognized in a favicon (browser tab) see attached image
* A color (non black and white) version of the logo should use primarily the purple color of stacks.co and stacks.org
```

**Comment by fluidvoice** [comment]
> Would love to support you all in creating a clear plan to better amplify this throughout the network (and maybe include a prize) so everyone who might be interested is aware of and has time to submit suggestions and concepts.

awaiting feedback in my post above.

**Comment by fluidvoice** [comment]
for the current contest I went ahead a solicited feedback from people in the Clarity discord channel here.
Might as well see what people think about the current crop of designs.  I specified that none of these will be the final design and we will like have another (larger) design contest to determine final design:
https://discord.com/channels/621759717756370964/713087894260023377/949067719272173598

**Comment by fluidvoice** [comment]
The first/prelim logo contest has ended. I saved many of the submissions [here](https://drive.google.com/drive/folders/1qen85A-V4GMCQrmqHKI9qn7Y3Butbl_C?usp=sharing) so that they can be used for a subsequent logo design contest:
https://drive.google.com/drive/folders/1qen85A-V4GMCQrmqHKI9qn7Y3Butbl_C?usp=sharing
For this contest, I ended up choosing one of the simpler designs as the winner (see below) as there was no consensus from the community.
Note: Community feedback on Discord showed most people did not like eye/eyeball focused designs that were supposed to cannote the _"what you see is what you get"_ aspect of Clarity.


![attachment_133937500](https://user-images.githubusercontent.com/373038/158064884-5bde1e69-1ba4-4ec0-82cd-0b3e80a76fa9.png)

**Comment by fluidvoice** [comment]
Another from the **same designer** and chosen contest winner is below.  I think it may have potential **but** needs further improvement IMO to bring out the "C" so it's more obvious/visible.  It reminded me a little of the Blockstream.com logo.
![attachment_133937615](https://user-images.githubusercontent.com/373038/158065428-6cb7c3d4-fd43-4bac-a36b-634838bcb435.png)

**Comment by fluidvoice** [comment]
I personally liked this one (also from the same designer) but most people on Discord did not agree.

![attachment_133847208](https://user-images.githubusercontent.com/373038/158065787-7626c0a8-964b-4825-8f78-0eb692c22812.png)

**Comment by fluidvoice** [comment]
Here are some files of the winner that I chose - again, just because it was a simple design and Discord users' feedback gave no clear preference of the designs submitted:
![8f9e5c9f-ab68-4398-808e-50cf3a0617cf](https://user-images.githubusercontent.com/373038/158234666-865a7d53-b4cb-40c4-9a19-8aabd77092fe.png)
![74c4252f-d54c-4874-9d39-ff28ca69cb91](https://user-images.githubusercontent.com/373038/158234669-a14fd665-0f3b-4587-8ad0-f76f996d304c.png)
![d47041ee-f922-4abe-b19c-8d4ffce3ab2f](https://user-images.githubusercontent.com/373038/158234779-3c9eafe4-de0e-4cd1-bc32-597d39973fab.png)
![1e3297cd-2a6a-456e-b0c4-ca93dffc8ed4](https://user-images.githubusercontent.com/373038/158234661-53d5c597-cf8d-478d-b5b6-902c623987bf.png)

**Comment by eugeniadigon** [comment]
Was this closed because a decision was made? Just wondering because I'd still like to submit some proposals

**Comment by will-at-stacks** [comment]
Hi @eugeniadigon Nope, no decisions have been made.  We would love for you to submit some proposals.  Please email me and Mitchell and we can come up with a game plan for re-starting this process.  will@stacks.org / mitchell@stacks.org

@fluidvoice please email me as well so I have your contact and then I will loop you in to the discussion.

Best,
Will

**Comment by fluidvoice** [comment]
> will@stacks.org

OK, emailed you Will.
