### ISSUE TITLE
TRAJAN Reputation and Identity Appchain - MVP

### ISSUE THREAD

**Issue by RagnarLifthrasir** [stacksgov/Stacks-Grant-Launchpad#287]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

_TRAJAN seeks to use Stacks to replace and improve upon LinkedIn, AngelList, and Glassdoor. TRAJAN's unique features will also improve upon skill assessment tests, crowdfunding platforms, and identity/authentication solutions. TRAJAN is proof of good work, and empowering ledger of record for individuals and organizations._

**Project Overview**
What solution are you providing? Who will it serve?

_TRAJAN will be a new professional network "appchain" that mixes social media functionality with some unique features of the Stacks 2.0 block- chain. It has elements of LinkedIn, Glassdoor, CityCoins, and Boom.Money.
Using the Stacks blockchain will enable TRAJAN to have:_
_1. A native token that can earn a yield
2. NFTs with multiple functionalities
3. A developer fund and founder’s reward thanks to Proof of Transfer (PoX)_

_TRAJAN will serve those who will benefit from a Web 3.0 reputation and identity platform._

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

_The scope is to build an MVP consisting of 1) user-profiles and 2) the ability for users to endorse specific skills of other users with TRAJAN “medals” – NFTs with a one-to-three-word description. The final deliverable will be a fully functional MVP. We will measure success by the MVP working as designed and having it be tested by ten experienced, trusted members of the Stacks community._

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

_Total Grant Request: $20,000.
Weeks 1-4: Low-fi mockup, high-fi mockup, and alpha MVP
Weeks 5-6: Testing of MVP by community members and improvements based on feedback._

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

_Our team consists of Ragnar Lifthrasir and Jonathon Hammond.
Ragnar -
Founder of a Bitcoin colored coin real estate conveyance platform called VeloxRE. He completed the first every property transfer on the blockchain in a successful pilot program with the second-largest county in the US, Clark County (Chicago). For the innovations of VeloxRE, Ragnar won the “Top Founder” award at the 2017 Global Prop Tech Awards. Ragnar also founded the non-profit International Blockchain Real Estate Association (IBREA) which received two nominations for “Top Organization” by the Global PropTech awards and Inman Innovator awards, also in 2017
Jonathon -
Jonathon has been active in stacks since "Blockstack" days in early 2020. Since then, he and his team Pixel8 have worked with Stacks to build tooling including the Discord moderation bot and the Grants Dashboard. In addition, Pixel8 has collaborated with leaders in the Stacks ecosystem including a recent gaming company, Moonray_

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

_The deliverable has a clear scope, and the tech is straightforward, so we expect few obstacles.
The main risk is some event that would cause a delay, for example, a long sickness or family issue. But in such instances, our contingency plan is to request more time to complete the MVP or hire outside help_

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

_Ragnar has experience with Bitcoin colored coins and Jonathon has experience with Stacks since 2020. We have shared the TRAJAN white paper and a flowchart with three community members, including Jenny Mith and Will Corcoran. All three gave positive feedback plus a few suggestions for improvements. We've shared the broader concept and MVP idea with a few community members, who were also encouraging. In the future, we will share our plan on the Stacks Foundation and Syvita Guild Discord groups. We will ask a few trusted community members to test and review the MVP. Once we have the final deliverable, we will share it on Discord and possibly Twitter._

**Comment by RagerMajor** [comment]
Great concept. "Proof of good work" is immensely valuable, and it will be interesting to see how you can create positive feedback loops with some of the incentives that seem to be embedded here. There is a lot of work being done to attract and nurture Stacks developer talent which could perhaps serve as an expanded pilot for this post-MVP. I can envision other synergies with things like Ryder too.

Looking forward to seeing how this develops!

**Comment by RagnarLifthrasir** [comment]
Thanks. I'll say here that I  think TRAJAN could work with TRUBIT. And Ryder as well.

**Comment by reinaldobtc** [comment]
Very interesting the proof of good work concept, the skill assessments  feature can solve the fake endowment skills that are given  from strangers or people you just had a good conversation on LinkedIn with no proof of working together on something to really asses that work.  How do you see the nfts playing a role on Trajan ? Like the passport ticket to enter to an exclusive network ? Also just curious what does Trajan stands for ?

**Comment by will-at-stacks** [comment]
@RagnarLifthrasir and @jhammond2012 -

Thank you for the awesome proposal - there is a strong need for these types of utility NFTs with the emergence of DAO's on Stacks.  This application is approved!

Jonathon, I know for a FACT - you need more than 6 weeks to get this done - because I will have you too busy with other things lol.  That is my only area of concern.  

Lastly, @RagnarLifthrasir please dialog with some of the DAO teams as you develop this Dre Faulkman, StackerDAOs, @castig and Trubit.  You might also want to join the Ryder calls coming up.  They might have thoughts on possible applications.

Best, 
Will

**Comment by RagnarLifthrasir** [comment]
> 

Thanks, @reinaldobtc. The role of NFTs will have several functions. The initial MVP will use NFTs as endorsements and attestations of accomplishments and beneficial social behavior. They're a form of utility NFTs. We have a lot planned that other applications of NFTs and using Proof of Transfer.

"Trajan" references Trajan's Column. 
_The victory of the Roman emperor Trajan over the Dacians in back-to-back wars is carved in numerous scenes that spiral around a 126-foot marble pillar in Rome known as Trajan's Column. It's a tale that reads like an ancient comic strip. The emperor is the story's hero. He appears 58 times, depicted as a canny commander, accomplished statesman, and pious ruler. Here he is giving a speech to the troops; there he is thoughtfully conferring with his advisers; over there, presiding over a sacrifice to the gods. "It's Trajan's attempt to be not only a man of the army," Coarelli says, "but also a man of culture._ 
-https://www.nationalgeographic.com/trajan-column/article.html

Just as Emperor Trajan sat atop a column that recorded and displayed his unique character and accomplishments, so too will TRAJAN users sit atop a public, blockchain-based catalog of their unique character and accomplishments.

**Comment by RagnarLifthrasir** [comment]
> @RagnarLifthrasir and @jhammond2012 -
> 
> Thank you for the awesome proposal - there is a strong need for these types of utility NFTs with the emergence of DAO's on Stacks. This application is approved!
> 
> Jonathon, I know for a FACT - you need more than 6 weeks to get this done - because I will have you too busy with other things lol. That is my only area of concern.
> 
> Lastly, @RagnarLifthrasir please dialog with some of the DAO teams as you develop this Dre Faulkman, StackerDAOs, @castig and Trubit. You might also want to join the Ryder calls coming up. They might have thoughts on possible applications.
> 
> Best, Will

Will, thanks. I'll get in touch with the projects and people you mentioned.

**Comment by will-at-stacks** [comment]
@RagnarLifthrasir How are you?  Can you please give me a quick update on this grant?  Thanks, Will

**Comment by jhammond2012** [comment]
> @RagnarLifthrasir How are you? Can you please give me a quick update on this grant? Thanks, Will

Hey! I wanted to give an update from the technical side. We have started planning out some of the databases and APIs. We have also started laying out some UI. 

![Profile](https://user-images.githubusercontent.com/3857428/159333006-36d2fcc4-d1a4-4eb8-ac38-0d7dbe895856.png)

You were right about the timeline :D The new dashboard has us a little behind but things are moving :) In the coming weeks, we will start to materialize some things to show that you can actually touch and feel.

**Comment by RagnarLifthrasir** [comment]
> @RagnarLifthrasir How are you? Can you please give me a quick update on this grant? Thanks, Will

See Jonathon's response above. We'll accelerate now that Jonathon will start having more time.

**Comment by castig** [comment]
Interesting project, thanks for sharing. Are there any other names then TRAJAN? It really reminds me of TROJAN, or TRAGEDY. Happy to give more functional/strategic feedback if you ever want to connect.

**Comment by RagnarLifthrasir** [comment]
> Interesting project, thanks for sharing. Are there any other names then TRAJAN? It really reminds me of TROJAN, or TRAGEDY. Happy to give more functional/strategic feedback if you ever want to connect.

Thanks for following our project Chris. The name TRAJAN comes from [Trajan's Column](https://www.nationalgeographic.com/trajan-column/), a Roman triumphal column that commemorates Trajan's victory in the Dacian Wars. Similar to how the column immutably records and details Trajan's accomplishments, so does our TRAJAN app records and shares the positive attributes and successes of the app's users. (We also like that the name is easy to spell, say, and remember).

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
