### ISSUE TITLE
Novum Insights Grant 2: Log In with Hiro functionality, Dataverse Extension, Software Package Bundling

### ISSUE THREAD

**Issue by albydeca** [stacksgov/Stacks-Grant-Launchpad#309]
Hi, this is Alberto from Novum Insights. As promised, following the recent conversations between the Novum team and the Stacks Grants team, I am opening this grant application which substitutes M3 of our previous grant (#138). Given the familiarity with the team and the material detailed below, I will simply summarise in this post the details of the grant which we are applying to build.

PLEASE NOTE: this grant depends upon the successful implementation of the Hiro Wallet feature described [here](https://github.com/hirosystems/stacks-wallet-web/issues/1051).

## M1: Log In With Hiro Wallet - $15k
One of the great features that has come to prominence lately in the realm of crypto wallet browser extensions is the ability to digitally sign data using wallet private keys. This has enabled a wide range of extra auth-based operations to be performed, most notably logging in to websites using Web3 credentials, and thus allowing usage of a website without the need to hand over personal data (emails, names…) to its administrators. 

Novum Insights has already implemented two [production-ready](https://github.com/novum-insights/sveltekit-unlock-firebase) [systems](https://github.com/novum-insights/unlock-protocol-firebase) based on Metamask that allow:
- Logging in by digitally signing a cryptographic challenge
- Integration between Metamask and Firebase Cloud Firestore
- Fine-grained access control to website features using NFTs (via Unlock Protocol)

These systems are already deployed to great effect in our [Momentum Pairs](https://novuminsights.com/) product.

We are noticing with great appreciation that Hiro are looking to [implement](https://github.com/hirosystems/stacks-wallet-web/issues/1051) a digital signature feature in the coming weeks for its Web Wallet. This will allow us to be able to implement similar functionality to that in the software packages described above (the first, and possibly the second bullet points) and therefore in effect provide a “Log In with Stacks/Log In with Hiro” user experience packaged in an **open source** repo.

(Comms with the Hiro team will likely be quite significant for this milestone as we learn how their implementation works)

## M2: extend Dataverse with DEX activity data and rich NFT portfolio view - $15k
This milestone will apply the software piece developed in M1 to create an extra section to the Stacks Dataverse which would function in a similar (albeit much more limited) way to Zerion. Zerion allows users to inspect the portfolio value of a given wallet in USD, as well as provide extra features to logged in members. We plan to therefore create an MVP for an extra section to the Dataverse application. This will:
- Provide a search functionality that allows users to provide an STX wallet address and the portfolio of the address (in terms of NFTs and token balances) will be provided, together with its combined USD value. - `this will be open source`
- For logged in users with Hiro Wallet, provide a separate area of the website to allow the user to perform extra features which require sending transactions. We are likely to provide in this area the possibility to send/receive STX using a similar UX to web wallet apps such as MyEtherWallet. This section is intended as an MVP demonstrator for our login functionality in action, and once M3 below is implemented, it can be picked up by other developers to build upon.
- We will investigate the possibility of documenting TVL on different platforms and where funds are going as well as money flows across all of Stacks - `this will be open source`

## M3: An Apache Airflow implementation of the Dataverse Backend and a SvelteKit implementation of the Dataverse Frontend - $15k
M3 ties together all the work Novum Insights has done for Stacks and makes it available for the community to further develop. The artifacts that will come out of this milestone are as follows:
- An [Apache Airflow ](https://airflow.apache.org/)implementation of the endpoints that make up the Stacks Dataverse M1 and M2 from the previous grant. This essentially consists of a Docker image which can be hosted on a remote server. This will fetch data from various existing Stacks APIs as well as the database, and put the computation results in an AWS S3 bucket for subsequent fruition by an [AWS CloudFront](https://en.wikipedia.org/wiki/Amazon_CloudFront) API (this is how Dataverse is currently built). A developer may then:
-- Extend the Python codebase to implement further data points or modify existing ones
-- Reduce the current implementation’s overreliance on third-party APIs by fetching some of the data natively
-- Set the docker image up as a source for any other application that may rely upon it.
- A [SvelteKit](https://kit.svelte.dev/) implementation of the Dataverse website frontend. This includes the charting, style and integration with the backend mentioned above (TypeScript). Once in possession of this codebase, a future developer may:
Use the template for a different data product
- Extend/host their own version of the Dataverse on a CC-BY basis.

**Comment by tycho1212** [comment]
Hey guys! Just re-read grant #138 and this addition. I'm very excited about this.

> We will investigate the possibility of documenting TVL on different platforms and where funds are going as well as money flows across all of Stacks

This would also be a big unlock for DeFi on Stacks. I often speak to investors with my DeFi on Stacks hat on who ask about this kind of data. If there's anything Trust Machines can do to help speed this up feel free to ping me (twitter/discord is probably fastest)

**Comment by will-at-stacks** [comment]
Hi @albydeca please use the link below to schedule a time to discuss this grant application.  @markmhx could you please review this application?  Its my understanding that the Hiro wallet [dependency](https://github.com/hirosystems/stacks-wallet-web/issues/1051) they noted in the application is not yet on the wallet roadmap.  Thanks, Will

https://calendly.com/d/cq8-hj7-xq2/25-minute-meeting

**Comment by will-at-stacks** [comment]
@albydeca -  Thanks for chatting earlier.  I actually just heard that Hiro is prioritizing the arbitrary message signing and it will be done soon!  That being said, just revise your application to flag the open-source items.  Thanks, Will

**Comment by albydeca** [comment]
Hi Will, I have done this. Thanks :)

**Comment by markmhx** [comment]
The wallet team at Hiro is indeed actively working on supporting arbitrary message signing per https://github.com/hirosystems/stacks-wallet-web/issues/1051. We hope to release it sometime over the coming month, assuming we don't run into roadblocks.

> [Per M1] This will allow us to be able to implement similar functionality to that in the software packages described above (the first, and possibly the second bullet points) and therefore in effect provide a “Log In with Stacks/Log In with Hiro” user experience packaged in an open source repo.

I'm curious about the benefits sought here for authentication beyond what's currently provided by the current authentication flow supported by the Hiro Wallet? In effect, users can already "Log in with Stacks" using [the Connect library](https://github.com/hirosystems/connect) which integrates the Hiro Wallet.

> M2: extend Dataverse with DEX activity data and rich NFT portfolio view

I'm not sure why arbitrary message signing is needed for these functional requirements, which seem to need only an unsigned public address as provided by the user?

> We are likely to provide in this area the possibility to send/receive STX using a similar UX to web wallet apps such as MyEtherWallet. 

For this functionality in particular, what will be the advantages to sending and receiving STX from the app instead of the wallet itself?

Thanks in advance for the points of clarification and interest in using the Hiro Wallet to create new user experiences! 🙏

**Comment by albydeca** [comment]
Hi @markmhx 

Thank you for your prompt feedback.

Regarding your first point, we are looking to implement an authentication mechanism that is able to interface with off-chain authentication/data management systems such as Firebase (in fact we are keen to deliver M1 using a Firebase backend). By doing this, 1- any app that uses Cloud Firestore is able to support log in with Hiro Wallet and 2- access to specific user data can be achieved through Firestore as opposed to just Gaia. What's more, proving ownership of a STX address in an off-chain environment allows for a great expansion in potential functionality (as per an example in the related Github issue where one user [suggested](https://github.com/hirosystems/stacks-wallet-web/issues/1051#issuecomment-803028237) that some operations on an NFT be available only once a user has proven ownership of their address)

Which brings me on to the second and third points. We really wanted to use M2 as a light-touch demonstrator of what can be achieved by gatekeeping access to data/functionality via the system developed in M1. We agree that a send transaction screen is rather basic, and are happy to explore with you other possibilities which could have more value. For example, we had in mind to allow a user authenticated with a given wallet to Favourite a basket of STX tokens of their choosing, and then gain access to price movement data on those tokens in one screen once they re-authenticate with that address. [Zerion](https://app.zerion.io/favorites) do this already. Similarly, the user could view price movements of just those tokens which they own. We are flexible on this piece and happy to talk about how we could add value.

Cheers
Alberto

**Comment by will-at-stacks** [comment]
@albydeca - Thanks for meeting with us and talking through your project and any possible dependencies the other day.  Sounds like you have a pretty clear runway and the vast majority of the project will be open source to all.  We are excited to approve this project.  

Best,
Will

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will

**Comment by albydeca** [comment]
Hi all, this has now been ported to the Dashboard and awaits approval. Apologies for the slow turnaround on this.
