### ISSUE TITLE
Design of BloodFuse Platform on Stacks

### ISSUE THREAD

**Issue by ogasky** [stacksgov/Stacks-Grant-Launchpad#312]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

**https://bloodfuse.com** is going to be a web-application with blockchain technology incorporated into it, that connects blood donors to blood banks and hospitals that are in need of blood for their patients. This project is to address the challenge of blood shortage and reduce death rate in Nigeria. Also payment and reimbursement can be processed via crypto (STXs) and fiat. 

**Project Overview**
What solution are you providing? Who will it serve?

The goal of **https://bloodfuse.com** design project is to carry out user research, user personas, competitive analysis, flow diagram and high fidelity design. The design will be handed over to the developers team for proper development of the https://bloodfuse.com platform. It is key to note that details of the design project will be published online.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Figma will be used for the design and the deliverables are: 
- User Research
- User Personas
- Flow Diagram
- High Fidelity Design

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $10,000 USD

M1: User research, user personas, competitive analysis, user flow diagram (1 week)

M2: Brainstorming/affinity mapping, Sketch, low-fidelity design, (1 week)

M3: High-fidelity design, (1 week)

M4: iteration and handoff (1 week)

**Design Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

- Tochukwu Ubah, is a UI/UX Designer with several design projects to his credit. More details on https://www.behance.net/TochuCu
- Kutaje J. Oghenevwaire, is a UI/UX designer with several projects done. More details on https://www.behance.net/kutajbaba
- Onose Oghenevwogaga, is a Project Manager & Blockchain Community Advocate, https://www.linkedin.com/in/onose-ogaga/

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

This project is an innovative one on the blockchain, thus more time may be consumed to produce the design.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We have purchased the domain name and we have competent UI/UX designers for the project.

**Comment by will-at-stacks** [comment]
@ogasky thank you very much for repositioning your application per our conversation.  This looks great and is approved.  I am going to break this up into (4) $2500 milestones.  Please provide us with a link to a document highlighting each milestones deliverables for us to review prior to releasing the next payment. Best, Will

**Comment by ogasky** [comment]
@will-at-stacks here is the link https://bit.ly/BloodFuse-Design-Timeline as requested. Thank you.

**Comment by ogasky** [comment]
@will-at-stacks the onboarding link did not work and it was showing this words 

**No Pending Grants
We’re sorry, no onboarding is ready for you.
Please comment on the Github issue
if experiencing issues.**

> Congratulations. Your grant is now approved. Please complete the on-boarding link here: https://grants.stacks.org/onboard?q=511d85b066dfe94b195d9c709e22e96a

**Comment by will-at-stacks** [comment]
@jhammond2012 can you please look into this?

**Comment by will-at-stacks** [comment]
@ogasky the process is automated and requires you to type this message in your github comment so that that milestone will complete itself - !M1_Complete

you will do the same for M2 (!M2_Complete) M3, M4..

thanks

**Comment by ogasky** [comment]
@will-at-stacks  wow.... quite understood. Thanks.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
