### ISSUE TITLE
Speed Spend as Educational Web App

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#32]
## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

The docs site at Blockstack.org contains many valuable content. However, developers and users do not have the possibility to experience all the different feature and aspects of Stacks 2.0. The more accessible and easier it is to learn about the possibilities of Stacks 2.0 and the user-owned internet the faster it will be adopted.

## Project Overview

> What solution are you providing? Who will it serve?

This grant proposal is about building a web application that allows developers and users to experience and try out features of Stacks 2.0 and the user-owned internet. More precisely, the project aims to developed and maintain the [Speed Spend web application](https://github.com/friedger/speed-spend) as an educational site for developers and end users that will only run on testnet before and also after mainnet launch.

Speed Spend was introduced in [September 2020](https://forum.stacks.org/t/introduction-to-speed-spend/11193) and extended through the OpenRiff grant. The current state is described in a [separate post](https://forum.stacks.org/t/speed-spend-updates/11367).

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The project will deliver
* an update to the landing page of Speed Spend to improve the educational value of the site. References to the current documentation of docs.blockstack.org will be added.
* an update to Flip Coin at Two page that uses multi-signature accounts and gaia storage to reducing blockchain transaction costs for a flip coin gambling game with two players.
* a new page that interacts with the [Rocket Tutorial contracts](https://github.com/blockstack/clarity-js-sdk/tree/master/packages/clarity-tutorials/contracts/rocket-tutorial) allowing users to build their own rockets and rent out to other pilots. The Rocket Tutorial is already referenced in docs.blockstack.org
* hosting of Speed Spend on the new domain "speed-spend.org".

While developing these features, 4 online session will be held to discuss issues and progress with other web app developers as well as a 4 written article about Stacks 2.0 features contained in Speed Spend. One session and one article per week.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Budget: $2860

Weekly effort:
* development and documentation (10h)
* one online session (1h)
* one article (2h)

Duration: 4 weeks

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

* Friedger. I have developed the current code of Speed Spend. I am contributing to Stacks code base since 2018. I participated in the Docs week and received the Dr Docs reward.

I am happy to share this grant with other designers and developers.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The documentation system on docs.blockstack.org could be evolve into an interactive site that makes alternative web applications irrelevant. If this is happening I will integrate the existing parts of Speed Spend to the documentation system and add the proposed feature of this grant to that system.

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Joe Bender, Stacks developer evangelist, mentioned Speed Spend as valuable resource for developers in his presentations and material, e.g. on https://community.blockstack.org/clarity-resources

Speed Spend has been used to find and verify issues in Stacks 2.0 like
https://github.com/blockstack/stacks-blockchain/issues/1791 or https://github.com/blockstack/stacks.js/issues/852

**Source Code**
Speed Spend source code: github.com/friedger/speed-spend

**Publication**
The articles will be continued to be published on my [sigle blog](https://app.sigle.io/friedger.id). With announcements on twitter and the Freehold and Stacks discord.

**Discussion of draft proposal**
https://forum.stacks.org/t/grant-draft-speed-spend-as-educational-web-app/11368

**Comment by RaffiSapire** [comment]
Hi @friedger , we have funded you for a grant that was never completed, that we then transferred over to the second one you proposed, which is also incomplete. For us to approve a 3rd grant we need to be confident that you can complete a grant before funding a new one, which we can gain if you complete the prior grant that is still open. Then we can dig in here and spend time together scoping this out.

**Comment by friedger** [comment]
If you and the community sees the ESSFI proposal as a higher priority than this one, I am happy to complete the ESSFI project first. With the current low availability of web apps using Stacks, I think that would the wrong decision.

**Comment by RaffiSapire** [comment]
Hi @friedger thanks for sharing the rationale here, we can see this being valuable for Stacks 2.0 launch! This is approved. We'll use the existing $666 that would be "refunded" from the previous grant as the initial payment, and the balance of the remaining capital will be disbursed upon completion of M3.

**Comment by friedger** [comment]
Thank you for your support!

**Comment by RaffiSapire** [comment]
Thank YOU for all your great work and contribution.

**Comment by friedger** [comment]
Progress in week 7th - 11th Dec 2020:

* Domain setup and deployed: https://speed-spend.org
* Article about contract calls on Speed Spend and nft token problem:  http://www.openintents.org/blog/2020/12/11/contract-calls-on-speed-spend.html
* Rocket contracts extended, added tests
* Rocket page added https://speed-spend.org/rockets, still not working due to unmerged https://github.com/blockstack/ux/pull/666
* Discussion with Alex about landing page
* Discussion with Joe about developer session

**Comment by friedger** [comment]
Progress in week 14th - 18th Dec 2020:
* refactor speed spend using latest libraries, still in progress 
* update smart contracts and unit tests to clarity-js-lib 0.3.4
* split Speed Spend into three parts: tokens, contracts and NFTs

The current version is not deployed yet: https://github.com/friedger/speed-spend/tree/chore/refactor

The next two weeks will be holidays. Week 3 will start 4th January.

As the new authenticator Connect 2.0 will be soon be available to test, the online sessions mentioned in the proposal will start once it is online. Currently, it is not possible for the user to transfer fund or change network e.g. to mocknet.

----
other contributions: support for mining competition

**Comment by RaffiSapire** [comment]
Hello! Thank you for all your hard work this year. We would love to send you a holiday note and some custom stacks stickers. Please email me at Raffi@stacks.org with your name/address if you'd like to receive one. We really appreciate all your help and contributions. Stacks is what it is because of you!

**Comment by friedger** [comment]
Progress in week 4th - 8th Jan 2021:
* Changed contract and contract calls of Flip Coin at Two to multi sig transactions
* Deployed develop branch to be used with Stacks Wallet beta (https://develop--speed-spend.netlify.app/?authorigin=beta)
* Smaller updates on Rockets.

No article about multi sig tx, as the Stacks Wallet is not yet ready to use and the testnet was instable earlier in the week. This will be done as soon as the Stacks Wallet beta is merged into master and develoeprs can try it out.

With the upcoming mainnet launch, I expect more focus on the network than on app development. Therefore, week 4 will start on 18th Jan 2021.

**Comment by friedger** [comment]
With the current state of the testnet, week 4 for will start later. 

Also for speed-spend to make sense, username support by Stacks Wallet/Connect would be ideal.

For the online session, it would make sense to do this after the Clarity challenge ending mid Feb.

**Comment by RaffiSapire** [comment]
hey! I just wanted to check in to make sure I didn't miss anything, is this completed? Would you still like to do the Clarity challenge?

**Comment by RaffiSapire** [comment]
Hi there @friedger , let us know if this is still in the works, if its complete, or if you don't plan to finish it.

**Comment by friedger** [comment]
@RaffiSapire This is still work in progress. The blockers are mainly the alpha status of Stacks Wallet and the missing bns features. Also the NFT standard for rockets and monsters is still under discussion.

For the video sessions, I don't see any demand for it. Currently, all is about understanding the protocol.

**Comment by RaffiSapire** [comment]
@friedger Hi there, wanted to check in on the status of this grant. Will you be completing it or moving on to focus on the pool?

**Comment by friedger** [comment]
Update: Speed Spend has its first SIP 9 NFT on sale:

![Screenshot from 2021-04-06 23-40-35](https://user-images.githubusercontent.com/1449049/113782081-e9678780-9731-11eb-9d0b-b9bd0a0d89de.png)


This concludes the technical part.

The last remain part are the online sessions. I'll update here with proposed sessions that could be evergreens as discussed in the office hours.

**Comment by friedger** [comment]
40 hours development work has been done
12 hours documentation work has not been done

666$ has been paid.
2194$ has not been paid because the work has not been completed.

To simplify things and stay healthy, I close this proposal.
