### ISSUE TITLE
Quadratic funding contracts

### ISSUE THREAD

**Issue by eamonpenland** [stacksgov/Stacks-Grant-Launchpad#323]
**Background**

I wasn't able to find a grant making contract for stacks that supports quadratic funding as a grant distribution mechanism. Quadratic Funding is a mathematically optimal way to fund public goods in a democratic community where the number of contributors matters more than the actual amount funded. Other ecosystems have versions implemented and are raising community funding, and I would like to help bring this functionality to stacks. I identified an opensource solidity project [dgrants](https://github.com/dcgtc/dgrants) that powers [GitCoin](https://gitcoin.co/grants/) as a reference implementation from another ecosystem.

**Project Overview, Budget and Milestones**

This is a 3 part grant that will serve stacks developers as well as the greater community looking to support stacks initiatives.

M1. Clarity Contract (Port dgrants contract) (80 hrs) ($10,000)
- Technical Discovery
- Grant Registry
- Grant Round
- Payout Calculation Script (off-chain)
- Merkle Proof
- Claim mechanism
- At least 80% test coverage on clarity code
- scripts to retrieve grant round data and calculate match payouts for grants

> Notes:
> This contract will only support SIP-010-TOKENS
> The clarity implementation will be simplified compared to the dgrants contract as it will not include features like Swaps, nor will it require deploying a new contract and transferring funds to the grant round

M2. Executor Dao Integration (20hrs) ($2,500)
- Modify the contract to work within the Executor DAO framework.
- Provides Community members an opportunity to vote on adding Merkle Root so users don't need to "trust" round admin

M3. Develop UI (100 hrs) ($12,500)
- UI and Mockups
- Mockups for Grant Detail and Grant List Pages (20hrs) ($2500)
- UI Development for Mockups (80hrs) ($10,000)

Total Grant Request: $25,000

**Team**

I'm a FullStack dev, and I already deployed a simplistic [funding contract](https://explorer.stacks.co/txid/0x409a5d2ed677b56a8112ae288f3e14d9e5c80008dc95647647d4bfde25534f9e?chain=mainnet) to the stacks mainnet as part of the cityswaps website I was working on.

Sunny Lee is a senior Web Designer based out of New York. You can see her work [here](https://sunnylee.design)
We have worked together on many projects in the past, and she's excited to do explore the design space in Web3.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
I've done a good amount of upfront work to de-risk as much of the technical implementation as possible. I've explored and adapted Jude's Merkle implementation from [nftree](https://github.com/jcnelson/nftree) to support the off chain payout calculation.

**Community and Supporting Materials**
There has been a lot of community interest in more democratic forms of funding and voting on grant making. M1 of this grant is intended to be a reference implementation for other devs and agnostic to the community/specific implementation. My intent for M2 and M3 is to make this available to the city coins community as a trustless, democratic grant making mechanism to provide more utility for city coins.

**Comment by castig** [comment]
Very interesting! Would it just be a UI for quadratic voting, or also consensus type voting? Is it kind of like SnapShot for Stacks? I'd love to connect and hear more.

**Comment by eamonpenland** [comment]
Hey thanks for responding. So i've been most active in the city coins community, and I see this grant mechanism as an opportunity for the city wallet to distribute some of their funds to community initiatives with community buy in. So this is a payout/grant making contract. The UI would support this grant making functionality. I haven't fully thought through the ui, but it will probably have some basic information about the grant, contact information, on chain history, current projected match amount, and wallet integration to broadcast a donation

**Comment by will-at-stacks** [comment]
@eamonpenland Thanks for the application. I feel a lot of good can come from this grant - in terms of composable code for others to build with and the funding mechanism itself.  Personally, we at the Grants Program would love to chat with you about possible applications for it, once things are a bit further along.  Its also great to see you dialoging with @castig.  I am going to mention @MarvinJanssen too so he is aware we are approving this effort.  Congrats!  We look forward to reviewing your process along the way.  Best, Will

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will

**Comment by eamonpenland** [comment]
I started out with a straight port of the dgrants contract, but i ended up simplifying everything into one contract and performing the weighted calculation in the contract rather than calculating off chain and submitting a merkle root. here is the code for anyone that is interested https://github.com/eamonpenland/quadratic-stacks/blob/main/contracts/quadratic.clar

**Comment by will-at-stacks** [comment]
@eamonpenland thanks for passing this along!  I will ask some folks from the grants team to look into where your grant is on the dashboard (I couldn't find it either) and to take a look at your code.  Best, Will
