### ISSUE TITLE
Option for DID-based user data exchanges

### ISSUE THREAD

**Issue by Regulr3** [stacksgov/Stacks-Grant-Launchpad#324]
### **Background
What problems do you aim to solve? How does it serve the mission of a user-owned internet?**

Currently there is no way to easily engage, aggregate, or manage all of your data within the Stacks ecosystem. While your data may be stored in your own Gaia hub and only be accessible by the specific app that you created it on, there needs to be an intuitive place a user can go to interface with all of their data as they transition some from Web2 into Web3 while also accounting for the net new data users will create in Web3. We’re building a DID-backed ‘data vault’ for all users and entities within the Stacks ecosystem to use and build upon as they see fit. This will enable the needed flexibility in the future when more and more services and entities are interacting with each other across potentially various networks or blockchains, while not requiring interactions to rely on chain-specific identifiers (i.e. wallet addresses).

In addition to this, there needs to be a privacy-preserving manner in which to engage with each other that does not necessitate the exchange of value on chain in the public view. Peer DIDs provide this functionality and needed channels for exchange without always publicly revealing the participants. (Note: all Stacks accounts automatically create a Stacks and Bitcoin DID) 
DIDComm is the planned backing strategy for implementing peer-to-peer communications.

DIDs here will allow for interoperability across a brand’s apps or services to “read in” additional user data across a broad range of networks, applications, services, and data sources. 

Our core focus is on helping users of dapps or services within the Stacks ecosystem to start more formally using DIDs for all participants and agreements by expanding the plumbing and basic set of utilities that allow each respective party to engage with the data they create over time. We’re working towards providing both brands and consumers alike a Web3 toolkit to truly usher in the benefits that Web2 can and has provided us like personalized experiences, product recommendations, and additional conveniences when navigating the web in a privacy-preserving manner. 

With the above laid out, we’re delivering the following updates which were outlined in milestone 1 of our previously approved grant ‘Extending the Use Cases of NFTs” - Issue #233.

_(Spoke with Will, he recommended we close this previous grant and submit this new grant given what we have already built while also considering the previous grant funding being cut in half due to the timing of grant distribution occurring when the market dropped and the STX price dropped roughly 50%, such that we received less than half of the $7,500 we had scoped for M1; thus slowing down some of our progress)_

**M1 Deliverables - From previously approved grant ‘Extending NFT Use Cases’ (https://github.com/stacksgov/Stacks-Grants/issues/233)](https://github.com/stacksgov/Stacks-Grants/issues/233)**

_- A working draft SIP proposal for mutable-NFTs we have been exploring:_ 
(https://github.com/TrubitTech/Mutable-NFT-SIP)
(https://github.com/TrubitTech/TrubitTech/tree/prototype/mutable-nft-api/packages/mutable-nfts)
	_1. Contract state maintains an up-to-date mapping of an NFT's id to its metadata url
        2. An external API serves up any initial/default metadata for a given NFT_

_- Mutable clarity contracts:_
(https://github.com/TrubitTech/TrubitTech/blob/prototype/mutable-nft-api/packages/mutable-nfts/contracts/mutable-nft.clar)

_- Gaia utility & JSON schema for handling data ingestion:_
(https://github.com/TrubitTech/stacks.js-gaia)
(https://json-schemas.vercel.app/schema_customer.json)

_- Trie creation script for user keyword and filtering functionality:_
(https://github.com/TrubitTech/trie-script-2)

_- Data extraction and parsing via OAuth and zip upload _(Facebook & Instagram data so far):_
(https://github.com/TrubitTech/DataExtraction/tree/facebook)

_- NFTree creation and testing with sample data sets (in collaboration with JacobRyan):_
(https://github.com/TrubitTech/nftree-test)

**Watch the ‘Data Vault’ demo recording:** [Here is a recording of our functioning ‘Data Vault’ we’ve been building and testing](https://www.loom.com/share/016768cb44be47f18b217a0944bbb943) with direct input and feedback with focus groups over the last month to ensure the user experience is intuitive and offers functionality users will be able to immediately benefit from, both new to Stacks/Web3 or who are well versed in Stacks/Web3 already.

**COMPLETED:**

- User onboarding
- Wallet authorization
- ‘Data Vault’ UI/UX with core functionality, additional screens, intuitive user flows
- Handling file upload/support to store in Gaia
- Data parsing and extraction of data zip files (facebook and instagram; Google ongoing)
- Storing and transforming data uploads into JSON data schema within user’s Gaia hub
- First draft of new Mutable NFT SIP proposal
- Creation and testing implementation of NFTrees using sample data sets
- Started testing, designing, and integrating LNSwap into our wallet to make data monetization payouts in bitcoin possible without the need to convert between STX/BTC
- 3 focus groups with over 50 attendees to learn what data they are willing to share, in what context and with what entities, what overall user experience we have to provide to make our product easy to use, and what will motivate them to adopt our product.
- Polling and surveys to understand what core features ‘the masses’ will find most attractive and through what channels they would most likely adopt a wallet that came with offers like the one we’re building

### 
**Project Overview
What solution are you providing? Who will it serve?**

1. Support concealing the identity of users from brands by ensuring that all respondents/participants in a brand’s campaign happen client-side and involve no storage of any identifying participant data. All brand campaigns will be broadcasted to all available clients and each client will respond–building audiences dynamically.

2. Open source UI package with reusable components for projects in stacks ecosystem 

3. Open source Gaia utility library to make Gaia easier to use/understand for creators and users of stacks apps/services

In order to create the optimal user experience, we have found there needs to be a fully functional web-based UI/UX to interface with one’s data stored in Gaia. That user experience is best accomplished and delivered outside of the browser extension we have built given the limited screen space it has but also our desire to create and provide a set of libraries/packages that lets users and other services within the Stacks ecosystem better engage and manage their data within Gaia. The ‘Data Vault’ we have created already within the web extension is the best way to place more data into a user’s Gaia hub on the fly and for future endeavors, we can speak to around sites/dapps having the ability to read in a user's data via the extension and an SDK and other backed plumbing of sorts.

If we are to create a truly user-owned data layer where the data still has value and the desire to be exchanged with entities a user consents to, then we need the above-enumerated deliverables to be available by default. This ‘data vault’ will contain both Web2 and Web3 data and our Gaia utilities along with our open source UI packages will provide a user’s a far more compelling manner to engage with their data in Gaia.

### **Scope
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?**

The key components of the project will include the following:
- Brand-side application for creating campaigns and managing data
- Client-side application for managing data uploads and viewing targeted campaigns
- Campaign broadcasting and client-side acceptance of campaign (“Yes, I am part of the target for this campaign”)
- Open-source UI package with reusable components for projects on stacks ecosystem
- Open source Gaia utility library to make Gaia easier to use/understand

### **Budget and Milestones
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

**Total Grant Request: $40,000** 
_(this includes the $10k we were approved to receive from the previously approved grant where we have not received the M2 funding.)_

Projected total of 320 hours for all efforts related to the milestones outlined below.

**M1: Scope of work, deliverables, and grant amount of total. (160 hours - $20,000)**
Developing Client-side Application for data uploads and OAuth and supporting utility libraries. 

- Implement OAuth for the 10 most common Web2 platforms. _(This is so TRUBIT users can easily grant their wallet permission to access their Web2 data and then easily copy over specific data into their data vault. We conducted 3 focus groups with over 50 attendees to determine what platforms were most commonly used and matched that with those platforms that had open APIs for OAuth so we can easily pull in the scope of data necessary to create a fluid user experience.)_

- Upload CRUD (view uploaded data, delete uploaded data, upload new data)
- Campaign Feed
- Brand campaigns are broadcasted to all clients on creation, the client determines if it matches a user’s interests based on their uploaded data. 

**@trubit/storage open-sourced package for interacting with Gaia**
- Reading a user’s gaia contents
- Fetching specific paths/’directories’

**@trubit/ui open-sourced package for reusable components for projects on the stacks ecosystem**
- Transaction Feed
- Data Tags
- Buttons
- Inputs/Form Controls

**M2: Scope of work, deliverables, and grant amount of total. (160 hours - $20,000)
Expanding on the existing DID support to implement off-chain interactions via Peer DIDs.**

**1. Enabling Stacks users to view and use their DID as a means to establishing relationships and connections with dapps, services, and other stacks users**
- Authentication
- Communication
- Transactions
- Additional open-sourced package for reusable components for projects on the stacks ecosystem

**2. Creating an intuitive ‘in-app’ user experience that allows for both on-chain and off-chain Peer DID relationships and interactions between entities**
- Peer DID creation from both stx and btc addresses
- Establishing n-wise relationships while maintaining anonymity
- Secure communications and agreements 
- Rotating Peer DIDs (acting as an alias) for on-chain relationships and interactions
- Key rotation and adding/removing keys
- Maintaining rules, services, agents, and privileges

### **Team
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.**

We are a seasoned team of entrepreneurs, technologists, developers, and product specialists. 

- Stephen is a systems engineer and product lead handling product development, product design, user research and testing, and the implementation of decentralized IDs

- Joey is a full-stack developer with a background in design who has built and led a wide range of projects–including applications for automating industrial drone flight, and developer tooling for expanding Ford’s in-car UI. He helps steer the technical direction of our offerings/packages and will be focused on creating our open-source UI kit, deployable dynamic smart contracts, and the client-side application for users.

- Darren is a full-stack developer handling the front-end development of the ‘Data Vault’ browser extension integration and overall user experience for engaging with data within Gaia.

- Vigas is a full-stack developer handling the efforts for parsing, extracting, and sending data to the user's Gaia hub from a wide range of data sources. Vigas is also helping lead the OAuth integration efforts and manual zip file uploads.

- Pedro is a backend developer leading the Gaia hub utilities for data handling, storage, and overarching data schema to make interacting with data intuitive and easy for other developers

**Risks
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?**

The biggest risk we see is the possibility of data leakage or bugs in potential smart contracts as we seek to provide reusable templates that both data owners and data consumers can access, deploy, and enforce without having to know too much about the technical requirements. We are focusing on making these ‘privacy-preserving shared data access’ smart contract templates as clean and simple as possible in order to not overcomplicate ongoing relationships that need flexibility but also enforce strict constraints. 

One other unknown we would highlight at this stage is uncertainty around the scope and types of structured data that web3 apps will require in the future. We believe this is a “known unknown” at this stage, and the contingency plan is to build this as an open framework that can be adapted to accommodate evolving needs of the web3 world.

**Community and Supporting Materials
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?**

(https://twitter.com/TRUBIT_TECH/status/1504068897812713472?s=20&t=J4o696jirb1dy4GzvOUhiQ)

We have a ton of support from the community to build a tool in which we have named a user’s ‘data vault’ and have had really compelling feedback as to what this user experience must be like in order for the masses to find it useful and to ultimately take the time to adopt a tool like this. We’ve conducted 3 focus groups in the last month to learn what people really want to get out of their data, what they are willing to share vs. what they are not willing to share, and what their ultimate motivations will be when it comes to adopting a Web3 tool like the one we’re developing. 

We have multiple testimonials (see below) and have attracted interest from several podcasts including Crypto Internet Show with Muneeb, Patrick and others, The Built On Bitcoin Podcast with Jake, the GoldSilverBitcoin Podcast, and The Bitcoin Magazine Podcast. We’re active Syvita Guild members and are actively collaborating with other members within the community.

**Comment by linden** [comment]
This looks very interesting, especially how DIDs will cross both bitcoin/stacks, further cementing them together.

**Comment by will-at-stacks** [comment]
@Regulr3 -  Very excited to continue supporting development on this tech.  This is approved.  Please email me and lets set up a meeting for the last week in April to discuss progress and get you introduced to the new Gaia residents.  

Best,
Will

**Comment by Regulr3** [comment]
@will-at-stacks awesome - thanks!!!

Yes will ping you and also hopefully see you down in Miami this coming week :) Excited to deliver this soon to everyone!

**Comment by Regulr3** [comment]
Contract signed!

**Comment by Regulr3** [comment]
@will-at-stacks just wanted to check to see when we should expect grant funds dispersed? thanks!

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
