### ISSUE TITLE
Decentralized learning platform on Stacks

### ISSUE THREAD

**Issue by fanjum11** [stacksgov/Stacks-Grant-Launchpad#325]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Humans have been teaching and learning since times immemorial. And there have been many different methods of teaching.

Web3 based on blockchain technology provides a decentralized approach towards spreading knowledge. This we believe will be another effective approach for spreading knowledge on any topic efficiently.

An approach where everyone involved in spreading knowledge can be compensated without having to depend on trusted third parties. This approach towards teaching can be used to educate people about any topic - old traditional topics or new web3 related topics.

In order to bootstrap this new learning approach, we use the Learn to Earn technique. In this case, the learners are provided rewards upon demonstrating proof of learning.

There have been some efforts toward creating Learn to Earn systems. For example, Coinbase app has the feature whereby you can learn about a token or a web3 company. After that you are asked some questions related to what you learnt and if you provide the right answers you are rewarded some tokens. However, this approach is a centralized approach. Coinbase controls all aspects of this learn to earn journey. And then there are a lot of web2 systems that are focused on making learning efficient (Udemy, Maven, Coursera, Teachable etc) but every one of these solutions depends on a centralized party. 

Our objective is to create a decentralized learn-to-earn platform based on the Stacks blockchain - a platform that provides for smart contracts on Bitcoin.  A platform where everyone spreading education gets the right incentives while those receiving pays for that. A platform that is more in tune with the objectives of Stacks - to create a user owned Internet. 

**We plan to achieve this objective in multiple stages.** 

Stage 1: Getting a platform set up to make people aware of the Stacks way of doing things (wallets, NFTs,, swapping etc)
Stage 2: To create a learn to earn system where by learners can get tokens when they show proof of learning. Version 1 of such a system is at https://github.com/fanjum11/leos And the initial group can teach and pull in others to increase the set of learners.
Stage 3: Making the system self-sustaining whereby creators and curators are paid for their services by the learners. This is a system with no gatekeepers and anyone can be a creator, curator or a learner.

**This grant proposal covers the first stage where we educate people about how to use Stacks and a few select services based on Stacks.  The goal of the first stage is to get an initial set of users who have no idea about Stacks educated about the Stacks way of doing things (logging using wallets, transactions using Stacks etc)**

**Project Overview**
What solution are you providing? Who will it serve?

**Our focus is on stage 1 for this proposal.**

We propose to build a solution on the Stacks blockchain that is targeted at absolute beginners who have no idea about Stacks. The focus of this solution is on spreading education about Stacks. We will build a solution that teaches beginners the concepts of wallets, stacks transactions as well as to use some solutions of the Stacks ecosystem such as swapping, use of stablecoins, NFTs etc in the form of tasks. 

People who complete all tasks successfully will be provided NFTs. These NFTs will then be used as an admission ticket for the LEOS (learn to earn on Stacks) solution which is stage 2 and is not part of this proposal. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The final deliverable will consist of a web app that rewards users with an NFT on performing the following tasks. 

![image](https://user-images.githubusercontent.com/4590487/160478588-56aa5935-bf6a-4bb4-bbfb-6f5e583b4eb0.png)

![image](https://user-images.githubusercontent.com/4590487/160476054-22c42e7a-3332-4684-8420-76407093f5c1.png)

![image](https://user-images.githubusercontent.com/4590487/160476109-9b89ce69-36b0-458e-b458-3ec7806a8ce5.png)

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $25,000 

M1: 
Scope of work: As given earlier
Deliverable: React based Webapp tied to smart contracts on stacks that guide users through the 8 tasks 
Breakdown: 

Design of solution (UI and UX) : $5,000 (50 hours)
Low Fi mockup of complete solution (webapp and smart contracts): $10,000 (100 hours)
Final solution deployed on mainnet: $7,000 (80 hours)
Marketing into other discord channels: $3,000 (50+ hours)
Total Grant Request: $25,000 

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

@fanjum and @jiga plan to work on this. 

Between the two of us, we cover all aspects of the solution. Most recently we were part of the Clarity Camp Cohort 2 where we submitted the following solutions to the hackathon

- https://github.com/fanjum11/leos 
- https://github.com/jiga/veritygames
- https://github.com/jiga/pub2btc

In addition, we have both worked together at a web2 startup ([groguru.com](http://groguru.com/)) where all developed code is proprietary @jiga has experience with react and other frontend technologies. @fanjum  has experience with building machine learning models as well as with various aspects of building web3 solutions (twitter handle @blockchain092 )

We might also consider outsourcing the React part of the solution in order to accelerate development.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

We plan to market this solution once built on various discord servers not related to Stacks. This so that we can attract people who are aware of crypto but new to the Stacks system. This would be plan A. 

If this does not result in getting a significant set of users, then we will use twitter and reddit to get to these initial group of people.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Not directly related to the above but @jiga and @fanjum got the top 3 places in the Clarity Camp cohort 2 hackathon for the following submissions in order of their ranking according to the hackathon judges: 

- https://github.com/jiga/veritygames
- https://github.com/jiga/pub2btc
- https://github.com/fanjum11/leos 

The output of this work will be available to the community in a github repository. The project will result in open-source code available to the entire community.

**Comment by will-at-stacks** [comment]
Hi @fanjum11 Thanks for the proposal.  This is a really great project. Can you please make a couple of revisions:

1. Back out the STX Faucet from the project.  We are open to funding this, but would like to see the rest of the work come into focus first - and work with you to determine the best amount to fund for the faucet.  Maybe its less, maybe its more. (We would also like to hear how the faucet can be designed to prevent Stacks veterans from front-running the STX available.)
2. Lastly, can you please explicitly acknowledge that the project will result in open-source code available to the entire community.

Thanks,

Will

**Comment by fanjum11** [comment]
Hi Will
 I have made the two changes as suggested by you. thanks for your support.
farooq
@fanjum11

**Comment by will-at-stacks** [comment]
@fanjum11 -

Great.  Thank you for making the requested revisions.  This is approved.  Please keep you eye open for a contract to sign.  Questions on the contract or payments can be directed to shakti@stacks.org

Thanks
Will

**Comment by fanjum11** [comment]
Thanks Will and Kenny ; I would like to ack Kenny's help in polishing our proposal.

**Comment by MarvinJanssen** [comment]
Just want to state I am also very much in support of this grant 👍 both @fanjum and @jiga are great builders.

**Comment by will-at-stacks** [comment]
@fanjum11 did you have questions about the contract?  It appears it has not been signed yet.  Please note payments cannot be disbursed until it is signed.  Thanks, Will

**Comment by fanjum11** [comment]
@will-at-stacks i have no questions about the contract; in fact, docusign shows me that it's all signed. i will email you the documents separately that I got from docusign.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/).  In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.  

- If you have questions about the Grants Dashboard in general please email ambassadors@stacks.org.
- If you have questions regarding payments and/or contracts please email payments@stacks.org.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will

**Comment by will-at-stacks** [comment]
Also, please note we are marking this grant 'closed' for organizational purposes, but it is still 'open' on the Grants Dashboard.
