### ISSUE TITLE
STALLET - DApp Mobile Wallet for Non-Crypto Savvy Users

### ISSUE THREAD

**Issue by AJAyanbisi** [stacksgov/Stacks-Grant-Launchpad#328]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

This is a grant application to design and potentially build STALLET, an all-in-one cross-chain decentralized mobile wallet built on Stacks blockchain and ecosystem, for day-to-day crypto and blockchain activities such as DeFi, Cross-Chain Exchange, NFT, GameFi and Metaverse with main focus on non-crypto savvy users.

From time to time, blockchain wallet users encounter various problems, which can be really frustrating, tiring and discouraging. Users encounter multiple problems when swapping tokens, as these problems often involve a lot of money at stake and it is stressful to deal with them.

So because Web 3 is relatively new, users are still trying to find their feet in the space as the user experiences of most of the existing web 3 products are vague and require some level of expertise to use and interact with.

STALLET is on a mission to change the narrative by designing and building a non-crypto savvy user-centered blockchain wallet using the current web 2 onboarding, content and information architecture structural model.

**Project Overview**
What solution are you providing? Who will it serve?

As said earlier, STALLET is set to be an all-in-one cross-chain decentralized mobile wallet built on Stacks blockchain and ecosystem, for day-to-day crypto and blockchain activities such as DeFi, Cross-Chain Exchange, NFT, GameFi and Metaverse with main focus on non-crypto savvy users.

The solutions STALLET aims to offer are numerous; it will cater for the non-crypto savvy users by providing better guidance throughout their new wallet creation, wallet connecting experiences and it will serve as their gateway to the world of web3 blockchain.

The non-crypto savvy users will be able to perform all blockchain wallet functions like store, manage, swap and trade their cryptocurrencies. And also, they can store their NFTs and any other digital assets using the seamless and user-friendly wallet.

STALLET will be similar to building “[CLV Wallet](https://clv.org/)” equivalent wallet infrastructure for Stacks blockchain, ecosystem and community, and it will also use some of its existing models.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Final deliverables for this project will consist of the following, which will be;

1. To carry out extensive and detailed UX research, competitive analysis, create user persona, user journey, empathy mapping, and other aspects of the UX research that will help in designing and building STALLET to be the go-to user-centered dApp mobile wallet.
2. To design the entire flow and high fidelity screens of STALLET dApp mobile wallet.
3. To deliver logo and brand identity for STALLET. 
4. To create interactive prototypes using the high fidelity product designs of STALLET dApp  mobile wallet.
5. To build a design system for STALLET dApp mobile wallet.
6. To write a detailed case study explaining my design thinking and thoughts process behind STALLET dApp mobile wallet.
7. To document and publish STALLET design system Figma file link to the community as an open source project. 

NOTE: STALLET design system will be reusable by people, teams or entrepreneurs looking to build similar products using the design system components. 

 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

M1:
Deliverables: To carry out extensive and detailed UX research, competitive analysis, create user persona, user journey, empathy mapping, and other aspects of the UX research that will help in designing and building STALLET to be the go-to user-centered dApp mobile wallet.
Timeline Duration: 3 Weeks
Delivery Work Hours: 90 Hours
Grant Request: $7,200

M2:
Deliverables: To design the entire flow and high fidelity screens of STALLET dApps mobile wallet, to build the design system for STALLET dApp mobile wallet alongside the product designs and also to deliver logo and brand identity for STALLET. 
Timeline Duration: 9 Weeks
Delivery Work Hours: 270 Hours
Grant Request: $21,600

M3:
Deliverables: To create interactive prototypes using the high fidelity product designs of STALLET dApp  mobile wallet.
Timeline Duration: 2 Weeks
Delivery Work Hours: 60 Hours
Grant Request: $4,800

M4:
Deliverables: To write a detailed case study explaining my design thinking and thoughts process behind STALLET. And also to document and publish STALLET design system Figma file link to the community as an open source project. 
Timeline Duration: 2 Weeks
Delivery Work Hours: 60 Hours
Grant Request: $4,800

Total Timeline Duration: 16 Weeks (4 Months)
Total Estimated Delivery Work Hours: 480 Hours

Total Grant Request: $38,400

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Akorede J. Ayanbisi, a creative web 3 product designer with an interest in designing user-centered products that proffer solutions to real-time problems facing users.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

There are no risks involved for this product design phase of the product.

Risks will only be involved when the development of the product commences, as I also envision to build and develop STALLET dApp mobile wallet when the product design phase is over and ready for development. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Yes, I do have previous projects I have worked on. I’m currently working as the lead product designer on [Songs To Radio](https://github.com/stacksgov/Stacks-Grants/issues/252), a project which aims at decentralizing the music and creative industry and it is currently funded by Stacks foundation. 

I also have links to my portfolio projects listed below:

- The Responsive Redesign & Visual Improvements of Polkaswap Decentralized Exchange (DEX) Web App — A UX Case Study - https://medium.com/@AJAyanbisi/the-responsive-redesign-visual-improvements-of-polkaswap-decentralized-exchange-dex-web-app-309e4b753824
- User-Centered Redesign & Visual Improvements of UBA Mobile Banking App — A UX Case Study - https://medium.com/@AJAyanbisi/user-centered-redesign-visual-improvements-of-uba-mobile-banking-app-a-ux-case-study-382090339a49

Attached below are screenshots of positive feedbacks gotten from the Polkaswap community members.
![3C74C8FC-76AA-4926-BEDC-B0A8F98696E3](https://user-images.githubusercontent.com/66640761/161354638-f22c13b6-372e-41e7-88a2-d145831ad9e6.jpeg)
![8E18C405-EEE8-44D5-BD31-1E3B53887B5A](https://user-images.githubusercontent.com/66640761/161354643-4a4fc037-5fff-40e0-a155-079971284875.jpeg)
![FB0A8002-63FE-4CD4-A29F-6FD7C7AA99DA](https://user-images.githubusercontent.com/66640761/161354647-0988dda7-f189-424f-8728-6721340505c2.jpeg)
![D7BA8B2D-7C4D-432D-9CDD-FEF0A293275C](https://user-images.githubusercontent.com/66640761/161354653-d4a4c4ac-e0d6-4b6f-952d-48ff41334f58.jpeg)

Social Media Links:
Twitter: https://www.twitter.com/aj_ayanbisi
LinkedIn: https://www.linkedin.com/in/ajayanbisi

**Comment by will-at-stacks** [comment]
Hello AJ and thank you for the application!  

We would like to ask you to please submit your grant application again using our new [Grants Dashboard](https://grants.stacks.org/) since we will no longer be monitoring this repo.  

Thanks in advance, 
Will
