### ISSUE TITLE
Review the possibility to add a messaging component, to the ID and data storage components of a Stacks Dapp.

### ISSUE THREAD

**Issue by paradigma-cl** [stacksgov/Stacks-Grant-Launchpad#33]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user-owned internet?

In our development experience of the Dapp Paradigma CrossCheck https://crosscheck.paradigma.global/, we needed different types of communication messages or contents to be exchanged between users or between the user members of a group. Like sharing a private document, attaching files to that document, digitally signing a document, exchanging chat messages associated with a document, among other similar actions. Each document is by itself independent of the rest so it is private, only the allowed users can “understand” what it is written and can interact. This model must be improved to be more interactive and to scale up in the future.
Additionally, there is a consensed need in the Stacks community to facilitate interaction between other Dapps, and it was proposed to implement it using the concept of collections, that can exchange data between Dapps.

The actual Stacks Dapp Architecture considers a decentralized ID and storage, but we have realized that we could add a new component to it, a decentralized messaging component.
So the proposal is to review the possibility to add a messaging component, to the ID and data storage components of a Stacks Dapp.

## Project Overview

> What solution are you providing? Who will it serve?

Study and define the way to add a messaging component to the actual Stacks Dapp architecture seeing that some decentralized applications require interaction (exchange of information) between other users of the same application or to other applications. Similar to what has been discussed as collections.
It will serve all Dapp developers that need interaction between their Dapps or with other Dapps.

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The deliverables are 
1. Assessment of the use and type of data exchanges that the Dapps could require.
2. Assessment of the available messaging components (market available) that could be integrated into a Stacks Dapp Architecture.
3. Proposal of the component design to integrate the potential messaging component to the actual Stacks Dapp Architecture.
4. Proposal of a plan of action to continue or not with the project.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

The requested grant amount is equivalent to  USD 5.000 (five thousand US Dollars).
To be executed in not more than 5 weeks with an estimated effort of 120 person-hours.

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

This project is going to be executed by:
Paradigma Team
Phillip Roe-Smithson (Project leader), More than 20 years of software development of an application for the Mining, Airline, Financial, and Construction Industry; massive software applications for web publishing (Paradigma ToDoWeb) and multidevice Social application (Paradigma TimeMachine) and now the Dapp Paradigma CrossCheck based on the Stacks architecture.
Jose Fontirroig (Developer), more than 20 years of software development, a key developer of the Dapp Paradigma CrossCheck based on Stacks architecture.
Ivan Tabkha (Architecture), more than 20 years of software development of Billing applications for Oracle (Portal Software) and integration consulting professional services.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The risk of the project is associated with the complexity of the integration and its security measures of the available messaging components that makes the project not feasible. At the same time costs of its implementation. 

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan with the community over time and as the final deliverable?

The deliverables are going to be shared with the community and there will be a presentation of the results.

**Comment by jcnelson** [comment]
Hey @paradigma-cl, thank you for your grant proposal.

It sounds like your proposed deliverables are of an exploratory nature.  You're proposing investigating how to make it so that users can send and store messages to one another in an app, but not actually building out a particular implementation, right?  If so, then you might be aware that the design space of possible messaging systems in Blockstack has been explored multiple times [1] [2] [3] [4] [5] over the past three years, with some proposals reaching a prototype stage.  Have you and your team considered this prior exploratory work, and if so, what novel contribution would you be providing with this grant?

[1] https://forum.stacks.org/t/proposal-gaia-hub-inboxes/5114/4

[2] https://forum.stacks.org/t/proposal-chat-provider-for-inbox-notifications/6926

[3] https://forum.stacks.org/t/activitypub-social-network-proposal/7403

[4] https://forum.stacks.org/t/how-to-define-chat-provider-in-profile/7018

[5] https://forum.stacks.org/t/app-message-delivery-workflow/7704

**Comment by paradigma-cl** [comment]
Hey @jcnelson, thank you for your feedback and questions!
Yes, the deliverables are of an exploratory nature with the objective to propose the component design to integrate the potential messaging component to the actual Stacks Dapp Architecture and a plan of action to continue or not with the project.
A decentralized application architecture still is a new development that has not been tested thoroughly yet.  Stacks Ecosystem has proposed one based on BNS (Blockstack Name Service) that initially gives you an ID to login to your applications and access to decentralized storage.  Based on that we developed a DApp that needs interaction with other decentralized nodes and considered the reference consultation about that need.  The experience gained showed us that even though we built a way to interact between nodes, it was not sufficient if we want more interactivity and if the number of users and interaction will grow.
We evaluated to integrate a messaging service to our Dapp, but we came to the conclusion that functionality has to be part of the Dapp architecture for all the applications that are going to be built for this ecosystem.
So our added value with this proposal is to put into action this conclusion to add a messaging service to the Stacks Dapp architecture, organize some of the previous experience we had with the Dapp, search and analyze the messages queue services available in the industry, see the ways that can be integrated and feasible to deploy technically and economically, propose the component design to integrate the potential messaging component to the actual Stacks Dapp Architecture and a plan of action to continue or not with the project.
The deliverables of this proposal have to be presented to the community for consensus approval before anything is built.
It is a very important and essential component to improve the Stacks Dapp Architecture.

**Comment by RaffiSapire** [comment]
Hi there, Thanks for your thoughtful responses here. We really want to see this built and are excited to fund it. We're pleased to grant you $1000 for this research work as its laid out. We are interested in scoping out a larger grant for the implementation of this work as the follow up to this grant.

**Comment by paradigma-cl** [comment]
Humbly accepting the challenge to execute this research work in the allocated budget! Thank you very much for the confidence.

**Comment by RaffiSapire** [comment]
Super, we're excited to see this move into the next phase in the new year :) Please email grants@stacks.org and we'll set you up to get paid.

**Comment by RaffiSapire** [comment]
Hello! I've completed payment for this grant.

**Comment by RaffiSapire** [comment]
Hello! Thank you for all your hard work this year. We would love to send you a holiday note and some custom stacks stickers. Please email me at Raffi@stacks.org with you and your colleagues names/addresses if you'd like to receive one. We really appreciate all your help and contributions. Stacks is what it is because of you!

**Comment by RaffiSapire** [comment]
Hi @paradigma-cl , wanted to check in and see if you have any updates here?

**Comment by paradigma-cl** [comment]
Still working on the summary of characteristics of Distributed or Decentralized applications to conduct in an argumented way the Assessment of the use and type of data exchanges that the Dapps could require.  Hopefully delivering this delivery next week.

**Comment by RaffiSapire** [comment]
Hi there, circling back!

**Comment by paradigma-cl** [comment]
Glad to share the report of the Study renamed as A Proposal of Change of the components for the Stacks Decentralized Application Development Architecture.
https://github.com/paradigma-cl/stackscomponents
Please, share your comments, ideas, and suggestions in this repository.

**Comment by RaffiSapire** [comment]
Hi @paradigma-cl please share this in discord! Wanted to check to see is this grant complete with that deliverable? or are there next steps?

**Comment by paradigma-cl** [comment]
It has been a very active and busy take off!  Here is the publication in Discord.  https://discord.com/channels/621759717756370964/745215530868277319/817076230163660850

**Comment by vanesvibes** [comment]
@paradigma-cl Vane here! I am supporting the Grants in updated information. Could you let us know your discord username?

**Comment by paradigma-cl** [comment]
> @paradigma-cl Vane here! I am supporting the Grants in updated information. Could you let us know your discord username? My discord user name is phillip.xck.app
