### ISSUE TITLE
Grant - DualX Finance

### ISSUE THREAD

**Issue by westridgeblockchain** [stacksgov/Stacks-Grant-Launchpad#36]
**Background and Team**

Westridge Markets is a financial technology and proprietary trading firm. The founders have over 50 years of combined experience in derivatives risk management, high frequency trading technology and market making. Inspired by the use of writing options to enhance portfolio returns in the traditional finance space we thought of of a De-Fi exchange to do the same. Also seeing how AMMs in the DEX ecosystem currently work leaving LPs negatively exposed to large one way moves in price, gave us the idea to use the owners of these options as the LPs in a DEX. Thus providing liquidity against the long option positions. 

This gave birth to the idea of DualX - our first prize winning entry to the Stacks De-Fi Hackathon.

Our team profiles can be viewed at:
http://westridgemarkets.com/
http://dualx.finance/

Contact Person: Omer Suleman (omer@westridgemarkets.com)

**DualX**

DualX is a collection of Clarity smart contracts for Stacks 2.0 blockchain that will implement a De-Fi ecosystem of exchanges (DepX and GamX). 

It provides the opportunity for an investor (say denominated in BTC) to earn a yield on their funds while passively waiting to buy an investment asset (say STX) with those funds. This results in a deposit at the Deposit Exchange (DepX). The counterparty who takes this deposit in return for providing the yield receives a Deposit Token (dToken) certifying their ownership of the deposit. Also agreed between the Investor and the Yield Provider are the maturity of the deposit and a conversion rate between BTC and STX. This gives the Yield Provider an option to decide at maturity whether to return the original BTC amount or an equivalent STX amount converted at the conversion rate. They would choose whichever is more profitable for them.

In second phase of the implementation (to be completed later) the Yield Provider would then take their dToken to a DEX called Gamma Exchange (GamX). This would provide two-way liquidity in the BTC/STX pair on the back of the optionality that the dToken owner have from the choice of currency they want to return the investment in. This would result in a pool of liquidity like Uniswap with the dToken owners as the liquidity providers. However, given the trading is happening on the back of the deposit exposure they have, there would not be any “impermanent” loss to them. At the time of maturity, the dToken owners should have the funds available to them (BTC or STX) in the more favorable currency for them to return to the Investor. 
More details on the project can be seen on the project page at:

http://dualx.finance/

At Inception of the Contract: 

Yield provider provides the yield Y [BTC] Investor provides funds (B-Y) [BTC]. Effectively Investor has received the yield upfront. They both agree a maturity time T and conversion rate K such that K = B/X where X is equivalent amount of funds in STX. The Yield Provider receives X number of dTokens.
  
At Maturity of the Deposit:

The Yield Provider decides on a number P such that 0<=P<=1, and returns his dTokens along with any STX funds, to the contract. The Investor is given back:

P*X  [STX] + (1-P)*X*K [BTC]
  
Benefits:
 
The investor (who is a passive buyer of STX using his BTC) earns a yield in BTC and has the chance of buying STX or getting his BTC back. 

In second phase of the implementation where dTokens will be entered into GamX we will be able to create a native pool of liquidity of any asset (e.g. STX/BTC in our exampe) which could be a great tool used by new projects to generate liquidity without having to incur costs either through market makers on CEXs or through “impermanent” losses on DEXs. 

## Budget and Milestones

Applying for a grant of USD 5k. We expect to spend more than that on development effort over the next two months. Milestone would be to be able to have a basic working version of the project on mainnet launch and hopefully feature as an example of the De-Fi powers of STX. The project will be split over the following milestones across 8 weeks:

M1: (2 weeks) Smart contract for the Deposit Exchange (Development and testing)

M2: (1 week) Client Application Design and Development 

Beta release on Mainnet launch

M3: (2 weeks) Smart contract for Gamma Exchange (Development and testing)

M4: (2 week) Update to client application for Gamma exchange (Development and Integration + testing)

M5: (1 week) Bug fixes and stable release

## Risks

The GamX exchange is something that isn't like anything that has been implemented in De-Fi space yet. This requires calculating option greeks including delta and gamma possibly inside a smart contract. Given that the smart contract languages generally lack any high level constructs this could be a challenging exercise.

## Community and Supporting Materials
DualX as an idea got support from the internal community within Stacks Discord channel. It also received a mention in a cointelegraph article: https://cointelegraph.com/news/cosmos-and-blockstack-hackathons-offer-glimpse-into-defi-s-future. We feel confident that its a great idea

**Comment by RaffiSapire** [comment]
Hi there, we're excited to see this created. To approve this, we'd like to see you flush out your milestones in a more specific way so we have a sense of the timeline and what technically is being built over a few milestones, and how long it will take. Thank you!

**Comment by RaffiSapire** [comment]
@westridgeblockchain please do let us know!

**Comment by westridgeblockchain** [comment]
Updated the milestones section with breakdown off work

**Comment by westridgeblockchain** [comment]
Added the project website link in grant description for more details on the core idea and use case flows.

**Comment by RaffiSapire** [comment]
Hi thank you, this is approved, please email me at raffi@stacks.org and I'll send you a contract to get started!
