### ISSUE TITLE
Grant

### ISSUE THREAD

**Issue by OmurCataltepe** [stacksgov/Stacks-Grant-Launchpad#43]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

There are undecided investors because they can't find enough resources in Turkish. They can't be sure about what is the Stacks and the vision of the project. We want to solve it by reaching them from big platforms / communities and big influencers. We know big influencers around us.

## Project Overview

> What solution are you providing? Who will it serve?

We will introduce Stacks and the Stacks Technology to tens of thousands of Turkish investors. Because Turkey is the largest cryptocurrency investor in middle-east. There is great potential!

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

We will organize AMA in big communities (>5000 member each community) and making advertisements, events with big influencers. In the same time, we’ll create short and illustrative videos for introducing Proof of Transfer, Clarity, Stacks. We’ll translate important articles and papers to Turkish. For example Whitepaper 2.0, Overview of Stacks. Also we have stacksturkey.com website. The site is our local community website. There will be a newsletter and guide for Turkish investors. Articles about Stacks will published in there. Stacks's whitepaper will be translated into Turkish and will be published on this website. It will serve to all of the potential Turkish investors. I believe the project will be enough to solve that. This project will be the first community website for a cryptocurrency in Turkey.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

We are seeking 4.090$ for doing these jobs.

**Milestone 1:**

**Development:**
Building stacksturkey.com Website
Website Front-End Editions (6 hours) = 6 * 20$ = 120$
Website Back-End Development (Integrating Medium REST API and filtering the data - 12 hours) = 12 * 20$ = 240$
Website Contents (Including research - 6 hours) - 6 * 20$ = 120$
General Tests and Cyber Security Tests (6 hours)  - 6 * 20$ = 120$ 
Sum of Development Costs:  $600
**Marketing Side:**
Partnership between of Stacks Turkey and TFB Coin
Advertising for Stacks and stacksturkey.com - 500$
Business Planning and Meetings with TFB CEO and CMO - 4 hours (4 * 20$ = 80$)
Activity Competition 
Rewarding the most active and helpful members (5 member * 15$) - 75$
Creating Turkish Resources and Guides
Translate Whitepaper to Turkish (Technical) - Translating Fee (3800 words - 0.15$ per word) - 580$
Building a Todo app (Technical) - Translating Fee (1100 words - 0.15$ per word) - 165$
Stacks Auth with Angular  (Technical) - Translating Fee (600 words - 0.15$ per word) - 90$
Overview of Stacks (Document) - Translating Fee (750 words - 0.10$ per word) - 75$
Proof of Transfer Article (Document) - Translating Fee (250 words - 0.10$ per word) - 25$
Stacks Token Article (Document) - Translating Fee (400 words - 0.10$ per word) - 40$
Kazanc Rehberi (6.6k members - Including other events and ads) - 500$
Sum of Marketing Costs: $2.130

Sum of Milestone 1: **$2.730**
	
**Milestone 2:**

Marketing Side: 
Promotional Illustrative Videos
4 promotions illustration / animated videos for Stacking,PoX,Clarity,ecosystem (video during: 10 sec) 
4 hours for illustration
2 hours for editing and content researching
Total: 4 video * 6 hour = 24 hours = 24 * 20$ = 480$
Ask me Anything events (AMA)
Kripto Sozluk (7.5k members) - Paid
Preparing answers for AMA Questions from partipicans and Preparing Dialogs - 4 hours = 4 * 20$ = 80$
Business Planning and All Meetings with Influencers for AMA - 4 hours = 4 * 20$ = 80$
Second Local Town Hall (First town hall will be done after Mainnet)
Advertising fees - 300$
Live Stream - 1 hours = 20$
Preparing Speech Text and Materials (Including research) - 4 hours = 4 * 20$ = 80$
Cast Trials - 4 hours = 4 * 20$ = 80$ 
Preparing Promotional & Tutorial Videos
Introducing Stacking and PoX Mining with Big Influencers
How to do Stacking?   
Brief video of Stacks Turkey - Shooting Video and Trials - 6 hours + Video editing and Intro - 2 hours (8 * 20$ = 160$) 
Business Planning and All Meetings with the Influencers - 4 hours  (4 * 20$ = 80$)
Sum of Marketing Jobs: $1.360

Total: **4.090$**

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

Omur Cataltepe - Community Leader, Web Developer, Translator
Sahin Ali Bayar - Community Leader, Translator
Ata Aydin - Translator
Emre Akkaya - Moderation Jobs and Translating

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

If any influencer or community gives up partnership, we will organize events with another persons / communities on the same budget. We have alternatives for that. We cannot predict another risk as it will be a marketing work. 

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We have good contacts for doing that.
We organized AMA events and prepared promotional videos for Stacks and also Sahin Ali Bayar and Omur Cataltepe is leading Stacks Turkey. There is great activity in this community. Member count is increased 3000+ from 300. 
91% of our members are completely Turkish and organic. 

**All of the statistics are in "Stacks Turkey Community Growth Planning Doc" paper. If it'll be requested, we can share the document with authorities.**

**Comment by OmurCataltepe** [comment]
All of the agreements and meetings with influencers will be made within first week after the application's approving, so we want to be evaluated on a single milestone.  
We are planning handle all of these jobs in 4 weeks.

**Comment by RaffiSapire** [comment]
Hi Omur, we want to disburse in various milestones, vs one single milestone. Please break it out into 2-3 milestones. 

Thank you!

**Comment by OmurCataltepe** [comment]
Hey Raffi,
Application is updated
Best regards

**Comment by RaffiSapire** [comment]
Hi there, this is approved. Please email raffi@stacks.org and we'll get you signed up with a contract so we can pay you.

**Comment by louiseivan** [comment]
@blocks8 and @RaffiSapire Just a bit of overview here. @OmurCataltepe and Ali were able to grow Stacks Turkey over the course 6 weeks. Both leads were able to increase visibility and increase STX holders by building local social proofs and growing their own local community. See the overall growth progress below. It is important to take note that the overall arching strategy executed was token focused.  

✅ Building the first STX community-run website.
✅ Community-run socials (Medium and Twitter)
✅ Stacks Turkey Telegram Community ( 700 → 2009 → 3391 members)
✅ Stacks Turkey is the largest and most active community in the Stacks Ecosystem.
✅ Stacks Turkey is the 2nd largest crypto community in Turkey coming second from Ripple with 4,300 members. Their member count and activity statistics are far greater than Avalanche Turkey, Algorand Turkey, Ontology Turkey and Chainlink Turkey.
✅ More than 5.000 messages were sent between 31 December and 7 January. Compared to 2598 Messages in STX main channel in Telegram. 
✅ Their Cointag Sponsored Article lead to the purchase of 136,054 STX. 
✅ They lead partnership with Local Influencer (Eren Solzuk)
✅ Both leads did the first community represented AMA with Tutulamayanlar
✅ More than 7 local Turkish educational content was made
✅ Stacks 2.0 Turkish Translation
✅ Tons of organic content such as these amazing videos 👇 
https://discord.com/channels/621759717756370964/663696966206619678/797050043789869076

@OmurCataltepe and Ali are great community leaders. Can't wait for both of them to accelerate the growth of Stacks Turkey this 2021.

**Comment by OmurCataltepe** [comment]
We have completed the Milestone #1. Our report for Milestone #1 is attached.
Best regards,
Omur

[Grants - Milestone #1 - Issue #43.docx](https://github.com/stacksgov/Stacks-Grants/files/5959679/Grants.-.Milestone.1.-.Issue.43.docx)

**Comment by RaffiSapire** [comment]
Hello! This has been paid, thank you!
