### ISSUE TITLE
Community Pooling

### ISSUE THREAD

**Issue by dantrevino** [stacksgov/Stacks-Grant-Launchpad#52]
**Background**
> What problems do you aim to solve? How does it serve the mission of a user-owned internet?

Currently, user stacking is limited to a few companies offering custodial pooling services. While these have been hugely valuable to the community, several community projects could use a base smart contract that would lower the barrier to providing stacking pools for a diverse range of communities and applications and be extensible so that individual stacking pool providers can differentiate their services.

**Project Overview**
> What solution are you providing? Who will it serve?

There are two primary demographics targeted for this implementation:

- stacking pool providers (admins)
- individual stackers (users)

We will be building a protocol for community stacking pools that:

- creates a registry of stacking pool providers
    - allows stacking pool providers to add, update, and delete their information
    - allows stacking pool providers to customize within their own services:
        - specification of features unique to the pool provider, including any rates, fees, or trust-minimization options.
        - customization of reward returns
- facilitates basic delegation/pooling for users
    - allows looking up registry list and getting more info about stacking pool providers
    - allows selecting a stacking pool and handling delegation of funds
    - allows switching between pooling services (limited to one at a time)

![community_pool](https://user-images.githubusercontent.com/7738/108040031-a9b5d680-6ff1-11eb-8f79-0cbbf628cf96.jpg)

**Scope**
> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The final delivery will include:

1. A Pool PoX smart contract trait that stacking pool providers should implement.
2. A sample pool provider smart contract implementation for stacking pool providers.
3. A registry smart contract implementation that:
    1. utilizes the above smart contract trait
    2. allows stacking pool providers to provide pool details, including any trust minimization mechanisms, rates, fees, reward distribution, etc.
4. Sample code in HTML and JavaScript that demonstrates using the registry smart contract implementation listed above
    1. how users can see a list of stacking providers, including details about rewards, etc.
    1. how users can join a pool and receive rewards

**Budget and Milestones**
> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Budget Request: $5000

Timeline: 100 hours over 4 weeks 

- M1: 25 hours, design and validation 
- M2: 50 hours, development and testing
- M3: 25 hours, deployment and documentation

**M1**
- Estimate: 1 Week
- Reward: $1,250
- Time: 25 hours

Build the initial prototype, seek community feedback, provide a general outline for the development of all functionality described.

**M2**
- Estimate: 2 Weeks
- Reward: $2,500
- Time: 50 hours

Deploy contract(s) to testnet, encourage community testing, create related documentation.

**M3**
- Estimate: 1 Week
- Reward: $1,250
- Time: 25 hours

Deploy contract(s) to mainnet, final testing, polish documentation for release.

**Team**
> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

The team building this is the team behind Boom wallet and the Boom NFT contracts.

- Layton Diament: long-time community member and developer of NoteRiot, LandHo, Boom, Webby, and more.
- Dan Trevino: long time community evangelist and developer of NoteRiot, LandHo, Boom, Webby, and more
- James Botwina: long-time community member, Clarity hackathon winner, a contributor to Boom.

Support will also be provided from:

- Friedger Muffke: long-time community evangelist, Stacks contributor, developer of OI App Center, Clarity hackathon winner/judge, more.
- Jason Schrader: community evangelist, Stacks contributor, developer of Stacks 101 and Unmuteable, Clarity hackathon judge, more.

**Risks**
> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The primary team supports the live Boom application.  Support could impact the time devoted to delivery.

**Community and Supporting Materials**
> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

There is significant community interest in non-custodial delegated stacking pool providers. This implementation provides the opportunity to standardize how a community pool is implemented and provides a bootstrapped method for new pools to come online.

We will seek community input during each milestone via the Stacks Discord, Stacks Forum, and other applicable outlets. On final delivery, documentation will be provided to use the smart contracts outlined in the grant.

**Comment by hstove** [comment]
Although these are non-custodial in comparison to, say, OKCoin, there is still a big element of trust in terms of who you're delegating to - mainly trust that they'll give you the fair share of rewards. As a user, I would be more concerned with the trust element behind a delegator, and would not simply choose one off of a registry at random.

That's not to say this isn't the base of a good idea, but I would want to hear how you're thinking about that.

**Comment by dantrevino** [comment]
Thanks Hank.  I've removed mention of bonds as those were just one of the optional things a pooling provider might do in  an effort to minimize trust. 

The intention of the pooling trait and the registry are to attempt to lower the barrier for communities to create their own stacking pools.  In most cases, users may know and possibly trust, the pool they are seeking to join.  Pooling providers can implement whatever features are most important to their own target markets.

**Comment by friedger** [comment]
Providing analysis of different pool providers can be a business by itself and build on top of the registry contract.

**Comment by jennymith** [comment]
Agree with @dantrevino and @friedger here. I think the first step is making those various stacking pools readily available and accessible to community members. After that, it should be up to pool providers to figure out distribution and how to minimize trust in general (this information should be included in the registry though). 

I do think that keeping things like bonds in the project would be helpful for potential pool providers, just in terms of offering options like you mention, Dan (i.e. you don't have to be too prescriptive). If I were a pool provider, I'd appreciate some ideas for how to get started on minimizing trust and assume that those efforts would evolve the more I work with my community.

Love @friedger's idea that providing analysis could be a business by itself - another grant/contract idea? :)

**Comment by jcnelson** [comment]
If you're worried about trusting pool operators, one way to incentivize them to be honest is to put up STX collateral (or some other valuable asset) that can get slashed if they don't deliver the BTC on time.  The associated Clarity contract could require the pool operator to (a) pay out the BTC, and (b) submit a Merkle proof of inclusion for that transaction in the Clarity contract within a certain number of blocks.  Otherwise, some of their collateral (maybe an equivalent amount?) becomes steal-able by the intended BTC recipient.  I'm sure there are others, too.

**Comment by RaffiSapire** [comment]
Lets start with M1 being awarded as $5,000. We plan to fund M2 and M3 once that's completed, and we think you could expand the scope M2 and M3 from a value perspective once M1 is delivered to completion given the value that this will create for the community. 

Please email me at raffi@stacks.org and we'll get you set up on the backend! THank you and we are looking forward to working with you.

**Comment by dantrevino** [comment]
Milestone 1 update.  A more general version of this has been posted in the forum as well [here](https://forum.stacks.org/t/community-stacking-pools/11764).

Milestone 1 of our roadmap includes building an initial prototype. To find out what is needed to run a pool, "Friedger Pool" was created as soon as the Stacks Wallet supported delegation. It has been wildly successful. **Over 1 million STX from roughly 200 users** has been stacked in the initial test of a [community pool](https://forum.stacks.org/t/friedger-stacking-pool/11747) led by @friedger. I'm still amazed by this, but we intend to make it easier for communities to build their own stacking pools. We received a lot of feedback and questions that will help us to create better documentation and tools.

"Friedger Pool" uses a smart contract to manage the delegated STXs. This is based on the "Boom Pool" contract. You can find that [here](https://gitlab.com/riot.ai/clarity-boom-pool/-/tree/develop). This contract has been deployed to testnet.

The development of the prototype happens in the [`clarity-pool-registry` git repo](https://gitlab.com/riot.ai/clarity-pool-registry). It contains the following smart contracts and unit tests:
* `pool-tool` for pool administrators
* `pool-registry` for the registry of pools 

Development tasks

Over the next 2 weeks, we plan on: 

1. Document the process of delegation and running a pool

2. Document interfaces for the Pool Trait

3. Work with the community to build simple Pool Provider options and test, e.g. variations of Boom Pool and a Charity Pool.

4. Build the web application

**Comment by friedger** [comment]
For legal advice about running a pool in a Germany, we got an offer for around 15k$. Could that be part of this grant?

**Comment by friedger** [comment]
Here is a first documentation about how to run a Stacking pool: https://app.sigle.io/friedger.id/UOvy85BCSD-bjlrv_6q74

**Comment by dantrevino** [comment]
> For legal advice about running a pool in a Germany, we got an offer for around 15k$. Could that be part of this grant?

For that much I'd want to sent payment to RunRiot, rather than me.

**Comment by dantrevino** [comment]
Milestone 2 & 3 update. 

Apologies for the lateness of the update.

### Current State

Milestones 2 & 3 had us deploying to testnet and mainnet, as well as working with the community to validate pooling options. To date we have the following related pools currently operating on mainnet:

* Friedger Pool with 4M STX locked
* Xverse Stacking Pool with over 500,000 STX locked

These pools are in development:

* Boom Pool - in testnet
* Turkey Community - in testnet
* Korea Community - in testnet
* Stacks Evangelist Pool - in development

Additionally, the pool registry contract has been deployed to testnet.

Documentation for using and operating the pools is in progress, but can be found here:

* https://forum.stacks.org/t/stacking-delegation-now-supported-by-stacks-wallet/11739
* https://www.youtube.com/watch?v=TTf--N0Wj1g

### Next Steps

* deploy the pool registry to mainnet
* Sample app deployment for Pool discovery via the registry.  Expected to be deployed to speed-spend.org and stackstx.com when ready.

**Comment by friedger** [comment]
The pool registry contract has been updated according to feedback at

It has been deployed to testnet and can be tested via [Speed Spend](https://speed-spend.org/pools). 

As an extra, the contract registers a new BNS name if required: See this pool registration as an example:
https://explorer.stacks.co/txid/0x550f7e9094f185f5dec7155c33ff2dd79411ffcc086720b7f572b9b68e3541b4?chain=testnet

It has been deployed to mainnet:
https://explorer.stacks.co/txid/0x89cff4241836c31c6a47bc268225b379f076a04709a27ec4665b7747d191d9c2?chain=mainnet

This completes the final milestone of this proposal.
Thank you for your support!

**Comment by friedger** [comment]
!m3_complete

**Comment by dantrevino** [comment]
!m3_complete

Completing this, per comments above this work was done in early April.

**Comment by jennymith** [comment]
> !m3_complete
> 
> Completing this, per comments above this work was done in early April.

Hey @dantrevino just double checking that all work for this grant has been completed. Let us know if there's anything else you need support on--thanks!
