### ISSUE TITLE
Risidio Auction Development Phase II

### ISSUE THREAD

**Issue by radicleart** [stacksgov/Stacks-Grant-Launchpad#54]
**Background**

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

Risidio Auctions is a decentralised marketplace for NFTs and Digital Collectibles on the Stacks Blockchain. The first phase was completed in December 2020, creating a baseline of UI and Clarity functionality within a beautiful UI design. Since then, we have been busy developing our business plan and commercialisation strategy as well as thinking hard about our product development roadmap.

A key challenge in bootstrapping such a platform is that it requires a some commitment upfront before being ready to go to market. We don’t feel we are alone in managing an ambitious project and would like to propose the following solution to this bootstrapping problem in the hope it helps ourselves and others, to mitigate risks and increase transparency of our process for both the community and the Foundation.

We will align the milestone deliveries in the Stacks grant application process with our internal Agile process, making it possible to deliver features iteratively in a way that is visible and measurable. Internally we use the Scrum process to deliver software on a rolling 3 week long sprints fed by stories from a backlog of epics and top level features. 

In doing this we will match fund support from the Stacks Foundation, if forthcoming, by contributing to the costs of the development work. We will also manage the business development and marketing work, in support of our project, in a separate stream. This includes running marketing campaigns and initiatives looking for potential clients and partners and building investment pitches. Earlier this year we completed a very complex grant application to the UK Government Innovate fund for support with this Stacks project. In this way we hope to simplify things by asking for support towards our software development costs.

Our [full project plan]( ) is a Product Requirements Document (PRD) which describes our project at the level of epics and features. These larger pieces are broken down into user stories as they enter the backlog where they are prioritised for the upcoming sprint. We intend to update the Stacks Foundation on a rolling basis in line with our 3-week sprint cycle for support in delivering the platform.

The PRD is a live document which connects the development roadmap to the UX/UI, Design and Marketing activities (delivery of mockups, wireframes, social media campaigns, etc.).

**Project Overview**

> What solution are you providing? Who will it serve?

The main problem we intend to solve in the first milestone / sprint is that of decentralised bidding. We will implement the English Auction bidding strategy (incrementing bids up to the end time) on single items in the marketplace using Clarity Contracts deployed on the Xenon Network. The rules for the bidding strategy will be refined during the sprint planning but are roughly as follows:

Bidding commences when the seller places the item for sale by 'place bid'. The seller enters a reserve price and increment amount and chooses an end time / end block.

The bidding proceeds with each bid transferring the amount of the bid, in STX, into the contract (held in escrow). For all but the first bid, the value transferred in the previous bid is returned to the previous bidder's address.

Bids received below the current bid, plus the bid increment will be rejected, i.e. no value transferred. This will be enforced in the client code (to minimise gas fee costs) and also in the Clarity Contract - it should be noted that due to the possibility of concurrent bids enforcement in the client is not always possible.

The bidding end time will be determined in blocks. The end time set on bidding will be the block height of the longest fork of the Stacks blockchain at that time. Bids received by the contract at block heights greater than this will be rejected. The winning bid will be the last bid received in the block before this.

The winning bid will automatically transfer ownership of the NFT to the bidder and reset the sale data on the NFT.

The second major deliverable in this sprint, is the beginning of a new multi-media NFT application aimed at enabling musicians to register their music files as NFTs. The ultimate goal is an application where musicians can register music, set up royalties and connect to the Risidio Auction marketplace. The drivers for this are our extensive research on the impact of Covid-19 on the creative industries globally and also from our own contacts and network within the industry. Additionally, this application will accompany Loopbomb on the platform and enable us to explore many more possible use cases for the platform itself.

In addition we will use this milestone / sprint to get the project back up and running, redeploy our contracts on the Xenon testnet, reconnect our current test application (Loopbomb) and mint some items.

> How does it serve the mission of a user owned internet?

Our project is wholly focused on delivery of the User Owned Internet. All our activities will be focused in support of this goal:

 - Our roadmap includes charity auctions and crowdfunding features for dApps connected to the platform. We want to build features that support other dApps in the NFT space and help them gain user / customer engagement and commercial viability
 - Digital Collectibles are already a big deal on the ‘other blockchain'. We are building an alternative place for collectors to gather and buyers and sellers to trade NFTs - assets backed by the value and security of Bitcoin
   - Training and mentoring two trainee engineers:
    - Building dApps on the Stacks Network - using Auth and Gaia
 - Deploying and writing Clarity Contracts
 - Integrating with the Stacks Wallet
 - Introducing and training / mentoring market researchers and UX/UI Designers in the Stacks eco-system
 - Developing customer stories
 - Combining beautiful user interfaces and great UX/UI with blockchain development we intend to open up the technology for adoption by a wider audience

**Scope**

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Our main project plan describes the full scope for our marketplace and crowdfunding platform. It defines the major epics and top level features and provides links to the business case activities going on in parallel including, but not limited to, market analysis, market research, commercialisation and financials for the project. 

The scope in this context is tightly focused on the next sprint / milestone that goes towards delivering the platform as a whole. 

This 3 week sprint is organised around the following user stories. The user stories are printed in italic and the sub tasks included in a way to be easily copied to our Trello board.

User Stories

**User Story**

*As a buyer I need the asset transferred to my wallet on sale*

**Acceptance Criteria**

the Clarity Contract must do the following, atomically:

1. transfer the funds from buyer to seller
2. transfer the platform fee from buyer to seller
3. transfer the NFT ownership from buyer to seller

note: this story includes the work to get the project back up and running

4. application registry and minting contracts developed in Phase I deployed on Mocknet and Xenon
5. reference client application (Loopbomb) deployed
6. 20 assets minted by at least 3 creators
7. assets stored in Gaia and indexed by Risidio Search

**User Story**

*As a seller I want to be able to set my item for sale by bidding*

**Acceptance Criteria**

1. seller must be able to set the bid increment, reserve price and end time for the sale
2. once a bid is received the details cannot be changed

**User Story**

*As a bidder I want to see the current bid amount (current bid plus increment) and be able to send the required amount to attempt to purchase the item (depending on concurrent bids, being within the end time, etc.)*

**Acceptance Criteria**

1. A **stateless micro-service** is used to provide current bid levels to all clients via a web socket connection - this server component is needed to build efficient usage of blockchain resources

**User Story**

*As a seller I want the value of the winning bid to be transferred to my wallet*

**Acceptance Criteria**

1. deals with payment splitting for the platform fee and possible residual payments (e.g. royalties to artist)
2. deals with transfer of NFT from seller to buyer

**User Story**

*As a bidder I want to see the individual asset's bidding history*

**Acceptance Criteria**

1. integration with Vue Charts

**User Story**

*As a musician, I’d like to see the first iteration of the multi-media NFT registration application, Sticks n Tones, delivered for user awareness*

**Acceptance Criteria**

 1. home/holding page is displayed - the user is able to log in and out via the Stacks Wallet
 
note: this story includes the infrastructure and design work needed to get the project up an running;

 2. repository in github defined
 3. typescript client (vue) application created and pushed to origin
 4. using the wireframes from the design process, the app will deliver the home page and the ability to log in and log / connect to the blockchain via Stacks Wallet
 5. Upload form that saves the music file, cover image and meta data in user storage (via Gaia).

**Success Metrics**

Success at this stage is measured by transparency of our process. Our code and documentation are all open source. Furthermore, at the end of each sprint we hold a review for stakeholders - including an open invitation to community members. The reviews will present the work finished in the sprint and present an opportunity to discuss problems encountered and insights for future development.

We will post invitations to our reviews on Discord and via direct messages to partners in the Foundation

**Budget and Milestones**
> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $7,500

In this proposal are seeking support for development of the bidding features and supporting stories and to begin development of a second NFT application based on registering music files.

Based on the breakdown of these stories we estimate the following delivery in a 3 week sprint. 

| User Story                   | Days  |
| ----------------------------| ------------|
| As a buyer I need the asset transferred to my wallet on sale| 7 |
| As a seller I want to be able to list my item for sale by bidding|   1.5 |
| As a bidder I want to see the current bid amount (current bid plus increment) and be able to send the required amount to attempt to purchase the item|    7 |
| As a seller I want the value of the winning bid to be transferred to my wallet| 2 |
| As a bidder I want to see the assets bidding history| 3 |
| As a musician, I’d like to see the first iteration of the multi-media NFT registration application, Sticks n Tones, delivered for user awareness| 10 |
| Total Cost| $14,766 |
| Foundation Contribution| $7,500 |

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Team Member | Role
-- | --
Sara Garbini | Creative Director
Céline Everaert | Trainee UX and Graphic Design
Mike Cohen | Tech Lead / Senior Developer
Thomas Lefebvre | Trainee Developer
Mahmud Adeleye | Trainee Developer
Irina Turkina | Story Shepherd

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

In relation to the project, the risks identified upstream are categorised into 6 categories (Technical, Economic, Commercial, Organisational, Regulatory and Operational) which will be maintained in the classification maintained during the control, identification, monitoring and mitigation of the risks.

The risk management process may be activated by any member of the team after a preliminary impact and proximity assessment via a defined process.

The ultimate responsibility for risk management rests with the Project Manager who implements appropriate responses in consultation with the Technical Lead and the Chief Strategist. The Project Manager is also responsible for maintaining and updating the risk register on a weekly basis which is used as a reference for the management and record of identified risks.

Technical

Although the Bitcoin blockchain is battle-tested, its Layer 2 technologies - Lightning and Stacks Networks are still in their infancy. The fact that these projects are based on award-winning research from computer scientists at top universities, including MIT and Princeton, helps to mitigate the risks involved.

Smart Contract development is more complex than normal development since contracts deployed on the network cannot be 'undeployed'.

Economic: Any bug or hack in the Bitcoin blockchain could have a serious impact on the market capitalisation of all projects in the space as Bitcoin underlies the stored value. This can be mitigated by keeping options open for development on alternative blockchains.

Commercial and Market: The main risks related to commercialisation are the current barriers to adoption, market volatility and the impact of the pandemic. We aim to address the commercial risks by a diversified strategy in relation to the target markets.

Organisational: High comprehension barrier and sophisticated technicality in the topics to be covered. Mitigation of this risk is managed through in-depth preparatory sessions with the project team(s), creation of precise briefs and information/demonstration material and workshops. Mitigation during the project will also be ensured through constant and transparent communication.

Regulatory: We have access to legal advice but mitigate the risks of incursion of regulatory frameworks such Anti-Money Laundering (AML) by avoiding custodial wallets in our solutions - preferring to use third party processors with full AML/KYC policies.

Operational: The difficulty of sustaining well-timed workloads and deadlines, exacerbated by working remotely. Mitigation of this risk is ensured through the timely management of the working day and managerial support for workloads through careful planning shared with the team.

[Risk Register.pdf](https://apply-for-innovation-funding.service.gov.uk/application/10000502/form/question/19022/forminput/46875/file/284036/download).

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

In phase I we worked with the community to start developing SIP based standards for NFTs. We are looking forward to continuing this work and extending it to included meta data standards for off-chain NFT data cf [Open Sea Meta Data Standards](https://docs.opensea.io/docs/metadata-standards). We are committed to working with other projects in the Stacks community. We intend to share our plans through;

 - **End of Sprint Review - open community invitation**
 - Attending Foundation events and community meetups in Discord
 - User testing and feedback via Block Survey
 - Blog posts on the [Risidio](https://risidio.com/blog) website and on the [Risidio Auction](https://dcmarket2.risidio.com/community?uid=lambda-v-stacks) platform
 - Through our social media channels

Over the past 9 months we have worked and learned with over 50 people from over 15 countries, across many time zones. Our guiding vision has been the idea that Bitcoin technologies hold the key to unlocking a fairer and safer Internet for everyone. Hardly any of our team knew anything about the crypto space when they joined but that soon changed as they became inspired by the social revolution that is happening, quietly, away from the hype and headlines, through the efforts of companies like Risidio and many more. We are now 24 and cover expertise from 3D web design to financial analysis and from Clarity smart contract development to managing social media campaigns and we are truly just getting going. Read more in our [blog](https://risidio.com/blog).

We are currently very happy to be integrating our multi coin payment card into [crowdfunding](https://thepromhq.com/) and [NGO](http://thehelpmatesfoundation.com/) websites. The card is highly configurable and integrates with

 - Square Pay for normal money
 - OpenNode for Bitcoin and Lighting
 - Stacks and Ethereum - direct via browser wallet.

We have also [developed](https://risidio.com/rpay-demo) a prototype of the [LSAT (402) protocol](https://lightning.engineering/posts/2020-03-30-lsat/) and are looking for clients and partners to push this versatile and revolutionary technology forward.

Risidio Auctions is our flagship decentralised marketplace. Any applications in the the creative industries can connect the to platform to mint (register on-chain) creative content to establish ownership. The owner can sell their digital property through ‘buy now’ or ‘bidding’ features. Phase I was delivered on time in December with the [support of the Stacks foundation]( ).

We are working with various partners and industry experts from within the Creative Industries. Through these relationships we are gaining wider access to influencers - especially within the music and films industries.

Our contribution to the crowdfund for the [PROM](https://thepromhq.com/) project - is now live and we are working with a top consultant from the [Indiegogo](https://www.indiegogo.com/) platform to deliver the PROM project within which we are key strategic and technology advisors on their plans to decentralise the movie industry.

[Loopbomb](https://loopbomb.com) is a generative art application that lets you register your ownership of artworks and also keeps you in control of the art files - even after they’ve been uploaded (hint they really get upload to your own cloud storage account). We built the blockchain bit (the bit that connects to your wallet and registers the artwork on-chain) in a separate web component so it can be easily plugged into any website that mints digital collectibles (or creative content or NFTs - as they’re also known).

Our management team have an extensive business development and growth portfolio with a track record running large scale product launches and marketing campaigns. In addition they also bring extensive experience in building online auction platforms with the Bidlogix project on Web 2.0. Further expertise includes scaling the auction platform to running over a thousand, live and event-based auctions a year, for auctioneers in sectors from collectibles like Dreweatts and Bloomsbury to GE, Rolls Royce, and Hilco in the industrial sector and Manheim car auctions.

**Comment by radicleart** [comment]
Hey @RaffiSapire , please let us know if this has been picked up? We posted it originally in the other process grant.io so am not sure of the status? Be really helpful to get some feedback.

**Comment by RaffiSapire** [comment]
Hi there,
Thank you for this application. Could you please share usage metrics on how people are using and interacting with the current product built with the first grant? What metrics are you tracking across usage, and specific actions taken? How many NFTs have been listed? How many have been bought? How has that trended month over month? How are you getting the word out? What's working well in terms of creating engagement? 
Thanks,
Raffi

**Comment by radicleart** [comment]
Hi, thanks for the feedback.

We minted over 500 assets as part of our testing of phase 1 and about 20% of these were bought and sold and successfully transferred between addresses on the Krypton network. We are able to track metrics from the following sources; 1) data stored in our Clarity smart contracts, 2) data indexed in our Lucene stateless search index and 3) using prometheus on our server which gathers metrics from key infrastructure - mainly nginx for the purposes of measuring unique visits etc. Our loopbomb.com application, which is live, has seen around 250 items minted with over a hundred unique users logging in via Stacks Connect, using Gaia storage, has sale throughput of around 8% - despite the high gas fees.

Our [videos](https://www.youtube.com/channel/UCrMDxxhMvpeyErw7m92IIXA?guided_help_flow=5), released as part of Phase I, have had over 200 views on youtube and our social media campaigns on [Instagram](https://www.instagram.com/risidio_official/) and on [Twitter](https://twitter.com/risidio1?lang=en) are really starting to gain traction.

Above and beyond all this, over the course of lockdown, since starting Risidio last March, we have put in place an apprenticeship model through which we have brought more than 50 Graduates and Post Grads into the Blockchain space with specific focus on learning about Bitcoin, Lightning and above all the Stacks project. As part of this we have run competitions around innovation using blockchain technology and paid small prizes in Bitcoin and Stacks to further enable and develop confidence with the technology. Several of our apprentices went on to join the Freehold community.

We regularly reach out to other members of the community - attempting to build bridges with like minded advocates of Stacks technology. This work was very helpfully and skilfully facilitated by Ryan.

I hope this provides enough context for your decision but please get back to me if you need anything more - we are always open and happy to meet online and to introduce you to our team and so on.

Best, Mike.

**Comment by RaffiSapire** [comment]
Is it possible to see usage (#assets minted, number bought, number sold, number transferred) broken out monthly, to see how engagement has grown/ changed over time?

**Comment by radicleart** [comment]
@RaffiSapire @blocks8 - its not really possible to see these things since the testing was on the Krypton network.

Since completing that first phase we spent time running nodes on Krypton and Xenon and took part in the mining challenges to help test the last testnet phases before mainnet release. We helped newcomers by answering questions on discord and even built an analytics app to try to understand the stats coming out of testnet. 

In early January we built a pitch to the UK Government (Innovate UK) - based around Stacks technology which we will hear about at the end of March. We then turned our attention back to our auction platform. Recent discussions with friends in the music industry has led us to add royalty information to our Phase I contracts and to start building a 2nd client app for our marketplace which allows minting of Music files and storing royalty information. This work is in progress.

We are self financing and this has been a hard road to travel and we are hoping the Foundation sees this as something they are able to support?

**Comment by RaffiSapire** [comment]
Hi there, as discussed on the phone, this is approved.

**Comment by radicleart** [comment]
Thanks so much Raffi - this is a great boost for us and we look forward to sharing progress in Q2 with you and community.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
