### ISSUE TITLE
Clarity Hackathon in Nigeria

### ISSUE THREAD

**Issue by oiclid** [stacksgov/Stacks-Grant-Launchpad#56]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

I intend to help grow the number of Clarity developers in Nigeria. The 3 day hackathon  would be for developers to build and deploy smart contracts with Clarity on Stacks.

**Project Overview**
What solution are you providing? Who will it serve?

This would be a virtual hackathon, which would hopefully make developers interested in building with Clarity and on Stacks, as well as educate people of the platform and its potential.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The goal is to successfully build and deploy at least 5 smart contracts on Stacks over a 3 day period. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $600
Time: 3 days

M1: Internet & miscellaneous costs : $300 
M2: Prize money: $300

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I would be the sole convener of the hackathon. I have over 13 years of professional software development. I am also active in several developer communities local, and have taken part in several hackathons.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The event would be virtual, so the largest risk (it being cancelled due to a surge in COVID19 infections) is almost non-existent.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

**Comment by RaffiSapire** [comment]
This approved! Please email me at raffi@stacks.org and I'll get you set up on bill.com and send over a contract.

**Comment by oiclid** [comment]
@RaffiSapire Done! Thanks.

**Comment by Teke-pixel** [comment]
Is this still available or the hackathon has already commenced ?

**Comment by Teke-pixel** [comment]
Would like to do another one 🥷🥷
