### ISSUE TITLE
Stacks Turkey Second Grant

### ISSUE THREAD

**Issue by OmurCataltepe** [stacksgov/Stacks-Grant-Launchpad#57]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Stacks Turkey is one of the fastest growing Stacks communities worldwide. In just a few months, we have grown from 1,300 members to 3,800 real members_. We are extremely passionate about Stacks and how it may be able to transform the financial system in Turkey. This grant application is an example of some of our longer term plans to grow the Stacks Turkey community sustainably. We want to first raise awareness about Stacks, and then educate the community about the technology that makes Stacks possible. Ultimately, our goal is to increase the number of Stackers and start a stacking pool that can sustain our community. With this work, we hope to officially be recognized as a Stacks chapter soon. 
In the meantime, there are undecided investors because they can't find enough resources in Turkish. They can't be sure about what is the Stacks and the vision of the project. We want to solve it by reaching them from big platforms / communities and big influencers. We know big influencers around us.

**Project Overview**
What solution are you providing? Who will it serve?

If this grant is funded and we are recognized as a Stacks Chapter, we will continue to focus on build and promoting Stacks and Stacks Technology to Turkish investors. Because Turkey is the largest cryptocurrency investor in middle-east. That is the key point. We must bring Stacks to this investment potential. We’ll work with big Turkish influencers as well. Getting more investor, more Stacker, more miner is our first priority.
We will introduce Stacks and the Stacks Technology to tens of thousands of Turkish investors. Because Turkey is the largest cryptocurrency investor in middle-east. There is great potential!

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
We are aiming to complete all these works in 1 month. We met with influencers early, so we are ready to start. We made our preparations, we are waiting to approving
We will organize Live Video AMA in Kripto Solzuk and making advertisements, events with big influencers. In the same time, we’ll translate important articles and papers to Turkish. 
It will serve to all of the potential Turkish investors. I believe the project will be enough to solve that. 
We want to make Stacks Turkey biggest cryptocurrency community in Turkey.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Milestone 1: 
Marketing Jobs with TFB : 
Do a survey to measure how conscious people are about STX and about user-owned internet and we will collect suggestions on how to strengthen our works – Service Cost (Estimated Participations : more than 1000+): 300$ 
Promotions for Telegram Community and Twitter Page – 300$ 
Third Local Turkish Townhall (Topics: Stacking, PoX Mining, Foundation, Freehold) - (Simultaneous Translator Fee - 250$ + Advertisement Fee - 150$) - Sum: 400$
Advertisements for Spreading Promotional Videos(https://www.youtube.com/watch?v=z7pmu3zojJE - https://www.youtube.com/watch?v=ulYSzN6FO84) – 200$ 
Promoting STX with MEMEs in the most popular Turkish Instagram Pages and Twitter – Estimated Reach: 300k+ users - Cost: 500$ 
Sponsored Article in kazancrehberi.com – 300$ 
Sponsored Article in coinotag.com – 400$  
Activity Competition in Turkish Community – 175$ 
Estimated Completion Time: 1 week
Sum of Costs: 2,575$
Milestone 2: 
Paid Articles: 
Sponsored Article in muhabbit.com – 400$ 
Live Video AMA with Kripto Sozluk's YouTube Channel (100.000+ organic followers): Influencer’s Fee: 1.000$ 
Promotional and Educational Video for Stacking with Kripto Sozluk's YouTube Channel (92.000 organic followers): Influencer’s Fee: 500$ 
Preparing Contents and Speeches: 8 hour – 8* 20$ = 160$ 
Preparing Contents and Speeches: 8 hour – 8* 20$ = 160$  
Estimated Completion Time: 1 week
Sum of Costs: 2.220$
Milestone 3:
Creating Turkish Resources and Guides:
Stacks Blockchain API -> (Technical) - Translating Fee (1130 words) - 150$
Understand Stacking -> (Technical) - Translating Fee (1210 words) - 150$
Understand Mining -> (Technical) - Translating Fee (540 words) - 70$
Summary of technical specifications of Stacks 2.0 (Consensus, Proof of Transfer Mining, Stacking, Accounts and Addresses, Transactions) -> (Technical) Translating Fee (950 words) - 130$
Adding Stacks to Watchlist on CoinMarketCap (Estimated Participants from Tfb: 1.000+) – 300$ 
Increasing Stacks fans (increasing like count of coin) to moving Stacks to most trending coins on CoinGecko (Estimated Participants from Tfb: 1.000+ ) – 300$
Estiminated  Completion Time: 1 week
Sum of Costs: 1100$
Milestone 4:
Rewarding Omur for Chapter Leading and All Contributions to Ecosystem – 1500$
Rewarding Ali for Chapter Leading and All Contributions to Ecosystem – 1500$
Sum of Rewards: 3.000$

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Omur Cataltepe - Community Leader, Web Developer, Translator
Sahin Ali Bayar - Community Leader, Translator
Ata Aydin - Translator

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
If any influencer or community gives up partnership, we will organize events with another persons / communities on the same budget. We have alternatives for that. We cannot predict another risk as it will be a marketing work.

We have good contacts for doing that.
We organized AMA events and prepared promotional videos for Stacks and also Sahin Ali Bayar and Omur Cataltepe is leading Stacks Turkey. There is great activity in this community. Member count is increased 3900+ from 300.
95% of our members are completely Turkish and organic.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?
We have good contacts for doing that.
We organized AMA events and prepared promotional videos for Stacks and also Sahin Ali Bayar and Omur Cataltepe is leading Stacks Turkey. There is great activity in this community. Member count is increased 3000+ from 300.
91% of our members are completely Turkish and organic.

All of the past and current statistics are in "Stacks Turkey Community Growth Planning Doc" paper. If it'll be requested, we can share the document with authorities.

**Comment by RaffiSapire** [comment]
Hi there, we discussed two items yesterday at the committee meeting 1) whether the completion of the current grant is still open and in progress and 2) the amount here is large for a month period and the amount of work being done, and @jennymith  will reach out to help you scope it.
Thanks, Raffi

**Comment by kriprodede** [comment]
Hi there, @RaffiSapire we actually finished our first milestone 2 weeks ago and waiting new fund from you to continue second one. We add large amount of work because of market current situation. Bull session won’t last forever therefore we want to growth stackers and telegram members as much as we can while market is good.. That is why  we want to accomplish all all work that we add. We cannot predict market after two or three months. Why don’t we take a chance while market is green.
