### ISSUE TITLE
STX Me (Easy STX Donations)

### ISSUE THREAD

**Issue by amorriscode** [stacksgov/Stacks-Grant-Launchpad#59]
## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

Creators all over the web have been using services like [Buy Me a Coffee](https://www.buymeacoffee.com) to easily accept donations from their supports. What if creators could easily accept STX donations?

## Project Overview

> What solution are you providing? Who will it serve?

I'm looking to create a JavaScript library that can easily be put on any creators website. All they have to do is initialize it with their wallet address and they can receive STX donations in one click!

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

- Marketing website
- JavaScript library for user's to put on their website

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $2500

M1: JavaScript Library

- Easily put onto any website (just pass a wallet address!)
- Great code coverage (>90%)
- UI/UX that follows Stacks best practices
- Connects to the Stacks Wallet Chrome Extension to allow donations with a single click

M2: Marketing Website

- Simple, clean design (similar to Stacks own designs)
- Provide documentation for adding the library to any website

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.

- [Just me](https://anthonymorris.dev)
- Previously worked on [Wrabit](https://github.com/writewithwrabit/webapp) and currently building [Merit](https://github.com/amorriscode/merit)

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

- Working alone brings some challenges but I'm confidence in my ability to execute
- I don't have experience working with Stacks but the community can support along the way

**Comment by espadon8004** [comment]
This is awesome! Really good idea.

**Comment by mardi00** [comment]
This is awesome! I have a project related to this! Good luck

**Comment by amorriscode** [comment]
Thanks @mardi00! Just signed the grant documentation so I'll be starting work on the project in the coming days! 🎉

**Comment by amorriscode** [comment]
⚠️ Update

Things are coming along nicely for STX Me. I'm hoping to complete the initial MVP this week.

Currently, the library works. Things I will be doing over the coming days:

- Getting that test coverage up
- Implementing a CI/CD pipeline
- Deploying the library
- Building a website with some simple documentation
- Posting on Product Hunt!

It's been a pleasure working on this project and I can't wait for the 1.0 release. :)

**Comment by amorriscode** [comment]
Today is a good day!

I'm happy to say I've finished up the first version of stx.me!

https://www.getstx.me/

Just going to work on finishing up the automated deployment pipeline but my first transaction has gone through in prod. I also plan to post on Product Hunt later this week.

Thanks, @RaffiSapire for helping me obtain a grant. It's been really fun working on this. I'm loving the Stacks developer ecosystem!

@mardi00 let me know if you end up giving it a spin. :)

Closing this issue!

**Comment by RaffiSapire** [comment]
That's awesome, @amorriscode could you share this back in Discord in the grants channel? Would love to make sure folks know this is available!

**Comment by amorriscode** [comment]
Thanks @RaffiSapire! I shared it there already. 💯

**Comment by vanesvibes** [comment]
@amorriscode Vane here! I am supporting the Grants in updated information. Could you let us know your discord username?

**Comment by amorriscode** [comment]
Hey @vanesvibes it's `amorriscode#3473` but I'm not really active on there much!
