### ISSUE TITLE
Stacks Commerce // STX-C

### ISSUE THREAD

**Issue by Alisammour** [stacksgov/Stacks-Grant-Launchpad#595]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ali@theflatlay.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ali#9835

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;flatlay

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Commerce (STX-C)

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;250,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;2,200

**Funding Stream:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Investment

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Developer Experience

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies & New Technology 

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers, Publishers (creators), Brands and other value add parties involved with logistics & fulfillment benefiting from partial ownership of NFT’s through Proof of Ownership and Proof of Conversion.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;nokhodian, erfanyeganegi, alisammour

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;NFT Fractionalizer: http://fractionalizer.droplinked.com

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;FLATLAY was part of Stacks Accelerator Cohort 2 and we're working across companies and partners between C1 & C2

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Commerce (STX-C) is a smart contract system enabling independent buyers, sellers & value add parties to contribute & be rewarded for the exchange of goods & services. The system provides mechanisms to automate affiliate sales tracking & autonomous rewards association enabling producers and publishers to directly compensate one another while addressing the compromises of centralized systems. Centralized networks are prone to a lack of transparency & keen to mistreat trust (lacking data & capturing excessive revenue from transactions across their networks).

STX-C provides the ability to mint NFTs & fractionalize them to a desired amount. The NFTs represent real goods, services & digital products to support decentralized inventory management. The fractions can equate to the volume of products produced or the amount made available for batch listings & collections. Exchange & ownership related to any fractions can represent the purchase of a product, service or true ownership of a listed item. Actual goods & services are represented as an exchangeable fraction of an NFT enabling many functionalities.

Affiliate sales tracking is one of the most important functions with this infrastructure. It transparently enables manufacturers, publishers (creators) and partners to make the request for token(s) locked into their own marketing and sales efforts on smart contracts with full transparency between parties. By implementing a Stacks payment gateway atop of this, adopters can provide direct payment solutions on their own websites & properties. This empowers anyone from being bound to arbitrary traffic channels on centralized platforms, enabling them to be self-sustainable and fairly compensated for their efforts.

In what ways does this project bring us closer to a user-owned internet?

This project helps to associate NFT fractions with real-world products and services. This enables a DAO or any 3rd party to fully organize an affiliate network with pre-agreed terms and conditions that are fully transparent between every authenticated and contributing party. This will enable 3rd parties to unlock many value-add features. Some examples would be a more efficient means of fulfillment, last mile delivery logistics providers working through more optimized routes and import facilitators being able to better coordinate cost estimates along with many other stakeholders being able to incorporate contributions on-chain.

How will this project accelerate a broader adoption of Stacks?

- Enabling businesses to create their dCommerce solutions atop of Stacks at scale
- Enabling a large amount of eCommerce 3rd parties and value-add partners to offer their services in a creative way on-chain in a trust-less manner 
- Enable affiliate sales and influencer marketing in a very efficient and transparent way that will benefit any retailer, marketplace or dapp being built for the ecosystem

Explain how this project will have a positive and meaningful impact on the Stacks community?

- Providing an affiliate network for the ecosystem so that any NFT seller and existing community members can provide access to 3rd parties with a way to incentivize co-promotions and co-selling.
- Providing the platform for developers to better leverage web3 commerce tools that can be customized into their own properties/sites along with integrating their eCommerce value-add offerings in a structured, trust-less format that can be made actionable across the network

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;What is your community engagement plan throughout the process of the project?

- Engaged with ecosystem partners (GAMMA, HeyLayer, RoundlyX, Hiro, Xverse, Console, Frens) to support the fractionalization of assets (blue-chip, high value NFT’s or resources) to support co-vesting and distribution between constituents and community members
- Working with executive teams and stakeholders to customize libraries and solutions to make shoppable collection embeddables to be used across their properties in order to make content and promotions more discoverable while providing a native look and feel
- Encouraging community feedback across various Discord threads/forums and Twitter spaces to gauge and incorporate input and improvements
- Providing updates on community foundation calls of the teams progress while asking for collaborative input from new strategic partners interested in adopting STX-C

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;What challenges, technical or otherwise, do you anticipate encountering throughout this project?

- Accounting for scalability when it comes to the number of smart product listings incorporated across the network.
- Incorporating room for anomalies or variables that are not standardized with the typical association of different use cases for adapting smart product listings.
- Building adoption across current marketplaces without overcomplicating usage and settlement of existing inventory

What is your plan for overcoming these challenges?

 - Working with members across the community, our investor and executive advisory portco’s along with Stacks backed teams to incorporate constructive feedback and input to avoid these scalability issues and pitfalls
-  Partnering with Mintery NFT artists and STX marketplaces to build sustainable infrastructure based on their needs to create scaled adoption use cases and case studies beyond to service future community adopters

**[Support Link:](https://docs.google.com/document/d/1ybeMfriXs-p5jNe_NZdcxxgK2kqHIOlsndmfRnLVK4w/edit?usp=sharing)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;It's a full outline with deeper context as to everything we plan to provide as final deliverables (portal, libraries, etc.). It was based on the previous format for grants in the previous dashboard that was sunset.

Morteza's presentation of the NFT fractionalizer and Ali answers 2 min of Q+A at the 34min mark:
https://www.crowdcast.io/e/community-updates-call-july-2022

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; Source code and libraries enabling collaboration between sellers & 3rd parties

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Interactive portal and libraries for 3rd party developers and publishers 

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;UI and storefront libraries for customization

**MILESTONE 4:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;STX Pay - a payment infrastructure mechanism to accept transactions associated to a fiat value for goods listed on the DIMST (decentralized inventory management and sales tracking) system.

**MILESTONE 5:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;An in-depth outline of all deliverables provided in google doc included on step6

**MILESTONE 6:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;https://docs.google.com/document/d/1ybeMfriXs-p5jNe_NZdcxxgK2kqHIOlsndmfRnLVK4w

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; A smart contract based system enabling anyone to participate in deComm at scale with STX.

**Comment by Alisammour** [comment]
We're interested in having a call with the team to explain the overall goal(s) of Stacks Commerce and the end solution benefits to the ecosystem.

**Comment by Alisammour** [comment]
@will-at-stacks thanks for quickly getting back to us.

1. Is there a way to breakout deliverables between things we provide as open source contributions and resources to the STX ecosystem vs. direct investment within the same app submission?

2. When submitting in the new portal, I didn't happen to see the option of choosing "Direct Investment" as a project type. Will review the process again in the interim.

Look forward to your feedback and we will plan to re-work the submission accordingly.

Thanks!

**Comment by will-at-stacks** [comment]
Hi @Alisammour to answer your questions:

1) No.  These will need to be separate applications.  We would only consider one application at a time too.
2) You just need to select the Project Type Direction Investment on the 5th page of the application (2nd from the bottom)

**Comment by will-at-stacks** [comment]
Thank you for your application.  We will let you know if we have any questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a timeline on a formal response.  
Best, 
Will

**Comment by Alisammour** [comment]
Thnx @will-at-stacks appreciate the quick correspondence, look forward to answering questions the foundation team may have.

**Comment by Alisammour** [comment]
@will-at-stacks for easy reference, we've broken out a separate grant application specific to the initial open source grant work and libraries we are contributing to the community. We've deducted those hours and deliverables from this direct investment application in the meantime.

https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/645

**Comment by purplesuede22** [comment]
I'm extremely excited to see Flatlay released into the Stacks ecosystem! Their fractionalizer alone is going to revolutionize the way people collect NFTs, and my team at RoundlyX is already working with them to implement some really cool upgrades to our system. Great work, team!

**Comment by sabbyanandan** [comment]
I have had the pleasure of getting to know and working with @Alisammour and @nokhodian on product discovery and research. They are not only bullish about Stacks but are embarking on simplifying the e-commerce scaffolding by bringing the more prominent brands closer to crypto, and that is fascinating. The simpler it gets, the more the reach is, and the more normal (crypto) becomes.

**Comment by JakeBlockchain** [comment]
The team here is top-tier. Very interested in what could come from the fractionalizer. Sounds like it could be a huge primative.

**Comment by falkonprods** [comment]
The linkage between real-world goods and NFTs is a critical step. Implementing Flatlay's affiliate system would allow for key e-commerce growth on the Stacks blockchain.

@Alisammour and his team chose stacks as the blockchain to launch their product on - a risky choice - but having products like this will bring considerable value and new wallets to Stacks. His team has shown they can execute on their Web2 initiative and are making considerable progress on their Web3 one.

I strongly support this initiative.

**Comment by will-at-stacks** [comment]
Hi @Alisammour 

I see you already have an open grant and another application submitted.  See links below.  Please note you cannot apply for another grant until all previously awarded grants are completed.  I will be closing both of these applications in a couple of days unless you feel I am mistaken about the open grant.

Thanks,
Will

https://grantsdashboard.stacks.org/dashboard/grants/509
https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/645

**Comment by will-at-stacks** [comment]
Hi @Alisammour 

Thanks for bringing to my attention that this is an application for Direct Investment not grant funding - and that the Flatlay team is not engaged in the Unity game engine grant with Trit.

Both this application and #645 will remain open.

Best,
Will

**Comment by gandalf77** [comment]
I had the pleasure to mentor Ali and the Flatlay team during cohort 2 of the Stacks Accelerator. 

Their work on https://www.flatlay.io/ shows that this is a highly capable team with big ambitions for bringing decentralized commerce to web3.

I want to express my support for this grant application - I believe that having an open source suite of tools to facilitate web3 eCommerce could be a significant unlock for the Stacks ecosystem.

**Comment by BowTiedMooneeb** [comment]
I've had the pleasure of getting to know Ali quite well during Cohort 2 of the Stacks Accelerator. Ali & the Flatlay team have vision, focus, experience, and a track record of successful execution.

This grant application proposes to lay the groundwork for a decentralized eCommerce network within the Stacks ecosystem. This is an entirely novel idea, and its successful execution has the potential to draw millions of dollars of in eComm transaction volume to settle on the Stacks blockchain. Ali & his team have already taken meaningful steps toward partnerships and integrations with various Stacks ecosystem participants. Stacks Commerce can bring a truly novel eComm experience to Stacks users. I fully support Ali and his team in this endeavor.

**Comment by will-at-stacks** [comment]
Hi @Alisammour -

We have identified the projects we will be awarding grants as part of Stacks Foundation Grants Program Cohort 18. I'm sorry to have to inform you that your project was not among those selected.

This is no way means that we do not see the value of the work you proposed. We're lucky to have so many talented independent researchers, developers, and community leaders like yourself building on Stacks. Unfortunately, we receive many more proposals than we can actually fund with our limited means, so competition is extremely tough. While we generally support innovation in all forms, we tend to prioritize projects that have the potential to advance and differentiate the broader ecosystem from other blockchains, as well as projects that meet critical needs of the community *at the time*. These constraints mean that in several instances, several excellent projects may not make it into a cohort.

We very much appreciate the time and effort you've put into this process and encourage you to continue watching this repo and consider submitting a new application if and when you feel your project better aligns with the current priorities of the Grants Program.

If you should have any questions, please let us know in the comment section below.

Best,
Will
Stacks Foundation Grants Program Manager
