### ISSUE TITLE
Ryder: Your Digital DNA

### ISSUE THREAD

**Issue by MarvinJanssen** [stacksgov/Stacks-Grant-Launchpad#6]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

Storing private keys on a computer that is connected to the internet in any form is dangerous and stories of people losing their crypto tokens due to private key theft are plentiful. Taylor, one of the creators of MyEtherWallet realized that they were harming their own users and the entire crypto ecosystem when they allowed them to enter their private key, keystores, and or mnemonic phrase on their site. This terrible practise resulted in countless scams and attacks on exchanges and crypto companies. Over 40,000 ETH has been sent to addresses that are flagged as being affiliated with scams or phishing sites. Marvin, Ryder’s Co-Founder also exposed how Blockstack applications go against best practices of the crypto industry and highlighted how it is possible to inject malicious code to steal app private keys of unsuspecting users. These circumstances are just some of the many and it does not stop here. Our team is convinced that none of the private keys — be it master, identity, nor app — should ever exist on the user’s machine. Instead, they should reside on a separate hardware device, much like the many existing hardware wallets out there. Thus, we set out to create the first hardware identity wallet, Ryder.

## Project Overview

> What solution are you providing? Who will it serve?

**Overview**

Every person on the internet has their own digital DNA that refers to the unique sequence of data collected and produced over a period of time. This sequence of data is the set of traceable digital activities manifested over the internet. The question is do you own your Digital DNA?

**Vision**
Ryder is an innovation in cryptocurrency hardware wallets that lets you own your digital DNA. Ryder stores not only your cryptocurrencies but also your identities, a total replacement for all crypto-related operations. Ryder disrupts the future of cryptocurrencies by bringing the web 3.0 (user-owned internet) to the masses. 

**Mission**
Ryder’s mission is to surpass every conventional crypto hardware-based key that we enjoy today by combining usability with added security. 

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Our team would like to make an application for a $5000 grant from the Stacks Foundation. We will use these funds to unlock Q42020 milestones as shown in table 1 of grant proposal document (link below). This grant will make sure that Ryder meets every deliverable for the next quarter and meets its next “fundable” milestone. The team plans to use crowdfunding as a clear evidence of demand for a seed round stage/venture funding later on, please see table 2 in the same document for a cost breakdown. Initial talks with a possible manufacturer indicate a startup research & development cost of $20,000, but this has to be explored further. As an open source project, transparency is at the core of Ryder and every milestone/deliverable unlocked will be shared first-hand with the Stacks ecosystem and Ryder’s channels moving forward.

_See "Table 1. Ryder's Roadmap" of the attached document for a more comprehensive timeline._

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

@MarvinJanssen has a lot of experience developing custom interdisciplinary products and has a discerning eye towards technological needs, and a specific interest in web 3.0, hardware, and security. Currently, Marvin runs a business developing custom applications and is the department head of a private school teaching web & application development (including Blockstack). He also built Simplecoin, a social cryptocurrency mining platform that gained 60,000 users.

@LouiseIvan is an external consultant at Blockstack PBC. He is currently based in Amsterdam after previously working with various tech-startups in Asia, Europe, and the United States while taking on various roles such as .NET Developer, Growth Hacker, Analyst and a Founder.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Please see below for the various risk factors.

**Technological Risk**
The current prototype is built using the Espressif Systems ESP32 microcontroller. There are a few points to consider for this hardware:

1. One future customer pointed out the trust factor of using a Chinese microcontroller. Espressif Systems is a very reputable company that dominates the IoT (Internet of Things) space with the ESP microcontroller series but it is a consumer sentiment that we should nonetheless think about.
**Risk Mitigation:** Point to the reputation of Espressif Systems, make all possible code open source. We also want to investigate the options of using a STMicroelectronics (Europe) or Atmel (US) microcontroller for various other reasons.

2. The ESP32 features a two-stage bootloader. A bootloader is a low-level program that runs before the actual device code runs. The first-stage of the bootloader is baked into the chip by the manufacturer and thus cannot be changed. For the ESP32, the first-stage bootloader handles the firmware update process. (Firmware is the code that lives inside the microcontroller.) The first-stage always accepts new firmware, which means that anyone can reprogram the microcontroller at any point in time. It is problematic because we want to protect against malicious firmware uploads.
**Risk Mitigation:** There are currently a few different proposals to this problem. First, the ESP32 firmware can be protected by two mechanisms handled by the first-stage bootloader: SecureBoot and flash encryption. Both will prevent unauthorized firmware from being installed and executed. Firmware would have to be signed by us in order to be able to be uploaded. Second, adding a secure enclave coprocessor to the device that handles the crypto functionality. Lastly, we are open to discussing these issues with our manufacturer and Espressif Systems to see if we can reach a (hybrid-)solution. Our aim is to stay as open as possible without compromising security. Since we are still early in the development process, we can also opt to replace the ESP32 with an STMicroelectronics or Atmel microcontroller. Our current manufacturing partner has experience with all three.

**Market Risk**
Established Crypto Hardware companies like Trezor might try to maintain their dominant position by adding a new product line similar to Ryder. We will try to mitigate this risk by building a strong community similar to that of Pebble. Another strategy that we have in mind is the "exit opportunity” for Ryder. This is a low-risk strategy for a company such as Trezor as they can easily acquire a small business. Lastly, we could also license Ryder or partner with these companies. 

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We were overwhelmed by the enthusiasm of the Blockstack Community and various thought leaders in the space such as Muneeb Ali (Blockstack), Alexander Lange (Inflection.xyz), Patrick Stanley (Blockstack), Jude Nelson (Stacks Foundation), Zach Voell (Coindesk) and prominent investors like Nick Grossman (USV) and Thomas Klocanas (WhiteStar Capital) just to name a few. Our team is excited about the possibilities that Ryder can unleash to the Stacks and the entire crypto ecosystem. 

To gauge initial interest, we did preliminary research with the Blockstack Community in the span of 5 days through a Blocksurvey form. Out of 36 respondents, we had a total of 81 pre-order for Ryder which puts us at over US$10,000 already at 150$ price point per unit. See Figure 2 and 3 of the grant proposal for a more detailed breakdown.

See links below for a sample of supporting materials about Ryder:

- https://medium.com/@marvinjanssen/stealing-app-private-keys-on-blockstack-2cec9d606390
- https://medium.com/@marvinjanssen/beyond-the-private-key-building-a-blockstack-hardware-identity-keychain-46418d90efd2
- https://medium.com/@marvinjanssen/ryder-introducing-the-first-functional-wearable-hardware-wallet-b4380c327a19
- https://twitter.com/MarvinJanssen/status/1289044819335983110
- https://twitter.com/nickgrossman/status/1289188878239199232
- https://www.theslowhunch.net/2020/hardware-based-identity/

## Grant proposal document

**The full grant proposal document can be found here: https://ryder.id/Ryder-Funding-Proposal-v1.pdf**

**Comment by louiseivan** [comment]
@friedger yes :)

**Comment by blocks8** [comment]
**Review Committee Feedback from 9/8/2020: We'd like more information on your proposal.**

Thank you for your application! You have a clear vision of an application that you can bring to the world and we're excited to see your plans. We need a bit more information about your plans to make sure we have the clear deliverables. 

According to your proposal, the grant funding you applied for of $5,000 will result in: 
● Ryder Incorporation (Singapore) 
● Ryder Rebranding 
● Initial batch (10 units) 
● Marketing for Crowdfunding

How will he raise the other $7,500 to be successfully launch the crowdfunding campaign? 

How will you use the initial batch of 10 units? 

We're excited to see your product come to life in the Blockstack ecosystem. If you would like to update your proposal with the above feedback, you may do so as a reply to this comment or edit the original application entry above.

**Comment by MarvinJanssen** [comment]
The initial batch of 10 units will be used for testing purposes and to sow the seeds of our future community of makers. We intend to release these (individually numbered) units as part of our upcoming crowdfunding campaign. We want to make them available to key figures in the community as our first “pioneers” or “Ryder ambassadors”. 

To clarify, the marketing for crowdfunding is broken down into two phases. The first phase will be unlocked through the Stacks Foundation Grant and will enable the team to deliver rebranding, initial batch, and commercial videography. After unlocking phase 1, we are hoping that this will enable us to apply for the next fundable milestone ($7,500) that will be used for legal and crowdfunding ads to ensure that Ryder will have a successful crowdfunding campaign.

Let me know if that answers your questions. We can amend the document if required.

**Comment by RaffiSapire** [comment]
Hi @MarvinJanssen, my name is Raffi and I'm working with the foundation on the grant program. For the purpose of this grant proposal and scope, let's stick with the phase 1 scope that you mapped out above. When this piece is completed and the time comes for Marketing, we can scope a new grant request. We're pleased to approve this grant proposal for $5,000 which will result in the rebranding, initial batch, and commercial videography, delivered in the next ~6 weeks. We'll leave this to you to disburse between you and any other teammates working on this. We'd like to highlight your work through two blog posts to share with the community, one update mid-way, and another once this grant is completed. 

As a next step, we'll send over a contract for you to sign so that we can disburse payment. Could you please let us know your email address and we'll send that over to you?  @blocks8 may have additional feedback for you as well, but I figured I'd share the good news!

**Comment by MarvinJanssen** [comment]
Hi @RaffiSapire, fantastic news! Kindly use "marvin at ryder dot id" for the email address. Looking forward to the documentation.

**Comment by blocks8** [comment]
Funded! We're pleased to approve this grant proposal for $5,000 which will result in the rebranding, initial batch, and commercial videography, delivered in the next ~6 weeks. We'll leave this to you to disburse between you and any other teammates working on this. We'd like to highlight your work through two blog posts to share with the community, one update mid-way, and another once this grant is completed.

**Comment by RaffiSapire** [comment]
Hi @MarvinJanssen, we closed this by mistake, but this will be where you share updates on the milestones with the community, and folks can review here. When is a good time you'd like to aim to share the mid-way blog post?

**Comment by MarvinJanssen** [comment]
Hi @RaffiSapire, we have yet to receive the funds. There was trouble with the payment processor (see @blocks8). However, we received word that the funds should arrive by Thursday this week. As such, we have only done some preparation work for our milestones so far.

**Comment by RaffiSapire** [comment]
@MarvinJanssen thank you for the update. Have you received the funds? Will make sure to address tomorrow during meeting if not.

**Comment by MarvinJanssen** [comment]
Yes we did, thanks!

**Comment by RaffiSapire** [comment]
Hello! Thank you for all your hard work this year. We would love to send you a holiday note and some custom stacks stickers. Please email me at Raffi@stacks.org with you and your colleague's names/addresses if you'd like to receive one. We really appreciate all your help and contributions. Stacks is what it is because of you!

**Comment by MarvinJanssen** [comment]
Hi all, happy to announce that we (finally) reached all the milestones in this grant. (Good things come to those who wait? 😁) Per discussion with the Stacks Foundation, we have moved some ramp-up for the crowdfunding forward.

We sent out a newsletter yesterday containing much of it, which can be found here: https://news.ryder.id/w/N3qHmROzN8COHCRS5FWoCA.

# Ryder Incorporation (Singapore)

![image](https://news.ryder.id/uploads/1610995324.png)

We are pleased to reveal the newly formed entity that will be managing everything related to the Ryder Project: Light Labs Pte. Ltd. in Singapore. 

# Ryder Rebranding

![image](https://ryder.id/ryder_logo_with_slogan_black.svg)

Already announced a bit earlier (via the newsletter), we contracted design firm Sharp & Sour to create a beautiful brand for Ryder. You can see some of it on our recently published landing page at https://ryder.id.

The complete brand manual can be found here: https://ryder.id/Brand-Manual-Ryder.pdf

# Initial batch (10 units)

![image](https://news.ryder.id/uploads/1610995503.jpg)

We have an initial batch of 10 prototypes waiting to be shipped. There are still some final changes to be made to make sure it works with the latest Stacks 2.0 infrastructure (libraries). We already selected and reached out to key figures in the Stacks community. Happy to say that everyone is excited to receive a unit. We will be shipping them out to everyone as soon as possible.

# Cost overview

![image](https://news.ryder.id/uploads/1610996692.png)

An overview of the costs that the grant was part of:

1. $2,102.19 for administration and incorporation cost (this went over-budget due to an unforeseen circumstance).
2. $1,813.80 for branding, market research, and other marketing costs.
3. $1,933.40 for R&D, prototype development, and shipping.

# Next steps

We are preparing the creation of our pioneer maker community along with the shipment of the prototypes. After an evaluation period (of which the length is still to be determined), we intend to launch a crowdfunding campaign. In the mean time, conversations with potential product designers to join the Ryder team are moving forward and we hope make our final selection soon. (Announcement to come.)

**Comment by markmhx** [comment]
@MarvinJanssen How can I get my hands on one of these? 😄

**Comment by MarvinJanssen** [comment]
@markmhx responding to our email about the shipping details is the first step. 😁

**Comment by markmhx** [comment]
I haven't seen an email yet, but I just submitted my information to the Ryder newsletter (since I don't recall if I'd done that before). So perhaps now I'll receive it?

**Comment by will-at-stacks** [comment]
Hi @MarvinJanssen 

We are in the process of pulling together an index of all completed grants and links to the work (code repos, presentations, etc) created as a result of the grant.  Would you be so kind as to post links here to the work you created as a result of this grant?

Thanks!
Will Corcoran
Stacks Foundation Grant Program Manager
