### ISSUE TITLE
Stacks Pakistan Chapter Grant Application

### ISSUE THREAD

**Issue by nabeelaq** [stacksgov/Stacks-Grant-Launchpad#60]
Hi Everyone,

PFA Stacks Pakistan Chapter Grant Application.
[Stacks Pakistan Chapter Grant (1).pdf](https://github.com/stacksgov/Stacks-Grants/files/6066729/Stacks.Pakistan.Chapter.Grant.1.pdf)

Looking forward to hearing back.

Best,
Nabeel Qadeer

**Comment by jennymith** [comment]
Hi @nabeelaq can you please paste the application in the issue rather than linking the document? That would make it easier for other community members to review and comment on your application here.
