### ISSUE TITLE
Advanced mobile games toolset for F2P and P2E merger v.1

### ISSUE THREAD

**Issue by norbertredkie** [stacksgov/Stacks-Grant-Launchpad#606]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;stacks.wannabe@gmail.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;norbertredkie.btc#4318

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@Nredkie

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;norbertredkie.btc

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Advanced mobile games toolset for F2P and P2E merger v.1

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;23,800

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;160

**Funding Stream:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developer Grants

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Developer Experience

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Mobile Web 2.0 and Web3 Game-Dev studios, Mobile Web 2.0 and Web3 Game Publishers

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;czeslaw , pisajew / pki-acs , telemetricsystems , mikaelit , michal.szymerski@gmail.com , s4ros , forkility , +team members who don't have GitHub (UI Designer, Tester, Community Manager, Scrum Master ...) 

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We will tap Stacks blockchain to a stream of tens of thousands of new users. 

Creating an “Advanced mobile games toolset for F2P and P2E merger” will create a bridge between Free to Play Web 2.0 gaming and Play to Earn Web3 gaming allowing non-crypto game dev studios and publishers to easily implement Stacks blockchain to their games. Porting old fully centralized battle tested games to Web3 with implemented P2E mechanics will open a massive potential of using BTC in the gaming industry. Imagine earning BTC for playing Candy Crush Saga or Angry Birds while on a subway with no internet connection. “Advanced mobile games toolset for F2P and P2E merger” will make offline Web3 gaming finally possible via unique Stake to Earn mechanics. Being a part of Stacks community (in stealth discord dm type of mode) we are in constant contact with leaders such as Trevor and Kyle as well as other GameFi teams building on Stacks, such as Stacks Degens and Stacks Force so we make sure our work does not overlap each other and that we all can cross benefit (as presented on a shared Miro board: https://miro.com/app/board/uXjVOleUZ5I=/?share_link_id=345217589406).

With signed LOIs with: 
-Vivid Games (over 170mln downloads of their games)
-Reddeer Games (over 100 games in portfolio)
-Intermarum (leading gamedev studio in Poland listed on Polish Stock Exchange)
-Stellis (UEFA IT partner, that creates  software for sports clubs)
-Gamepressure (Gamepressure.com is a division of GRY-OnLine S.A., the leader in Polish rankings of digital entertainment portals with 4,2 mln unique users monthly)

As during our application (https://grants.stacks.org/dashboard/grants/580) grant application form has changed, Will asked us to resubmit using the new form. To do that we had to cut the application into batches. This is batch v.1

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;"Advanced mobile games toolset for F2P and P2E merger" will allow bridging hundreds of Web 2.0 gaming projects along with their current user base, but also game dev studios and publishers to Stacks. This will make Stacks blockchain and its community a go-to place in terms of “know how” on building Web3 games powered by Bitcoin. As Bitcoin is the only crypto that is known by regular Web 2.0 people, allowing them to interact with their favorite games using BTC will make Stacks Blockchain and STX the essential part of the digital future – everybody will know that you have to use “http” to browse the web and have Stacks wallet to surf the open ocean of Web3 gaming.

We want to onboard as many Web 2.0 non-crypto users as possible to Stacks. Therefore "Advanced mobile games toolset for F2P and P2E merger" is in a quite unique position (in a similar way to the App Store) with two different target groups – creators and players. Onboarding players the easiest possible way - by Referral Code NFTs (rNFT) and by using blockchain wallets (such as  Xverse to create seamless mobile experience) will create an inflow of regular non-crypto users to Stacks. But our main target group, and thus community, is obviously game developers and creators, who will be using the Toolset mostly to increase their earnings. Publishers and game developers will be benefiting from a merger of F2P world with P2E mechanics, as it will allow new ways of marketing and therefore lower user acquisition costs. By default when you want to increase your earnings you put as much work as possible to bring as many users as possible, this means that each new game built with proposed Advanced Toolset will engage their audience to grow rapidly, increasing the number of Stacks users. This will create an inflow of users to our Discord server where they will be notified of new GameFi projects built on Stacks. We will proactively (by design) support and utilize traffic and users rotation between projects. As a result a synergy will be achieved as each project separately will bring into the community their user base fueling further growth of the whole Stacks ecosystem. 

As this is batch v.1 of whole “Advanced mobile games toolset for F2P and P2E merger” our key metric will be more LOIs that we will provide

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Most are purely non-technical and connected to the way that blockchain is viewed by the gamedev community. This is going to change by having such tools as our Advanced Toolset, however this process will be a significant challenge. Game developers can use multiple technologies. Positioning ourselves as a go-to tool on this market, as well as actually onboarding independent creators (on the idea of blockchain), who are the ones driving innovation, will be a marketing challenge. Similar, yet different challenges are connected with games’ users, players that we want to become Stacks users. Persuading them to get familiar with a technical, perceived as exclusive and complicated blockchain terminology, might be a challenge and therefore needs to be addressed already on a design phase, to build the whole project as inclusive as possible and easy-to-start even without any understanding of the blockchain itself. The third major challenge is much more technical – and revolves around the merger of WEB2.0 and Web3 thinking. We believe that in order to scale fast gamedev studios and publishers will need to use centralized architecture on game backend and merge it with P2E mechanics making it hard to accept by crypto/bitcoin/blockchain maximalists.

Having strong partnerships (LOIs mentioned before) and a wide web of connections in one of the most flourishing markets of gaming industry (we are located in Poland which has more gamedev studios than California) allows us to evangelize and if needed personally convince leading gamedev studios and publisher to give blockchain a try and tap into Web3 potential using our Toolset. We are well known entrepreneurs in Poland, which is giving us an unfair advantage in building Stacks community here. For example the CEO of CD Projekt (creators of The Witcher) is just one phone call away. Having an experience from porting a WEB2.0 mobile game (Creature Racer) into the P2E blockchain era, we just know what are the obstacles and we want to create a comprehensive set of tutorials and FAQs on how to overcome most frequent problems both for users and developers. We know the entrance level for Web2.0 users into Web3 must be as low as possible. In a perfect scenario not demanding from the user anything else except a sole decision to connect their wallet and just give it a try! The game itself should onboard users to a play & earn model and focus only on fun, beneficial parts, not on technicalities behind the curtains. Third challenge is a psychological one, but we believe that most maximalists will benefit from wide blockchain adoption so one day they will give a try to those F2P and P2E merger products – especially during the current “crypto winter”. 

But the biggest risk right now is that we applied for a grant with an old form (Grant580) and all our scope and work will now go to trash as new form is not allowing us to apply to build whole  “Advanced mobile games toolset for F2P and P2E merger”. The only plan to overcome this is right what I just wrote to make you know and understand that we want to build a bigger toolset and we will apply for next grants as soon as we will see that this one is being finalized in terms of job done on our side. 

**[Support Link:](https://drive.google.com/drive/u/1/folders/162CQVpPlOFHrY7rs3dBTp4LhZt2OvYbz ; https://grants.stacks.org/dashboard/grants/580 ; https://miro.com/app/board/uXjVOleUZ5I=/?share_link_id=109698652778)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Google drive - LOIs, screenshots of talks with Stacks Degens, Stacks Force, Kyle and Trevor
Grant 580 - Will asked us to resubmit because grant form changed
Miro - Stacks Degens + Stacks Force + Wannabe Games shared board no to overlap work (we also have a discord group for Stacks GameFi creators) 

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Generic item operations: purchase with funds transfer  to reward pool contract to stake&earn, upgrade with new NFT minting, mint with royalties burned in the contract, mint with expiration date.  Generic Stake NFT to Earn operations: stake with expiration date, unstake, auto-unstake when expired, upgrade with auto new NFT mint. Reward Pool with operations: everyday flush operation, flush when reached, flush from backend, auto divide rewards, send rewards to staked NFTs Referral Code NFT (rNFT) with operations: mint new, auto upgrade when level reached, claim funds.

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;There are many other client platforms, such as Unreal, PlayStation and others, and we aim to implement it but before we do we will create a set of guidelines so other developers can fasttrack gaming adoption in Stacks. For example our partners at Reddeer Games are interested in facilitating "Advanced mobile games toolset for F2P and P2E merger" to perform a merger of their over 100 games on Nintendo Switch

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;A set of generic advanced P2E smart-contracts (generic, so allowing multiple gists implementation):

**Comment by Scarlett-Web3** [comment]
I think you have an interesting project. If you haven't already gone through the Stacks Web3 Startup Lab, I would like to invite you to apply.  

Here's a 5-minute read on how we can help you turn your startup idea into an investment-ready startup:
www.web3startuplab.io

If you are interested, you can apply through the "Apply Now" button.

Feel free to ping me on email:  scarlett@stacks.ac
