### ISSUE TITLE
Advanced mobile games toolset for F2P and P2E merger

### ISSUE THREAD

**Issue by czeslaw** [stacksgov/Stacks-Grant-Launchpad#611]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;stacks.wannabe@gmail.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;norbertredkie.btc#4318

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@Nredkie

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;norbertredkie.btc

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Advanced mobile games toolset for F2P and P2E merger

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;23,400

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;160

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Developer Experience  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Mobile Web 2.0 and Web3 Game-Dev studios, Mobile Web 2.0 and Web3 Game Publishers

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;pisajew, pki-acs, telemetricsystems, mikaelit, michal.szymerski@gmail.com, s4ros, forkility, FilipCichorek

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We will tap Stacks blockchain to a stream of tens of thousands of new users.
Creating an “Advanced mobile games toolset for F2P and P2E merger” will create a bridge between Free to Play Web 2.0 gaming and Play to Earn Web3 gaming allowing non-crypto game dev studios and publishers to easily implement Stacks blockchain to their games. Porting old fully centralized battle tested games to Web3 with implemented P2E mechanics will open a massive potential of using BTC in the gaming industry. Imagine earning BTC for playing Candy Crush Saga or Angry Birds while on a subway with no internet connection. “Advanced mobile games toolset for F2P and P2E merger” will make offline Web3 gaming finally possible via unique Stake to Earn mechanics. Being a part of Stacks community (in stealth discord dm type of mode) we are in constant contact with leaders such as Trevor and Kyle as well as other GameFi teams building on Stacks, such as Stacks Degens and Stacks Force so we make sure our work does not overlap each other and that we all can cross benefit (as presented on a shared Miro board: https://miro.com/app/board/uXjVOleUZ5I=/?share_link_id=345217589406).
With signed LOIs with:
-Vivid Games (over 170mln downloads of their games)
-Reddeer Games (over 100 games in portfolio)
-Intermarum (leading gamedev studio in Poland listed on Polish Stock Exchange)
-Stellis (UEFA IT partner, that creates software for sports clubs)
-Gamepressure (Gamepressure.com is a division of GRY-OnLine S.A., the leader in Polish rankings of digital entertainment portals with 4,2 mln unique users monthly)
As during our application (https://grants.stacks.org/dashboard/grants/580) grant application form has changed, Will asked us to resubmit using the new form. To do that we had to cut the application into batches. This is batch v.1

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;..."Advanced mobile games toolset for F2P and P2E merger" will allow bridging hundreds of Web 2.0 gaming projects along with their current user base, but also game dev studios and publishers to Stacks. This will make Stacks blockchain and its community a go-to place in terms of “know how” on building Web3 games powered by Bitcoin. As Bitcoin is the only crypto that is known by regular Web 2.0 people, allowing them to interact with their favorite games using BTC will make Stacks Blockchain and STX the essential part of the digital future – everybody will know that you have to use “http” to browse the web and have Stacks wallet to surf the open ocean of Web3 gaming.
We want to onboard as many Web 2.0 non-crypto users as possible to Stacks. Therefore "Advanced mobile games toolset for F2P and P2E merger" is in a quite unique position (in a similar way to the App Store) with two different target groups – creators and players. Onboarding players the easiest possible way - by Referral Code NFTs (rNFT) and by using blockchain wallets (such as Xverse to create seamless mobile experience) will create an inflow of regular non-crypto users to Stacks. But our main target group, and thus community, is obviously game developers and creators, who will be using the Toolset mostly to increase their earnings. Publishers and game developers will be benefiting from a merger of F2P world with P2E mechanics, as it will allow new ways of marketing and therefore lower user acquisition costs. By default when you want to increase your earnings you put as much work as possible to bring as many users as possible, this means that each new game built with proposed Advanced Toolset will engage their audience to grow rapidly, increasing the number of Stacks users. This will create an inflow of users to our Discord server where they will be notified of new GameFi projects built on Stacks. We will proactively (by design) support and utilize traffic and users rotation between projects. As a result a synergy will be achieved as each project separately will bring into the community their user base fueling further growth of the whole Stacks ecosystem.
As this is batch v.1 of whole “Advanced mobile games toolset for F2P and P2E merger” our key metric will be more LOIs that we will provide

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Most are purely non-technical and connected to the way that blockchain is viewed by the gamedev community. This is going to change by having such tools as our Advanced Toolset, however this process will be a significant challenge. Game developers can use multiple technologies. Positioning ourselves as a go-to tool on this market, as well as actually onboarding independent creators (on the idea of blockchain), who are the ones driving innovation, will be a marketing challenge. Similar, yet different challenges are connected with games’ users, players that we want to become Stacks users. Persuading them to get familiar with a technical, perceived as exclusive and complicated blockchain terminology, might be a challenge and therefore needs to be addressed already on a design phase, to build the whole project as inclusive as possible and easy-to-start even without any understanding of the blockchain itself. The third major challenge is much more technical – and revolves around the merger of WEB2.0 and Web3 thinking. We believe that in order to scale fast gamedev studios and publishers will need to use centralized architecture on game backend and merge it with P2E mechanics making it hard to accept by crypto/bitcoin/blockchain maximalists.
Having strong partnerships (LOIs mentioned before) and a wide web of connections in one of the most flourishing markets of gaming industry (we are located in Poland which has more gamedev studios than California) allows us to evangelize and if needed personally convince leading gamedev studios and publisher to give blockchain a try and tap into Web3 potential using our Toolset. We are well known entrepreneurs in Poland, which is giving us an unfair advantage in building Stacks community here. For example the CEO of CD Projekt (creators of The Witcher) is just one phone call away. Having an experience from porting a WEB2.0 mobile game (Creature Racer) into the P2E blockchain era, we just know what are the obstacles and we want to create a comprehensive set of tutorials and FAQs on how to overcome most frequent problems both for users and developers. We know the entrance level for Web2.0 users into Web3 must be as low as possible. In a perfect scenario not demanding from the user anything else except a sole decision to connect their wallet and just give it a try! The game itself should onboard users to a play & earn model and focus only on fun, beneficial parts, not on technicalities behind the curtains. Third challenge is a psychological one, but we believe that most maximalists will benefit from wide blockchain adoption so one day they will give a try to those F2P and P2E merger products – especially during the current “crypto winter”.
But the biggest risk right now is that we applied for a grant with an old form (Grant580) and all our scope and work will now go to trash as new form is not allowing us to apply to build whole “Advanced mobile games toolset for F2P and P2E merger”. The only plan to overcome this is right what I just wrote to make you know and understand that we want to build a bigger toolset and we will apply for next grants as soon as we will see that this one is being finalized in terms of job done on our side.

**[Support Link:](https://drive.google.com/drive/u/1/folders/162CQVpPlOFHrY7rs3dBTp4LhZt2OvYbz; https://grants.stacks.org/dashboard/grants/580; https://miro.com/app/board/uXjVOleUZ5I=/?share_link_id=109698652778))**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Google drive - LOIs, screenshots of talks with Stacks Degens, Stacks Force, Kyle and Trevor
Grant 580 - Will asked us to resubmit because grant form changed
Miro - Stacks Degens + Stacks Force + Wannabe Games shared board no to overlap work (we also have a discord

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;MILESTONE 1: A set of generic advanced P2E smart-contracts (generic, so allowing multiple gists implementation): Deliverable:                   Generic item operations: purchase with funds transfer to reward pool contract to stake&earn, upgrade with new NFT minting, mint with royalties burned in the contract, mint with expiration date. Generic Stake NFT to Earn operations: stake with expiration date, unstake, auto-unstake when expired, upgrade with auto new NFT mint. Reward Pool with operations: everyday flush operation, flush when reached, flush from backend, auto divide rewards, send rewards to staked NFTs Referral Code NFT (rNFT) with operations: mint new, auto upgrade when level reached, claim funds.

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;A set of generic advanced P2E smart-contracts with guidelines what Stacks GameFi needs to thrive

**Comment by stacks-foundation** [comment]
👋 @czeslaw
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by KolegaLiterat** [comment]
Interesting project!

**Comment by will-at-stacks** [comment]
Hi @czeslaw  -

Thank you for your application. As the Grants Review Committee begins their reviews this week and next, we wanted to reach out and see if there is potential to rescope the size of your grant request. Given the projected outcomes of your project compared to cost and the competitive applications in this review batch, this grant is not likely to get approved at it's current size and deliverables. As of now, we have funding for 40-50% of the applications received. If you would still like to be considered in this round, we recommend rescoping your proposal to a lower amount that closer reflects the industry standard of $75/hr.

Lastly, when we kicked off the review cycle with the Review Committee we brought them up to speed on the top three objectives we are prioritizing for this cohort:

1. Support grants that improve Stacks-Bitcoin integration.
2. Support grants that improve the Clarity developer experience and attract new Clarity developers to Stacks.
3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

If you could, please comment here if you feel your project is consistent with one or more of these objectives and let us know how and why.

Thanks!
Will

**Comment by czeslaw** [comment]
Hi @will-at-stacks ,

we can cut the total budget to USD 12 000, with cutting out the team that will be coordinating work on our side. As we are a battle tested team, we will be able to do it just to progress in terms of working on the „Advanced mobile games toolset for F2P and P2E merger”. As mentioned in grant application, we have LOIs with companies that are waiting for tools that we want to build and we want to start asap as we got caught up in grant application transition which delayed our roadmap in the first place for few months :( . We know that some of the things that are mentioned may seem as already existing on Stacks blockchain (as for example staking NFTs), but they need to be reshaped and redone to properly work for web 2.0 GameDev studios to have a toolset for a smooth transition to Web3 using Stacks, powered by stake and earn mechanics that we propose. None of web f2p GameDev studios will be willing to create a blockchain team to dig through contracts and adapt them to their special needs just to try if Web3 is something they want to go for. We propose a toolset of generic contracts that will be drag and drop with guidelines on how to use them. Stake and earn mechanics that will allow a merger between the  p2e decentralized and f2p centralized thinking, as web2 needs incentivizing bridges to web3 and not creating a web3 stronghold that will be anti web2. 

In terms of prioritizing in this cohort we are a perfect match for: Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

LOIs that we have prove that our grant will greatly improve the attractiveness of Stacks as a place to build GameFi products. As a GameDev accelerator alumni (KPT Digital Dragons https://digitaldragons.pl) and a part of portfolio companies of Satus Games VC (http://www.satus.pl/en/fund/ ) we have broad contacts  to GameDev community allowing us to bring more founders to Stacks

Kind regards,
Piotr, Norbert & Wannabe Team

**Comment by owenstrevor** [comment]
Have met with this team and find them both competent and focused on an important problem for this ecosystem.

**Comment by stxfrc** [comment]
We at Stacks Force know Wannabe team and think that their toolset will be much needed in the ecosystem. With LOIs that they have Wannabe will bring faster Stacks adoption bringing founders to Stacks

**Comment by will-at-stacks** [comment]
Hi @czeslaw -

Congrats!  Your grant application has been approved.  We just sent you an invite (to the email the application was submitted with) to an onboarding call on Monday.  We will use this call to provide an overview of next steps and expectations for proceeding with the grant.

If you are not able to make the call, don't worry, it will be recorded.  

Best,
Will
Stacks Foundation Grants Program Manager.

**Comment by czeslaw** [comment]
Thank you @will-at-stacks ! I'm already excited! 

Can I bring my team with me to the call, or should I be alone?

Kind regards,
Piotr

**Comment by Scarlett-Web3** [comment]
I think you have an interesting project. If you haven't already gone through the Stacks Web3 Startup Lab, I would like to invite you to apply.  

Here's a 5-minute read on how we can help you turn your startup idea into an investment-ready startup:
www.web3startuplab.io

If you are interested, you can apply through the "Apply Now" button.

Feel free to ping me on email:  scarlett@stacks.ac

**Comment by will-at-stacks** [comment]
Updates to this grant can also be found [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/762)

**Comment by SzakaBum** [comment]
Hi @will-at-stacks, we have completed the work specified in the grant. I am sending you a link to our gitbook where you will find the results.

[General Intro - Mobile games toolset for F2P and P2E merge (gitbook.io)](https://wannabe.gitbook.io/mobile-games-toolset-for-f2p-and-p2e-merge/)

Please verify this and let me know if we can settle the grant.

Best regards 
Maciek

**Comment by will-at-stacks** [comment]
Hi @SzakaBum and @czeslaw -

Thanks for the update.  This looks great!  

@shaktistacks please disburse M1 payment (noted in Notion too).

@SzakaBum minor detail, but please post updates and funding requests [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/762) moving forward.

**Comment by JakeBlockchain** [comment]
@SzakaBum  @will-at-stacks The Gtibook link above works but the contracts lead to a 404 page.
https://wannabe.gitbook.io/mobile-games-toolset-for-f2p-and-p2e-merge/contracts

Have these Clarity contracts have a new home?

**Comment by will-at-stacks** [comment]
Confirmed.  Please fix @SzakaBum @czeslaw 

Thanks for flagging @JakeBlockchain

**Comment by SzakaBum** [comment]
@will-at-stacks @JakeBlockchain The content of the page is available to logged-in GitHub users. Non-logged-in users will see a 404, while logged-in users will have access to the repository.

**Comment by JakeBlockchain** [comment]
@SzakaBum Im logged in and still getting a 404. Here's one specific page its happening on.
https://github.com/Wannabe-games/creature-racer-stacks/blob/devel/protocol/contracts/creature-racer-referral-pool.clar

**Comment by SzakaBum** [comment]
@will-at-stacks @JakeBlockchain Hi, actually it was our oversight, the repository was private, now it's public and there shouldn't be any access issues.
