### ISSUE TITLE
STR Web 3 Streaming Service on STX

### ISSUE THREAD

**Issue by JacobRyan258** [stacksgov/Stacks-Grant-Launchpad#612]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;jacobryan258@gmail.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;jryan258#2041

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@JacobRyanMedia

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;JacobRyan

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;STX Web 3 Streaming Service

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;40,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;400

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks dApps & Clarity  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Audience is anyone who listens to music and collects Music NFTs 

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;JacobRyan258, Sahrodion, YourMercury

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;My team and I have successfully completed milestones for 2 previous Grants and have our Music NFT marketplace live on mainnet.

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Web 3 Startup Lab

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;This streaming service will be the first of its' kind where you will be able to deploy a music NFT - automatically upload song into our streaming service. Listeners can then purchase NFTs with a click of a button and be taken directly from streaming service to the artists profile to mint or buy the NFT they were listening to. 

Artists own the music and create a record label of sorts between their communities and fans. 

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The platform will be measured by the number of users who sign up to deploy their Music NFTs on our platform and NFT sales volumes. 

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Risks associated include an incorrect estimation on time it will take to complete. We overcome this by meeting weekly to determine immediate course of action. We meet Wednesdays at 3 PM Central Standard Time

**[Support Link:](https://www.loom.com/share/90af1c09322747fcb5100925ec7413d4)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Loom video of current progress of STR Marketplace with STX web 3 streaming service design. 

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Frontend completion of the fully designed streaming service

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;NFT contracts auto input music to streaming service - users can listen & buy

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;STX web 3 streaming service - marketplace connected.

**Comment by stacks-foundation** [comment]
👋 @JacobRyan258
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by friedger** [comment]
Is this related to gaideo.com?

**Comment by JacobRyan258** [comment]
Hi Friedger, thank you for your question. 

I don't believe so - my team and I have been working on STR since January of this year. Happy to meet the Gaideo team if there is any interest.

**Comment by friedger** [comment]
Will you own the uploaded music? How is the copyright handled?

With gaideo videos are hosted by the users themselves: https://github.com/gaideo/gaideo

**Comment by JacobRyan258** [comment]
That's a great question - we are creating a backend infrastructure system with this grant application that will allow for tracking of music via web 2.0 and web 3.0 solutions. This will allow for music to be uploaded to the Stacks Blockchain and broadcast into your 'Radio Vault' where you can point any NFT metadata to on any chain. Music will be owned by the creator or the entity that controls the master copyrights identified when the Radio Vault gets created. We will not own the music or the rights at all. This infrastructure is needed in order for mainstream to adopt music and web 3.

**Comment by RagnarLifthrasir** [comment]
Music NFTs are a proven use case, and this grant application seems to fit a gap in the market. I've spoken to @JacobRyan258, and I'm confident his team can execute their deliverables.

**Comment by G1ne** [comment]
Can't wait to see this really grow!  Building to include Web2-Web3 streaming and the management of 3rd party royalties is the nut to crack for NFT's and music.  This project proposes developments that would extend to and improve gaming and other types of media and content.  Full support!!

**Comment by DocHolliday637** [comment]
This would be a great thing to have built on STX.

**Comment by Justin954** [comment]
I think this project will unlock a lot of potential with music in games, metaverse, and music streaming for web 3! I can’t wait to see this project completed! The team is committed to the music industry and the Stacks blockchain! This goes a long way in creating a user owned internet secured by Bitcoin!  I see this grant opportunity as a path to the future with web2-web3 technology! I am sure this project is why many people have been waiting for to transcend into the future! Full support!

**Comment by Justin954** [comment]
I think this project will unlock a lot of potential with music in games, metaverse, and music streaming for web 3! I can’t wait to see this project completed! The team is committed to the music industry and the Stacks blockchain! This goes a long way in creating a user owned internet secured by Bitcoin!  I see this grant opportunity as a path to the future with web2-web3 technology! I am sure this project is why many people have been waiting for to transcend into the future! Full support!

**Comment by bill3129066** [comment]
Music NFTs are the things would bring lots of traffic into Stacks, and @JacobRyan258 is a seasoned industry professional. Full support :)

**Comment by smithzach772** [comment]
I am in full support of this innovational approach, not only is it needed but it is valued. We have seen especially during these times of the pandemic that these types of services are valued globally and nationally.

**Comment by will-at-stacks** [comment]
Hi @JacobRyan258  -

Thank you for your application. As the Grants Review Committee begins their reviews this week and next, we wanted to reach out and see if there is potential to rescope the size of your grant request. Given the projected outcomes of your project compared to cost and the competitive applications in this review batch, this grant is not likely to get approved at it's current size and deliverables. As of now, we have funding for 40-50% of the applications received. If you would still like to be considered in this round, we recommend rescoping your proposal to a lower amount that closer reflects the industry standard of $75/hr.

Lastly, when we kicked off the review cycle with the Review Committee we brought them up to speed on the top three objectives we are prioritizing for this cohort:

1. Support grants that improve Stacks-Bitcoin integration.
2. Support grants that improve the Clarity developer experience and attract new Clarity developers to Stacks.
3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

If you could, please comment here if you feel your project is consistent with one or more of these objectives and let us know how and why.

Thanks!
Will

**Comment by JacobRyan258** [comment]
Hi @will-at-stacks,

Yes that works for our application. We would like to adjust the amount of the grant to reflect 400 hours at $75/hour for a total grant amount of $30,000. 

As for the top three objectives - 
1. Our application supports and encourages all the best music and artists to house their music NFTs on Stacks to secure to Bitcoin. 
2. Our focus on music will not only bring in a community of music artists but also developers, designers, and other professionals to the Stacks ecosystem. Our team already has 2 devs that are proficient in clarity and will continue to teach as our team scales. 
3. Our infrastructure and the support of this grant will bring in a large number of users to not only listen and consume music freely, but also have the opportunity to own and have access to artists. Music NFTs are going to be an important piece for individual artists and artists that belong to record labels. 

Thank you,
Jacob

**Comment by 3hunnatheartist** [comment]
> # APPLICANT
> **Type:**                                                                        Direct Application
> 
> **Email:**                                                                    [jacobryan258@gmail.com](mailto:jacobryan258@gmail.com)
> 
> **Discord:**                                                    jryan258#2041
> 
> **Twitter:**                                                        @JacobRyanMedia
> 
> **Stacks Forum:**           JacobRyan
> 
> # GRANT BASICS
> **Grant Name:**                                        STX Web 3 Streaming Service
> 
> **Total Budget:**                              40,000
> 
> **Total Duration:**                 400
> 
> **Grant Type:**                                               Open Source Dev Repeat Grantees
> 
> **Grant Track:**                                          Stacks dApps & Clarity
> 
> **Grant Goal:**                                               Create New Technology
> 
> **Grant Audience:**             End Users (Consumer)
> 
> **Specific Audience:**         Audience is anyone who listens to music and collects Music NFTs
> 
> **Grant Team:**                                       JacobRyan258, Sahrodion, YourMercury
> 
> **Previous Grants:**                      My team and I have successfully completed milestones for 2 previous Grants and have our Music NFT marketplace live on mainnet.
> 
> **Ecosystem Programs:**      Web 3 Startup Lab
> 
> # GRANT MISSION, IMPACT, RISKS & REFERENCE
> **Grant Mission:**         This streaming service will be the first of its' kind where you will be able to deploy a music NFT - automatically upload song into our streaming service. Listeners can then purchase NFTs with a click of a button and be taken directly from streaming service to the artists profile to mint or buy the NFT they were listening to.
> 
> Artists own the music and create a record label of sorts between their communities and fans.
> 
> **Grant Impact:**               The platform will be measured by the number of users who sign up to deploy their Music NFTs on our platform and NFT sales volumes.
> 
> **Grant Risks:**                          Risks associated include an incorrect estimation on time it will take to complete. We overcome this by meeting weekly to determine immediate course of action. We meet Wednesdays at 3 PM Central Standard Time
> 
> **[Support Link:](https://www.loom.com/share/90af1c09322747fcb5100925ec7413d4)**                                     Loom video of current progress of STR Marketplace with STX web 3 streaming service design.
> 
> # GRANT ROADMAP & DELIVERABLES
> **MILESTONE 1:**
> 
> **Deliverable:**                   Frontend completion of the fully designed streaming service
> 
> **MILESTONE 2:**
> 
> **Deliverable:**                   NFT contracts auto input music to streaming service - users can listen & buy
> 
> **FINAL DELIVERABLE**
> 
> **Deliverable:**                   STX web 3 streaming service - marketplace connected.

Thanks for your application!

**Comment by 3hunnatheartist** [comment]
Amazing Work Jacob

**Comment by will-at-stacks** [comment]
Hi @JacobRyan258 -

Amazing!  Thanks for the feedback and budget accommodation.  I will let you know if we have any further questions.

Best,
Will

**Comment by G1ne** [comment]
I would like to comment on this one particular objective in relation to this application.  Just to reiterate my support and confidence in this.

> 3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

From my understanding and speaking with @JacobRyan258 STR long-term will enable many record labels, musicians and music companies to build their businesses and fanbases intricately to align with royalty distributions, merchandising and more...

The solutions proposed by this application are among the top sought-after solutions in the media/music (especially)/gaming industries when it comes to their utility in the Web3 world.

I would go as far as saying that should this solution be completed in a way that is easy to implement or to connect to, it is likely to have a majorly positive impact on the attractiveness of Stacks and building using this solution for musicians across the board, all of the named industries and possibly more.  The correct implementation also speaks volumes to handling IP in Web 3 overall.

Great feedback @will-at-stacks and smashing work Jacob!

**Comment by JacobRyan258** [comment]
> I would like to comment on this one particular objective in relation to this application. Just to reiterate my support and confidence in this.
> 
> > 3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.
> 
> From my understanding and speaking with @JacobRyan258 STR long-term will enable many record labels, musicians and music companies to build their businesses and fanbases intricately to align with royalty distributions, merchandising and more...
> 
> The solutions proposed by this application are among the top sought-after solutions in the media/music (especially)/gaming industries when it comes to their utility in the Web3 world.
> 
> I would go as far as saying that should this solution be completed in a way that is easy to implement or to connect to, it is likely to have a majorly positive impact on the attractiveness of Stacks and building using this solution for musicians across the board, all of the named industries and possibly more. The correct implementation also speaks volumes to handling IP in Web 3 overall.
> 
> Great feedback @will-at-stacks and smashing work Jacob!

Thank you for your support @G1ne  - this is absolutely correct and we are lucky to be the team working on this :)

**Comment by JacobRyan258** [comment]
Thank you everyone for your support of this grant! We are very excited to make an impact in Music and Web 3 all secured to Bitcoin via Stacks! My team and I really enjoy building here! Onward ^-^

**Comment by Tools2023** [comment]
This infrastructure will be huge for music and web 3! I completely back this grant and know the team is capable of delivering the milestones and more!

**Comment by dartman10** [comment]
+1

**Comment by AJAyanbisi** [comment]
Love this amazing idea, will be great if built on Stacks. 👏

**Comment by will-at-stacks** [comment]
Hi @JacobRyan258 

We have identified the projects we will be awarding grants as part of Stacks Foundation Grants Program Cohort 18. I'm sorry to have to inform you that your project was not among those selected.

This is no way means that we do not see the value of the work you proposed. We're lucky to have so many talented independent researchers, developers, and community leaders like yourself building on Stacks. Unfortunately, we receive many more proposals than we can actually fund with our limited means, so competition is extremely tough. While we generally support innovation in all forms, we tend to prioritize projects that have the potential to advance and differentiate the broader ecosystem from other blockchains, as well as projects that meet critical needs of the community *at the time*. These constraints mean that in several instances, several excellent projects may not make it into a cohort.

We very much appreciate the time and effort you've put into this process and encourage you to continue watching this repo and consider submitting a new application if and when you feel your project better aligns with the current priorities of the Grants Program.

If you should have any questions, please let us know in the comment section below.

Best,
Will
Stacks Foundation Grants Program Manager
