### ISSUE TITLE
Stacks Pakistan Chapter Grant Application

### ISSUE THREAD

**Issue by nabeelaq** [stacksgov/Stacks-Grant-Launchpad#62]
### Help us understand your vision for your Stacks Chapter by answering the following questions:

**1. What about Stacks are you most excited about? Please be specific. (For example, you could be excited about “recruiting more Stackers” or “bringing DeFi to Bitcoin”.)**
Pakistan is the 5th largest population in the world. We are a young nation with 64% of our population that is 30 years and under. We are excited about educating our young minds about Web 3.0. 
We envision Pakistan to be an early riser in tech and with Stacks being co-founded by a Pakistani, we have found our direction in making Pakistan adopt Stacks as its tool for a decentralised internet. So what we’re most excited about Stacks is to prepare and direct our youth to become believers of Stacks! 

**2. Why are you so excited about this? How do you think it can help your community?**
In Pakistan, we have a natural inclination towards either pursuing a career in Medicine or Engineering. Computer Science and Software Engineering are popular subjects that youngsters opt for. According to the Pakistan Software Export Board, Pakistan’s IT exports increased by 44% during the first quarter (July, August and September) of the fiscal year 2020-21 alone. This indicates our nation’s potential of adopting Blockchain technology secured by Bitcoin i.e. Stacks. 

In addition, with our teledensity of 83% and consistent efforts by government to make the internet accessible to all, we have a high adoption rate of new technologies. Our startup landscape is also booming with more and more youngsters stepping into technology-based startups. Hence, how Stacks will help our community is by giving our young developers and budding entrepreneurs an opportunity to be a part of the global movement of web 3.0 and collectively putting Pakistan on the map of early risers in Crypto and Blockchain.

**3. What do you think is the single most effective thing you can do to bring Stacks to your community?**
The first step is to make people aware of the global shift towards decentralisation of the internet. We have been working on spreading awareness through disseminating educational content on social media platforms (Facebook & Twitter) as well as assigning spread of Stacks information to City Leads (representatives of Stacks in different cities of the country). We now have a strong community in 7 metropolitan cities of Pakistan namely, Lahore, Karachi, Islamabad, Peshawar, Quetta, Abbottabad and Faisalabad. This encompasses all provinces of the country. So now, our next step is to train this community in Blockchain, Crypto and Carity language through online bootcamps as well as through creation of technical video content in local language.

**4. What are your goals for your Stacks Chapter for the next 3 months? 6 months? 1 year?**

- In 3 months, we aim to host Pakistan’s first Stacks Hackathon on Blockchain. We aim to launch Stacks Bootcamp to educate and train a thriving developer community on Blockchain, Crypto and Clarity Language (this would be an ongoing Bootcamp repeating every quarter).
- In 6 months, we aim to host Pakistan’s largest conference on Blockchain. This will help in creating awareness of Blockchain Technology and its use cases, Web 3.0, Stacks Tools and above all policy awareness which will lead to Blockchain and Crypto Regulation of Pakistan.
- In one year, we want to introduce 100 hard-core Stacks developers to Stacks Community, identify developers who can build at least one of the Wish List grants and lastly, make Stacks the most active crypto network for developers in Pakistan.

**5. How do you plan to achieve those goals? (You can share broad strategies here.)**
Strategy:

- Community Building:
1. Build community of Blockchain developers, Cryptocurrency enthusiasts and advocates of data privacy on the internet, 
2. Run University & Industry awareness drives, 
3. Host Facebook Community Calls, 
4. Host AMAs with Global Stacks Team, 
5. Launch Stacks Ambassadors Program, 
6. Build partnerships with Educational and Training Institutes.

- Education: 
1. Launch Blockchain and Clarity Bootcamps, 
2. Conduct Blockchain Hackathons,
3. Make Certifications, Short Courses, Diplomas on Blockchain and Clarity language,
4. Online tutorials on how to build from zero to dApps.

- Advocacy: 
1. Industry Roundtable Conferences on Blockchain and Cryptocurrency, 
2. Industry Meetings on Blockchain and Cryptocurrency Regulation.

**6. If you have growth goals (e.g. “grow the Telegram community by X%), is there a place where the Stacks community can see and track your progress?**
1. Create a Discord Channel for local Blockchain developers.
2. Increase subscribers from Pakistan to Stacks Newsletter.
3. Increase our Facebook community by 100% in the next 3 months.
4. Increase Twitter followers by 100% in the next 6 months.
5. Telegram(We would like the admin control of it)= Increase it by 100% in the next 1 year.

**7. (Optional) Share examples of any community growth or progress so far. This can be in the form of metrics (e.g. Twitter or Telegram growth), press/good news, or community stories.**

- PR Mentions= 28

1. [The Nation](https://nation.com.pk/03-Dec-2020/blockstack-pbc-successful-in-bootstrapping-a-thriving-ecosystem-around-stacks-blockchain)
2. [The Financial Daily International](http://epaper.pknewspapers.com/the-financial-daily-international.html)
3. [Daily Islamabad Post](https://islamabadpost.com.pk/e-paper-dec-1/)
4. [BNews99.com](https://bnews99.com/blockstack-a-new-internet-where-you-own-your-data-comes-to-pakistan/)
5. [TechShaker.com](http://techshaker.com/2020/12/03/blockstack-a-new-internet-where-you-own-your-data-comes-to-pakistan/)
6. [NUT](https://newsupdatetimes.com/blockstack-a-new-internet-where-you-own-your-data-comes-to-pakistan/)
7. [TechnologyTimes.pk](https://www.technologytimes.pk/2020/12/03/blockstack-pbc-successful-in-bootstrapping-a-thriving-ecosystem/)
8. [Will Pakistan Reap the Benefits of Crypto or Not?](https://en.dailypakistan.com.pk/28-Dec-2020/will-pakistan-reap-the-benefits-of-crypto-or-not)
9. [Interview with Muneeb Ali, a Pakistani-American computer scientist and entrepreneur](https://www.brecorder.com/news/40046933)
10. https://www.brecorder.com/news/40066335/lums-leverages-41m-stacks-grant-to-build-novel-academic-programme-in-pakistan
11. https://propakistani.pk/2021/02/22/lums-to-launch-pakistans-first-ever-academic-program-in-cryptocurrency/
12. https://www.technologytimes.pk/2021/02/19/lums-partners-with-stacks-pakistan-to-develop-courses-focused-on-blockchain-technology/
13. https://dnd.com.pk/stacks-gives-lums-research-grant-of-five-million-stx-tokens-worth-approximately-4-1-million/213304
14. https://whenwherehow.pk/2021/02/22/in-a-first-lums-to-launch-pakistans-academic-program-in-cryptocurrency/
15. https://www.thenews.com.pk/print/794223-stacks-gives-lums-4-1m-research-grant
16. https://zivallo.pk/2021/02/21/lums-partners-with-stacks-pakistan-to-develop-courses-focused-on-blockchain-technology/
17. https://startuppakistan.com.pk/lums-and-stacks-pakistan-join-hands-to-bring-blockchain-technology-to-the-forefront/
18. https://www.technologytimes.pk/2021/02/22/stacks-gives-lums-a-research-grant-of-five-million-stx-tokens/
19.  https://lahoreherald.com/lums-cryptocurrency-program/
20. https://defence.pk/pdf/threads/lums-to-launch-pakistans-first-ever-academic-program-in-cryptocurrency.702497/#post-12976537
21. https://lifeinpakistan.net/lums-to-develop-pakistan-first-blockchain-technology-academic-program/
22. https://nationbytes.com/lums-to-launch-pakistans-first-blockchain-courses
23. http://www.enews.pk/lums-introduces-first-cryptocurrency-academic-program-in-pakistan/
24. http://www.zemtv.co/stacks-gives-lums-research-grant-of-five-million-stx-tokens-worth-approximately-4-1-million/
25. https://futureprotech.com/2021/02/22/lums-to-launch-pakistans-first-ever-academic-program-in-cryptocurrency/
26. https://tacbz.com/2021/02/22/lums-to-launch-pakistans-first-ever-academic-program-in-cryptocurrency/
27. https://www.reporterpk.com/stacks-gives-lums-a-research-grant-of-five-million-stx-tokens/
28. https://pk.mashable.com/blockchain/7912/stacks-gives-lums-a-grant-approximately-worth-us41-million-to-research-blockchain-technology-and-dis

- Number of Community Outreach Partners: 12
- We have designed and rolled out our City Leads Program called Stacks Developers Guild (SDG) - A premier consortium of Stacks believers from Pakistan. We have presence in the following cities now:
• Lahore
• Karachi
• Islamabad
• Quetta
• Peshawar
• Abbottabad
• Faisalabad
For every city we have an SDG Lead who is helping us scout Stacks Ambassadors in universities of their respective cities.
- Number of Facebook Community members: 120
- Number of Facebook page followers: 643
- Number of Twitter followers: 207
- Number of Telegram Community members: 68 
- Number of Community Calls hosted: 12
- Online campaigns launched/ our hashtags = 7
#OwnYourInternet and #StacksPakistan goes with every digital post or reshare.
#StacksLocal used with local language Posts
#StacksPartner for every partnership
#02dApps for every bootcamp post
#StacksAMA for all our AMA’s
#StacksMention when we get featured anywhere
#StacksArchive for any past video
#StacksDYK for all informational posts

**7. Briefly summarize your operating costs for one quarter (3 months).**

> **Summary
> Team= $4,188/ mo = $12,563/quarter
> Social Media + Softwares = $145/mo = $435
> Marketing & PR = $906/mo = $2,719/quarter
> Miscellaneous = $1,000/ quarter
> Total= $16,716/ quarter**

- Team: Country Consultant, Community Manager, Social Media Manager, Graphic Designer and Operations Manager
- Social Media + Online Softwares: Facebook, Canva and Streamyard
- Marketing & PR: PR Firm, Video production
- Miscellaneous: Any additional expenses. 

However, a one-time cost we need to incur is of merchandise which we’ll get made for the entire year in one go. This is to give to our community members. Here are the details:

Merchandise (One time Cost for 1 year)
- Mask
Quantity: 500
Total Price= $375 
- Pen 
Quantity= 500
Total Price= $156
- Paperback Diary
Quantity= 500
Total Price= $1,719
- Holographic Stickers
Quantity= 1000
Total Price= $75
- T-shirts
Quantity= 100
Total Price= $500
- Paper Bag
Quantity= 500
Total Price= $313
-Hand Sanitizers 
Quantity= 500
Total Price= $219
- Mugs
Quantity= 500
Total Price= $625
- Standees 
Quantity= 4
Total Price= $75

**Total for merchandise= $4,056**
**Please note: For any events such as Hackathons and Conferences, budget will be shared in addition to this.**

**Comment by RaffiSapire** [comment]
Hi there, @jennymith has approved this as part of the Chapter program. I will set up a monthly disbursement cadence. Please continue to share here and with Jenny any updates or fun community sharebacks!

**Comment by RaffiSapire** [comment]
please email me at raffi@stacks.org and I'll help you get set up on bill.com.
