### ISSUE TITLE
STX-C // Community Event Management & Inventory Tracking

### ISSUE THREAD

**Issue by Alisammour** [stacksgov/Stacks-Grant-Launchpad#645]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ali@theflatlay.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;     ali#9835

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;flatlay

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;STX-C // Community Event Management & Inventory Tracking

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;32,500

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;425

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Developer Experience  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; Developers and companies benefiting from providing partial ownership of NFT’s through proof of ownership and proof of conversion. This supports the foundation's request for token gating event management with infrastructure tooling compatible with Xverse/Hiro. Also will enable Heylayer/RoundlyX to allow their members to roll savings towards vesting on blue chip NFTs and track progress. 

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; nokhodian, erfanyeganegi, alisammour

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/570    http://fractionalizer.droplinked.com

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;FLATLAY was part of Stacks Accelerator cohort 2 and we are working across companies and partners between C1 & C2

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; Stacks Commerce (STX-C) is a smart contract system enabling independent buyers, sellers & value add parties to contribute & be rewarded for the exchange of goods & services. The system provides mechanisms to automate affiliate sales tracking & autonomous rewards association enabling owners and contributors to partner with one another while addressing the compromises of centralized systems. Centralized networks are prone to a lack of transparency & keen to mistreat trust (lacking data & capturing excessive revenue from transactions across their networks).

STX-C provides the ability to mint NFTs & fractionalize them to a desired amount. The NFTs can represent physical goods, services & digital products. The fractions can equate to the volume of products produced or the amount made available for batch listings & collections. Exchange & ownership related to fractions can represent the purchase of a product, service or true ownership of a listed item. Actual goods & services are represented as an exchangeable fraction of an NFT enabling many functionalities.

In what ways does this project bring us closer to a user-owned internet?

This project helps to associate NFT fractions with real-world products and services. This enables a DAO or any 3rd party to fully organize an affiliate network with pre-agreed terms and conditions that are fully transparent between every authenticated and contributing party. This will enable 3rd parties to unlock many value-add features.

How will this project accelerate a broader adoption of Stacks?

- Enable businesses to create their dCommerce solutions atop of Stacks
- Enable  event management for STX community members and projects focused on the STX ecosystem
- Enable affiliate and secondary sales in a very efficient and transparent way that will benefit any retailer, marketplace or dapp being built for the ecosystem

Explain how this project will have a positive and meaningful impact on the Stacks community?

Provides open source tooling empowering devs to adapt the solution to their own use cases. However this use case specifically will support the community for any future events that want to enable token gating functionalities.

Community Event Management Tooling:

A library to provide infrastructure that allows event organizers to mint and distribute Attendance NFTs on Stacks. Create an API library that enables event organizers/developers in the Stacks community to distribute digital badges/collectibles NFTs minted on Stacks for their events. 
1. Given a minter: mint NFTs for all attendees with the same metadata and artwork. The NFT minted should include a memo/taxon field that include information about the event (date, location and description) and an artwork that represents the event.
2. Gateway for attendees: collect the NFTs through their wallets of choice or create new wallets and distribute them securely.
3. Event attendees lookup: Add a way for people to look up wallets with the same event NFTs.
4. Event NFT ownership verification: Add an API for people to verify the event NFT using their signature to prove that they are the owner of the account associated with the NFT.

Other use-cases: 

- Providing the platform for developers to better leverage web3 commerce tools that can be customized into their own properties/sites 

- Allow for the integration of dCommerce value-add offerings in a structured format that can be made actionable across the network (dapp devs, shipping and logistics providers, merchandise production and fulfillment, etc.)

- An affiliate network for the ecosystem so that all NFT sellers and existing community members can provide access to 3rd parties a way to incentivize co-promotions and co-selling.

What is your community engagement plan throughout the process of the project?

- Engaged with ecosystem partners (STX Foundation, The Mintery, GAMMA, HeyLayer, RoundlyX, Hiro, Xverse, Console, Frens) to support NFT gated event management along with the fractionalization of blue-chip high value NFT’s for co-vesting between constituents and community members

- Working with executive teams and stakeholders to customize libraries and solutions to make shoppable collection embeddable units to be used across their properties in order to make content and promotions more discoverable while providing a native look and feel

- Encouraging community feedback across various Discord threads/forums and Twitter spaces to gauge and incorporate input and improvements

- Providing updates on community foundation calls of the teams progress while asking for collaborative input from new strategic partners interested in adopting STXC

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our community engagement plan throughout the process of the project:

- Working with executive teams and stakeholders to customize libraries and solutions to make interactive collection embeddable units to be used across their properties in order to make content and promotions more discoverable while providing a native look and feel

- Encouraging community feedback across various Discord threads/forums and Twitter spaces to gauge and incorporate input and improvements

- Providing updates on community foundation calls of the teams progress while asking for collaborative input from new strategic partners interested in adopting STXC

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;What challenges, technical or otherwise, do you anticipate encountering throughout this project?

- Accounting for scalability when it comes to the number of smart product listings incorporated across the network.
- Incorporating room for anomalies or variables that are not standardized with the typical association of different use cases for adapting smart product listings.
- Building adoption across current marketplaces without overcomplicating usage and settlement of existing inventory

What is your plan for overcoming these challenges?

 - Working with members across the community, our investor and executive advisory portco’s along with Stacks backed teams to incorporate constructive feedback and input to avoid these scalability issues and pitfalls
-  Partnering with Mintery NFT artists and STX marketplaces to build sustainable infrastructure based on their needs to create scaled adoption use cases and case studies beyond to service future community adopters

**[Support Link:](https://docs.google.com/document/d/1ybeMfriXs-p5jNe_NZdcxxgK2kqHIOlsndmfRnLVK4w/edit?usp=sharing)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;With this grant submission, we will be contributing the open source portion and libraries needed for the decentralized inventory management and sales tracking system on STX.

https://www.crowdcast.io/e/community-updates-call-july-2022
First 3 min Morteza/34m Ali QA

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Source code and libraries enabling collaboration between sellers & 3rd parties

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Interactive portal with libraries for 3rd party developers to use

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Full documentation behind the contract and libraries for custom adoption & use.

**MILESTONE 4:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;STX Pay - system to accept transactions associated to a fiat value 

**MILESTONE 5:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;An in-depth outline of all deliverables provided in google doc included here: https://docs.google.com/document/d/1ybeMfriXs-p5jNe_NZdcxxgK2kqHIOlsndmfRnLVK4w/edit

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Sandbox to enable any 3rd party to adopt a trust-less deComm solution using STX.

**Comment by stacks-foundation** [comment]
👋 @Alisammour
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by Alisammour** [comment]
Hi team - we've gone ahead and broken out the initial open source portion to be covered within the grants program to support the STX companies and projects we're working with.

**Comment by Alisammour** [comment]
@will-at-stacks just wanted to confirm but all our supporting comments went onto our bigger app under #595

**Comment by nokhodian** [comment]
Update! Actually, we are using 2nd version of our NFT fractionalizer which is using SIP13 and it's able to associate minted NFTs to SFTs and as well create new SFTs.

**Comment by will-at-stacks** [comment]
Hi @Alisammour   -

Thank you for your application. As the Grants Review Committee begins their reviews this week and next, we wanted to reach out and see if there is potential to rescope the size of your grant request. Given the projected outcomes of your project compared to cost and the competitive applications in this review batch, this grant is not likely to get approved at it's current size and deliverables. As of now, we have funding for 40-50% of the applications received. If you would still like to be considered in this round, we recommend rescoping your proposal to a lower amount that closer reflects the industry standard of $75/hr.

Lastly, when we kicked off the review cycle with the Review Committee we brought them up to speed on the top three objectives we are prioritizing for this cohort:

1. Support grants that improve Stacks-Bitcoin integration.
2. Support grants that improve the Clarity developer experience and attract new Clarity developers to Stacks.
3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

If you could, please comment here if you feel your project is consistent with one or more of these objectives and let us know how and why.

Thanks!
Will

**Comment by Alisammour** [comment]
Thanks @will-at-stacks appreciate the feedback, we actually curbed back the application significantly to address:

#3: Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

We will be creating specific tooling to community event management and developer tooling that allows for the use of NFT fractionalization and gating functions to SIP13 for upcoming community events and developer partnerships. We've stripped out the extra's and brought the grant back down to an awardee range that is reflective to the current batches budget. Look forward to the teams consideration.

**Comment by will-at-stacks** [comment]
Amazing!  Thanks for being flexible and for providing feedback!

**Comment by will-at-stacks** [comment]
@Alisammour we have a couple of final questions for you:

- If this grant is approved on 9/39/22 are you able to complete the work and have it operational by 3/31/23?
- Are you confident the extensive scope outlined in this application can be accomplished?
Thoughts?

Thanks
Will

(cc: @jennymith )

**Comment by will-at-stacks** [comment]
Hi @Alisammour -

Congrats!  Your grant application has been approved.  We just sent you an invite (to the email the application was submitted with) to an onboarding call on Monday.  We will use this call to provide an overview of next steps and expectations for proceeding with the grant.

If you are not able to make the call, don't worry, it will be recorded.  

Best,
Will
Stacks Foundation Grants Program Manager.

**Comment by Alisammour** [comment]
@will-at-stacks thanks for earlier today during the grants review session. We are officially requesting completion of milestones 1 & 2 (initial contract for deployment of events on chain) along with the events dapp front end that we will continue to iterate upon based on community feedback. 

Our final deliverable will be the completed dapp on mainnet and reference documentation to the repo.

**Comment by will-at-stacks** [comment]
Excellent.  Thanks @Alisammour this request is approved.  @shaktistacks can you please disburse payment and post a confirmation here after the fact?  Thanks

**Comment by Scarlett-Web3** [comment]
I think you have an interesting project. If you haven't already gone through the Stacks Web3 Startup Lab, I would like to invite you to apply.  

Here's a 5-minute read on how we can help you turn your startup idea into an investment-ready startup:
www.web3startuplab.io

If you are interested, you can apply through the "Apply Now" button.

Feel free to ping me on email:  scarlett@stacks.ac

**Comment by will-at-stacks** [comment]
Updates to this grant can also be found [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/764)

**Comment by Alisammour** [comment]
@will-at-stacks thanks for the time this week, we are excited to kick off the events Dapp with the foundation team going straight into 2023!

To recap on the discussion:

- adjusting the slippage/grant payment amount for milestone 2's completion
- completion of the final milestone, all codebase, instructional documentation and the updated UXUI that will be deployed from the Figma file can  be found here:

Figma: https://www.figma.com/file/zbSn9C2ygyXNr4gs86JoDF/Events?node-id=0%3A1&t=GJvMZI578Sh8Psj2-1
fractionalizer.droplinked.com (see the bottom for events dapp library repo)

**Comment by will-at-stacks** [comment]
Hi @Alisammour just confirming this was received.  The grant was paid in full (h/t @shaktistacks)

**Comment by Alisammour** [comment]
Thanks @will-at-stacks @shaktistacks confirming that this was covered in full thank you!

**Comment by will-at-stacks** [comment]
All done!  https://fractionalizer.droplinked.com/
