### ISSUE TITLE
bitflow

### ISSUE THREAD

**Issue by diegomey** [stacksgov/Stacks-Grant-Launchpad#647]

**Comment by stacks-foundation** [comment]
👋 @diegomey
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by diegomey** [comment]
@stacks-foundation please delete this submission - submitted while testing the new grants platform :) thanks
