### ISSUE TITLE
NFT2Loan - lending protocol

### ISSUE THREAD

**Issue by NFT2Loan** [stacksgov/Stacks-Grant-Launchpad#653]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;info@bigfungus.xyz

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ropl.btc#7091

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ropl_btc

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ropl.btc

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;NFT2Loan - lending protocol

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;25,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;1,250

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks dApps & Clarity  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;NFT Holders of the top 7 collections.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;petehodl, unclemantis, jayjaybtc, ropl-btc, shrimpo-btc

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Web3 Startup Lab with Albert. This grant is essential for developing our product and will help the Stacks Community grow & pour liquidity into the market.

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;NFT2Loan is an NFT Lending protocol that enables all Stacks users to get a stable coin loan using their NFTs as collateral.

This is a completely new function on Stacks and just to start will potentially unlock an additional $2 million USD in liquidity based on only the top 7 NFT collections. 

Based on the cost of the grant, this is roughly a 80x ROI ($2,000,000 liquidity unlocked / $25,000 grant cost).  This ROI will grow as the number of NFT collections grows on Stacks.

Steps to the goal of a user-owned internet:
- More liquidity in the Stacks Ecosystem = accelerate the growth of the user-owned internet
- Non-custodial: Users have control over their NFTs 
- Increases decentralized activity by giving NFT users access to DeFi features: 
  This project merges NFT and DeFi worlds.

We already built a thriving 900-member community with Rehab Resort.
NFT2Loan is already 200+ member community.
We will use our Discord and Twitter to engage with the community and bring on new users and creators.
We will also work closely with other Stacks community members such as StackerDAO and Gamma.

In the course of our Stacks Pre-Accelerator journey, we have done 70+ customer interviews to find product market fit and a relevant product.

Because of our deep engagement with the Stacks NFT community and our highly skilled team, we believe that we are the best team to execute this product and it will greatly benefit the Stacks ecosystem and users.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our protocol creates more liquidity in the Stacks Ecosystem which accelerates the broader adoption of Stacks because more liquidity on Stacks attracts more NFT creators and their NFTs will attract more users which creates a virtuous cycle of more creators and users on Stacks.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;One challenge will be the development of this protocol and getting the pricing, liquidation mechanism and interest metrics right.
We have built a strong and diverse team that is highly motivated and skilled in various fields. Through the Pre-Accelerator we also made great peers who are happy to help

**[Support Link:](nft2loan.com; https://youtu.be/Z5Vex8PW0tI; https://www.figma.com/file/0jAs0BR4nQIeU9hfsYToN8/NFT2Loan-UI?node-id=0%3A1)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Landing page: nft2loan.com
Pitch: https://youtu.be/Z5Vex8PW0tI
Figma UI mock-ups: https://www.figma.com/file/0jAs0BR4nQIeU9hfsYToN8/NFT2Loan-UI?node-id=0%3A1
GitHub: https://github.com/cyber-fungus (repo is still private but will be public shortly)

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Launch of MVP on Testnet

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Launch of MVP on Mainnet with Megapont as first collection.

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;NFT2Loan will be launched, >1000 NFT holders have access to NFT loans.

**Comment by stacks-foundation** [comment]
👋 @NFT2Loan
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by ropl-btc** [comment]
Small correction: shrimpo-btc is actually Shrimpo44 on GitHub.

**Comment by JacobRyan258** [comment]
Really excited to get liquidity from my NFTs I fully support this grant application! 

Looking forward to this teams progress!

**Comment by Albert-Present** [comment]
This will be a groundbreaking project for Stacks because it will merge the DEFI and NFT worlds.  I can see this project having far reaching results because it will activate the valuable service of activating more liquidity into our ecosystem - this added liquidity helps with growth in a tough market.  Truly a necessary project that will help us achieve the user owned Internet!  In addition, I personally have seen this team overcome challenges so I know they will get the job done!  I support to see this grant get approved!

**Comment by will-at-stacks** [comment]
Hi @NFT2Loan -

Congrats!  Your grant application has been approved.  We just sent you an invite (to the email the application was submitted with) to an onboarding call on Monday.  We will use this call to provide an overview of next steps and expectations for proceeding with the grant.

If you are not able to make the call, don't worry, it will be recorded.  

Best,
Will
Stacks Foundation Grants Program Manager.

**Comment by ropl-btc** [comment]
@will-at-stacks 

Here is an update on where we're at right now.

We deployed testnet version 1.0.1:

**Features**
- Connect Wallet
- Borrow a fixed amount against Testnet Megapont
- Fixed loan duration
- Repay active loans partially or fully anytime
- liquidation when 1. floor price drops below danger zone and 2. loan is not repaid after a set duration
- auction when liquidation occurs
- bidding on live auctions

Here is a Demo Video of our Testnet Dapp so far: https://youtu.be/PPlHYt2xOtM

**Upcoming Features**
_2.0:_
- variable loan duration
- variable loan amount
- a moving average of floor price as the measured value

_3.0:_
- protection against liquidation
- variable interest rate according to loan duration
- Increase Borrow amount when the floor price rises


**What is different from the initial Grant Application:**
- We're using STX instead of stable coin for loans (much easier to track floor price, liquidation price, etc.)
- We will have a treasury to fund loans for MVP, and we might need a follow-up grant to fund the treasury
- We want to add P2P loans later on to avoid having to fund a treasury and make our product accessible to many more collections

**TLDR:** We're pretty much there from what our delivery is. We would only need to bring what we have right now to mainnet. We want to offer more convenience and security, so the product is complete.

Thanks again for the grant, and I hope this little update helps with transparency.

**Comment by will-at-stacks** [comment]
@NFT2Loan -

This looks great!  Thanks for the detailed breakdown.  Milestone 1 is approved.  Looking forward to the final deliverable.  @shaktistacks please disburse this payment.  Thanks, Will

**Comment by shaktistacks** [comment]
Milestone 1 is paid @will-at-stacks  @NFT2Loan 
https://explorer.stacks.co/txid/0x70f8b35fb4bb75278ba34f4bd7439dd36d5c8420ee757e715c6a55349de9853e?chain=mainnet

**Comment by will-at-stacks** [comment]
Grant completed!
