### ISSUE TITLE
Memorializing the Self

### ISSUE THREAD

**Issue by thelifeofpi** [stacksgov/Stacks-Grant-Launchpad#659]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;jah@memora.io

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;parth #9999

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@ogmemora

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Memorializing the Self

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;25,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;150

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Interface  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Bitcoin Wallet Holders & Collectors of Memorabilia! 

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;lifeofPI, neuroscr,  clarencepenz

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We are connecting traditional collectables and memorabilia to the liquidity that exists on blockchain. The issues we faced in 2008 were due to discrepancies between financial regulations, legal enforceability, and unethical rating agencies. As we transition into a world of Open Finance, data dependency is the root of all future possibilities. There is nothing new under the sun, and in order to bank the unbanked fintech will be required to reach scale. Memora is building the primitives to build an inter blockchain NFT standard which allows us to pool global liquidity. This means that your Bitcoins can be used in Banking protocols: lending, credit expansion, P2P trade, Estate Planning: among others as we roll out Memora. 

Life is all about service and building metrics to assess and understand community feedback are core principles of a healthy governance. As a result of this process, cohesive consensus can  be formed at the objective level: given subjective differences in opinion. Proofs of things will lead to the discovery that all is interconnected, no matter what walk of life one is from. In order for personal value to be trusted, a decentralized Memora must be present to preserve collectable records and build wealth and attention for collectors of memorabilia. Our primary niche is in the collectables space, with a primary focus on Collectable cards. We look forwards to presenting our findings to the world and empower all to buidl memorable Stacks! Gracias for your time. 

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Average Transaction Volume, # of DID's created, Total Staked Value / TVL 

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The risks are that this is too early for the market and that as a result of the sentiment the timing is not optimal to launch. Nonetheless, we will mitigate this risk with incentivizing early bird participation and continuing to build utility services for private property/memorabilia. 

**[Support Link:](https://www.youtube.com/watch?v=ThJC38-40Q0&t=125s; internft.org)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;This is a link to our pitch presentation we diid at the Hyper Conference, hosted by Constellationnetwork.io! The following link is a working group of which Memora is contributing towards.

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Attach Bitcoin Wallet DID to your Memora Keychain 

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Mint Memora Non-fungible rights on the Bitcoin blockchian. 

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Securing our Intellectual Property / Rights on the Bitcoin blockchain

**Comment by stacks-foundation** [comment]
👋 @thelifeofpi
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
Hi @thelifeofpi  -

Thank you for your application. As the Grants Review Committee begins their reviews this week and next, we wanted to reach out and see if there is potential to rescope the size of your grant request. Given the projected outcomes of your project compared to cost and the competitive applications in this review batch, this grant is not likely to get approved at it's current size and deliverables. As of now, we have funding for 40-50% of the applications received. If you would still like to be considered in this round, we recommend rescoping your proposal to a lower amount that closer reflects the industry standard of $75/hr.

Lastly, when we kicked off the review cycle with the Review Committee we brought them up to speed on the top three objectives we are prioritizing for this cohort:

1. Support grants that improve Stacks-Bitcoin integration.
2. Support grants that improve the Clarity developer experience and attract new Clarity developers to Stacks.
3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

If you could, please comment here if you feel your project is consistent with one or more of these objectives and let us know how and why.

Thanks!
Will

**Comment by thelifeofpi** [comment]
Peace and good day @will-at-stacks. 

I give thanks for your timely reply! We absolutely can elaborate on how us being granted the opportunity to provide value in achieving the goals for this cohort! We are also more than willing and able to adjust for the 75/hour rate...as we have access to a range of high quality developers at varying levels of skill. I believe that by building Memora, we will be supporting goals 1-3 effectively. 

Memora tokens are used to create Memorandums or to Memorialize existing contracts and collectable assets. By building using Stacks on Bitcoin, we are able to give Bitcoin additional use cases as well as expand the use of Bitcoin to the traditional world by using Bitcoin as an extra layer of security for important documents such as a deed of ownership. Traditional law and property rights have complexities which will attract developers as well as new founders in non technical spaces to join Memora DAO and contribute so that we are able to build a lasting legal infrastructure for anyone to leverage in the digital space. This in turn increases the amount of global trade for small, medium, and large producers; as well as increasing the quality of life for all Collectors of time. One has the right to manage their whole stack, all they have stake in and in a MEMORABLE presence. If it is able to Memora, join us....We thank you very much for the opportunity to be granted a chance to manifest our vision. 

Happy to continue conversation and answer any additional questions. All the best @will-at-stacks @jcnelson @blocks8 Mahalo!

**Comment by will-at-stacks** [comment]
Hi @thelifeofpi Thank you very much for the warn reply!  We appreciate your budget compromise - I've updated our internal budget to reflect 150hours @ $75/hr = $11,250.

I will let you know if we have any additional thoughts or questions.  Final determinations will be posted on 9/30.

Best,
Will

**Comment by will-at-stacks** [comment]
Hi @thelifeofpi - 

We have identified the projects we will be awarding grants as part of Stacks Foundation Grants Program Cohort 18. I'm sorry to have to inform you that your project was not among those selected.

This is no way means that we do not see the value of the work you proposed. We're lucky to have so many talented independent researchers, developers, and community leaders like yourself building on Stacks. Unfortunately, we receive many more proposals than we can actually fund with our limited means, so competition is extremely tough. While we generally support innovation in all forms, we tend to prioritize projects that have the potential to advance and differentiate the broader ecosystem from other blockchains, as well as projects that meet critical needs of the community *at the time*. These constraints mean that in several instances, several excellent projects may not make it into a cohort.

We very much appreciate the time and effort you've put into this process and encourage you to continue watching this repo and consider submitting a new application if and when you feel your project better aligns with the current priorities of the Grants Program.

If you should have any questions, please let us know in the comment section below.

Best,
Will
Stacks Foundation Grants Program Manager
