### ISSUE TITLE
Legal advice for community pool

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#66]
**Background**
Friedger Pool as a community pool currently runs as a test. The goal is to establish the pool as an automated pool run on smart contracts. In order to continue the pool legal advice is required to establish whether running the pool by a German based entity requires a crypto licence from the regulators. 

**Project Overview**
Discuss the legal framework of delegated stacking in Germany. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The scope is limited to establishing whether a crypto licence is required or not. Acquiring the licence is a separate project. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $10k

M1: memo about legal framework for running a pool (20h-25h)

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

* Friedger is running the Friedger Pool. 
* Linden partners, Berlin based lawyers with crypto expertise 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

There might not be an existing legal framework fits delegated stacking in Germany. I could imaging to create a new entity in a different country. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

The pool is already used by 150+ users.

**Comment by friedger** [comment]
@RaffiSapire as the next cycle is approaching this is kind of urgent.

**Comment by blocks8** [comment]
@friedger Do you have a law firm you want to work with? We retain a legal firm at the Foundation that may be able to help provide information. We may be able to ask some members of our community too, then get a clear quote on cost.

**Comment by blocks8** [comment]
Thank you for your grant application. Unfortunately, after discussion we've concluded that funding legal advice for individual companies is outside the scope of grants funding. We are happy to leverage the Foundation's network to get you connected to experts in the field and to help crowdsource the information you need to proceed. 

As we discussed, there are experts like Jesse from Hiro.so and Ken from SecretKeyLabs who may have some information that supports your search. We hope you'll be able to find a legal compliant solution. We're happy to assist with further resources, please ask in Discord. Also, if you come up with learnings during your time, it would be great to have you share them in the forum for others who are in a similar boat. Hopefully we can learn together! 

Thank you. I will close this application.
