### ISSUE TITLE
StableSwap DEX on Stacks

### ISSUE THREAD

**Issue by dylanft** [stacksgov/Stacks-Grant-Launchpad#664]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;dylan@bitflow.finance

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;dylanft#2961

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@StacksDeveloper

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;StableSwap DEX on Stacks

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;25,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;360

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks dApps & Clarity  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Smart contract developers looking to build mature DeFi solutions with secure post-conditions.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;dylanft, diegomey

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We were accepted into the Stacks Web3 Startup Lab, and together we’ve founded BitFlow Finance, a decentralized protocol built to reward native Bitcoin holders based on trading activity between price-stable tokens. We were selected to present on Demo Day for Cohort 1 (link included in the attachment)

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We are missing an essential utility that will accelerate the broader adoption of Stacks: a decentralized exchange where users can trade and/or earn yield with stable cryptocurrencies in a non-custodial manner without the need for an intermediary to facilitate the transactions. The deepest liquidity pools for price-stable token pairs should reside on Stacks, and the work in this grant will serve as a building block towards making that a reality.

New:
1) the first stableswap DEX live on Stacks
2) a 'real yield' protocol design that rewards liquidity providers with the same tokens used in the underlying pools

Benefits:
1 ) Building blocks for a mature stableswap market:
This kind of DEX offers an alternative to centralized platforms for trading between and/or earning yield on price stable assets. Having a DEX optimized for stableswaps results in lower fees, fewer slippage failures, and deeper liquidity pools. This will be a catalyst in attracting additional stablecoin liquidity (USDC, USDT, etc) to Stacks

2) More DeFi developer resources enable more DeFi products:
We'll provide fully open source code for the dApp, plus tutorial resources to experiment with building a DEX. For example: We will build a protocol based on this template to disrupt Curve and provide Bitcoiners with an advantage in DeFi. Other protocols, like Convex, can be built on top of it.

We've received encouraging feedback from community members and DeFi pioneers in the Stacks ecosystem who want this built.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;- Github favorites / forks / comments
- Trading / LP activity on testnet
- YouTube + Medium/Sigle: views/likes, outbound link conversion, subscriptions
- Twitter engagement / responses
- Signups for products built using the template (such as BitFlow)

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Using this DEX / template won't require putting any xUSD/USDA at risk. The biggest risk is related to how long the front-end portion of the template will be useful based on upgrades to different frameworks. We'll minimize the front-end complexity wherever possible, and upgrade the repo as necessary.

**[Support Link:](https://docs.google.com/document/d/1Wdzj0AXyzG8sdWBMGGEGC6vHK-rHfXS7xFvCclZLdFI/edit?usp=sharing)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Contains screenshots / links:
- Front-End Interactive Mockup
- BitFlow Mockup
- Stableswaper Hackathon Github repo + link to live dApp on testnet
- BitFlow main website
- Web 3.0 Startup Lab Demo Day Video (5 min) + Clarity Hackathon Github Repo
- Kano Survey results
- Tokenomics canvas

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Smart contracts: Bringing the stableswap AMM framework from curve.fi to Stacks

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Front-End dApp code + Tutorial on Stableswaps: how to build/use, tokenomics, etc

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;A StableSwap DEX live on testnet & mainnet, with fully open-source code and tutorials to walk through the Clarity smart contracts and front-end development.

**Comment by stacks-foundation** [comment]
👋 @dylanft
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by JacobRyan258** [comment]
Looking forward to seeing this project progress! Being a web 3 Startup Lab cohort member alongside this team, I can share that their work ethic is very strong! Fully support this grant application!

**Comment by ropl-btc** [comment]
Very excited for this project. Dylan and Diego are definitely the right ones to get this thing rolling!

**Comment by The-advisor-btc** [comment]
BitFlow is among the most interesting DeFi projects on Stacks. Not only would it create an efficient DEX for stable pools, but it would give utility to BTC holders, which is Stacks goal.

Diego has been an active member of Stacks ecosystem for a while & I'm curious to see the team building this great product.

**Comment by eliherf** [comment]
Can't wait to see this project unfold. Stable coins and native BTC is definitely the big unlock on Stacks for wider adoption. And Bitcoiner adoption. Much endorsement from me.

**Comment by BowTiedDeployer** [comment]
Interesting project! Looking forward to development of DeFi innovations like this.

**Comment by scott4044** [comment]
Exciting to see a stable swap protocol coming to Stacks -- it's a no brainer . Dylan & Diego are a perfect team to get the job done and am excited to follow the progress of this project

**Comment by orlandobtc** [comment]
Definitely support this team. I have been fortunate to work with Deigo on his CityPacks NFT project and am confident that he is a person who can execute and deliver. 

In terms of the proposal itself, a stablecoin DEX is badly needed in the ecosystem. Right now, the only decentralized stablecoin on Stacks, USDA, is not holding its peg to USD. The only other stablecoin in the ecosysem is xUSD (wrapped USDC) which carries both bridge risk (bridges are well known as a honey pot for hackers) and censorship risk (since Circle can freeze anyone's USDC). A stablecoin DEX would make it easier for USDA to maintain its peg as arbitrageurs would be able to more easily swap between USDA and xUSD. Additionally, this DEX would incentivize other stablecoins to potentially come to Stacks as they would know that their a stablecoin DEX would be waiting for them to assist in maintaining their peg.

**Comment by will-at-stacks** [comment]
Hi @dylanft 

- Have you (or would you be willing to) consult with ALEX to see if some of the tooling has already been built and is open source and ready for you to use..?  
- Have you (or would you be willing to) consult with MattyTokenomics?
- If this grant is approved on 9/39/22 are you able to complete the work and have it operational by 3/31/23?

Thanks
Will

**Comment by dylanft** [comment]
Hey @will-at-stacks 

Yes to all 3!

1) I met with Chiente and Chan back in June about creating a stable swap dex and ways it can benefit the whole Stacks ecosystem. They've definitely made some progress preparing a stablecoin pool for ALEX, and Chan was kind enough to share a link to one of their contracts on a dev branch. From what I gathered, the alexgo-io/alex-v1 repo is open source and falls under the standard MIT license without any restrictions for us to use, if needed. The protocol designs are different, and there are advantages to having a product where yield is paid out using the tokens in the underlying pools and a governance token dedicated exclusively to stable swap protocol voting + yield boosting. But they obviously have a brilliant team, and I’m sure it’d be helpful if we shared more insight/tooling going forward.

2) I met with MattyTokenomics this summer as well. During one of the Web3 Startup Lab sessions, Diego and I volunteered to present the Tokenomics Canvas for a stable swap dex similar to Curve. Filling it out was a helpful exercise for designing/engineering sustainable incentives, so we’ll definitely include a polished walkthrough of that for this dex as part of our tutorial deliverable. Happy to meet with him again to ensure we're publishing quality tokenomics content.

3) Absolutely. The research and work we did throughout the summer in the Web3 Startup Lab  has prepared us to hit the ground running for this grant. Our own timeline for these deliverables is a bit more aggressive, and I'm confident we will complete the work before 3/31/23.


Thanks,
Dylan

**Comment by Albert-Present** [comment]
I can vouch for all three as I was the one who helped facilitate those connections during the Startup Lab.  Dylan and his team are highly capable and thorough as well as plugged into our community.

**Comment by will-at-stacks** [comment]
Hi @dylanft -

Congrats!  Your grant application has been approved.  We just sent you an invite (to the email the application was submitted with) to an onboarding call on Monday.  We will use this call to provide an overview of next steps and expectations for proceeding with the grant.

If you are not able to make the call, don't worry, it will be recorded.  

Best,
Will
Stacks Foundation Grants Program Manager.

**Comment by dylanft** [comment]
That is great news, thanks Will!

And also a big thank you to everyone who took time to voice their support for this grant application.

**Comment by will-at-stacks** [comment]
Updates to this grant can also be found [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/771)
