### ISSUE TITLE
Stacks Board Observer

### ISSUE THREAD

**Issue by RagnarLifthrasir** [stacksgov/Stacks-Grant-Launchpad#665]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Ragnarly#4014

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ragnarlif

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Board Observer

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;10,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;80

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Community Builder Grant 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education & Community  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Strengthen Community

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;My audience is all Stacks users interested in the Stacks Foundation's mission.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Two completed grants for Trajan. I have a pending grant application to compile a database of investors in Stacks startups.

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Having direct (Observer) representation on the Board of directors of the Stacks Foundation will benefit the Stacks community in the following ways:

1) By collecting anonymous, open-ended feedback (via blocksurvey.io) from all Stacks users and presenting it directly to the Board of directors at quarterly meetings, Stacks users can have substantial input into the direction of the Stacks Foundation.

2) By attending the Board of directors' quarterly meetings and then giving a live stream presentation summary of the meeting, Stacks users can receive a direct follow-up of the feedback they previously provided.

3) By hearing the raw yet organized and summarized feedback from the community, the Board of directors will benefit from grassroots, bottom-up data from Stacks users of all types. This data will help the Board, and thus the Foundation, set goals and directions for the next quarter. 

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The community feedback submitted via BlockSurvey will be summarized into a slide presentation and will be published after the board meeting.  A summary of the board meeting will be presented as a live stream within two weeks of the board meeting.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;One risk is insufficient BlockSurvey feedback from the community to present to the board. I will overcome this risk by raising awareness of the survey on Twitter and Discord and asking the Foundation to help spread awareness through its channels. 

**[Support Link:](https://github.com/stacksgov/pm/issues/66)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Previous "Community Board Seat" discussion and results.

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Four milestones: For each quarter, a presentation to the Board & then community.

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Presentation to Board and then to Community for each quarter, for four quarters.

**Comment by stacks-foundation** [comment]
👋 @RagnarLifthrasir
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by RagnarLifthrasir** [comment]
I want to amend my application. Instead of attending four board meetings, attend one board meeting. So the grant amount would change to $2,500.

**Comment by joberding** [comment]
I'm interested to see what comes of this proposal. Perhaps a new voice can make a difference. You have my support.

**Comment by JacobRyan258** [comment]
I think this would add a lot of value for understanding community wishes! I support this application!

**Comment by RagnarLifthrasir** [comment]
> I'm interested to see what comes of this proposal. Perhaps a new voice can make a difference. You have my support.

Thank you.

**Comment by RagnarLifthrasir** [comment]
> I think this would add a lot of value for understanding community wishes! I support this application!

I appreciate it.

**Comment by RagnarLifthrasir** [comment]
I have [created a post on the Stacks Foundation Discussion Forum](https://forum.stacks.org/t/stacks-foundation-community-board-observer-grant-proposal/13672) about my grant application.

**Comment by Hero-Gamer** [comment]
Hi @RagnarLifthrasir thank you for starting this proposal!

As a community member, who thinks practically and takes a problem-solving approach, I like something has been proposed to clear the bottleneck re Community Board Seat conversation. 
* I've mentioned in a related Github issue thread: https://github.com/stacksgov/pm/issues/65#issuecomment-1236360947 my thought in relation to an Ecosystem Community Representatives idea I had, which I think might compliment each other.
* I have seen Ragnar come into Stacks ecosystem, watched his Podcast with Jakeblockchain today, had brief interaction with him so far. I cannot say I know him well, or already deeply rooted into Stacks yet, however I think he is bringing the right mentality to governance, taking action to move things in the positive direction.
* For @RagnarLifthrasir to get the pulse of every corner of Stacks ecosystem where communities /sub-communities reside, I'd be (and others I'm sure) happy to support him wherever he needs or sees fit. 

**To conclude**: I'd be in support of this initiative, particularly from the perspective of, let's just get something off the ground. Once we started it, we will learn and iterate on it. I see limited risk based on one board meeting. 

_(One related note, in the future once EcosystemDAO from Marvin/Mike is ready, we (Stacks community) will even be able to vote on who is the Board Observer (and amongst other things). Currently EcosystemDAO is in development to get ready to see if we can use it to vote on Stacks 2.1 Upgrade.)_

**Comment by dantrevino** [comment]
The board meets once every three months.  $2500 for a single meeting seems excessive.  Certainly @RagnarLifthrasir deserves something for his time though.  With that in mind, I'd like to see:
1. specifics on how community feedback will be solicited (How did @joberding do it in the past?  Do we even know what lessons she learned there??)
2. a commitment to report on 
    a) how community feedback was received in the meeting, 
    b) actions resulting from community feedback
    c) lessons learned, or how we can ensure we get more actions/results next time
(again, for this report, I would suggest/hope @RagnarLifthrasir meets with @joberding to get her feedback/suggestions)

I mention this because we've been through this exercise before, and while doing something is generally better than doing nothing, I think its better that we're improving how we (the community) engage, rather than repeating the same mistakes of the past.

**Comment by RagnarLifthrasir** [comment]
@dantrevino, thanks for your feedback. 

Regarding the $2,500 grant amount, I will be doing much more than attending one meeting.

As I described in the proposal: Before the board meeting, I will solicit, collect, synthesize, and create an impactful presentation. Next, I will attend the meeting, take notes on the salient actions, deliver my presentation to the board, and record their reactions. Finally, I will take everything I saw and did and craft another impactful presentation which I will share with the community. The person who performs these actions needs a set of skills and experience that are difficult to find in the right combination. These are, and I have: leadership experience with blockchain-related non-profits, experience creating and giving executive-level presentations, social media reach to maximize data collection and dissemination, and willingness to navigate contentious, high-stakes issues and personal dynamics.

I anticipate that doing all of the above will take 80 hours. My usual rate for consulting is $300/hour. If my grant is $2,500 and it takes 80 hours, that is about $31 per hour. This is a significant discount from $300/hour. 

> 1. specifics on how community feedback will be solicited (How did @joberding do it in the past? Do we even know what lessons she learned there??)

In my proposal, I specified that I would solicit feedback by creating a questionnaire with blockservey.io. I will spread awareness of the survey on the Stacks Discord, Stacks discussion board, and Twitter (I have 17K+ followers).

> a commitment to report on
> a) how community feedback was received in the meeting,
> b) actions resulting from community feedback
> c) lessons learned, or how we can ensure we get more actions/results next time

Yes, these three points are what I would do. And I will chat with @joberding. I appreciate her previous work and her support of my grant proposal.

**Comment by joberding** [comment]
@RagnarLifthrasir you can reach me on Stacks Discord. My discord name is Juliet Ӿ LexyLab#6742

**Comment by binayatripathi** [comment]
I support this effort by @RagnarLifthrasir to incorporate more voice from the Stacks community to the Stacks Foundation directly. More input from the community and more transparency in foundation's work is good and I believe this effort will help in that direction. 
Looking forward to hearing quarterly updates from Ragnar.

**Comment by Rapha-btc** [comment]
I support this initiative. Bringing Ragnar's contribution and help to the foundation. Getting more outreach to the Stacks Community and a level of transparency (not too cumbersome thou) is a net positive. Ragnar is a phenomenal builder (just look at Trajan) and an outstanding communicator. I love his no bullshit culture approach. Go Ragnar!

**Comment by will-at-stacks** [comment]
Hi @RagnarLifthrasir -

We have identified the projects we will be awarding grants as part of Stacks Foundation Grants Program Cohort 18. I'm sorry to have to inform you that your project was not among those selected.

This is no way means that we do not see the value of the work you proposed. We're lucky to have so many talented independent researchers, developers, and community leaders like yourself building on Stacks. Unfortunately, we receive many more proposals than we can actually fund with our limited means, so competition is extremely tough. While we generally support innovation in all forms, we tend to prioritize projects that have the potential to advance and differentiate the broader ecosystem from other blockchains, as well as projects that meet critical needs of the community *at the time*. These constraints mean that in several instances, several excellent projects may not make it into a cohort.

Additionally, we will be approving another grant you applied for and only allow one active grant per person.  Lastly, we will work to highlight the need to fill this position through the Governance processes as noted above.

We very much appreciate the time and effort you've put into this process and encourage you to continue watching this repo and consider submitting a new application if and when you feel your project better aligns with the current priorities of the Grants Program.

If you should have any questions, please let us know in the comment section below.

Best,
Will
Stacks Foundation Grants Program Manager
