### ISSUE TITLE
SC Automation on Stacks

### ISSUE THREAD

**Issue by ayshptk** [stacksgov/Stacks-Grant-Launchpad#666]

**Comment by stacks-foundation** [comment]
👋 @ayshptk
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by friedger** [comment]
Can you integrate with arkadiko keeper? https://docs.arkadiko.finance/keepers/introduction

**Comment by will-at-stacks** [comment]
Hi @ayshptk this application appears to not have any contents.  I am going to close this issue.  Please submit again if this was a mistake.  Thanks, Will
