### ISSUE TITLE
ToDeFi: Torino Decentralized Finance Conference	

### ISSUE THREAD

**Issue by LorenzoSchoenleber** [stacksgov/Stacks-Grant-Launchpad#668]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;lorenzo.schoenleber@carloalberto.org

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;ToDeFi: Torino Decentralized Finance Conference	

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;7,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;100

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education Grant 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education & Community  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Strengthen Community

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Institutional)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Finance - Academic Researchers (Professors), Students, and PhDs

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Prof. Lorenzo Schoenleber, Prof. Roberto Marfè

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Proposal Summary

We would like to organize a new international conference purely dedicated to topics within decentralized finance partially sponsored by Stacks. We strongly believe that frontier research involving DeFi platforms will become more and more important. However, currently the academic community is not offering sufficient events for the exchange and discussion of ideas related to the DeFi subject.

Therefore, we are planning a one-day conference in early 2023 hosted by the Collegio Carlo Alberto and the University of Turin, which aims to promote the highest level and up-to-date research in DeFi within the academic community. Speakers and discussants are selected among the world’s most innovative junior researchers and established scholars. One presentation slot is devoted to the PhD candidate for the best paper in DeFi. The winner of this slot will receive a discussion during the conference and will be awarded a prize.

We are planning to include 6-7 paper sessions (30min presentations + 15min discussions + 5min Q&A) into the conference program covering for example topics such as DEX (AMM), Yield Farming (Staking, Lending, Liquidity Provision), Tokenization, NTFs, and Cryptocurrencies. Our goal is to provide a setting that produces the kind of in-depth participation of a small conference but including a large audience. Currently, we are planning for an in-person conference (with an online option for additional non-presenting and non-discussing audiences). We also plan to invite students from our Master’s in Finance Program (from the Collegio Carlo Alberto and the University of Turin) to participate in the event. To maximize the visibility and outreach for your foundation and ecosystem, we would appreciate having a guest presentation from one of your members on a DeFi-related topic during the conference.

The Collegio Carlo Alberto is a well-experienced institution in the organization of academic events. We successfully host the yearly LTI conferences, which cover topics related to the long-term finance. For fall 2022, we will host the 5th Asset Pricing Conference. Long-Term Investors (LTI) is a think tank established as a joint initiative of some of the major Italian market players in long-term financing and the University of Turin, which is hosted by the Collegio Carlo Alberto.

The grant would allow us to host and organize the described one-day conference in early 2023. The Collegio Carlo Alberto and the University of Turin will host the conference.  

To our knowledge, there are almost no academic research conferences covering solely DeFi topics in Europe (at most, major conferences offer a single session covering cryptocurrencies). Our proposed conference created and offered by established academic researchers, would facilitate the research activity within the DeFi subject and allow the interaction of several researchers worldwide. 

Beyond the conference organization, we are potentially open to discuss about a deeper cooperation with your company. In particular, the Collegio Carlo Alberto hosts a postgraduate Master’s in finance, insurance, and risk management (Mafirm), which is a small high-quality program that exists for more than 20 years. The program appears in several international rankings (e.g., 1st in Italy, 6th in Europe, and 25th worldwide in the quantitative finance masters' ranking by Risk.net) and has established regular partnerships with a few local players in the financial industry (partnerships concern, e.g., visibility and promotion, career day and placement, events organization, and student scholarships). The students attending our master lectures are excellent but more importantly, really motivated.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Benefits for your Foundation and Ecosystem

You would sponsor a high-level academic research conference on the DeFi subject and hence gain visibility among the academic community, students, and participants. We will promote the event online on various channels. The promotion of your logo on all the communication tools related to the conference (including the website, the playbills and posters, the social channels, and any other ad-hoc material) is self-evident. We could for example award the best paper award for the PhD candidate on behalf of Stacks or name a conference session after Stacks.

To maximize the visibility and outreach for your foundation and ecosystem, we also plan to invite students from our Master’s in Finance Program (from the Collegio Carlo Alberto and the University of Turin) to participate the event. We would appreciate having a guest presentation from one of your members on a DeFi related topic during the conference.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Funding Request

We estimate to have total costs for the conference of about 7.000-9.500€ covering travel, accommodation, catering, and social dinner for approximately 15 invited international speakers and discussants. Any amount of sponsorship or donation would be beneficial for us since we are trying to request funding from different funding sources.

Budget Breakdown
•	Travel: 3.000€ - 4.000€
•	Hotel: 2.000€ - 3.000€
•	Catering & Social Dinner: 1.500€-2.000€
•	Promotion: 500€
•	PhD Price: typically, around 500€ but the price can anything (for example tokens, delegation rights for your DAO or company, or any other ``non-cash prize”)

**[Support Link:](https://www.dropbox.com/s/j4krp6db8zdkv7f/Schoenleber-Stacks_ToDeFi_Torino_Decentralized_Finance_Conference_08_2022.pdf?dl=0)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT ROADMAP & DELIVERABLES

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Early 2023

**Comment by stacks-foundation** [comment]
👋 @LorenzoSchoenleber
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
