### ISSUE TITLE
Prediction Market

### ISSUE THREAD

**Issue by pseudozach** [stacksgov/Stacks-Grant-Launchpad#67]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

* Prediction markets are fundamental applications for a blockchain. They provide users the ability to speculate on future outcome of events, both trivial and crucial. They also enable diffusion of knowledge in society, there are many use cases as listed in [Prediction Market Uses by truthcoin](https://bitcoinhivemind.com/papers/3_PM_Applications.pdf) 

**Project Overview**
What solution are you providing? Who will it serve?

* We plan to build a prediction market implementation in clarity that provides a way for anyone to easily create a market, take side and resolve.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Deliverables:
1. Clarity smart contract that has public methods for 
  * creating a market - description of the market, outcomes and resolution details.
  * taking sides - one of multiple potential outcomes
  * resolving a market - set the outcome (manually or via external trigger) Winners will be calculated by the contract and stx payments will be dispersed to winners as set in rules of the market.

Note that initial approach will be for creator of a market to resolve it manually by setting the outcome. External oracles will also be researched as part of this application. All community feedback and guidance is welcome for both or alternative approaches.

2. Web App that provides a straight forward way to interact with the clarity smart contract to expose possible functions and enable anyone to easily use the capabilities.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Overall Timeline: 100 hours over 4 weeks
M1: 50 hours, implementing/optimizing the clarity contract
M2: 25 hours, testing, integrating external triggers/oracles
M3: 25 hours, deployment, feedback and iteration for Web App & GUI

M1
Estimate: 2 Weeks
Reward: $2500
Time: 50 hours
SoW: Write the clarity contract, deploy to testnet, deploy sample markets, request community feedback and see how it's used. Expand/optimize as per feedback.

M2
Estimate: 1 Week
Reward: $1250
Time: 25 hours
SoW: Integrate external triggers like API calls and/or oracle solutions to enable market creators to plug-in existing capabilities for resolving markets. Test, gather feedback, re-deploy as needed.

M3
Estimate: 1 Week
Reward: $1250
Time: 25 hours
SoW: Develop & Deploy Web App to interact with the contract, deploy to mainnet, release.

Total Grant Request: $5000

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

* pseudozach: Building on stacks since Mid-2019, deployed multiple apps for app mining e.g. [Can't be Evil Hackathon 2nd place](https://devpost.com/software/yaver), recent Clarity Hackathon 2nd place.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

* Manually resolved markets are expected to be completed but resolving markets via external triggers/oracles need to be researched. If proves too complex to implement from scratch, existing oracle providers will be utilized.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

* A scaffold already exists as part of recent Clarity hackathon on which we'll continue building. Plan is to be active in Stacks discord sharing updates/milestones and requesting feedback plus guidance from the community.
* There is interest and support for this type of open ended application. We believe this will also encourage other implementations and similar applications which will provide long term benefits to the Stacks community.

**Comment by RaffiSapire** [comment]
Hi there, we discussed Tuesday as a grant committee. Here's some feedback we had to share: 
We'd encourage you to flesh out and conceptualize the oracle piece as M1. Here, share insights on oracle research, work required on oracle side of this.
As M2, we'd be curious to see real use cases for stacks community. We'd love to see some shared examples of where you’ve seen a need for this (discussions, etc.).
Let us know what you think, feel free to reach out and ask us questions on the stacks-grants channel on discord. Based on this and if it's something you're still excited about, let us know what you think the appropriate grant amount is for the above.

**Comment by pseudozach** [comment]
> Hi there, we discussed Tuesday as a grant committee. Here's some feedback we had to share:
> We'd encourage you to flesh out and conceptualize the oracle piece as M1. Here, share insights on oracle research, work required on oracle side of this.
> As M2, we'd be curious to see real use cases for stacks community. We'd love to see some shared examples of where you’ve seen a need for this (discussions, etc.).
> Let us know what you think, feel free to reach out and ask us questions on the stacks-grants channel on discord. Based on this and if it's something you're still excited about, let us know what you think the appropriate grant amount is for the above.

Thanks for the feedback. I'll start with answering the demand side of it, probably my mistake I didn't provide solid figures because I thought it would be obvious. Here are some stats regarding TVL in [Augur](https://defipulse.com/augur) and another similar app to show number of open predictions [polymarket](https://polymarket.com/). I've also started a poll on discord, will update this post with results. This should give some idea on demand side of things.

Upon further research, I did notice there's still some plumbing missing to build out this type of platform on Stacks so I agree there's need to dig deeper and build out some tooling,

Please see below my updated proposal:
M1
Estimate: 2 Weeks
Reward: $2500
Time: 50 hours
SoW: Research current state of oracles and in context of Stacks. Unearth any prior work (I'm unable to find anything else other than tweets and announcements so far), build on that work/or from scratch to release sample oracle powered clarity contracts for community usage.

M2
Estimate: 2 Week
Reward: $2500
Time: 50 hours
SoW: Using M1 output, build a prediction market platform that users can create any market, set rules and attach external oracle data to resolve these markets. Platform would include clarity contract and simple Web UI to accomplish goals set in this proposal.

Total Grant Request: $5000

Let me know any further feedback,

**Comment by RaffiSapire** [comment]
Thank you! We'll talk about this tomorrow. In the meantime, I wanted to ask, do you have any initial thoughts on where you’ve seen a need for this (discussions, etc.) specifically for the stacks community?

**Comment by pseudozach** [comment]
Hi Raffi,

Please see below for a poll ran on stacks discord, answer is almost all positive except for one person. There are also comments from multiple community members that they would like to see this happen and they would use it. 

![Screenshot_20210322-145803](https://user-images.githubusercontent.com/3731591/112063711-12c3c900-8b1f-11eb-8c8f-bcfb91a85e3e.png)

**Comment by RaffiSapire** [comment]
Hi there, we're keen to approve this grant. We wanted to share a couple things here. 
Flush out M1 oracle research. What questions do you want to answer? For instance: what tech capabilities are we lacking, whats the gap? what do we need to work on? Would be great to get a bit more of a research plan in place for M1 here. Generally are supportive and excited to approve. Please email me at raffi@stacks.org and we'll get you set up.

**Comment by pseudozach** [comment]
> Hi there, we're keen to approve this grant. We wanted to share a couple things here.
> Flush out M1 oracle research. What questions do you want to answer? For instance: what tech capabilities are we lacking, whats the gap? what do we need to work on? Would be great to get a bit more of a research plan in place for M1 here. Generally are supportive and excited to approve. Please email me at [raffi@stacks.org](mailto:raffi@stacks.org) and we'll get you set up.

Hi,
I updated the above proposal with itemized research details and sent you an email. Thanks!

**Comment by friedger** [comment]
@pseudozach There was #37, a proposal for prediction market game. Maybe @GeeVeldek is interested ..

**Comment by pseudozach** [comment]
@friedger it seems their application was to add stx price pair to their existing site. Not really related to the direction of this grant but of course I'm always open to collaboration.

**Comment by pseudozach** [comment]
Hi,
Please find first draft of the oracle report (as part of M1) at this link: [State of Oracles in Stacks Report](https://docs.google.com/document/d/1vyGwN3-hlNDTHtRFlqFoGkLHX_t6GxagzbI0DHx_UmI/edit?usp=sharing)
All feedback is welcome.

**Comment by jennymith** [comment]
> Hi,
> Please find first draft of the oracle report (as part of M1) at this link: [State of Oracles in Stacks Report](https://docs.google.com/document/d/1vyGwN3-hlNDTHtRFlqFoGkLHX_t6GxagzbI0DHx_UmI/edit?usp=sharing)
> All feedback is welcome.

This is really helpful, thanks Zafer! Reaching out to you directly about where this can be helpful.

**Comment by pseudozach** [comment]
Hi,
Please find the link to [stxoracle library](https://github.com/pseudozach/stxoracle) that allows anyone to deploy and update a price feed oracle on Stacks.
This deliverable concludes the M1 of the proposal. There are now [two sample price feed oracle contracts](https://github.com/pseudozach/stxoracle/wiki/stxoracle-list) running on Stacks testnet. 
The library can also be used as a template and modified to import any outside-world data (weather condition, random number or any externally available data) into Stacks.

**Comment by pseudozach** [comment]
Hi,
I'm happy to share that stxpredict - a clarity smart contract and a web UI exposing the functionality is released as M2 of this grant.
Please find the source code here: https://github.com/pseudozach/stxpredict
stxpredict web app is here: https://stxpredict.vercel.app
contract is deployed on testnet: https://explorer.stacks.co/txid/ST15RGYVK9ACFQWMFFA2TVASDVZH38B4VAV4WF6BJ.stxpredict_v1?chain=testnet

As per grant's M2 targets, v1 of predictionmarket clarity contract has the capability to create a new market with a definition, minimum entry price and an oracle (i.e. based on stxoracle from M1 of this grant) as resolver. It keeps track of market participants and upon resolving, it can distribute funds to winners.
Any feedback is welcome,

**Comment by pseudozach** [comment]
v2 for the contract is deployed on testnet with minor fixes: https://explorer.stacks.co/txid/ST15RGYVK9ACFQWMFFA2TVASDVZH38B4VAV4WF6BJ.stxpredict_v2?chain=testnet
[web app](https://stxpredict.vercel.app) is also improved, aligned with v2 and announced to the community on discord. Looking forward to feedback and guidance from the community on deciding next steps for this project.
These deliverables conclude the M2 of the proposal.

**Comment by RaffiSapire** [comment]
Hi @pseudozach the committee reviewed your work and don't feel you've completed the milestone yet. 

Marvin: M2 deliverable according to OP: “Integrate external triggers like API calls and/or oracle solutions to enable market creators to plug-in existing capabilities for resolving market.” His predictionmarket_v2.clar is pretty much the same as v1, there is literally only one change. Whilst it is true that you can set an external resolver for a market, I do not directly see “external trigger”/oracle integration. He sets the resolver to Pascal’s address, not the actual USD oracle contract. It means that Pascal can resolve the market, not the contract. Furthermore, Pascal’s oracle is not aware of the prediction market and has no mechanism to resolve any markets, if even it were assigned properly. The resolver has to call function resolveMarket on predictionmarket_v2, which the oracle is incapable of doing. He needs a “glue resolver contract” to make that happen. I am therefore not convinced he delivered on M2. (Might be a lack of technical understanding, which I can help with.)

Jude: He needs to show us the code (and running instance) of the oracle process that calls `resolveMarket` before we give him funding.  He has a price oracle, but that’s not the same as a market resolver.  His sample app has a betting market open for who’s going to win a sports game; where’s the oracle for that?

Marvin is happy to talk with you and help you get it to the finish line.

**Comment by pseudozach** [comment]
Thanks for the great feedback and especially Marvin for guidance.

[stxpredict contract v4](https://explorer.stacks.co/txid/ST15RGYVK9ACFQWMFFA2TVASDVZH38B4VAV4WF6BJ.stxpredict_v4?chain=testnet) is deployed on testnet, [web app](https://stxpredict.vercel.app/) is updated as well:
* This update enables markets that can be resolved automatically by oracles.
* When user creates a market and sets it to be auto-resolved by an oracle, they also set a threshold value for the prediction. (For price feed this can be $ value, for other types of markets it can be temperature, goal count in a game etc.)
* After resolve time has passed anyone can trigger a call to oracle contract to "request resolution" of the market.

I've also pushed an update to the [stxoracle library](https://github.com/pseudozach/stxoracle) and [contract](https://github.com/pseudozach/stxoracle/blob/main/contracts/oracle_v4.clar) to provide the required functionality
* Oracles expose a requestResolution public function which can be called by anyone
* When triggered oracle will try to fetch a predefined threshold from the prediction market and decide how it should resolve a market
* Oracle contract will call resolveMarket on the prediction market.

As stated in the contract intro there are limitations to this implementation but choices were made to provide a working system inline with goals of the grant. 

Let me know any further feedback please, thanks!

**Comment by pseudozach** [comment]
!m1_complete

**Comment by pseudozach** [comment]
After further discussion with Marvin, I've now deployed an additional feature that allows users to create and deploy their own glue resolver contracts!
These contracts allow users to fetch data from pre-existing oracles (like [psq's signed exchange oracles](https://github.com/psq/stacks-open-oracle)) by using these glue contracts user does not have to trust stxpredict or stxoracle but they can use signed exchange data as their data source.
Web app is updated with the additional option and all code is pushed to github.

Let me know if there's any remaining action items to close out M2. 
Thanks!

**Comment by RaffiSapire** [comment]
This is great! We reviewed and are excited to see this get to the finish line. Thanks for your time here. I’ll disburse for the next milestone.

**Comment by pseudozach** [comment]
!m3_complete

**Comment by RaffiSapire** [comment]
Hi @pseudozach could you please share the latest on M3? Thank you!

**Comment by pseudozach** [comment]
Hi, 
Almost finished with testing and other small tweaks. Expecting to deploy to mainnet soon. Will update here.

**Comment by jennymith** [comment]
Hey @pseudozach would you say this grant is essentially done or is there more review needed here?

**Comment by pseudozach** [comment]
Hi @jennymith, this grant is completed. Everything is on mainnet and code is on github.

**Comment by jennymith** [comment]
@RaffiSapire This grant has been completed. Can we please update in Airtable, the apps, etc.?
