### ISSUE TITLE
The Stacks Chronicle

### ISSUE THREAD

**Issue by fungiblesystems** [stacksgov/Stacks-Grant-Launchpad#673]
<img width="1000" alt="chron3" src="https://user-images.githubusercontent.com/94925084/189375536-c9995219-a2aa-47ae-bff5-82c3d092ffe2.png">

> **Note**
> This is something we've been dreaming of building since we started the studio. We are very confident that if we can build this as we imagine it, it will have a huge impact on stacks, and will be a product that doesn't exist on any other chain. Thanks for considering us :)

# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;thomas@fungible.systems

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;aulneau#8426

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;aulneau_

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;aulneau

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The Stacks Chronicle

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;320,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;6 months

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Interface  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Both users and developers, and other infra like wallets

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;aulneau, fungiblejasper, jjenzz

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;503, residencies, etc.

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The Stacks Chronicle is a much more powerful kind of explorer. Explorers let you view the raw data of individual transactions, but you are left to your own devices if you want to see patterns or trends. Chronicle parses this data into meaningful insights and trends that show you what’s happening on Stacks. It’s designed for regular people, and will make data human-readable, use deep linking between different types of data, and of course, look great.

<img width="1372" alt="chronicle" src="https://user-images.githubusercontent.com/94925084/189371446-c9147591-d178-492c-b148-e3e521f362f0.png">

First, we’ll explain what users can do on Chronicle. Then we’ll explain the tools we’ll build to enable this, and how other developers, too, can use these tools to improve user experience across the board.

Chonicle is your home on Stacks. On Chronicle, you can:

**Discover apps**

- You can see the most popular apps, or apps trending during a certain timeframe. You can filter by category and metrics such as number of users. List of apps will no longer need to be curated, Chronicle will always have the most up-to-date list of Stacks apps.
- How? Chronicle relates every transaction to a particular app using a registry. App developers can add their app to the registry and create a profile with a name, logo, description, and more, much like they would on the App- or Play Store.

**Discover people**

- Chronicle is your “meta” profile on Stacks. While some apps already provide profiles, they are centered around their specific usecase. We believe the best place for a profile will be on Chronicle. Curious which user made the most transactions? Or who spent the most on Gamma? There will be a list of all users on Stacks that you can sort, filter and group. Each profile will come with personalizable metadata (e.g. profile image, bns name, website) and relevant statistics. These profiles will live beyond Chronicle, apps can make use of them, too.

**See the state of their transactions**

- Instead of searching for your address and looking for your transaction, you can sign in to Chronicle and see your latest transactions and their status right on the homepage.

**See the state of the network**

- Are certain parts of Stacks down? You could figure this out by inspecting your nodes or constructing patterns from individual transactions and blocks. Chronicle will make this easier by using heuristics from our API to display a site-wide banner that informs people about the state of the network if necessary.

<img width="1497" alt="chonicle-2" src="https://user-images.githubusercontent.com/94925084/189371467-f7b665e7-1c2c-449b-90e6-058516f1322f.png">

**Tools**

**Registry**

The registry is what enables app discoverability and relating individual transactions to apps. Here’s an example of how other developers can use this registry to improve Stacks’ user experience:

- Wallets can improve user experience by using the registry. Instead of seeing the function and contract you’re calling, you’ll also see which app you’re using — a great bit of feedback to confirm you’re indeed doing what you’re trying to do.
- Wallets can improve security by using the registry. Because we publicize usage numbers of apps and contracts, wallets can show you which app you’re using and how many others have used this app. This improves security in two ways: 1) If you see a different app name, you’ll know something is wrong. 2) If you think you’re using a popular app, but for instance you were sent to a spoofed URL & contract, you’ll see dramatically lower usage numbers which will be alarming. Wallets could even go a step further and proactively warn users if they’re attempting to use a low-usage app with a similar name to another more popular app.

**New, more bespoke APIs and tooling**

To build a more advanced and human readable experience for the data that exists on Stacks, we'll need to build out a new API that powers everything. Working with teams like Gamma, Zest, and others on their data indexing needs, we have built up a lot of do's and do-not's when it comes to building indexing solutions on Stacks. With this, we have a long term goal of opening up a much more powerful graph-based API that would enable highly customizable querying of on-chain data. 

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Some highly quantifiable metrics:
- apps start to adopt the registry and want to be in it --> number of apps
- hiro and xverse wallets want to integrate the api in their wallet
- usage and traffic to the web app/apis
- number of users that connect their wallet -> percentage of all stacks users

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;There are existing explorers and users might not find this new kind of explorer appealing (we think they will). New APIs need to be built and tested, there could be some risk there. Any existential risk to stacks would affect the success of this project, too.

**[Support Link:]()**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;I tried to enter in https://fungible.systems but it was incorrectly invalidated as an incorrect URL.

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Wireframes and Designs

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;MVP of universal app registry

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;MVP of initial web app

**MILESTONE 4:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Public availability of registry api

**MILESTONE 5:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Flesh out features in web app

**MILESTONE 6:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Personalized homepage

**MILESTONE 7:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integration with ecosystem partners (wallets, etc)

**MILESTONE 8:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Project complete

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;A new kind of explorer built on stacks

**Comment by stacks-foundation** [comment]
👋 @fungiblesystems
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by aulneau** [comment]
Greetings! Just wanted to pop in to say that I used our company github profile because I didn't feel comfortable connecting this account to the app due to the permissions requirements it had, normally I'd use my primary github account :)

**Comment by will-at-stacks** [comment]
> Greetings! Just wanted to pop in to say that I used our company github profile because I didn't feel comfortable connecting this account to the app due to the permissions requirements it had, normally I'd use my primary github account :)

flagging this for @criadoperez and @wileyj so we can adjust permissions to the grants.stacks.org Github login to be less intrusive.

**Comment by will-at-stacks** [comment]
Hi @aulneau  - 

Thank you for your application.  As the Grants Review Committee begins their reviews this week and next, we wanted to reach out and see if there is potential to rescope the size of your grant request. Given the projected outcomes of your project compared to cost and the competitive applications in this review batch, this grant is not likely to get approved at it's current size and deliverables.  As of now, we have funding for 40-50% of the applications received.  If you would still like to be considered in this round, we recommend rescoping your proposal to a lower amount that closer reflects the industry standard of $75/hr.

Lastly, when we kicked off the review cycle with the Review Committee we brought them up to speed on the top three objectives we are prioritizing for this cohort:

1. Support grants that improve Stacks-Bitcoin integration.
2. Support grants that improve the Clarity developer experience and attract new Clarity developers to Stacks.
3. Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

If you could, please comment here if you feel your project is consistent with one or more of these objectives and let us know how and why.

Thanks!
Will

**Comment by aulneau** [comment]
Hi @will-at-stacks! 

Sure -- that makes sense. I'd love to give more context on the cost and structure of this grant. Ideally, we'd like to have 6 months of funding from this grant to dedicate time on this product to bring it to the place where we think it would have the most impact. We strongly believe this product will have an outsized impact on the experience of using the Stacks network, and provide a place for newcomers to come and see what makes Stacks great. If done correctly, this product will be unique not just in Stacks, but in the larger crypto ecosystem.

> a lower amount that closer reflects the industry standard of $75/hr.

As someone who has been actively hiring roles in web3/crypto for our studio, this is very much not been our experience around costs in the industry (even in a bear market). One designer and two-to-three engineers will be working on this and shipping new features often, and based on the time spent and total cost of this grant, we are already below industry standard when it comes to the cost of building a product of this nature. 

We're open to splitting up the grant if that makes more sense. I'm curious if it would be possible to break this grant up into multiple grants, potentially something like this:

- The main application, _The Stacks Chronicle_
- An API and UI for managing applications in the apps registry

If this is possible, would it still work to have it in this cohort? I'd love to understand better how the cohorts connect with time spent on a given grant, is it the case that grants need to be similar duration to the grants definitions of cohorts?

I think that would allow for us to still accomplish all that we hope to with this product, while working within the guidelines and requirements of the grants program. 

---

To answer your other questions:

> Support grants that improve Stacks-Bitcoin integration.

While this grant does not aim to build any bitcoin<>stacks specific tooling, we do want to build in references and connections to bitcoin from stacks where-ever possible. This means app integrations with protocols such as [Magic](https://www.magic.fun/), or [LN swap](https://www.lnswap.org/). Additionally, we'd be including PoX related information (think stacking.club), mining information, and Bitcoin anchor block related information in new and novel ways.

> Support grants that improve the Clarity developer experience and attract new Clarity developers to Stacks.

Outside of the apps-specific work we've described above, we have many plans to build out much deeper developer related functionality in the app. Some examples of this are: a new sandbox that allows for folks to call contracts, deploy contracts, request faucet funds, etc. This functionality is in the current Hiro Explorer sandbox, but the features have barely been updated since they were implemented. 

Outside of having a section of the application for this sandbox, we plan to build in the ability to call and read contract functions directly in various views of the application, so imagine you're looking at a listing transaction from Gamma, you'd be able to call read only functions associated with the contract, or potentially construct the contract calls to buy that item, right in the page. 

One other area of developer related features I want to explore is having a panel or section on each transaction page that integrates directly with one of our other open source projects, `micro-stacks`. You can imagine a developer coming to a contract call transaction, clicking on a section of the page that would then give them the exact code snippets they would need to re-create this call in their app. 

> Support grants that improve the attractiveness of Stacks as a place to build for founders and attract founders to Stacks.

I would say this grant is set up perfectly to accomplish this goal more than the other two. We have been in the Stacks ecosystem for a long time, and this product is something we've wanted to dedicate real effort and time towards to create something truly unique. We think the characteristics and features of Stacks are really great, but they don't have a place where they all shine brightest. We want the Chronicle to be that place, to show the wonderful apps being built, the cool NFTs that exist, the novel interactions with Bitcoin that are becoming more possible each day. 

To summarize, I'd say we have a pretty good track record of delivering high quality work in the ecosystem: our work at [Hiro](https://hiro.so) on the wallets, our work on the open source library [micro-stacks](https://micro-stacks.dev), the redesign and rebuilding of [Gamma](https://gamma.io) (previously STXNFT), and our other projects like [stacking.club](https://stacking.club).

We have been thinking about building this product for a long time, and hope that through the foundation and the grants program we'll be in a position to go above and beyond the details of this grant :)

Thanks! Happy to answer any other questions around this, and always happy to get on a call if that's easier.

**Comment by janniks** [comment]
Great grant project proposal! 💡 
Just here to voice my support — we can definitely use this type of user-centric approach in the Stacks ecosystem.

**Comment by nickgamma** [comment]
I absolutely love this product idea and think it could be a game-changer for new user onboarding—something lacking not only in Stacks but in all of web3. The next billion users will not survive on web3 today, not on any chain. While the shortcut is moving to blockchains that are less decentralized and rely on trusted third parties (undermining the very principles upon which decentralized applications are built), Fungible Systems has a track record of building apps that anyone can use, without compromising on the principles of decentralization, sovereignty, and immutability. In this way, I feel this app absolutely draws closer the Stacks and Bitcoin relationship: one of simplicity through strong foundations and first principles.

We take for granted the concept of a "home" to go to to know what is happening, where to go, what to do, and who to trust. In web2, this is your Google, your Facebook, Twitter, and Reddit, which then funnel you to thousands of other websites and applications, tracking you and injecting intrusive ads along the way. Web3 builders have committed to ditching this model, but we're not quite there yet with a proper replacement for UX. But there's a major difference (and benefit) in web3—your blockchain data, open source projects and APIs, and more, allow for a truly decentralized and open network of information that makes exposing "what's happening" and who to trust a matter of data visualization and delightful UI/UX.

At Gamma, we worked closely with Thomas, Jasper, and Jenna, and could not be more confident in their ability to execute and deliver products that people _love to use_ and _actually understand_. There is a major difference between a product, and a product that _just works_—these folks know how to make stuff work.

+1

**Comment by will-at-stacks** [comment]
```
As someone who has been actively hiring roles in web3/crypto for our studio, this is very much not been our experience around costs in the industry (even in a bear market). One designer and two-to-three engineers will be working on this and shipping new features often, and based on the time spent and total cost of this grant, we are already below industry standard when it comes to the cost of building a product of this nature.

We're open to splitting up the grant if that makes more sense. I'm curious if it would be possible to break this grant up into multiple grants, potentially something like this:

- The main application, The Stacks Chronicle
- An API and UI for managing applications in the apps registry

If this is possible, would it still work to have it in this cohort? I'd love to understand better how the cohorts connect with time spent on a given grant, is it the case that grants need to be similar duration to the grants definitions of cohorts?

I think that would allow for us to still accomplish all that we hope to with this product, while working within the guidelines and requirements of the grants program.
```

Hi @aulneau  - 

Thanks for the response.  Ideally, we would work with you to award the main application this cohort and the API next cohort. 
 If you were to break out the application into two sub-applications as you suggested:
What would that look like from a dollars POV for each sub-application?
If you were awarded a grant for the main application on 9/30 and the API on 11/25 would that have an adverse impact on your teams ability to deliver the work?

We 100% want to compensate the grant recipients with fair wages, but we do have set budgetary ranges we are working with for each cohort.  Admittedly, $75/hr is probably different than you experience when trying to hire full time talent, but keep in mind this is grant funding from a non-profit.  If you have the ability to defer costs for audits, etc - until a later date - please consider that.  We find its better to get firm quotes for that type of work once the project is further along - and we would be happy to work with you on those costs via supplemental funding.  

Please reach out with any additional thoughts or comments.  Happy to chat on a call too if that is easier.

Thanks
Will

**Comment by aulneau** [comment]
> What would that look like from a dollars POV for each sub-application?

I think this makes sense:
- Primary application: $250,000
- Apps registry public API & UI for managing apps: $70,000

> If you were awarded a grant for the main application on 9/30 and the API on 11/25 would that have an adverse impact on your teams ability to deliver the work?

The only tough part is that much of the work is tightly coupled -- eg the main application will rely on some kind of API layer for the data around apps, etc. I think it will be possible to structure some of the work such that it would conform to the requirements of the grants. 

One thing to note, we plan on spreading this work out over 6+ months, so if it's easier for it to be broken up between quarters or grant cohorts, I think that makes sense. My only concern is how best to structure it such that we can still deliver what we need to without being bound to waiting to do certain work with the hopes of future grants being applied to them.

> but keep in mind this is grant funding from a non-profit. 

Noted, and thank you :)

**Comment by hstove** [comment]
This is a really exciting proposal!

I am a huge fan of the "registry" idea. This would utilize one of the things that makes Stacks so unique - human-readable contract APIs for 100% of interactions. Ethereum is still grappling with the difficulties of compiled contracts, and there are huge efforts right now to try and figure out a way to provide more context and security when making contract calls. Stacks has a big opportunity to leap to the forefront on this area. At the moment, interacting with a smart contract is daunting. Stacks is already so much better by using post conditions and showing all relevant function information, but it's still hard to grasp what is actually happening. Thomas and I have discussed ways to improve this many times, and I have high confidence that Fungible's 'registry' approach will make a huge difference.

With Fungible's work history in Stacks, it's obvious that they are extremely well suited for building out this product. Gamma, for example, is so feature-rich and pleasant to use, and a lot of that is a result of Fungible's great design and engineering. The Fungible team is unique in having experience building Stacks apps, Stacks wallets, and Stacks infra, which puts them in a position to execute this at a high level.

Best of luck to this grant and I am very hopeful for what it can bring.

**Comment by lgalabru** [comment]
I love it, thank you for pushing the envelope @aulneau!

**Comment by obsidianbtc** [comment]
Makes sense to combine this UI with the existing indexer grant api https://grantsdashboard.stacks.org/dashboard/grants/483

**Comment by friedger** [comment]
I like the proposal to take a different approach to blockchain explorers.

I am concerned about the linking between apps (DNS domains) and protocols (smart contracts): 

> discover ... most popular apps, or apps trending
Does this help to build a more user-owned internet? 
We have already a huge dominance of the link between mail.google.com and SMTP protocol.
Do you have any plans to support innovation, independent developers alternative access to the protocols? For example apps focussing on a11y might not get discovered that easily.

**Comment by Scarlett-Web3** [comment]
I think you have an interesting project. If you haven't already gone through the Stacks Web3 Startup Lab, I would like to invite you to apply.  

Here's a 5-minute read on how we can help you turn your startup idea into an investment-ready startup:
www.web3startuplab.io

If you are interested, you can apply through the "Apply Now" button.

Feel free to ping me on email:  scarlett@stacks.ac

**Comment by fungiblesystems** [comment]
Hi all -- we are going to put a pause on this application in place of our new application for improvements to stacking.club, seen here: https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/741

**Comment by will-at-stacks** [comment]
@aulneau @fungiblesystems sounds good.  I am going to close the issue for management purposes.  Feel free to re-open if/when you want to come back to this idea.
