### ISSUE TITLE
Options Yield Vaults

### ISSUE THREAD

**Issue by gandalf77** [stacksgov/Stacks-Grant-Launchpad#676]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;optionsyield@proton.me

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;Options Yield Vaults

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;25,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;480

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;Bitcoin Utility via Stacks  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;End Users (Consumer), End Users (Institutions)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;1) Users looking to generate yield 2) Users looking for long exposure via call option contracts

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;&thinsp;&thinsp;&thinsp;gandalf77, anch09

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

We want to build smart contracts that execute a covered calls options strategy to harvest yield. A detailed description of the final deliverable can be found [here](https://docs.google.com/document/d/1g24TAIE5zIouSZJbY8_gBnp14-vahKxJ5kqKp8ZiHwo).
 
Derivatives arbitrage strategies are a time-tested way to generate yield. Using options and futures contracts, these strategies can generate steady income streams in specific market conditions without liquidation risk.
 
For example, a covered call strategy holds an underlying asset and sells short dated, out-of-the-money call options against it. This allows the strategy to collect a stream of payments in bearish and mildly bullish market environments, only becoming unprofitable during times of fast and steep market appreciation. During the right market conditions, this strategy can generate a yield of 15%+ APY in a sustainable way while not depending on inflationary protocol token incentive payments (subsidies) like many AMM yield farming strategies do.

A certain level of financial acumen is required to execute these strategies successfully and therefore, in the traditional financial system, they have mainly been employed by financial institutions and sophisticated high net worth individuals.

We believe that by automating the execution using Clarity smart contracts we can make these strategies available to a much wider audience. In our opinion, this is a crucial step towards a truly open and democratized financial system. A financial system that makes sophisticated arbitrage strategies accessible to anybody with a Stacks account and without the need to give up custody over your assets.
 
Stacks is in a unique position to become the smart contracting layer for Bitcoin and by extension the home of Bitcoin DeFi. In making sustainable yield strategies available on Stacks we believe that we can help unlock the ecosystem's potential and contribute to accelerated user adoption.
 

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

A total value locked (TVL) of 100,000 STX within 3 months of the application going live. 

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

- Since the contract will hold user funds, the overall security of the vault contract is a significant risk factor.
- Integrating a price oracle (i.e. Redstone) might carry risk.

We plan to mitigate these risks by (1) using rigorous testing in our development process and (2) engaging a smart contract auditor to review our work.

**Support Links:**

- Pitch video: https://drive.google.com/file/d/1fqeKunVXPi946-pCGhhk7JUwlKXZ9Ak7
- Pitch deck: https://docs.google.com/presentation/d/11yP6zxSwF5ottg9jixkSWWFQ5GhvP2PH_vkunQ7mZus
- Smart contract design mock-up: https://drive.google.com/file/d/1KcTrqGDKW_43nFsrTvGqjTc0AvDQQFyg
- Product description: https://docs.google.com/document/d/1g24TAIE5zIouSZJbY8_gBnp14-vahKxJ5kqKp8ZiHwo

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:** Vault and auction contract

**FINAL DELIVERABLE**

**Deliverable:** Vault, auction and settlement contract + simple UI to interact with contracts

**Comment by stacks-foundation** [comment]
👋 @gandalf77
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by swanhtethtetswan** [comment]
This is pretty interesting. I want to use this to harvest yields. Please make this happen.

**Comment by gandalf77** [comment]
Hi @will-at-stacks - I saw that you removed the `Bitcoin Utility` label from the application so I wanted to add a couple of lines on the longer term vision of the product and how we think it can create value for Bitcoin.

The first version of the product (as described in the application) will focus on providing covered call vaults for STX as the underlying asset. So this version of the product does not directly create value for the BTC main chain - I'm fully with you on that point. 

However, the long term vision is to use dlc.link's technology to create vaults for native BTC. Users deposit into the vault by sending a native BTC transaction on the main chain and we then use dlc.link to make that BTC available as collateral in a Clarity smart contract. The contract then sells BTC options against the collateral and all yield generated from the strategy flows back to the user in native BTC (I've put together a mock-up drawing of the system design [here](https://drive.google.com/file/d/16eUpLCwK1pyKowRljD0aZXW4FYL3p9St/view?usp=sharing)).

So the user experiences locking up native BTC to get a native BTC yield, all facilitated by Clarity smart contracts. 

We believe that a product like this has the potential to create considerable utility for Bitcoin by giving BTC holders a way to  generate sustainable (un-subsidized) DeFi yield.

**Comment by will-at-stacks** [comment]
Hi @gandalf77 that was just a housekeeping item on my end.  We had a duplicate of that label in the system and I deleted one and forgot to assign the correct one to this grant.   I’ll do it in the morning.  Thanks for the reminder!

**Comment by kaizengrowth** [comment]
This looks extremely promising! Excited to see this project continue to develop with additional support from the community!

**Comment by murad-alqadi** [comment]
Given the current lack of quality DeFi products built on Bitcoin, I believe this product is sorely needed by the community. Given the current context of the Ethereum merger, Bitcoin will need to offer increased utility beyond being a store of value in order to maintain its market share. This sustainable yield-generating service would increase Bitcoin's utility.

**Comment by TensionCoding** [comment]
I am really interested in this product. I would definitely use it because of the sustainability of the yield and the removal of the barriers to entry of this particular yield generation. A great potential addition to the Bitcoin ecosystem.

**Comment by Alisammour** [comment]
This looks like an interesting product helping to further the democratization and utility of the Bitcoin DeFi ecosystem. @gandalf77 and the team outlined a clear way to provide a simple interface and smart contract based method to do option calls via STX, I'm a fan : )

**Comment by tycho1212** [comment]
Hi @gandalf77 - interesting stuff. Just out of interest, did you primarily draw inspiration from Ribbon Finance, Dopex, or another protocol that's already live?

**Comment by gandalf77** [comment]
Hey @tycho1212 - thanks for your comment. Our main inspiration has been [Friktion.fi](https://friktion.fi) and their various option vaults and structured products on Solana. 

I was aware of [Ribbon](https://ribbon.finance) but since reading your comment have been doing more research into their offering and have drawn a great deal of inspiration especially around their design of open auctions using the Gnosis auction mechanism ([link](https://ribbonfinance.medium.com/open-auctions-a981ff10db2b)), automated Strike price selection ([link](https://ribbonfinance.medium.com/algorithmic-strike-selection-e07ae917c146)) as well as the potential to offer loans against option vault positions to increase capital efficiency ([link](https://ribbonfinance.medium.com/borrowing-against-ribbon-vault-deposits-a802ee4609eb)).

[Dopex](https://www.dopex.io/) is completely new to me. They seem to have a fairly wide and diverse product offering. Their Single Staking Options Vaults (SSOVs) are very close to what we envision to build, so we will research their internal mechanics further.

Thanks for bringing these two protocols to our attention. We will continue to use and study existing protocols to refine our product design and roadmap. If any other comparable protocols come to mind, please feel free to share them with us.

**Comment by Albert-Present** [comment]
One of our Startup Lab teams has already built the foundation of an options vault for their startup project.

I encourage you to reach out to Deep Lake Derivatives to make sure you are not doing duplicate work.

**Comment by gandalf77** [comment]
Hi @Albert-Present - thank you for your comment.

I've been in communications with Abdel from Deep Lake and my current understanding is that their product is focused on giving users the ability to get directional exposure to a wide variety of markets, not on creating yield via automated options arbitrage strategies. If anything, I believe that our products are synergistic as our smart contract will be a seller of call options which could be utilized by Deep Lake to provide long exposure to their clients.  

I'll ping Abdel to get his input on this as well. Thanks again for bringing it up Albert.

**Comment by will-at-stacks** [comment]
@gandalf77 privately, you told me you would favor doing this grant over #662 if you were approved for both.  curious if you can explain your passion for this project over the other?

**Comment by gandalf77** [comment]
Hi @will-at-stacks - thanks for your comment.

The main reason that we would prefer working on this project over #622 is that while stxmempool.space would be a one-off project, the options yield vault product is a long-term project we intend to continue to work on even after the grant milestones are met.

Our vision is to built the options yield vault product into a fully fledged business. The funding from the grant will allow us to build a first version of the product which will serve as the the foundation to apply for the Stacks accelerator program and seek seed financing. We believe that a sustainable yield product will unlock significant utility for the Bitcoin and Stacks ecosystems and in consequence allow us to build a profitable enterprise that can attract and employ engineering talent.

So while we're also passionate about building stxmempool.space (#622) we believe that focusing our time and energy on the options yield vault will have a bigger long-term impact for the Stacks and Bitcoin ecosystems and is thus a better use of the foundation's capital.

**Comment by will-at-stacks** [comment]
@gandalf77 thanks for the feedback!  If we made an exception to our rule and approved both applications, would you have the bandwidth to complete both efforts by the end of Feb '23?

**Comment by gandalf77** [comment]
@will-at-stacks that's great news! Thanks for making an exception and trusting us with the two grants. We will discuss this internally and will get back to you in the next couple of days on whether we feel confident about executing against both project plans within the Feb '23 timeline. Thanks again.

**Comment by will-at-stacks** [comment]
Hi @gandalf77 - 

We have identified the projects we will be awarding grants as part of Stacks Foundation Grants Program Cohort 18. I'm sorry to have to inform you that your project was not among those selected.

This is no way means that we do not see the value of the work you proposed. We're lucky to have so many talented independent researchers, developers, and community leaders like yourself building on Stacks. Unfortunately, we receive many more proposals than we can actually fund with our limited means, so competition is extremely tough. While we generally support innovation in all forms, we tend to prioritize projects that have the potential to advance and differentiate the broader ecosystem from other blockchains, as well as projects that meet critical needs of the community *at the time*. These constraints mean that in several instances, several excellent projects may not make it into a cohort.

Additionally, we will be approving another grant you applied for and only allow one active grant per person.  

We very much appreciate the time and effort you've put into this process and encourage you to continue watching this repo and consider submitting a new application if and when you feel your project better aligns with the current priorities of the Grants Program.

If you should have any questions, please let us know in the comment section below.

Best,
Will
Stacks Foundation Grants Program Manager

**Comment by gandalf77** [comment]
Hey @will-at-stacks - thanks for your message.

I've sent you an email earlier today, can you quickly confirm that you saw the email?

**Comment by Albert-Present** [comment]
I think you have an interesting project.  I would like to invite you to apply to the Stacks Web3 Startup Lab.  Here's a 5 minute read on how we can help you turn your startup idea into an investment ready startup:

www.web3startuplab.io

If you are interested, you can apply through the "Apply Now" button.

Ping me on email:  Albert@stacks.ac
