### ISSUE TITLE
New Startup Lab v2 

### ISSUE THREAD

**Issue by Albert-Present** [stacksgov/Stacks-Grant-Launchpad#686]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;albert@stacks.ac

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;albert_igenesiis#7883

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@btc_albert

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Albert | Stacks Web 3.0 Startup Lab

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;New Startup Lab v2 

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;100,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;3760

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education & Community  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Entrepreneurs and Founders.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Discord: albert_igenesiis#7883, mmmyaa#2172, Mazza#5701, SunnyLi#4635, Scarlett Lyu#0294

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/310

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We aim to reach 300 startups building on Stacks in 12 months. The New Startup Lab increases startups by 6x and retention by 2x = 12x increase in growth.

The way we reach 12x increase in growth can be summarized in two points:

(1) Old Start Lab = 25 teams in 6 months with only 33% into Accelerator = 8 teams building on Stacks.

(2) New Startup Lab = 100 teams in 6months and with over 66% into Accelerator = 66+ teams building on Stacks.  

This is just the first cycle. 

In the second cycle we will increase output to 150 teams + we will be rolling out an entrepreneurs community management component with a community peer to peer self-training track that will feed into our program to bring the total to over 300 startups building on Stacks in 12 months.

The New Startup Lab aims to solve the following problems on Stacks: (1)  Not enough talented entrepreneurs stay and build on Stacks, yet.  (2) Not enough capital, liquidity, and user activity on Stacks.  

By increasing the number of Startups on Stacks, we bring in an estimated $300M in capital through the combined efforts of 300 new startups fund raising. We estimate about 1 unicorn or killer app per 50 startups trained through our program which results in more liquidity from all the new users using all the killer apps.  This will 10X STX price before the next Bitcoin Halving.  Let's shoot for the moon!

1 in 50 become unicorns: 
https://jaredheyman.medium.com/on-600b-of-y-combinator-startup-success-fc85b2076d0d

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Size: # of teams in each cohort
Retention: # of teams that complete and continue on to second leg of the New Startup Lab

After the grant we can also measure by (1) The capital raised by all the startups combined. (2) Number of startups that get into the Stacks Ventures Accelerator.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;#1 Sustainable funding:  We will raise funds from investors who want a piece of the upside of the startups we create through the New Startup Lab

#2 Centralize solution to start:  Convert to Web 3.0 model in the months after to decentralize and scale our solution to empower thousands at a time.

**[Support Link:](https://docs.google.com/document/d/1fjRifW56HMe8Jvpg4oIhTxX6SEOEMjDQuHJwOD759BY/edit?usp=sharing)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;This reference document shows how important it is for us to kickoff the New Startup Lab in September 2022 because it is the beginning of our plan to reach 300 startups building on Stacks within 12 months.  We also outline the short, mid, and long term ROI.  Let's do this awesome initiative together!

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Online Portal: Recruit & filter talented entrepreneurs. Recruit 25 - Cohort 1.

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Cohort 1: Co-founder matching, startup training, validation research, more...

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Recruit Cohort 2: 35 entrepreneurs + Online Portal v2 with self-training videos

**MILESTONE 4:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Cohort 2: Co-founder matching, startup training, validation research, more...

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;2 cohorts =  50 entrepreneurs/startup teams trained

**Comment by stacks-foundation** [comment]
👋 @Albert-Present
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by Albert-Present** [comment]
Please excuse the late application.  This was due to a miscommunication with Foundation staff.

**Comment by Albert-Present** [comment]
@criadoperez Just to confirm, is my grant being considered as part of "Grant Cohort: 18"?

**Comment by ropl-btc** [comment]
I went through the Startup Lab with Albert as our mentor and it was a great experience.
It helps so much to have someone leading you in the very early stages of the journey of an entrepreneur. 
With Albert and the Startup lab you really have someone who motivates you, gets you to believe in yourself and also stops you from giving up.
Without him I wouldn't be where I am now!

**Comment by stxfrc** [comment]
Anatoly from Stacks Force is here. As a founder with two exits and vast experience with various acceleration programs, I can confirm that this is the best program I have ever seen. 
If we talk about which grant can give the most value per dollar invested, then this one should definitely be among the leaders.
The program helps founders to focus on the right things so that the development of the Stacks ecosystem is most effective.
In my opinion, this program is one of the strongest competitive advantages of Stacks over other blockchains in terms of attracting founders.
I really hope that this program will be approved. Our team will definitely recommend it to all the founders we know.

**Comment by babazulu** [comment]
Nick from Stacks Force is here. This is definitely a very powerful program! As a CTO, I discovered a lot of new aspects in terms of building startups. Which allow our team to move much faster and more efficiently. It is especially cool that even after the end of the program, our cohort continues to stay together and help each other in the development of projects and the entire ecosystem.

**Comment by scott4044** [comment]
Albert's program has really opened my eyes to the art & science of launching a digital product. Not have his courses helped my company , but the community that has been built around the Startup Lab is second to none. Looking forward to being a part of the future growth of this program

**Comment by diegomey** [comment]
The Web3 Founder Lab was an invaluable experience for me and our recently founded business. The connections we made and advice from the expert mentors were invaluable, on top of Albert's methodology and growth-oriented mindset. The program helped us to validate our business model and to develop a clear Product market fit that will support our go-to-market strategy. We are now better positioned to scale our business and positively impact the web3 and Stacks ecosystem.

**Comment by dylanft** [comment]
I strongly recommend continuing to fund Albert's efforts to scale the number of entrepreneurs building on Stacks. I cannot imagine a better way for aspiring founders/developers to become fully immersed with the ecosystem and its unique advantages in such a short period of time. Having gone through the program already, I can say that the quantity and quality of resources made available to the cohort were immeasurably helpful. Despite dealing with teams in timezones all around the world, Albert remains dedicated to helping us succeed. Albert has a well-earned understanding of how to establish a strong foundation for lean, early-stage startups. And I doubt you'll hear anyone say "this seems like a solution looking for a problem" about a business that successfully completes his program.

**Comment by orlandobtc** [comment]
I 100% support funding for another cohort of the Startup Lab. I have been fortunate to speak to, and am currently working with, many of the teams that have gone through the Startup Lab. 

I have been impressed not only by their high quality, but also by their improvement throughout the life of the cohort, which is a testament to Albert and his team. 

Additionally, as someone who has gone through the fundraising process with a startup building on Stacks, one of the biggest challenges is that investors have not yet seen many projects or traction on Stacks. I believe that having a program that helps bring projects from idea to MVP is badly needed in the ecosystem and would benefit all projects and startups building here--regardless of whether they are part of the Startup Lab themselves--by driving more attention and usage to Stacks. 

Finally, I have had conversations with Albert to one day incorporate a DAO into the Startup Lab which would further the Foundation's goal of a user-owned internet by allowing investors, mentors, and program participants to have ownership in a part of the Startup Lab itself.

**Comment by hudakurniawan** [comment]
I received valuable knowledge, experiences, and networks from this program, which benefited me in launching a digital product in many aspects. I want this program to succeed and continuously deliver innovation to the Stacks ecosystem.

**Comment by owenstrevor** [comment]
Absolutely blown away by the progress from the first cohort and would love to see this program scaled to help level up all the builders in our ecosystem!

**Comment by abdelghafour** [comment]
- High-quality program
- Tremendous amount of learning
- Targets a segment of entrepreneurs that are looking to be onboarded to the Stacks ecosystem but are not complete accelerator materials

The program fits perfectly in the logistics of building great companies on top of Stacks.

**Comment by zeroauthority** [comment]
Would love to see the Web3 founders lab continue to provide a place for people operating as a pre-accelerator in preparation for the next stage. Talking to people from cohort 1 there is a buzz about the program and it is been a value add.

**Comment by gcotsikis** [comment]
Very high quality programme which I think needs to be supported to help the nascent Stacks ecosystem. Would argue a larger grant allocation is warranted not only to have more pre-accelerator resources but potentially capability of small investments in companies. Stacks has a lot of potential but has not reached critical mass of either builders or investors - this lab can help catalyse the first steps in a meaningful manner.

**Comment by will-at-stacks** [comment]
Hi @Albert-Present -

Congrats!  Your grant application has been approved.  We just sent you an invite (to the email the application was submitted with) to an onboarding call on Monday.  We will use this call to provide an overview of next steps and expectations for proceeding with the grant.

If you are not able to make the call, don't worry, it will be recorded.  

Best,
Will
Stacks Foundation Grants Program Manager.

**Comment by Albert-Present** [comment]
On behalf of me and my team, we thank you for the great news Will!  

And thank you everyone for the support!

Let's grow Stacks and Bitcoin together!

**Comment by will-at-stacks** [comment]
Milestone deliverable updates on this grant can be found [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/774)
