### ISSUE TITLE
Elenktis - stacks dashboard

### ISSUE THREAD

**Issue by sahrodion** [stacksgov/Stacks-Grant-Launchpad#698]

**Comment by stacks-foundation** [comment]
👋 @sahrodion
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by sahrodion** [comment]
I edited and removed the content on this issue. I think there's a problem with the submit button, it doesn't disable after the first click, multiple clicks mean multiple submits. There should be a state to check for button click on the submit application button to check when the button has been clicked.

**Comment by will-at-stacks** [comment]
Please resubmit your application via grants.stacks.org - if you have a bug to report please add it [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/categories/launchpad-issues)
