### ISSUE TITLE
Infinity Wallet - Stacks Integration & Ecosystem Support

### ISSUE THREAD

**Issue by InfinityWallet** [stacksgov/Stacks-Grant-Launchpad#704]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;aron@infinitywallet.io

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Aaron | Infinity Wallet#9732

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;InfinityWallet

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Infinity Wallet - Stacks Integration & Ecosystem Support

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;75,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;850

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Interface  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our audience are DeFi and Web3 users (both novice and experienced) who desire to take ownership of their finances, as well as the bank-less (instant cross-border payments, DeFi and Web3) on desktop and soon mobile, located globally (currently Europe/Americas focused, but we aim to expand and focus further via strategic partners in Asia soon).

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Information on our team, location and experience can be found at the following link https://docs.google.com/document/d/19L9fGt241UVQlXxUtbx7BqkhCFxS6DzlFYu7svtUCi4/edit?usp=sharing

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

![Infinity Wallet](https://i.gyazo.com/e1a68afab6f7150a2baecacb06868a88.png)

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Infinity Wallet is the first non-browser-extension, all-in-one non-custodial wallet ecosystem of its kind on desktop, supporting over 170,000 users within August. Providing a one-stop solution for seamless usability of DeFi, NFTs and easy cross-border payments, with a gateway to the world of Web3/DApps directly within the wallet’s Web3 browser. Fulfilling all a user's needs, while removing the complexities of decentralized finance and enabling economic freedom for everyone globally!

From day one, we have focused on enhancing and providing the best possible user experience and lowering the barrier to entry, to allow for streamlined and secure adoption of DeFi and Web3. Providing a world-class user experience with a seamless user interface, and a full spectrum of constantly growing features and services as a one-stop hub, delivering a more curated in-wallet experience. Making Infinity Wallet the complete solution for all crypto users’ needs, while making adoption and usage of cross-border payments, DeFi and Web3 easier than ever before.

Infinity Wallet is also the first desktop platform to provide users with access to the entire Web3 and DApp space without needing to leave their wallet, with the first Web3 browser and Web3/DApp store (https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/browser-less-dapps-and-web3). Finally removing the need to ever use unintuitive browser extension wallets again! Providing a far superior, safer and more natural user experience, with a range of unique advantages/benefits for users, DApps and chains alike, while enabling easier use and adoption.

A further introduction can also be found in our docs at https://docs.infinitywallet.io/

**Benefit:**
Infinity Wallet will benefit the Stacks ecosystem and holders by providing a unique all-in-one wallet & ecosystem solution on Desktop (with mobile to come in the future), with a focus on premium quality. Delivering a seamless user experience and a user-centric interface, along with access to current and a wide range of constantly growing features/services. Providing Stacks access to the many advancements we have, bringing much needed value (infrastructure, features/services and a premium quality platform) to Stacks.
 
Infinity Wallet will allow Stacks and its ecosystem to be more easily adopted and used by the general public, in a unique crypto wallet, payment solution and Web3/DApp browser built for the masses, and used already by hundreds of thousands of users worldwide for easy cross-border payments, access to DeFi and interacting with Web3/DApps directly within their wallet. As a one-stop platform for all users to directly access all their DeFi, Web3 and crypto needs, making adoption of the Stacks ecosystem as easy and intuitive as possible and boosting awareness, usage and utility.
 
Below are some of the key features and services that chains are already benefiting from within Infinity Wallet and that could benefit and bring value to the Stacks ecosystem:
- DeFi Wallet Solution
![image](https://user-images.githubusercontent.com/64919828/197571201-120588d5-873a-4920-800c-161ba4bc25ba.png)

- Portfolio and Analytics Monitoring/Dashboard;
![image](https://user-images.githubusercontent.com/64919828/197571218-f2713090-b486-43d6-b98b-7dc1e12937f0.png)

- Instant decentralized cross-border payments
![image](https://user-images.githubusercontent.com/64919828/197571297-339d307e-7b87-4f10-8905-5daf787eb7c8.png)

- Web3 browser and DApp store (One-click Connect to DApps, with the utmost discoverability and use of a chains’ ecosystem);
![image](https://user-images.githubusercontent.com/64919828/197571325-1b531563-268c-4b76-a20a-586fda524018.png)
![image](https://user-images.githubusercontent.com/64919828/197571338-bcc71c15-3d81-4bb6-89d6-2600f091ffaf.png)

- Cross-chain swap and bridge (Swap/Bridge between multiple supported chains);
![image](https://user-images.githubusercontent.com/64919828/197571357-f4614297-9513-4527-abaa-b00a4c9e0a8b.png)

- NFT support to manage (view, send and receive) and trade NFTs;
![image](https://user-images.githubusercontent.com/64919828/197571397-7d1decfd-1d12-4a72-8ffd-ce288e42b13b.png)

- Advanced Transaction History and balance/value charts;
![image](https://user-images.githubusercontent.com/64919828/197571416-b47a2b8c-81a3-42d0-a459-25b7d7fd2158.png)

- Custom Token Importing (Allowing any token to be imported even if not default supported);
![image](https://user-images.githubusercontent.com/64919828/197571436-e222367e-3519-4830-ac81-0589e6dc7f74.png)
 
For a detailed look over our many current and future features/services please see our information deck available at https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf (pages 10-24 list core features/services and roadmap), or our docs here https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements (detailing further information on core features/services and secondary features, as well our roadmap)

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The infrastructure/services/features that Infinity Wallet would bring to Stacks would provide much needed value and allow easier awareness, usability and adoption of Stacks and its ecosystem to access Web3/DeFi. Additionally, Stacks will have access to all current and future Infinity Wallet users, providing constant free marketing/awareness of Stacks and its ecosystem. Infinity Wallet will also support Stacks Web3 projects and DApps via our Web3 Browser and Web/DApp Store, with free integrations for the first 15 DApps (waiving our usual $5,000 fee per DApp), to drive Stacks ecosystem awareness, discoverability and adoption.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;There are no risks or other factors that would limit our ability to complete the proposed grant for the integration/development and continued support of Stacks within the Infinity Wallet.

Infinity Wallet has been in live use by hundreds of thousands of users for 2 years, with multiple white-hat hackers testing, and much valued user feedback. We additionally internally audit each release, operate an ongoing bug bounty program, and provide live support to ensure our users' experience is flawless.

Also as Infinity Wallet is a fully self-custodial wallet, users can always access their funds with their seed phrase and private keys, ensuring high security and little risk.

**Support Link:** https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Stacks chain and core functionalities, Add support for custom Stacks token importing and Support Stacks for cross-chain swaps/trading between multiple tokens/chains;

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate/develop Stacks into Infinity Wallet Web3 browser to connect/authenticate with Web3 projects/DApps, and create Stacks Web3/DApp store for easy discoverability and use of Stacks projects. Develop Stacks NFT support, with the ability to send/receive/view NFTs, view NFT information, and easily trade NFTs;

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Implement Stacks into remaining features/services and secondary features (eg. Address Book, Payment Requests, Desktop QR Scan, etc.), internal testing & audit of the Stacks integration. preparation for release, and finally live release of the Stacks integration as a default chain;

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Public launch of Stacks along with ongoing support of Stacks and its ecosystem in the Infinity Wallet, providing great value to the Stacks ecosystem through enhanced usability and adoption.

**Comment by stacks-foundation** [comment]
👋 @InfinityWallet
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
Hi @InfinityWallet -

Right now and for the next quarter or so, grants are going to be reserved for critical blockchain related work and addressing priorities outlined from community feedback, which you can find [here](https://github.com/stacksgov/Stacks-Grant-Launchpad#current-grant-priorities).  While this application covers some really exciting territory, we feel we need to pass for now.  Additionally, we ask that all first-time grantees keep applications below $25k.  If you feel you can reposition your application to align with the priorities, provide new & novel (and open source) tooling critical Stacks for under $25k we invite you to reapply.

Best,
Will

**Comment by will-at-stacks** [comment]
@InfinityWallet -  Thanks for the feedback.  We appreciate your passion and your vision.  The fact that we are passing on the grants does not mean we don't believe in the project, we are just in a time period where we need to be very systematic about approving grants that align with the priorities outlined in the link above.  Again, if you are interested in abstracting out parts of your project that you feel align with those priorities and can easily be repurposed by the developer community - AND - add value to your overall project - please feel free to submit a new application for that limited scope.

Best,
Will

**Comment by Crytogenz** [comment]
Great project one of the best in the space and was looking forward to using stacks on IW. Pretty disappointing that stacks declined it when its one of the best proposals they have ever had so seems kind of self destructive.

**Comment by InfinityWallet** [comment]
> @InfinityWallet - Thanks for the feedback. We appreciate your passion and your vision. The fact that we are passing on the grants does not mean we don't believe in the project, we are just in a time period where we need to be very systematic about approving grants that align with the priorities outlined in the link above. Again, if you are interested in abstracting out parts of your project that you feel align with those priorities and can easily be repurposed by the developer community - AND - add value to your overall project - please feel free to submit a new application for that limited scope.
> 
> Best, Will

Do you have a discord or telegram contact so we can better discuss how we can benefit Stacks and provide much needed infrastructure? Thanks

**Comment by gabril785** [comment]
> Great project one of the best in the space and was looking forward to using stacks on IW. Pretty disappointing that stacks declined it when its one of the best proposals they have ever had so seems kind of self destructive.

I agree this is exactly what the stacks eco needs, especially as wallets are the core for a chains use, for developers dapps to be access and used, and for users to access the chain and its eco. @will-at-stacks why was this declined as it aligns perfectly from what I can see with current priorities more then anything else I have seen recently proposed

**Comment by will-at-stacks** [comment]
@gabril785 see my initial response for reasoning. additionally, this scope of work sounds more aligned with a business development partnership that benefits InfinitiWallet not an open-source grant.  If the team wants to re-position the application and re-apply with a total budget of $25k or less, that would be great.  

https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/704#issuecomment-1295336213

**Comment by InfinityWallet** [comment]
> @gabril785 see my initial response for reasoning. additionally, this scope of work sounds more aligned with a business development partnership that benefits InfinitiWallet not an open-source grant. If the team wants to re-position the application and re-apply with a total budget of $25k or less, that would be great.
> 
> [#704 (comment)](https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/704#issuecomment-1295336213)

Hi @will-at-stacks, do you have a way for our team lead to contact you to discuss this further?
