### ISSUE TITLE
Social3

### ISSUE THREAD

**Issue by Tlazypanda** [stacksgov/Stacks-Grant-Launchpad#713]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;mishrasneha.bb@gmail.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;lazy_panda#0274

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;sneha_bb

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Social3

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;75,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;360

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks dApps & Clarity  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Job seekers & recruiters in web3 - Professionals working in web3

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Tlazypanda, Jaagrav, Atoo35

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;https://grantsdashboard.stacks.org/dashboard/grants/410

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We are on the mission of building a decentralised network of web3 professionals. This is a community driven initiative that invites more transparency for not just individuals (since their data is collected from on-chain activity) but incentivises them to learn and upgrade their profiles to be considered for web3 opportunities.

- As of now Stacks jobs and clarity lang need to be advertised more heavily to allow users to understand the opportunities of working in this ecosystem which we believe our application can help with. 
- For current Stacks companies hiring, it's difficult to find skilled clarity devs. By issuing badges based on user's activity on Stacks blockchain would make it quite simple to understand if a candidate is the right fit for a role. For ex- a person claiming to be a clarity dev but hasn't deployed a single contract on testnet can be filtered out easily.

We currently have 2500+ following on twitter with >700 users on the app from a week of launch who are actively seeking work in web3. This grant will allow foster a long term relationship between Social3 and Stacks to help out with any of your hiring needs. This also opens doors towards future collaborations such as educational initiatives around Stacks Protocol awareness and AMAs with our headstrong community of web3 professionals. We will also be heavily posting on our social channels (Discord, Twitter etc) spreading awareness of the protocol and any opportunities that shall open up.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;- No. of people who connected their stacks wallet
- User badges issued on querying stacks activity
- Traffic in terms of job applications on stacks ecosystem job listings 
- Users who joined stacks learning partner programs listed on our learn section

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;- Comms w Recruiters in Stacks eco: Follow up on candidates we recommend for roles.
- Connects w Learn Partner: connect w learn partners so they provide api/nft contract to get a candidate's progress 
- Tech: Converting our solidity contracts in clarity
Overcome by office hours, request intros

**[Support Link:](https://app.social3.club/, https://twitter.com/Social3Club)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Live app link, Twitter link
Check this link of our product launch - https://twitter.com/Social3Club/status/1576229173164580865?t=SV_DcK_OP4_CP1g3pbUFUw&s=08 

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Milestone #1 - Integration of Stacks RPC Endpoints  [Context: We would like to setup Stack public RPC Endpoints as stated in the docs.] - Integration of Stacks wallet Hiro by adding @stacks/connect package. [Context: Currently we have the web3-react package already within the application with metamask, wallet connect as options. We would like to add Hiro connect as an option as well.]  - Onboard Stacks learning based partners/orgs by listing them on our learn page. Integrate with them to check progress of learners on these modules and launch badges based on it.

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Milestone #2  - Use Stacks Explorer API to find out user wallet activity on Stacks and award them badges based on it.  [Context: We currently award badges based on user’s activity in chains like Ethereum and Polygon. We would like to perform the same for Stacks by querying and finding out the NFTs owned, tokens, transactions etc by the user. We also would like to dedicate one badge to highlight the user is a user of Stacks if they complete their onboarding and connect Stacks wallet.]

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Milestone #3 - Create equivalent solidity based contracts on Clarity for our on chain referral system [Context: Currently we have our Solidity based contracts - Referrals, NFT minting deployed on polygon testnet. We would like to deploy them on the Stacks blockchain] - Explore the IBC interoperability modules and how to reflect that for users on the application including transfer of assets into other IBC compatible chains. 

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Social3 Integration with Stacks

**Comment by stacks-foundation** [comment]
👋 @Tlazypanda
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
Hi @Tlazypanda 

Thanks for reaching out and thanks for the application!  Applications for this cohort close next Friday 11/4 and then the Grants Review Committee will be doing the full review.  Currently, I am in the process of doing some pre-review and one of the things I wanted to ask you about is the overall budget for your grant.  

Right now and for the next quarter or so, grants are going to be reserved for critical blockchain related work and addressing priorities outlined from community feedback, which you can find [here](https://github.com/stacksgov/Stacks-Grant-Launchpad#current-grant-priorities).  While this application covers some really interesting territory, we are trying to be cognizant of only funding the portions that are the most high-impact and aligned with those priorities.  Additionally, we have been asking applicants to keep their budget in the **$75/hr range** and your application appears to pencil out to $208/hr.  If you could take a close look and try to keep your overall budget around $25k that would be great.  You can also refer to the awarded applications from Cohort 18 to see the amount of scope they were able to cover for similar budgets.

Additionally, we can't award you a new grant until you complete all other active grants.

Lastly, you should take a look at these two applications and avoid seeking funding for any scope that was covered by them.  If you would like details, perhaps reach out to @RagnarLifthrasir.  [1](https://grantsdashboard.stacks.org/dashboard/grants/287) [2](https://grantsdashboard.stacks.org/dashboard/grants/494) 



Please let me know if you have any questions.

Best,
Will

**Comment by Scarlett-Web3** [comment]
I think you have an interesting project. If you haven't already gone through the Stacks Web3 Startup Lab, I would like to invite you to apply.  

Here's a 5-minute read on how we can help you turn your startup idea into an investment-ready startup:
www.web3startuplab.io

If you are interested, you can apply through the "Apply Now" button.

Feel free to ping me on email:  scarlett@stacks.ac

**Comment by Tlazypanda** [comment]
Heyy @will-at-stacks my bad I actually only included the total no. of hours without taking into consideration that they need to be separately counted for each dev- that should bring it to 360*3 = 1080 hrs. In terms of reducing the budget scope we can bring it to 30k by removing some of the scope that as you have pointed out has been the scope of the 2 projects mentioned. 

Precisely this is what we would like to be removed Milestone 3 - 
- We would like to deploy them on the Stacks blockchain] - Explore the IBC interoperability modules and how to reflect that for users on the application including transfer of assets into other IBC compatible chains.
- Referrals on Stacks

**Comment by Tlazypanda** [comment]
Heyy @Scarlett-Web3 sure lemme take a look!

**Comment by will-at-stacks** [comment]
@Tlazypanda thanks very much for the reply and for the budget adjustment.  I will note this for the review committee!

**Comment by will-at-stacks** [comment]
Hello @Tlazypanda 

Thank you for the application and for your patience with the grant review process. We did a thorough review of all of the applications (each application received an average of 6 reviews from members of the Grants Review Committee).  However, after much consideration, we decided not to fund any of the Cohort 19 grant applications as we did not feel they aligned with critical priorities core to the development of the Stacks blockchain.  

We invite you to please read this [blog post](https://stacks.org/grants-program-cohort-19) we authored to help elaborate on the reasoning behind this decision and clarify the current mission of the Grants Program.

Thanks in advance,
Will
Stacks Foundation Grants Program Manager
