### ISSUE TITLE
Lightning Stacking Pool #610.1

### ISSUE THREAD

**Issue by will-at-stacks** [stacksgov/Stacks-Grant-Launchpad#715]

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Process#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
