### ISSUE TITLE
BTC (Stacks) Excellence Center

### ISSUE THREAD

**Issue by BellaIrons** [stacksgov/Stacks-Grant-Launchpad#734]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;bella@academicnftconference.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;BellaIrons#3623

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@Bella_Irons

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;BellaIrons

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;BTC (Stacks) Excellence Center

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;120,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;2,000

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Foundation Resident Program 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education & Community  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Strengthen Community

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Institutional)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks community and founders, STEM Deans, Division chairs, or Professors, DeSci community, non-STEM Institutions or divisions, and organizations, government, or non-profit industries

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Bella Irons (and Academic Web3 Conference Interns)

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;City Packs collaboration with Academic Web3 Conference, StackerDAO applicant

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Diego Mey with City Packs collaborated with our Academic Web3 Conference (Youth Web3 Models Session), we are in the early applicant phase with StackerDAO with guidance from Orlando Cosme

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;GRANT MISSION:       To establish a standardized Residency program, and the planning, and implementation of supporting infrastructures, such as an Excellence Center (EC), to innovate beyond competition, broaden adoption, have a meaningful impact, and ensure the success of a user-based internet through cross-industry support, opportunity, investment, and development. 

This grant’s mission could include (but is not limited to)...

Broader Adoption: Bridging outside ecosystems like institutes, government, investment, and nonprofit industries that can have significant impact to STX adoption by utilizing current models and systems within these agencies as catalysts for collaboration. Implementing supportive soft systems such as marketing, PR, and communications can continually provide collaborative models with these agencies for substantial adoption.  

Meaningful Impact: This grant could not only extend the Stacks ecosystem’s expertise to the government, investment, academic, and nonprofit industries, which expands reach by over *100m, but this grant could significantly impact Stacks *diversity, equity, and inclusivity (DE&I) through outside agency collaborations, and support initiatives as well as communications and engagement with the general public. 

Expanding a User-Owned Internet: A standardized Residency Program and the supporting infrastructures (EC) will allow the Stacks ecosystem to have a place, and a dedicated position, where their expertise can be compiled, archived, standardized, and communicated for outside engagement. Helping advance greater adoption of a user-owned internet by integrating traditional soft system models in business, institution, government, or non-profit agencies, within the Stacks community and advancing diversity, and innovation through significant reach within collaborations, support, and investments.

A supportive infrastructure could include (but is not limited to) the following...

- Establishing an Excellence Center (EC) to coordinate the Stacks ecosystems through communicating expertise, best practices, careers, education, training, or outreach initiatives through traditional soft systems such as marketing, PR, communications, database and/or platform administration, awards, grants, research, or sponsorships.
- Establish Expansion hubs with academic, government, or nonprofit agencies that aid in developing Stacks projects through initiatives, collaborations, and sponsorships.
- Bring innovation to institutions like Aca-thons (academic hackathons), and non-STEM integrated curriculums, to develop and implement Stacks wishlists, or projects.
- Drive a greater diversity of adoption and development by engaging the public through targeted models of marketing, PR, communications, and events. 
- Glossary & Terminology - growing academic resources such as graduate projects translating the Blockchain Super Glossary that I'm a core contributor of as well as the other open-source documentation (DeSci wiki) that our conference continually sources.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Grant Impact:    The Stacks Residency can have a long-term impact on founders, projects, and the community by implementing soft systems in marketing, PR, diversity, and communications paired with cross-industry standardization to easily integrate industry, and community investment. Some of which could be…

Establishment of the Stacks Residency Program - through standards, milestones, review processes, and calls for papers/proposals (CFPs) - that expands support through initiatives such as (but not limited to):
- Campus career projects through student initiatives with Stacks projects such as MiamiCoins (https://www.mdc.edu/bitcenter/bit-workshops/)
- Form collaborations with DE&I initiatives with student projects
- Establishing Stacks education(s) in state-based career centers or secondary college certificate programs with BIT (https://www.mdc.edu/bitcenter/bit-workshops/) 
- New wallet connections with extracurricular gaming/investment initiatives
- Regular community exposure and engagement through PR, and events
- Expanding databases for community support, promotions and engagement

Launch of an Excellence Center (EC) to regularly-engage ecosystem expertise through (but not limited to):
- Publications, research, and proposal collaborations with non-STEM programs to grow overall campus adoption
- Pairing StackerDAO Labs as a student-led activity collaborator
- Welcoming BTC investors and social organizations through youth projects in collaboration with CityPacks, Foundation For New Education Initiatives and Miami-Dade County Public School - Division of Academics - STEAM
- Residency Program research CFPs (call for papers/proposals) that will encourage continued publication and collaboration with institutions, government, and nonprofits
- Implementation of Stacks-funded projects to build cohesion and engagement with all those in the ecosystem
- Educational outreach with workshops, and initiatives for campus groups such as MIT's Bitcoin club (http://bitcoin.mit.edu/) and student initiatives like the Summer of Bitcoin (https://www.summerofbitcoin.org/)
- Create channels for regular BTC investment and funding through community programs, sponsorships, initiatives, and awards
- Community growth through alliances, and communication of Stacks expertise, resources, and news or events
- Stacks community proposals implemented through EC infrastructures
 
Innovating competitor outreach in areas such as (but not limited to):
- Non-STEM divisions with Aca-thons (academic hackathons)
- Non-STEM-driven collaborative projects that provide full campus opportunities within various fields
- Bridged web2 & web3 industry initiatives

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Grant Risks:    There are known (and unknown) risks with this grant, which could include:

Increased competition within institutions, or systems by established competitors like:
- Algorand's Centres of Excellence programes
- Cardano's work with the University of Zurich's Blockchain Center and the Blockchain and Distributed Ledger Technologies (BDLT) Group

The establishment of new pedagogical practices, procedures, outreach, and implementation could incur additional community resources such as:
- Regular Stacks community reviews for standardization consensus
- Establishing/collecting multiple internal systems for a centralized space (Excellence Center) that a Residency’s rotating participants would engage with, such as databases, websites, procedures, communication, and outreach

An unsecured Residency could prohibit the program's success by:
- Creating stagnant reception or decreased involvement
- No standardized traction for business, investment, and academic institutions to get involved or collaborate
- Unclear communications throughout the ecosystem can cause undo chaos
- Retention or application atrophy
- Inconsistent grant applications and applicants
 
Overcoming challenges: The Resident’s standards could be made responsible for regular engagement with the Stacks community to help…

- Establish a regular review scheduled with the Stacks community and teams to incorporate feedback on guideline/standardized development for community & cross-industry support
- Collaboration with the Academic Web3 community to build sustainable campus-wide & research (DeSci) networks for driving innovation to projects, or Clarity adoption
- Incorporate soft-systems design and management into Residency through supportive infrastructures to regularly integrate ongoing Stacks proposals and funded-projects

**[Support Link:](https://academicnftconference.com/btc-excellence-center)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;For a comprehensive grant application including links, CV, case studies, media and supporting documentation, visit: https://academicnftconference.com/btc-excellence-center

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Residency Program guidelines in review, soft systems plan drafted

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Residency guidelines established, Excellence Center model in review

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Excellence Center launched, 2024 CFPs & applications open, EOY Report drafted

**MILESTONE 4:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;2024 Residency & Excellence Center, applicants, and calendar publicly announced

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Residency Program guidelines, BTC (Stacks) Excellence Center launched

**Comment by stacks-foundation** [comment]
👋 @BellaIrons
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by diegomey** [comment]
Bella Irons is an excellent leader and an asset to the Stacks Ecosystem. Her Academic background, experience, and innovative mindset are ideal for building the necessary framework for establishing an Excellence Center to further the Stacks adoption. I highly recommend her for the grant, not only to aid in the extension of the Stacks ecosystem’s expertise to the government, investment, academic, and nonprofit industries but also to impact founders, builders, and the community by implementing systems to diversify and optimize essential projects on stacks and bitcoin.

**Comment by Fluttar** [comment]
This is a brilliant proposal and visionary for BTC to have a Centre of Excellence!

**Comment by will-at-stacks** [comment]
Hi @BellaIrons -

Thank you so much for the thoughtful application.  However, right now and for the next quarter or so, grants are going to be reserved for critical blockchain related work and addressing priorities outlined from community feedback, which you can find [here](https://github.com/stacksgov/Stacks-Grant-Launchpad#current-grant-priorities).  While this application covers some really interesting territory, we feel we need to pass for now.  However, I would recommend that you connect with @haundre the Community Growth Lead at the Stacks Foundation.  He would be a great person for you to make contact with and might have some ideas on how to help moving you forward with your efforts.

Best,
Will
