### ISSUE TITLE
Do not submit

### ISSUE THREAD

**Issue by Alisammour** [stacksgov/Stacks-Grant-Launchpad#742]
# PLEASE NOTE: THE STACKS FOUNDATION GITHUB GRANT ISSUES ARE FOR ARCHIVE PURPOSES ONLY

All new grant application should be submitted via https://grants.stacks.org/.

If you submit an application for a grant via this repo the application will not be review.

If you have any comments, questions or concerns please visit the #grants channel on the Stacks Discord server or email ambassadors@stacks.org.

Thank you!

**Comment by stacks-foundation** [comment]
👋 @Alisammour
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
