### ISSUE TITLE
WISHLIST GRANT / RFP / BOUNTY :  Stacks Libraries / SDKs (multiple languages)

### ISSUE THREAD

**Issue by will-at-stacks** [stacksgov/Stacks-Grant-Launchpad#750]
The Stacks Foundation is currently accepting applications for the development of libraries / SDKs that provide the building blocks required to work with the Stacks blockchain for the following languages:

- Rust
- C
- GoLang
- Java
- Python

If you wish to be considered for developing one of these please send an email to grants@stacks.org with the subject line: "Stacks Library for `[language name]`".

In your email please include the following:

1. Link to your Github repo and any team members
2. Link to relevant Github repo's demonstrating your expertise in the proposed library language
3. Proposed scope of functionality you intend to cover (see these links [1](https://docs.stacks.co/docs/intro) [2](https://github.com/hirosystems/stacks.js) [3](https://micro-stacks.dev/))
4. Estimated number of hours for the proposed scope
5. Estimated budget for the proposed scope

If you do not see a particular language listed above that you are interested in contributing a library for, please submit a request by following the same instructions!

Thank you!

Will 
Grants Program Manager

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by fluidvoice** [comment]
I don't see why **GoLang** and **Java** can be on this list but not **Elixir** voted #2 most loved lang after **Rust** [in the 2022 Stackoverflow survey](https://survey.stackoverflow.co/2022/#section-most-loved-dreaded-and-wanted-programming-scripting-and-markup-languages)... and the **Elixir** framework **Phoenix** [voted #1 most loved framework](https://survey.stackoverflow.co/2022/#most-loved-dreaded-and-wanted-webframe-love-dread).

**Comment by will-at-stacks** [comment]
@fluidvoice Elixir was covered here:
https://grantsdashboard.stacks.org/dashboard/grants/555

The list came from Kenny and JW - and there is an option for people to suggest whatever language they want.

**Comment by fluidvoice** [comment]
> @fluidvoice Elixir was covered here: https://grantsdashboard.stacks.org/dashboard/grants/555
> 
> The list came from Kenny and JW - and there is an option for people to suggest whatever language they want.

Thanks Will. Very glad to see it.  I hope we can attract some Elixir devs. There are some big brain bro's in that tribe.

**Comment by rswol** [comment]
@fluidvoice StacksOnChain.com backend is written in Java. If we had SDK already, the development would be way easier. StacksOnChain is part of Stacks infra with multiple projects relying on its work. It would also enable Clojure for free.

As for GoLang - it is a very popular language for building infra projects. Once you start integrating with cloud providers and external services, you quickly find that Java and GoLang are the most convenient choices.

**Comment by fluidvoice** [comment]
@rswol sure popularity should probably be the top metric to look at.
But eg., **Discord** used to be written in Go and they had to rewrite it in Elixir and Rust to improve scalability.  
Different langs are important for different reasons.

**Comment by rohitverma007** [comment]
Hey @will-at-stacks,
Are you by any chance still accepting proposals for this? Specifically Python?

**Comment by will-at-stacks** [comment]
Hi @rohitverma007 -

Yes, we are!  Please feel free to email the broadstrokes of your application as outlined above.

Thanks!
Will

**Comment by friedger** [comment]
Can you please cc me? I am interested to see what is worked on.

We will work on C.

**Comment by jruffer** [comment]
We did most of our grant work in Golang and started a sdk for it but it never found a home.  Did someone else submit or finish a goland sdk already?

**Comment by fluidvoice** [comment]
Here is what ChatGPT reports as top 5 languages per their 2021 data:

![2023-01-17_17-32](https://user-images.githubusercontent.com/373038/213006915-f1d6a2ea-edad-46ad-a2b2-ce1fedb219ce.png)

**Comment by friedger** [comment]
I suggest to focus on the language that brings the most benefits to the ecosystem. Maybe chatgpt can help maybe not.

**Comment by fluidvoice** [comment]
> I suggest to focus on the language that brings the most benefits to the ecosystem. Maybe chatgpt can help maybe not.

The point isn't about ChatGPT. That's just generating a consolidated search result. 
Github Octoverse latest data agrees with the result as shown below.  
**Do you mean to say that (app) lang popularity isn't the most important criteria for choosing?**

![2023-01-17_19-16](https://user-images.githubusercontent.com/373038/213024948-9435c20b-5f42-44e5-878c-cbb4778592de.png)

**Comment by friedger** [comment]
I don't know at what data Github Octoverse is looking but I guess it is not looking at which languages are most used in the web3 ecosystem.

**Comment by fluidvoice** [comment]
> I don't know at what data Github Octoverse is looking but I guess it is not looking at which languages are most used in the web3 ecosystem.

Maybe it's not definitive but it's supportive ;-)

![2023-01-18_15-46](https://user-images.githubusercontent.com/373038/213267999-81e60e98-1218-40e7-9431-12a0b798a899.png)

**Comment by fluidvoice** [comment]
Also as I'm sure you know Python is used quite a bit in AI, ML (machine learning):
https://www.codecademy.com/resources/blog/machine-learning-programming-languages/
So is Go lang (I think).

**Comment by fluidvoice** [comment]
question: Shouldn't the criteria and goals be surfaced here so everyone knows what the focus and priority is on?

There are so many possible reasons for focusing on a language. Eg., Rust is very fast and used in smart contracts on Polkadot and Solana in addition to Stacks core.  
But is this grant/topic more focused on dapps and app developers or smart-contracts, or...?

**Comment by fluidvoice** [comment]
PS. even though there is an endless list of articles like this, gonna drop this I just bumped into in the event it's helpful...
https://techbeacon.com/app-dev-testing/23-blockchain-languages-driving-future-programming

**Comment by will-at-stacks** [comment]
Closing this issue as it has been superseded by targeted Critical Bounties (one per language).  Rust and Python are the most pressing and are being funded first.  Please apply if you are interested.

#869 
#870
