### ISSUE TITLE
Ryder: bringing web 3 to the masses

### ISSUE THREAD

**Issue by MarvinJanssen** [stacksgov/Stacks-Grant-Launchpad#78]
**Background**
As DeFi disrupts the financial industry and NFTs start to empower creators to monetize directly with their fans. We believe that the next crypto cycle and boom-bust will be focused on data ownership and privacy, all while achieving true self-sovereign identity. A cycle wherein we try to realize the full potential of web 3.0 by tying all the innovation through DIDs.

We intend to make (digital) identity truly personal and achieve self-sovereignty with our hardware device: Ryder.

Our first proposal can be found at #6. This led to the development of the first hardware identity device of its kind, with currently 10 working prototypes in the hands of key community members. We refer to them as the Pioneers.

**Project Overview**
(For a historic overview, we refer to the posted issue at #6 and the corresponding documentation.)

**Our full proposal, including what we achieved so far, can be accessed here:**
https://www.notion.so/Ryder-Deck-v_01-67526501bbde43a39dce76a0fc83b923

**Scope**
Our project is fully scoped in the document linked above. The section "2021 Timeline: Ryder Roadmap" delineates major milestones and deliverables. We divided these milestones over multiple funding quarters. 

A direct link to the roadmap: https://www.notion.so/b319b1b729ed435c9d697a3f124d71ca?v=1039f64aaff34d74866c4951e5c83538

**Budget and Milestones**
Our team would like to make an application for a $100,000 grant from the Stacks Foundation. The remaining $30,421.25 will come from the founders. We will use these funds to unlock our 2021 timeline as shown above. This grant will ensure Ryder meets every deliverable before becoming a self-sustainable startup, either through token issuance or SEC regulation crowdfunding (Reg CF).

- **Q22021 - $30,000**
- **Q32021 - $30,000**
- **Q42021 - $40,000**

A cost breakdown can likewise be found in the linked proposal document.

**Team**
Ryder is brought to you by co-founders Marvin Janssen (@MarvinJanssen), Louise Ivan (@louiseivan), and Kiki Grammatopoulos (@kikigramm19), the Pioneers, with a special mention of Niclas Wimmerstedt (@niwim) for helping us compile this grant proposal. Ryder would not be possible without the community members.

- Marvin has worked on projects related to digital identities, DeFi, and blockchain integration, for various players in the crypto space. Recent notable clients include Hiro PBC and OpenSea.
- Louise co-founded Ryder to accelerate the mission of a building better internet on Bitcoin and capturing 100% of the value we create on the Internet today through digital identities. Louise was an external consultant to Hiro PBC and Freehold.
- Kiki is a Product Designer inspired by the worlds of fashion, vehicle, industrial and product design. She studied at Central Saint Martins school of Design in London, and worked in a broad range of companies such as Aston Martin, Jaguar Land Rover and Ace & Tate.

We are currently writing our "Genesis Blog" where we will fully introduce our team and tell our origin story.

**Risks**
With a project of this magnitude, many obstacles are to be anticipated. However, we feel we are in a good spot and have already lined up the partnerships needed to make this work. Our head of product has experience with the product development process and we have an industry veteran as a consultant to help us avoid common pitfalls. For details we again refer to our proposal document.

**Community and Supporting Materials**
Our first proposal and development cycle was a community success and generated a lot of exposure from key members in the Stacks ecosystem, as well as the crypto space as a whole. Take a look at the previous proposal and deliverables for social proofs, and the current proposal document for the kinds of messages we receive daily. The responses have been humbling to say the least. 🙏

**Comment by OmurCataltepe** [comment]
Louise is an great builder who can make this project successful with his other teammates. The project is really good and will increase value of the ecosystem. I think this project should be supported. I loved it!

**Comment by GAD2511** [comment]
This is just woow.
Think a kind of "AMA" is needed at this point to let the community know what is being prepared so that community can bring more tools or his support to the team.

Go ahead, you guys have our support.

**Comment by zrixes** [comment]
Great A+ team from Stacks OGs to key specialists in hardware product & digital identities! Excited for Ryder and cant wait to try it when its available!

**Comment by Raikku22** [comment]
Great Team. Can't wait to try . Plus Louise is a great Community leader, he can do what's best for the community

**Comment by kriprodede** [comment]
I think everyone know how Louise is passionately working and how he is successful .I think he deserves to get support for that project. That will be good for ecosystem as well❤️❤️

**Comment by louiseivan** [comment]
Thanks for the warm support everyone!

**Comment by tycho1212** [comment]
Huge fan of this! 😍

One thing that might help you guys internally is to structure your roadmap like an overview of dependencies rather than / in addition to a timeline (i.e. we will first do a, then b, then c). I've always found during product development that a list of dependencies immediately shows where the leverage is & helps to execute accordingly.

This is quite a nice piece on Roadmap vs Timeline: https://www.mindtheproduct.com/free-your-product-roadmap-and-ditch-the-timeline/

**Comment by RaffiSapire** [comment]
Hi there, thank you for the application. This is approved and we're excited to support you however we can. I'll email you an updated docusign to sign.

**Comment by mardi00** [comment]
Awesome guys! I can't wait to have mine

**Comment by RolandDecker** [comment]
This is awesome. I wish you guys all the very best...

**Comment by MichaelforMichigan** [comment]
Looking forward to learning more about this. I’m interested in supporting you too.

**Comment by louiseivan** [comment]
!m1_complete

We're proud to say that we've completed all of our M1 milestones. See the breakdown below for the comprehensive list of achievements during Q2021. 

1. [Ryder User Product Journey](https://shrl.ink/sJ65) - this is Primary Research done by Kiki Grammatopoulos
2. Grow Maker Community 

- [100 dedicated members in Discord](https://discord.com/invite/42ukQRXU4E)
- [317 subscribers in the newsletter](https://ryder.id/)
- 372 followers on Twitter

3. [Phase 1 for full implementation of connect with New Maker Bridge](https://www.notion.so/lightlabs/New-Maker-Bridge-a70796aa03674da8b1b030851861b5af)
4. [Concept Design Phase](https://www.notion.so/lightlabs/Preliminary-designs-9658d85472de4274809304b147ed8aeb)
5. Formalize the Ryder Protocol 0.0.2
6. [Release of Ryder Simulator](https://ryder.id/blog/ryder-maker-bounties/)
7. [Release of Ryder Maker Bounties](https://ryder.id/blog/ryder-maker-bounties/)
8. Technical Design Phase - Onboarding John as a technical consultant

A detailed blog post about each item will be shared soon.

**Comment by MarvinJanssen** [comment]
!m1_complete per Louise's post above.

**Comment by louiseivan** [comment]
!m2_complete
Another quarter, another milestone. See the breakdown below for a comprehensive list of high-level goals that our community completed to help us navigate our Northstar of bringing crypto to the next 100m this Q32021.

1. Onboarded Niclas as a Core-contributor
2. Transaction signing
3. Ryder Q3 Maker Meetup
4. Ryder Commercial Specification Document

- Introduction
- Commercial Requirements/Product positioning
- Device Overview
- Projected end-users
- Projected distribution form and channels
- Projected commercial introduction and regions
- Projected commercial and technical lilfetime
- Projected ecosystems
- Project functional features
- Project Mechanical features
- Project technical protocols and standards
- Projected environmental conditions
- Projected unit packaging

6. New Product Renders
7. The Human-Centered Design of Ryder

A detailed blog post about each item will be shared soon.

**Comment by MarvinJanssen** [comment]
!m2_complete

Adding to Louise's update above, I am happy to announce that we have reached the following technical milestones:

- Basic Stacks transaction decoding.
- Header, with single spending conditions.
- Fee, nonce, origin, the usual... 
- Token transfer payload decoding.
- "c32check", Stacks-flavour Crockford base32 encoding to represent Stacks addresses.
- TXID generation.
- **Transaction signing.** (The big one.)

See:
- First-ever Stacks transaction signed by a Ryder prototype: https://ryder.id/blog/transaction-signing-is-here/
- `send-stx` CLI command draft PR: https://github.com/Light-Labs/ryder-cli-proto/pull/10
- Firmware 0.0.4: https://ryder-proto-v2.ryder.id/pioneer/
- Simulators for 0.0.4 (Windows build coming): https://ryder.id/downloads/

<img width="352" alt="Screenshot 2021-11-30 at 8 44 56 PM" src="https://user-images.githubusercontent.com/5727806/144117125-89f459d0-c2d2-41ea-b7da-d2a3788ad8de.png">

Firmware 0.0.4 can be tried out today. Install it using the `ryder-cli-proto`:

```bash
marvin@Leviathan ryder-cli-proto % ./bin/run firmware fetch -R /dev/cu.usbserial-020259E1
Fetching latest firmware versions
0.0.1
0.0.4
$ ryder-cli-proto firmware -R /dev/ryder-device download 0.0.4
Downloading ryder-firmware-0.0.4.bin
$ ryder-cli-proto firmware -R /dev/ryder-device install 0.0.4
```

This and the above posted by Louise concludes Milestone 2.

**Comment by jennymith** [comment]
> !m2_complete
> 
> Adding to Louise's update above, I am happy to announce that we have reached the following technical milestones:
> 
>     * Basic Stacks transaction decoding.
> 
>     * Header, with single spending conditions.
> 
>     * Fee, nonce, origin, the usual...
> 
>     * Token transfer payload decoding.
> 
>     * "c32check", Stacks-flavour Crockford base32 encoding to represent Stacks addresses.
> 
>     * TXID generation.
> 
>     * **Transaction signing.** (The big one.)
> 
> 
> See:
> 
>     * First-ever Stacks transaction signed by a Ryder prototype: https://ryder.id/blog/transaction-signing-is-here/
> 
>     * `send-stx` CLI command draft PR: [Transaction support Light-Labs/ryder-cli-proto#10](https://github.com/Light-Labs/ryder-cli-proto/pull/10)
> 
>     * Firmware 0.0.4: https://ryder-proto-v2.ryder.id/pioneer/
> 
>     * Simulators for 0.0.4 (Windows build coming): https://ryder.id/downloads/
> 
> 
> <img alt="Screenshot 2021-11-30 at 8 44 56 PM" width="352" src="https://user-images.githubusercontent.com/5727806/144117125-89f459d0-c2d2-41ea-b7da-d2a3788ad8de.png">
> 
> Firmware 0.0.4 can be tried out today. Install it using the `ryder-cli-proto`:
> 
> ```shell
> marvin@Leviathan ryder-cli-proto % ./bin/run firmware fetch -R /dev/ryder-device
> Fetching latest firmware versions
> 0.0.1
> 0.0.4
> $ ryder-cli-proto firmware -R /dev/ryder-device download 0.0.4
> Downloading ryder-firmware-0.0.4.bin
> $ ryder-cli-proto firmware -R /dev/ryder-device install 0.0.4
> ```
> 
> This and the above posted by Louise concludes Milestone 2.

Hey @MarvinJanssen, thanks for submitting this update! I know the milestones are listed in the roadmap you shared but it's a little difficult to discern the milestones from other content. Can you share a list of milestones (with a brief summary of each) in a comment on this thread?

**Comment by MarvinJanssen** [comment]
Oops forgot to reply... 

You're right, we started using a different document for the milestones at some point which left the original we linked in the OP in disarray.

We have updated the completion status of the items in the document: https://www.notion.so/b319b1b729ed435c9d697a3f124d71ca?v=1039f64aaff34d74866c4951e5c83538

These concern the milestones marked **Q32021** per the grant proposal (m2). We also started on some tasks of **Q42021**, as the end of the quarter is fast approaching. We are only posting our grant milestone completion now because the _transaction signing_ milestone was a blocker for the completion of m2. 

You can find a short description on some of them when clicking them. Then there is also the blog post that describes the milestones: https://ryder.id/blog/m2_complete-ryder-q32021-recap-and-whats-ahead/

**Comment by jennymith** [comment]
Thanks @MarvinJanssen! M2 looks great. We'll be disbursing M3 soon.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
