### ISSUE TITLE
Grant support for product and marketing purposes for Web3Campus powered by Cointelegraph

### ISSUE THREAD

**Issue by wladap** [stacksgov/Stacks-Grant-Launchpad#783]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;daniel@web3campus.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Grant support for product and marketing purposes for Web3Campus powered by Cointelegraph

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;380.000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;6

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education & Community  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Improve Existing Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our target audience is Web2 developers who will receive higher career opportunities through switching to Web3. We’re going to spend 70% of the marketing budget on this customer segment. Also, we’re going to reach out to non-tech users who are interested in the topics of crypto, DeFi, and NFT.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our team consists of highly-skilled professionals with experience in successful project leadership and expansion. All team members are passionate about building a product that would support the new wave of creators on their way to the Web3 world.   ⦁ Co-founder/CEO - Vlad Baimurzin: Ex-Head of Product at Geecko with 5+ years of software engineering as a developer and CTO;  ⦁ Co-founder/CPO - Daniel Seman:  Ex-CEO at Cointelegraph. Advanced the media to number one in market share. Launched 7 international editions from scratch. Currently Cointelegraph Advisory Board Member;  ⦁ Interim-CMO & Executive Advisor - Artem Kazakov: CCO & ex-CMO at Skillbox Holding Limited, revenue in 2021 is $185 mln;  ⦁ CBDO & Co-founder - Leo Glazõw: Strategic Business Developer at Cointelegraph;  ⦁ Advisor - Teigi Lee: Head Of Growth Marketing & Expansion at Blockchain.com. Previously held senior leadership roles at OKEx, Microsoft, Web Summit;  …and 12 more experienced team members (developers and content team).

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;With efficient learning methodology and Web3 mechanics, we will accelerate the adoption of the Stacks ecosystem for Web2 developers. The result of our partnership will be 1K new builders and creators for Stacks. 

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;1. Launching of above-mentioned Stacks-related courses and features.
2. Acquiring first users that are engaged in Stacks courses, in particular, growing them to 1K by Jan ‘23.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our major challenge is ensuring the high quality of Contribute2Earn content. One of our platform’s features is encouraging users to create educational materials and share their experiences. Nonetheless, to guarantee their reliability and usefulness, we need to come up with some content-approval mechanics. 

We are going to overcome this by automated filtering our users by their portfolio: their past experience (W3C Digital Identity feature is going to be helpful), number of successful courses completed, and their historical digital footprint on W3C (comments, help on other students’ issues). That would separate “good” students from spammers.

**[Support Link:](https://docsend.com/view/fkzq96qr2dthwp4r)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Please consider the link to our pitch deck.

# GRANT ROADMAP & DELIVERABLES

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Courses and Quests related to Stacks -  How to build DeFi projects (core course), two mini-courses, and two engaging quests. -  $45,000 - Dec’ 22 - Feb’ 23  ⦁ Learn-to-Earn -  student encouragement to use Stacks infrastructure tools with additional result of increased course completion - $20,000 - Dec’ 22  ⦁ Decentralized Identity for student’s traction and company-employee interaction built on Stacks blockchain; Job board with companies’ vacancies - $35,000 - Mar’ 23  ⦁ Contribute-to-Earn - an incentive for users to create content, tasks, guides, and projects for Stacks blockchain - $30,000 - Apr’ 23  ⦁ Marketing of Stacks Courses only and support of students - The sum will be spent on performance and content marketing, community growth, influencers, and webinars. - $150,000 - Dec’ 22 - Apr’ 23  ⦁ Rewards in Stacks for learn-to-earn and contribute-to-Earn - 310,000 STX. - up to Apr’23

**Comment by stacks-foundation** [comment]
👋 @wladap
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
Hi @wladap 

Thank you for the application.  While this sounds like an interesting platform focused on educational efforts we are supportive of we are going to pass on your application.  At this time the grants program is laser focused on critical ecosystem priorities (outlined [here](https://github.com/stacksgov/Stacks-Grant-Launchpad#current-grant-priorities)) and will primarily be deploying funds via critical bounties.  I would encourage you to reach out to Kenny Rogers, the Stacks Foundation Developer Advocate (kenny@stacks.org) to see if there are collaborative opportunities he feels would align with efforts on the dev-rel side of things.  Kenny writes a lot of content and engages other learn to earn platforms so he would be a great person for you to get in contact with.

Best,
Will
