### ISSUE TITLE
Infinity Wallet - Stacks Integration

### ISSUE THREAD

**Issue by InfinityWallet** [stacksgov/Stacks-Grant-Launchpad#792]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;aron@infinitywallet.io

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Aaron | Infinity Wallet#9732

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;InfinityWallet

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Infinity Wallet - Stacks Integration

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;25,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;315

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Interface  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Consumer)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our target audience are both retail users and developers (DApps & Tokens).

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Information on our team, location and experience can be found at the following link https://docs.google.com/document/d/19L9fGt241UVQlXxUtbx7BqkhCFxS6DzlFYu7svtUCi4/edit?usp=sharing

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:** Infinity Wallet is the first all-in-one non-custodial wallet ecosystem and web3 browser of its kind on desktop, launched in 2019, and supporting hundreds of thousands of users. Providing a one-stop solution for seamless access and usability of DeFi, NFTs and cross-border payments, with a gateway to the world of Web3/DApps via the first desktop web3 browser and Dapp store removing the need for unfriendly, unintuitive and feature-lacking browser extension wallets. Fulfilling all a user's decentralized needs in a single platform, while removing the complexities of decentralized finance and enabling economic freedom for everyone globally!

From day one, we have focused on enhancing and providing the best possible user experience and lowering the barrier to entry, to allow for streamlined and secure adoption of DeFi and Web3. Providing a world-class user experience with a seamless user interface, and a full spectrum of constantly growing features and services as a one-stop hub, delivering a more curated in-wallet experience. Making Infinity Wallet the complete solution for all crypto users’ needs, while making adoption and usage of cross-border payments, DeFi and Web3 easier than ever before.

A further introduction can also be found in our docs at https://docs.infinitywallet.io/

**Benefit:**
Infinity Wallet will enable Stacks and its developer ecosystem to be more easily adopted and used by the general public, in a unique crypto wallet, payment solution and Web3/DApp browser built for the masses, and used already by hundreds of thousands of users worldwide for easy cross-border payments, access to DeFi and interacting with Web3/DApps directly within their wallet. As a one-stop platform for all users to directly access all their DeFi, Web3 and crypto needs, making adoption of Stacks and its developer ecosystem as easy and intuitive as possible.

Below are some of the key features and services that chains are already benefiting from within Infinity Wallet and that could benefit and bring value to the Stacks ecosystem:
- One-stop DeFi Wallet Solution
![image](https://user-images.githubusercontent.com/64919828/197571201-120588d5-873a-4920-800c-161ba4bc25ba.png)

- Portfolio and Analytics Monitoring/Dashboard;
![image](https://user-images.githubusercontent.com/64919828/197571218-f2713090-b486-43d6-b98b-7dc1e12937f0.png)

- Instant decentralized cross-border payments
![image](https://user-images.githubusercontent.com/64919828/197571297-339d307e-7b87-4f10-8905-5daf787eb7c8.png)

- Cross-chain swap and bridge (Swap/Bridge between multiple supported chains);
![image](https://user-images.githubusercontent.com/64919828/197571357-f4614297-9513-4527-abaa-b00a4c9e0a8b.png)

- Advanced Transaction History and balance/value charts;
![image](https://user-images.githubusercontent.com/64919828/197571416-b47a2b8c-81a3-42d0-a459-25b7d7fd2158.png)

- Custom Token Importing (Allowing any token to be imported even if not default supported);
![image](https://user-images.githubusercontent.com/64919828/197571436-e222367e-3519-4830-ac81-0589e6dc7f74.png)
 
For a detailed look over our many current and future features/services please see our information deck available at https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf (pages 10-24 list core features/services and roadmap), or our docs here https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements (detailing further information on core features/services and secondary features, as well our roadmap)

**Grant Impact:** The infrastructure/services/features that Infinity Wallet would bring to Stacks would provide much needed value and allow easier usage and adoption of Stacks and its ecosystem (by users and for developers) on a standalone desktop application with mobile coming soon. 

**Grant Risks:** There are no risks or other factors that would limit our ability to complete the proposed grant for the integration/development and continued support of Stacks within the Infinity Wallet.

Infinity Wallet has been in live use by hundreds of thousands of users for 2 years, with multiple white-hat hackers testing, and much valued user feedback. We additionally internally audit each release, operate an ongoing bug bounty program, and provide live support to ensure our users' experience is flawless.

Also as Infinity Wallet is a fully self-custodial wallet, users can always access their funds with their seed phrase and private keys, ensuring high security and little risk.

**Support Link:** https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:** Integrate Stacks chain and core functionalities, portfolio & analytics dashboard, advanced transaction history, and support for Stacks tokens throughout Infinity Wallet features, as well as custom token importing;

**MILESTONE 2:**

**Deliverable:** Develop out support for Stacks cross-chain swaps/bridging and implement Stacks into remaining features/services and secondary features (eg. Address Book, Payment Requests, Desktop QR Scan, etc.), internal testing & audit of the Stacks integration, preparation for release, and finally live release of the Stacks integration as a default chain;

**FINAL DELIVERABLE**

**Deliverable:** Public launch of Stacks, along with marketing and announcements. Ongoing support for Stacks, providing great value to the Stacks ecosystem through enhanced usability and adoption.

### Note: Re-applied as suggested by @will-at-stacks, but with a budget of $25,000

**Comment by stacks-foundation** [comment]
👋 @InfinityWallet
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
