### ISSUE TITLE
The SOWL Decentralized Education Expansion Grant

### ISSUE THREAD

**Issue by sowltoken** [stacksgov/Stacks-Grant-Launchpad#795]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;megan@sowltoken.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@sowltoken

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The SOWL Decentralized Education Expansion Grant

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;10,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;2,500

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education Grant 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Education & Community  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Strengthen Community

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;End Users (Institutional)

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Ages 16 and up, all genders, no limitations on geographical whereabouts.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@sowltoken

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Mission Statement: To become the world leader in Decentralized Education by developing fun and interactive games with a gamification-centric focus, by always keeping our users (our SOWLdiers) at the forefront of our minds in everything we build, and by making our standard of excellence a benchmark throughout the Crypto and Education industries.  There has never been an educational arcade built, let alone one of the blockchain, which will provide a high-growth and innovative area for the Stacks community to see growth, while also feeling good about making a difference through providing decentralized education to many people, including those who do not regularly receive any education due to lack of resources.  SOWL is the ultimate education equalizer and the Stacks community will be at the forefront of this growth.

Grant Roadmap: 

January 2023: - Continue development of Game #1 (Math game; Saffron's Moonshot) - Complete development of the SOWL Educational Arcade website (sowlarcade.com) - Complete development of Game #1 - Launch Marketing Campaign for Game #1 and the SOWL Educational Arcade website overall All of the above will cost $3,000. 

February 2023: - Begin development of Game #2 (Science Game; JewelBlaster).  Development will take 4-6 weeks. - Continue Marketing Campaigns for both Game #1, the Arcade website, and teasers of the upcoming Game #2 All of the above will cost $1,500 

March 2023: - Complete development of Game #2 - Continue Marketing Campaigns for Game #1 and the Arcade website - Launch Marketing Campaign for Game #2 - Begin development of Game #3 (Technology Game; Call of Hacker).  Development will take 6-8 weeks. All of the above will cost $3,500. 

May 2023: - Complete development of Game #3 - Continue all Marketing Campaigns, including a Global Press Campaign that we have already partnered with Press Farm with as well as BSCNews. All of the above will cost $2,000 Grant Grand Total = $10,000 and 4.5 Months.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Our key metrics (KPIs) that will show the grant had a high impact are as follows:
1). Holders - currently we have 1,130 holders which is a relatively low amount and anything greater than that will be a way to determine the success of the grant.
2). Active Users - the growth in users from Game #1 (currently under development) as well as our centralized app is another great way to determine the success of the grant.
3). Games Developed - going from 1 centralized app and no arcade games to 1 centralized app and 3 arcade games will also show the growth and success of the grant.
4). Number of Underprivileged Users Served (and the countries they hail from) - via our "The SOWL Purpose" initiative we provide free virtual education to those who cannot afford it.  The growth in this program will show the success of the grant as it is a central part of our marketing campaigns mentioned in the road map.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;One of the members of our Executive Committee has a degree in Risk Management so this is a topic very central to our operations.  The primary risks are: Securing user data from game play (which we will be purchasing a Data Protection Policy for); Lack of team size (with only 5 main people involved, however we make up for this with the vast technological experience we, as a collective, have); and Market Volatility (which burdens every crypto company currently, however given our low Market Cap and high-growth potential we will continue marketing our many benefits and we will draw in new users given our P2E (Play 2 Earn) model where all users are receiving SOWL tokens for game play).

**[Support Link:](https://github.com/sowltoken/SmartContract2022)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The above link is to our Smart Contract. 

Website:
www.sowltoken.com 

White Paper:
https://www.sowltoken.com/_files/ugd/6cd61e_e372f80eac1d4946af9dcfa596e71cc8.pdf

KYC:
https://idopresales.com/sowl-token-kyc-verification/

Audit and SAFU Badge also available on www.sowltoken.com

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;May 2023 - Game 3/3 development and integration onto website arcade.

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Provide 3 cohesive, interactive, and reward yielding games in our SOWL arcade.

**Comment by stacks-foundation** [comment]
👋 @sowltoken
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
Hi @sowltoken 

Thank you for the proposal, but we have decided to deny your application.  For the next several quarters we are laser focused on only funding efforts that have clear alignment with the current priorities of the grants program noted [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/blob/master/README.md#current-grant-priorities).

Best,
Will
