### ISSUE TITLE
x-chain identity attestation

### ISSUE THREAD

**Issue by xylophonez** [stacksgov/Stacks-Grant-Launchpad#799]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;xylophonezygote@gmail.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;decentdotland

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;x-chain identity attestation

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;20,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;200

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev 1st time Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Cross-Chain & Off-Chain  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Devs and dApp using cross-chain identity. Stacks -> other chains, and vice versa

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;charmful0x, maxknivets, xylophonez

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The decent.land Stacks integration will unlock the ability for developers of dApps on non-Stacks chains to offer their users a way to attest to their Stacks identity.

Expanding on this initial building block, dApps could implement novel cross-chain features, such as DAO token-voting on a non-Stacks platform using Stacks NFTs and fungible tokens. Or, social platforms which include user verification based on the addresses from other chains they have connected (a kind of proof-of-history, especially interesting since it would allow an Ethereum user to prove on-chain that they own a specific BTC address).

As part of the grant, we would look to ship the cross-chain signing component then take it further by getting adoption from Stacks dApps that care about cross-chain identity and social, and integrating Stacks assets an option for token-voting on platforms like AstroDAO and others.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;# of integrations built using the tooling
# of users adopting integrated dApps

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Initial R&D suggests the plan has no technical limitations (our team has already built similar functionality for Arweave, NEAR and EVM chains).

The only foreseeable risk is developer adoption for the tooling, since it is not as strongly under our control.

**[Support Link:](https://github.com/decentdotland)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Of specific relevance in our organization's repo is https://github.com/decentldotland/ark-protocol. 

As well as https://github.com/decentldotland/ar.page, which already integrates grantee TradePort's Byzantion API, making it ready to go with Stacks token integration.

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Tooling to sign non-Stacks contracts w/ Stacks and verify Stacks asset ownership

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Tooling to sign non-Stacks contracts w/ Stacks and verify Stacks asset ownership

**Comment by stacks-foundation** [comment]
👋 @xylophonez
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by friedger** [comment]
What does tooling include? Android? Javascript? C?

**Comment by xylophonez** [comment]
@friedger The tooling will written in JavaScript and interactable with by reading the foreign chains' smart contract states. To explain in better depth, the identity attestation piece will be done by integrating our molecule.sh library for exm.dev contracts into Ark Protocol. This will then broadcast a user's Stacks address alongside their other chain addresses in a complete profile via oracles that can be cross-contract called, and an API that can be called by any web app or a dApp built on EXM.

**Comment by charmful0x** [comment]
Hello @friedger ! 👋 
This is a lower level technical comment about [DecentLand](https://decent.land) grant deliverable milestones. (1 -> 4)

## 1- [molecule.sh](https://molecule.sh)
The `molecule.sh` library is, by analogy, the Openzeppelin of [EXM ](https://exm.dev) smart contract protocol. It's a set of composable building blocks for EXM smart contracts used as infra for decent.land protocols, and other decentralized protocols like [permacast.dev](https://permacast.dev).

By integrating Stacks in molecule.sh dev tooling set, EXM developers will be able to build and deploy smart contracts that can handle Stacks Account as contract caller.

### About EXM
*from EXM.dev*

> Execution Machine (EXM) is a developer platform that powers the creation and usage of highly available and highly performant applications within a decentralized environment. Currently, EXM is the only technology that powers blockchain- based [serverless functions](https://en.wikipedia.org/wiki/Serverless_computing).

EXM smart contract can be written in the following programming languages: Javascript, TypeScript, C, C++, Zig, Rust, and AssemblyScript.

With molecule & EXM, the smart contract written for Stacks will be gasless, having instant finality, and the contract's states are stored permanently on [Arweave](https://arweave.org) network!

This milestone will open various opportunities for Stacks developers interested to deploy Stacks-callable smart contracts that have a new paradigm, in multiple programming languages.

## 2- [Ark Protocol](https://ark.decent.land)
*What is Ark Protocol?*
>Ark is a multichain identity linking protocol built to power decent.land, ANS, and any other applications that rely on users attesting to their identity on other chains. Example use cases include token gating and social data aggregation. With Ark, users can use their Arweave wallet as a master identity to prove activity on multiple other chains.

Ark Protocol Stacks integration is the second deliverable milestone for this grant request. After integrating Stacks network in Ark Protocol stack, web3 users will have the ability (first of its kind) to link, on-chain, their Stacks address to many other blockchain networks under their Ark identity.

Stacks address will be linkable with up to [15 EVM and non-EVM network](https://github.com/decentldotland/ark-protocol#ark-protocol-contracts).

Example: reverse resolving the NEAR address (non-EVM) linked with an ETH address (EVM) https://ark-core.decent.land/v2/address/resolve/decentland.near

![image](https://user-images.githubusercontent.com/77340894/211169176-8a00c1b4-ef1d-4de1-bfa9-c37f26b9d6c3.png)



## 3- Ark API

After integrating Stacks in Ark Core (Ark Protocol, `3`), we will add support for it in the protocol API endpoints for whatever retrievable data from Stacks (assets, NFTs, domains, recent TXs, etc). As mentioned before in this thread, we use the grantee TradePort's Byzantion API already. Ark API will empower [ar.page](https://ar.page) Stacks integration.

## 4- [ar.page](https://ar.page)

With nearly 600 closed-beta users, ar.page is the web3 instragram of ANS & Ark protocols users (ANS is also developed by DecentLand team). Similary to eth.limo or eth.link, ar.page is a much richer user's profile resolver that aggregates and display all the on-chain data provided by Ark API and that belongs to the user's linked addresses on Ark Protocol.

### Example: [dameon1.ar.page](https://dameon1.ar.page/)
![image](https://user-images.githubusercontent.com/77340894/211170134-0f1c663e-5417-4514-a734-e83c4c7c99ff.png)

## 5- Github Repos & Helpful links

## Github
- Ark Protocol & API: [link 1](https://github.com/decentldotland/ark-protocol/)
- molecule: [link 1](https://github.com/decentldotland/molecule) - [link 2](https://github.com/decentldotland/molecule-apis-wrapper)
- ar.page: [link 1](https://github.com/decentldotland/ar.page)
- ANS (referenced): [link 1](https://github.com/decentldotland/ANS)
- Docs: [link1](https://docs.decent.land)

*All the repositories are licensed under the MIT license.*

## Social 
- Twitter: [@decentdotland](https://twitter.com/decentdotland)
- Discord: [discord.gg/decentland](https://discord.gg/decentland)
- Mirror.xyz: [blog.decent.land](https://blog.decent.land)

Have a ***decent*** day! 😄

**Comment by will-at-stacks** [comment]
@xylophonez 

Thank you for the proposal.  We appreciate your interest in the grants program, but (unfortunately) we have decided to deny your application.  For the next several quarters we are laser focused on conserving funding for efforts that have clear alignment with the current priorities of the grants program noted [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/blob/master/README.md#current-grant-priorities) - specifically sBTC.

Best,
Will
