### ISSUE TITLE
Unmarshal indexing Solution

### ISSUE THREAD

**Issue by DeeptiGn** [stacksgov/Stacks-Grant-Launchpad#826]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;deepti@unmarshal.io

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Deepti#2211

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;https://twitter.com/deeptiGN2

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Deepti G N

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Unmarshal indexing Solution

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;65,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;30

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Interface  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integrate Between Technologies

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Dapp developers make up the majority of our users, and we adapt to their demands as needed. Our developer community is growing, and 1500+ Dapps use Unmarshal services focused on user friendliness:

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Manohar Kolagondanahalli - CEO & Founder - https://www.linkedin.com/in/manoharak/ ,Shivakumar HG - CTO & Co - Founder - https://www.linkedin.com/in/shivhg/ ,Yogesh Talurmath - CMO - https://www.linkedin.com/in/yogeshtm/ , Chetan Kashetti - https://www.linkedin.com/in/chetan-kashetti-0972317a/  , Pujith - https://www.linkedin.com/in/pujith-m/  ,Anusha- https://www.linkedin.com/in/anusha-sridhar-9a5a93191/ ,Suyog - https://www.linkedin.com/in/sygbht/ ,Abbas - https://www.linkedin.com/in/abbas-travadi-8460b4194/,Chiranth- https://www.linkedin.com/in/chiranthv/ ,Deepti GN - https://www.linkedin.com/in/deepti-g-n-666b0b93/ ,Saarika velaydhapani- https://www.linkedin.com/in/saarika-velayudhapani-b62836184/

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Data accessibility problem - Though Blockchain Data is public, its inconsistent and not readily accessible.Accessing the data from blockchain is difficult because of complex data processing needs. We are providing Reliable blockchain data infrastructure that’s composable and easily accessible to Clients.

1. Adapt the Unmarshal framework to incorporate the Stacks Chain.
2. The Stacks community will have access to all onchain data by using our services. We will explore opportunities to promode No code indexer parser, so that anyone can use Parser to build analytical dashboards based on smart contracts if they want their own data to be indexed. 
3.By the end of Q2 2023, or three months after the revenue stream begins, we hope to increase partnerships with Dapps and Blockchain. Improve Unmarshal's product features to expand its user base.
4.Through a variety of marketing initiatives, email campaigns, and hosting hackathons, we raise brand recognition.
5. The figure below shows how earlier quarters performed. With the aim of significantly exceeding prior quarters by over 50%, we will leverage social media marketing to encourage sign-ups and boost API users.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Increase in No of users 
Increase in Web 3 adoption

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Potential Risks:
1.Failing to retrieve the node data is the potential risk, which may cause a delay in achieving more milestones.
2.Unmarshal requires a stable node to retrieve data from. Unavailability of the node or any downtime in node service will cause service disruptions. 

**[Support Link:](Discord: discord.gg/SqhYdGYtEr , Twitter: twitter.com/unmarshal , Instagram: https://instagram.com/unmarshal_io , Website : https://unmarshal.io , Documentation : https://docs.unmarshal.io,  Telegram Channel : https://t.me/Unmarshal_Chat , Linkedin : https://www.linkedin.com/company/unmarshal-io,  Github: https://github.com/eucrypt/ , Console: https://console.unmarshal.io/)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Socials

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; Milestone 1 — Indexing The Node Estimated Tech Work - 12 days Time to Sync data - 7-14 days (depends on the volume of data) Number of resources - 4 Approximate Estimated Cost - $10,000 Milestone 2 — Decoding Data Estimated Duration - 18 days Number of resources -  2 Approximate Estimated Cost - $10,000

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Milestone 3 — API services Estimated Duration - 14 days Number of resources  - 2 Approximate Estimated Cost - $10,000 Milestone 4 — Explorer Integration (Xscan.io) Estimated Duration - 14 days Number of resources - 3 Approximate Estimated Cost - $5,000

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Milestone 5 — Notification Services Estimated Duration - 14 days Number of resources - 3 Approximate Estimated Cost - $10,000 Milestone 6 — Parser Services Estimated Duration - 21 days Number of resources - 2 Approximate Estimated Cost - $10,000 Milestone 7 — Enabling Analytics Framework Estimated Duration - 14 days Number of resources - 2 Approximate Estimated Cost - $10,000

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Adapt the Unmarshal framework to incorporate the Stacks Chain. The Stacks community will have access to all on chain data by using our services. We will explore opportunities to promote No code indexer parser, so that anyone can use Parser to build analytical dashboards based on smart contracts if they want their own data to be indexed.  By the end of Q4 2022, or three months after the revenue stream begins, we hope to increase partnerships with Dapps and Blockchain. Improve Unmarshal's product features to expand its user base.   Through a variety of marketing initiatives, email campaigns, and hosting hackathons, we raise brand recognition. The figure below shows how earlier quarters performed. With the aim of significantly exceeding prior quarters by over 50%, we will leverage social media marketing to encourage sign-ups and boost API users.

**Comment by stacks-foundation** [comment]
👋 @DeeptiGn
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
@MiamiNFTBuildathon 

Thank you for the proposal, however we we have decided to deny your application.  For the next several quarters we are laser focused on conserving funding for efforts that have clear alignment with the current priorities of the grants program noted [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/blob/master/README.md#current-grant-priorities) - specifically sBTC.  

I would suggest you reapply later this year, once sBTC is live on mainnet and priorities shift to subnets and data availability solutions.

Best,
Will
