### ISSUE TITLE
Unlocking the Potential of sBTC: The GameFi Subnet 

### ISSUE THREAD

**Issue by czeslaw** [stacksgov/Stacks-Grant-Launchpad#829]
# APPLICANT

**Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Direct Application

**Email:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;stacks.wannabe@gmail.com

**Discord:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp; norbertredkie.btc#4318

**Twitter:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;@Nredkie

**Stacks Forum:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;norbertredkie.btc

# GRANT BASICS

**Grant Name:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Unlocking the Potential of sBTC: The GameFi Subnet 

**Total Budget:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;242,000

**Total Duration:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;3,025

**Grant Type:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Open Source Dev Repeat Grantees 

**Grant Track:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Stacks Developer Experience  

**Grant Goal:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Create New Technology

**Grant Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Developers

**Specific Audience:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Explicitly: for web2.0 developers wishing to port their apps to web3.

**Grant Team:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;       pisajew, pki-acs, telemetricsystems, mikaelit, michal.szymerski@gmail.com, s4ros, forkility, FilipCichorek

**Previous Grants:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/611

**Ecosystem Programs:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Wannabe is currently a part of the Stacks Accelerator programme. We've even got our kickoff meeting today!

# GRANT MISSION, IMPACT, RISKS & REFERENCE

**Grant Mission:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;We are excited to present our proposal to the Stacks community for the creation of a comprehensive GameFi Subnet, powered by sBTC and Ordinals. Our team at Wannabe is committed to driving Stacks adoption even further, and we believe that a GameFi Subnet will be a major step forward in achieving this goal.
 
Our Subnet will consist of a suite of SDK tools designed to drive Stacks adoption and streamline the development process for game developers. We are proposing a "gasless system," eliminating the need for players to handle complicated web3 issues. We will also offer a "managed wallet" that is automatically created for each player, compatible with BTC, sBTC, and other Stacks tokens, allowing for easy minting and storage of Ordinals. This all will be included in a comprehensive SDK architecture that combines  and extends already existing tooling created by Wannabe (iOS, Android, Unity, Construct 3), Stacks Degens (web3 guidelines) and Stacks Force (simple Unity) with extra toolsets consisting of Unreal Engine SDK to bring AAA developers to Stacks.
 
Additionally, GameFi Subnet will include a "white label subnet marketplace" where players within the game can easily trade items with each other and generate royalty fees for the game developer and item creators (player minting an item). We will implement "transfer timelocks" to restrict the transfer or trade of specific items for a specific period. Our "advanced lootbox adoption" will offer game mechanics such as booster packs, treasure chests, and lootboxes that require multiple items to open. We will also offer a "limited offer redemption" setting limits on the number of times an offer can be used globally, as well as a "crafting system" that allows for flexibility in crafting offers to fit the needs of the game.
 
To ensure our work does not overlap with other GameFi teams building on Stacks and to maximize the benefits to the community, we communicate regularly with other Stacks Startup Founders through the Telegram group created by Ragnar and with Stacks leaders, including Muneeb, as well as with Trevor and the Accelerator team, Stacks Degens and Stacks Force via Discord DMs. We also plan to partner with startups such as Liqudium, NeoSwap, Gamma and Alex, to offer a comprehensive and cross-promoting solution for in-game tokens.
 
Our team has already received a grant to build a F2P and P2E merger toolset for the Stacks ecosystem, which we have completed on time and has already been settled by Will. Our focus on unlocking the potential of billions in BTC/sBTC/Ordinals through our GameFi Subnet is in line with our previous work in the Stacks ecosystem. We are confident in our ability to deliver a professional, technically sound solution that can be used by many different games built on Stacks, and that will lay a proper framework for others to follow to expand the ecosystem in the future.
 
Moreover, our team has the necessary experience to deliver on this proposal. Stacks Degens are open-source and residency-focused, providing knowledge on fully decentralized GameFi applications. Stacks Force is business-focused with a dash of web3 mechanics implemented into very simple games such as Chess. Wannabe, on the other hand, is focused on creating innovative GameFi solutions that can be used by Web 2.0 game developers and distributors making Stacks adoption our priority.
 
In conclusion, we believe that the creation of our GameFi Subnet, powered by sBTC and Oridnals, is a critical step forward in driving Stacks adoption even further. Our comprehensive suite of SDK tools will streamline the development process for game developers and provide a seamless, end-to-end solution for creating and launching Stacks-powered games. We urge the Stacks community to support our proposal, and we look forward to working together to achieve our shared goals.

**Grant Impact:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The community will verify the impact of the grant through metrics such as the number of games developed on the Wannabe Subnet (4), user engagement (4k users on Discord), trades on the subnet marketplace (100), and overall impact on the Stacks ecosystem. These metrics indicate the success of the grant.

**Grant Risks:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;The main risk factor with the grant is the Subnet structure and creating a managed wallet for both BTC and sBTC. The potential for technical limitations during the development process is present, but Wannabe is committed to overcoming these challenges by re-writing and forking existing smart-contracts and regularly communicating with other Stacks startup founders and leaders to ensure compatibility and avoid overlap.

**[Support Link:](https://wannabe.games/docs)**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Please find attached the latest library of SDKs and other developers tools built by Wannabe, that help to grow the Stacks community. The list is still expanding. We're hoping that it will grow much faster with the help of this grant.

# GRANT ROADMAP & DELIVERABLES

**MILESTONE 1:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Design and implementation of GameFi Subnet contracts, swap and wallet contracts (including Ordinals). Contracts allowing players to transfer funds in and out of the GameFi Subnet, using sBTC FT.

**MILESTONE 2:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Development of game developer contracts. Contracts to service developers in the GameFi ecosystem. Supported features include transfers, Ordinals minting, withdrawals, and player sponsoring.

**MILESTONE 3:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Implementation of a marketplace and item trading system. Definition of items in the context of game studios. Contracts for listing and trading the items.

**MILESTONE 4:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Integration of advanced features such as crafting system, transfer timelocks, advanced lootbox adoption, and limited offer redemption.

**MILESTONE 5:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Development of an SDK for Unreal Engine and extended SDK tooling for iOS, Android, Unity, Construct 3. The SDK will include a JS client library, developer documentation, and tools for easy integration with existing game development workflows.

**MILESTONE 6:**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;Development of an SDK for C# client library, tools, and documentation for seamless integration with existing game development workflows. The SDK will include advanced features such as cross-chain support, smart contract interaction, and token management. The clear and concise documentation will enable developers to easily build fast GameFi applications on the Stacks ecosystem using a subnet.

**FINAL DELIVERABLE**

**Deliverable:**&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&hairsp;&thinsp;A well documented system of interconnected GameFi tools implementing cutting edge blockchain technology: GameFi contracts, gamedev contracts, marketplace, more advanced contracts gamedev SDKs.

**Comment by stacks-foundation** [comment]
👋 @czeslaw
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by will-at-stacks** [comment]
Hi @czeslaw -

Thanks very much for the thoughtful application.  While it is sBTC-related we are going to pass on this for now.  These sorts of experiments *may* start to receive consideration in Q3 of this year once protocol-level blockers are addressed.  However, the ecosystem already has marketplaces and we aim to limit funding any duplicate work via grants.  Please note that we will be posting several sBTC-related Critical Bounties in the coming weeks here.  Please keep your eyes peeled and submit an application to complete a bounty if any of them jump out at you.

Best,
Will
