### ISSUE TITLE
Pool Registry - Part 2

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#84]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Delegated Stacking is a way to participate in the PoX consensus algorithm with same amounts. Users need to be informed about existing pools and have ways to join the pools.

**Project Overview**
What solution are you providing? Who will it serve?

In the previous grant #52 , a smart contract and a basic UI has been provided. This grant application is about extending the UI for pool admins and users so that it can be used with the Stacks Wallet for Web (once it is released).

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The UI will be updated such that 
* pool admins can
    * edit pool data
    * see pool data verification errors before submission
* pool users can 
    * filter/group/search pools
    * see that pool data are verified by the web app maintainer
* the documentation is more accurate

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 500 USD

M1: Improve UI and documentation (1 week)

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Friedger Müffke

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

A different design could be more appealing, therefore, the work done on this UI could be replace by different pool registry UIs in the future.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

**Comment by RaffiSapire** [comment]
Hi @friedger, this grant is approved. Please email me at raffi@stacks.org and we'll get you a new contract.

**Comment by RaffiSapire** [comment]
Hi there, I don't believe I've received an email yet!

**Comment by friedger** [comment]
@RaffiSapire I sent an email 6 days ago.

**Update**
The source code has been updated and deployed to https://stacks-pool-registry.pages.dev/
The web site..
* let pool admins edit their pool data in the profile page with verification before submission. 
* let pool users search and filter pools and see whether the pool's website is built by the pool admin managing the pool data. The website needs to publish the pool admins BNS names as `author` in the `manfest.json`.
* shows better documentation about the fields required to enter by pool admins and users.

I have any issue with the traits api of stacks node, therefore pool contracts are currently verified on-chain whether they implement the pool trait or not.

Next is to get all public pools' data on-chain.

Future work to improve the design will probably be done as part of #88 .

**Comment by friedger** [comment]
> Next is to get all public pools' data on-chain.

I tried my best, pinging admins individually and on twitter. However, until now only Friedger Pool is registered. Spending more effort will go beyond this proposal. 

I'll keep promoting it but eventually, only integration in stacking club or the release of Stacking Wallet for Web will encourage pool admins to join the registry protocol.

In a way, the project was not successful because it was too early.
The source code is published on https://github.com/friedger/stacks-pool-registry and can be used on https://stacks-pool-registry.pages.dev/

**Comment by friedger** [comment]
Feedback so far from pool admins: 
* No time to add the pool data to the registry 
* No confidence in the Stacks Wallet for Web until officially released

I'll keep poking now and then until the start of cycle 9 and continue with other work meanwhile.

**Comment by friedger** [comment]
Xverse, planbetter and Friedger Pool have been registered in the registry. This complies M1

!m1_complete

**Comment by friedger** [comment]
!ma_complete

**Comment by friedger** [comment]
!m1_complete

**Comment by friedger** [comment]
!m1_complete
