### ISSUE TITLE
CB-23Q2-00.1 : sBTC Unwrapping Priority Preference (Research and Critical Bounty Development)

### ISSUE THREAD

**Issue by will-at-stacks** [stacksgov/Stacks-Grant-Launchpad#863]
### Discussed in https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/845

<div type='discussions-op-text'>

<sup>Originally posted by **will-at-stacks** March 17, 2023</sup>
### Introduction:
sBTC is a SIP-010 fungible token on the Stacks blockchain that can be used in DeFi protocols, NFT marketplaces, DAOs, governance, and several other use-cases. The sBTC Bridge is a trustless two-way mechanism that allows users to wrap and unwrap BTC as sBTC.

### Critical Bounty Mission Statement:
The purpose of this Critical Bounty is to explore the development of a mechanism whereby on wrapping BTC a user could indicate their unwrapping priority preference with the intention of mitigating risks associated with collateralization management for the sBTC threshold wallet.  Early discussions on this topic can be found [here](https://forum.stacks.org/t/making-sbtc-ready-for-defi-prime-time/14421) and have brought to light the following topics that need to be explored:
- Possibility of allowing participants to indicate something like a minimum collateralization ratio (CR). 
  - Those that have specified a lower minimum CR would have their peg-outs processed first. 
- The Critical Bounty recipient will be required to work with the sBTC Resident and the Go To Market Working Group to determine how to best incentivize those that indicate a lower liquidity preference as they are essentially performing the service of giving longer term stability to the peg.

### Functionality / Deliverables (shall include, but not be limited to):
- GitHub Repo or GitBook documenting research findings
- The expectation for this Critical Bounty is for the recipient to conduct research on this topic, review it with the advisors below, and produce a more fully scoped Critical Bounty request for proposals, including:
  - Mission Statement
  - Deliverables
  - Req'd Skills
  - References
  - Number of Developer Hours Req'd 

### Required Knowledge / Skills:
- Strong understanding of block production or mining fork rules in Stacks and Bitcoin.
- Familiarity with Bitcoin Script, Rust, Typescript
- Front end web development encouraged, but not req'd: sveltejs, typescript, fabric bootstrap, popper
- Strong documentation skills

### References:
1. [sBTC Whitepaper](https://stacks-network.github.io/stacks/sbtc.pdf)
2. [Stacks Nakamoto Release Whitepaper](https://uploads-ssl.webflow.com/618b0aafa4afde65f2fe38fe/6399d5ca541ccc6c51882bed_stacks.pdf)
3. [sBTC project dashboard](https://github.com/orgs/Trust-Machines/projects/5/views/10)
4. [Related GH Issue](https://github.com/Trust-Machines/core-eng/issues/111)
5. [Forum Post](https://forum.stacks.org/t/making-sbtc-ready-for-defi-prime-time/14421/20)

### Critical Bounty Fee:
- Maximum Fee: $4,000

### Reviewers / Advisors:
[Igor Sylvester](https://github.com/igorsyl), Core Engineering Lead, Trust Machines
[Tycho Onnasch](https://github.com/tycho1212), General Manager, Trust Machines
[stxnomnom](https://github.com/stxnomnom)
[Andre Serrano](https://github.com/andrerserrano), sBTC Resident and sBTC Go To Market Working Group Lead
[Will Corcoran](https://github.com/will-at-stacks), Grants Lead, Stacks Foundation

### Additional Comments:
Recipient will be expected to attend sBTC Core Engineering Working Group calls while the bounty is in development and provide weekly updates.

### **[APPLY HERE](https://stx.is/5kVQbn)**

----
NOTES ABOUT CRITICAL BOUNTIES:

If you have thoughts, questions, or comments on the rough outline for this Critical Bounty above, please comments below.  

Please note, all 2023 Q2 Critical Bounties  that have funding approved for them will be moved to the Issues page ([here](https://github.com/stacksgov/Stacks-Grant-Launchpad/issues?q=is%3Aopen+is%3Aissue+label%3A%22CRITICAL+BOUNTY%22)) on Tuesday 03/21/2023.

Some procedural items to keep in mind with 2023 Q2 Critical Bounties:

1. Each Critical Bounty will have a pre-approved minimum and maximum budget listed within the issue. 
2. All applications will be submitted via a BlockSurvey which will be linked within the Issue.
3. Applications will be open from 03/21/2023 to 04/03/2023.
4. Critical Bounty applications will be reviewed by relevant members of the sBTC Core Engineering Team and technical staff from the Stacks Foundation.  
5. The selected recipient will be the low, qualified bidder (in the eyes of the reviewers).
7. Selected Critical Bounty recipients will be announced on 04/07/2023 and will be expected to start work immediately and attend sBTC Core Engineering meetings to provide weekly updates on their work.</div>

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
