### ISSUE TITLE
CB-23Q2-00.2 : Ordinal and sOrd Research (Research and Critical Bounty Development)

### ISSUE THREAD

**Issue by will-at-stacks** [stacksgov/Stacks-Grant-Launchpad#864]
### Discussed in https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/850

<div type='discussions-op-text'>

<sup>Originally posted by **will-at-stacks** March 17, 2023</sup>
### Introduction:
Similar to how sBTC trustlessly converts BTC into a SIP-010 fungible token on the Stacks blockchain that can then interact with smart contracts, sOrdinals (or sOrds) has the potential to trustlessly convert Ordinals native to Bitcoin into SIP-009 non-fungible tokens on the Stacks blockchain. 

### Critical Bounty Mission Statement:
The purpose of this Critical Bounty is to research the most current developments in Ordinal Theory and highlight the following:
- What are the blockers to implementing sOrds as outlined in the [sBTC Mini Whitepaper](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#heading=h.u94dr92tpmoq)
- And more generally speaking, what infrastructural improvements need to be made to help harden Ordinals and provide them with more functionality.

### Functionality / Deliverables (shall include, but not be limited to):
- GitHub Repo or GitBook documenting research findings
- 3-4 scoped Critical Bounties that can address blockers identified by your research.  Critical Bounties RFPs consist of:
  - Introduction statement
  - Mission Statement
  - Functionality / Deliverables
  - Required Knowledge / Skills
  - References
  - Min and Max Number of Developer Hours Req'd
  - Suggested Reviewers / Advisors

### Required Knowledge / Skills:
- Experience working with Ordinals and PSBTs
- Experience working with Stacks transactions encouraged, but not req'd
- Strong documentation skills

### References:
1. [sBTC Whitepaper](https://stacks-network.github.io/stacks/sbtc.pdf)
2. [sBTC Mini Whitepaper](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#heading=h.u94dr92tpmoq)
3. [Ord](https://github.com/casey/ord)
4. [Ordinal Collection Standard](https://github.com/ordinals-wallet/ordinals-collections)

### Critical Bounty Fee:
- Maximum Fee: $4,000

### Reviewers / Advisors:
[Igor Sylvester](https://github.com/igorsyl), Core Engineering Lead, Trust Machines
[Trevor Owens](https://github.com/owenstrevor), Bitcoin Frontier Fund
[Andre Serrano](https://github.com/andrerserrano), sBTC Resident and sBTC Go To Market Working Group Lead
[Jesse Wiley](https://github.com/wileyj), Integration and Security Lead, Stacks Foundation
[Kenny Rogers](https://github.com/kenrogers), Developer Advocate, Stacks Foundation
[Will Corcoran](https://github.com/will-at-stacks), Grants Lead, Stacks Foundation

### Additional Comments:
Recipient will be expected to attend sBTC Core Engineering Working Group calls while the bounty is in development and provide weekly updates.

### **[APPLY HERE](https://stx.is/5kVQbn)**

----
NOTES ABOUT CRITICAL BOUNTIES:

If you have thoughts, questions, or comments on the rough outline for this Critical Bounty above, please comments below.  

Please note, all 2023 Q2 Critical Bounties  that have funding approved for them will be moved to the Issues page ([here](https://github.com/stacksgov/Stacks-Grant-Launchpad/issues?q=is%3Aopen+is%3Aissue+label%3A%22CRITICAL+BOUNTY%22)) on Tuesday 03/21/2023.

Some procedural items to keep in mind with 2023 Q2 Critical Bounties:

1. Each Critical Bounty will have a pre-approved minimum and maximum budget listed within the issue. 
2. All applications will be submitted via a BlockSurvey which will be linked within the Issue.
5. Applications will be open from 03/21/2023 to 04/03/2023.
6. Critical Bounty applications will be reviewed by relevant members of the sBTC Core Engineering Team and technical staff from the Stacks Foundation.  
7. The selected recipient will be the low, qualified bidder (in the eyes of the reviewers).
8. Selected Critical Bounty recipients will be announced on 04/07/2023 and will be expected to start work immediately and attend sBTC Core Engineering meetings to provide weekly updates on their work.</div>

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
