### ISSUE TITLE
CB-23Q2-00.3 : The Graph Integration w/ Stacks and Bitcoin (Research and Critical Bounty Development)

### ISSUE THREAD

**Issue by will-at-stacks** [stacksgov/Stacks-Grant-Launchpad#865]
### Discussed in https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/858

<div type='discussions-op-text'>

<sup>Originally posted by **will-at-stacks** March 17, 2023</sup>
### Introduction:
While sBTC is currently the mission-critical project within the Stacks ecosystem, it is important to also support the development of tools that make for a more enjoyable, productive, and contemporary developer experience on Stacks.  One such service that we have been told by our developer community to bring to Stacks is the indexing protocol, [The Graph](https://thegraph.com/en/).

### Critical Bounty Mission Statement:
The purpose of this Critical Bounty is to support research in and around the technical feasibility of integrating Stacks into The Graph's indexing protocol, the technical feasibility of integrating Bitcoin into The Graph's indexing protocol, and the developer appetite for these integrations.

### Functionality / Deliverables (shall include, but not be limited to):
- GitHub Repo or GitBook documenting research findings
- 1-4 scoped Critical Bounties that can advance your research into the implementation phase.  Critical Bounties RFPs consist of:
  - Introduction statement
  - Mission Statement
  - Functionality / Deliverables
  - Required Knowledge / Skills
  - References
  - Min and Max Number of Developer Hours Req'd
  - Suggested Reviewers / Advisors

### Required Knowledge / Skills:
- Knowledge of Stacks and Bitcoin blockchain architecture
- Knowledge of GoLang
- Preferably some knowledge of Rust
- Preferably some knowledge of Clarity / Clarinet
- Strong documentation skills

### References:
- [The Graph Docs](https://thegraph.com/docs/en/network/indexing/)
- [Firehose Acme](https://firehose.streamingfast.io/integrate-new-chains/firehose-starter)

### Critical Bounty Fee:
- Maximum Fee: $4,000

### Reviewers / Advisors:
[Igor Sylvester](https://github.com/igorsyl), Core Engineering Lead, Trust Machines
[Jesse Wiley](https://github.com/wileyj), Integration and Security Lead, Stacks Foundation
[Kenny Rogers](https://github.com/kenrogers), Developer Advocate, Stacks Foundation
[Will Corcoran](https://github.com/will-at-stacks), Grants Lead, Stacks Foundation

### Additional Comments:
Recipient will be expected to attend sBTC Core Engineering Working Group calls while the bounty is in development and provide weekly updates.

### **[APPLY HERE](https://stx.is/5kVQbn)**

----
NOTES ABOUT CRITICAL BOUNTIES:

If you have thoughts, questions, or comments on the rough outline for this Critical Bounty above, please comments below.  

Please note, all 2023 Q2 Critical Bounties  that have funding approved for them will be moved to the Issues page ([here](https://github.com/stacksgov/Stacks-Grant-Launchpad/issues?q=is%3Aopen+is%3Aissue+label%3A%22CRITICAL+BOUNTY%22)) on Tuesday 03/21/2023.

Some procedural items to keep in mind with 2023 Q2 Critical Bounties:

1. Each Critical Bounty will have a pre-approved minimum and maximum budget listed within the issue. 
2. All applications will be submitted via a BlockSurvey which will be linked within the Issue.
5. Applications will be open from 03/21/2023 to 04/03/2023.
6. Critical Bounty applications will be reviewed by relevant members of the sBTC Core Engineering Team and technical staff from the Stacks Foundation.  
7. The selected recipient will be the low, qualified bidder (in the eyes of the reviewers).
8. Selected Critical Bounty recipients will be announced on 04/07/2023 and will be expected to start work immediately and attend sBTC Core Engineering meetings to provide weekly updates on their work.</div>

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by ldiego08** [comment]
Hey @will-at-stacks,

I'm Luis from Zest Protocol. We have special interest in the outcome of this bounty as we're in need of a stable, battle-tested solution for indexing our contract events to power our frontend showing liquidity pool funding, loan requests and drawdowns, repayments, and others. We believe The Graph has tremendous potential for our use case. I mentioned this to @tycho1212 some time ago and we were pleasantly surprised to see this bounty posted here. With that said, I would like to volunteer as a reviewer, if possible, and help in whatever I can in this process. I have past experience working with The Graph in similar scenarios.

Best,
Luis

**Comment by palsev** [comment]
As a blockchain developer, I will complete your project perfectly. 
I have rich experience in Smart contract, Defi, Dex, Dapps solidity, rust, web3.js, ether.js, NFT(marketplace, minting, staking) and so on.
So I have enough skills and abilities to be responsible for your project.
You will get to know a talented and trustworthy developer by choosing me and I will be honored to satisfy you.
I'd like to discuss this with you asap.
Looking forward to hearing you.
Best Regard.

**Comment by will-at-stacks** [comment]
Hi @palsev - thanks for your interest in this project.  While the official application period has closed - we are still willing to fund this so as to get the work done.  If you are interested, please submit a formal application via the "Apply Here" link in the issue above.  Once you submit - please comment here so I am aware.
