### ISSUE TITLE
CB-00.5 : BNS Research and Critical Bounty Development (Request for Comment)

### ISSUE THREAD

**Issue by will-at-stacks** [stacksgov/Stacks-Grant-Launchpad#867]
### Discussed in https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/861

<div type='discussions-op-text'>

<sup>Originally posted by **will-at-stacks** March 21, 2023</sup>
### REQUEST FOR COMMENT
----

We would love your feedback on ideas for BNS-focused Critical Bounties.  If you would like to see a Critical Bounty funded please comment below and let us know why BNS is critical to the success of Stacks & Bitcoin-layers AND what specific bits of code, tooling, or research need to be funded.  Thank you!

----
</div>

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by igorsyl** [comment]
Got one idea for browser extension to allow for BNS to be used.

**Comment by will-at-stacks** [comment]
> Got one idea for browser extension to allow for BNS to be used.

This is an idea you had - or you received from someone?

**Comment by igorsyl** [comment]
I was registering BNS names over the weekend and was disappointed I couldn't use them in my browser. Does that count?

**Comment by empeje** [comment]
> I was registering BNS names over the weekend and was disappointed I couldn't use them in my browser. Does that count?

What you would imagine it will be? Does it something that is embedded in the Wallet like ETH with the ENS resolving the BNS? Would that be a scope of wallet app or any DApp that integrates with Stacks?
