### ISSUE TITLE
Risidio Exchange Grant Application

### ISSUE THREAD

**Issue by radicleart** [stacksgov/Stacks-Grant-Launchpad#87]
**Background**
For period: 29th March to the 17th May 

Ask: $19,844 USD (50% of total cost - see below)

**Preamble**

Risidio Exchange is a decentralised marketplace for NFTs and Digital Collectibles on the Stacks Blockchain. The first phase was completed in December 2020, creating a baseline of UI and Clarity functionality within a beautiful UI design.

Our first grant, delivered in December 2020 laid the foundations with the inception of our decentralised marketplace. Our second grant March covered some of the work we did subsequently over the beginning of 2021 where we developed and enhanced our Clarity layer with more robust and complete marketplace functionality, in particular, bidding. 

All this work has prepared us to meet the challenge of the recent surge of interest in NFTs and while delivering the second grant application we were approached to build a high end NFT application for artists and musicians - collaborating on innovations in this area. 

Our strategy of delivering the Risidio Exchange, “OpenSea on the Stacks Blockchain”, has proven a great foundation for meeting this challenge as we are already building in a modular and extensible manner.

The Risidio Exchange focuses primarily on the creative industries which have been so decimated by the pandemic but really opens the door to minting and creating digital property rights in general and for much wider classes of assets.

**New Clients**

This pitch is to support the work we have been doing over the period 1st April to the 15th May. In this time window we have been developing and extending the foundations of the decentralised marketplace we began with our first foundation grant last September.

This includes;

1. Developing our Clarity contracts, testing and extending the marketplace functionality
2. Developing client applications and concepts for minting NFTs
    - thisisnumberone.com - a site for high end artist collaborations
    - ruma.risidio.com - a universal minting application - able to mint and display gltf/glb, documents, images, audio and video files.
    - Start of Peoples Republic of Movies - NFTs in a 3D web context
3. Developing client relationships - e.g. with the thisisnumberone team, the Virtual Vinyl team and the PROM (Peoples Republic of Movies) team.
4. Developing and improving our marketplace, e.g. by;
    - building read only cache of contract data
    - building websocket API to this cache
    - building cache and Lucene search for Gaia data - asset meta data
    - Implementing SIP standards (nft-trait) in our main NFT contract

The continued support from the foundation will enable us to continue this work and go to market over the next 90 days with these exciting projects. 

What problems do you aim to solve?

**Proving the technology** - we intend to show how NFTs can be successfully managed on the Stacks network with all the inherent benefits this brings; low and predictable gas fees, Bitcoin level security, all the beneficial features of Clarity Smart Contracts

**Decentralising Gaia User Storage** - the Gaia project shows a possible path to the User Owned Internet. However that goal can only be realised by projects pushing the limits of Gaia, setting up new hubs and giving users choice and control over their own hubs. We intend to take a first step on this road by hosting a Gaia hub, contributing to decentralising the storage network and in so doing enable artists to upload larger audio visual files to Gaia than is currently permitted via the Hiro hub.

**Moving Beyond the Crypto Native Market** - by onboarding well known artists and providing highly scalable technological solutions (based on Gaia/Stacks) we will entice users from beyond the traditional crypto native space and open up the ideas to a much larger audience. We are tackling this particular problem through consistent story telling and building compelling case studies through which we are communicating the inherent social and economic benefits of blockchain technologies and Stacks in particular.

**Cost / Time of Getting to Market** - by providing modular tools and templated contracts we hope to significantly reduce the costs for other innovations in the NFT space to get to market quickly with their ideas.

**Environmental Issues** - There is no additional proof of work energy cost involved in minting NFTs on the Stacks network as we reuse the energy that has already been used to secure Bitcoin - in effect we are turning the ‘gold’, mined by the Bitcoin network into jewellery. To address the problem at a deeper level we believe we have a shared corporate social responsibility to offset any carbon released through industrial activity including Bitcoin mining, travel, use of video conferencing etc. For this reason we are working towards and introducing a levy on minting NFTs through our platforms that can be used to reduce the footprint through use of our solutions.

**Awareness** - we aim to increase awareness that Stacks is the future - especially in the field of NFTs and digital asset management by showcasing high profile artists, film makers and musicians on our NFT applications and platforms. We are furthermore building in a Charitable donation model into the royalties paid when NFTs change ownership. These royalties are baked into our contract templates.

How does it serve the mission of a user owned internet?

Our platform, tools and open source software are all fully decentralised, based on Stacks Blockchain for state and Gaia hubs for decentralised user data.

**Project Overview**

**NFTs on Stacks for Everyone**

Delivering tools and services to the Stacks community which allow anyone to get up and running with NFT applications at minimal cost. For example;

1. NFT minting contracts as templates
    * complex features such as buy now, bidding, make offer
    * plugin capability via javascript NPM modules
2. A platform (Risidio Exchange, similar to Open Sea) that provides a generic marketplace to all NFT projects on Stacks
3. Export this marketplace as an NPM module so other Stacks NFT can re-brand and present as their own marketplace (as opposed to forcing them to connect to Risidio Exchange)

We have two client applications currently (thisisnumberone.com and ruma.risidio.com) for whom we are proving these concepts and scheduled to go live early May.

**And the Creative Industries**

One of the problems that particularly struck us has been the precarious condition in which artists – of all kinds - find themselves, clearly exacerbated by the pandemic and the terrible state of the market over the past year. We firmly believe that although this problem is a huge issue, it represents an opportunity for our project and the wider community, because of the possible solutions we are able to offer.

Our objective is not only to attract artists who are curious about experimenting with new technologies, but to offer something that has the maturity to solve the problems that this troubled category is suffering without a tangible way out. We want to offer a solid way to reduce the time and cost of getting to market for artists. By providing modular tools and templated contracts, we hope to significantly reduce the costs for other innovations in the NFT space to get from idea to market as quickly as possible.

Building on this system, and creating assets based on it, is the first step to helping to promote and monetise their products, using their own information/art/creativity, owned by them.

In addition to that, we believe that the Gaia project shows a possible path to the user-owned Internet. However, we believe that goal can only be realised by projects pushing the limits of Gaia, setting up new hubs and giving users choice and control over their own hubs. We intend to take a first step on this road by hosting a Gaia hub, contributing to decentralising the storage network and in so doing enable artists to upload larger audio-visual files to Gaia than is currently permitted via the Hiro hub.

Furthermore, we are building in a charitable donation model into the royalties paid when NFTs change ownership. These royalties are baked into our contract templates.

**Scope**

Our main reference is a Product Requirements Document (PRD) which describes our project at the level of epics and features. These larger pieces are broken down into user stories as they enter the backlog where they are prioritised for the upcoming sprint.

The scope in this context is tightly focused on the next timebox / milestone that goes towards delivering the platform as a whole.

This timebox is organised around the delivery of the following features which will culminate in the development of applications to mint NFTs:

April:

- Buy now and transfer - implementation of the SIP 009 nft-trait 
- Make offers in contract, displaying offers, accepting offers
- Development of bidding feature
- Minting audio-visual files
- Mint multiple editions
- Display NFT ownership history
- Payment splitting via royalties
- Stacks wallet integration
- Mint 3D assets
- Client application wire framing and design
- Client application implementation of design

May:

- Minting all file types (including 3D assets gltf/glb)
- Testing bidding on items
- Gaia hub setup - (freeing us from the Hiro hub limit and decentralising Gaia hub)
- This is #1 Launch
- RUMA (Risidio - Universal Minting App)
- Marketplace development
- Client application wire framing and design
- Client application implementation of design

**Budget and Milestones**

Epic | User Story | Costs (days) | Release Date
-- | -- | -- | --
Milestone 1: thisisnumberone.com
  | Wire framing & Design | 15 |  
  | DevelopmentImplement Design (5)Contract Minting (6)Contract - Offers (4)Contract Caching (4)Gallery Page (5)Upload Multi-Media ‘Artwork’ Files (6) | 30 |  
  | Testing | 15 |  
Launch |   |   | May 3
Milestone 2: ruma.risidio.com
  | Wire framing & Design | 2 |  
  | DevelopmentImplement DesignContract MintingMarketplace IntegrationManaging general asset types | 10 |  
  | Testing | 5 |  
Launch |   |   | May 6
Milestone 3: Inception Work for Peoples Republic of Movies
  | 3D Modelling | 5 |  
In Progress |   |   | May 15
 | | |
Total Cost (Days): | | | 82
Total Cost (USD) | | | $39,688
Foundation Contribution | | | $19,844

**Team**

The team we are building, with support from the Foundation, will have people from the development, research and marketing teams with a project management coordination involved.

We believe that everyone in the team brings a range of experiences and views and anyone can contribute to the success of the project. Although we present a formal dev team organisational structure the reality will be a good deal of overlap between different roles within an open friendly decentralised and essentially collaborative development environment, reflecting the overall values of Risidio.

The Risidio team is currently supporting all the work necessary to deliver a project of this complexity and scale. 

Our CEO, Peter, leads our client relationship management development and market research activities. Mike looks after the strategic technical direction and also acts as lead developer. Michele handles communications and project management issues.

In addition to our core team, Sara leads on Creative issues, managing our brand and UI/UX. She is supported by Celine our junior UX/UI designer. Thomas and Valentin are delivering value in areas across UI development and Clarity integration testing. Jamel is developing 3D assets and 3D worlds - preparing the way for our movie/NFT project - coming soon. 

Coudy has been working to build our corporate social responsibility (charity and sustainability) strategy and implementation. Irina has been heading up all our market research activities in support of the project. 

Caitlin and Sihame have been working to manage client relationships, story telling and developing content and messaging.

We are building on this base with Duncan joining the team to give us a massive boost across devops and testing capabilities and Andrei who will help manage the backlog and help deliver the user stories. 

We are looking to further enhance our development team with an additional experienced UI/UX designer, a UI developer, test engineer and a smart contract developer. In addition we’d like to hire a dedicated product owner to help manage the backlog and prioritise the work going forward. 

**Risks**

In relation to the project, the risks identified upstream are categorised into 6 categories (Technical, Economic, Commercial, Organisational, Regulatory and Operational) which will be maintained in the classification maintained during the control, identification, monitoring and mitigation of the risks.

The risk management process may be activated by any member of the team after a preliminary impact and proximity assessment via a defined process.

**Community and Supporting Materials**

During the previous phases we always tried to work and involve the community in what we were developing and the growing interest and help towards our work makes us even more motivated to seek contact with other members.

We are increasingly convinced that what we are doing is of benefit to the whole Stacks ecosystem and we therefore feel it is essential to be actively and proactively involved over the coming weeks.

The opening of a dedicated #risidio channel in Discord also makes communication faster, more open and more transparent and we plan with our team using this opportunity extensively to gather feedback and engagement.

We intend to share our progress through this channel, but above all we want to invite anyone who wants to actively contribute to the project as much as possible.

- We also intend to share our progress through:
- End of Sprint Timebox - open community invitation
- Attending Foundation events, Town halls and community meetups in Discord
- Involving the community directly in the testing of milestones
- Posts and “Invite to Collaborate” on the Risidio team Discord channel

The Risidio team is open to anyone who wants to collaborate and so we will help share information about the project, requesting help in areas where specific skills can help increase the success rate.

Over the past 9 months we have worked and learned with over 50 people from over 15 countries, across many time zones. Our guiding vision has been the idea that Bitcoin technologies hold the key to unlocking a fairer and safer Internet for everyone. Hardly any of our team knew anything about the crypto space when they joined but that soon changed as they became inspired by the social revolution that is happening, quietly, away from the hype and headlines, through the efforts of companies like Risidio and many more. We are currently a diverse, cross-cultural team comprising 24 people, covering expertise from 3D web design to financial analysis and from Clarity smart contract development to managing social media campaigns. And we’re only just getting started!

**References**

[Thisis#1 Project Overview](https://drive.google.com/file/d/1DrgeiDFYfrg3U_VXR8tU1Z61cWSaKL_8/view?usp=sharing)

[Risidio Development Roadmap](https://drive.google.com/file/d/14kS7ju-tgjm7qxi2G0_Ga0SRpS7pG7HJ/view?usp=sharing)

[Corporate Social Responsibility](https://drive.google.com/file/d/1icKuvjC5WQ7f0aPxZGju6Fq6Cxms2N_P/view?usp=sharing)

[Risidio PR Strategy](https://drive.google.com/file/d/10si_sOA5Vh2j8B6zjdwnqBeoGWzGlt5I/view?usp=sharing)

**Comment by RaffiSapire** [comment]
Hi there, this is approved, we're excited to see this through!

**Comment by MickM21** [comment]
!m1_complete

**Comment by MickM21** [comment]
We are very happy to report that the first milestone has been successfully completed.

In particular, as announced through the various community channels, on Thursday 13th May we officially launched the application [This is #1](https://thisisnumberone.com/), through press releases from various online publications and social media.

Yesterday, Monday 18th May, we started the auction of the first NFT (created by Chemical X) which will be followed by the auction of the remaining 4 according to the schedule on the website. Obviously, we will continue to update the community on events in real time through our Discord channel.

As for RUMA, we are in the process of finalising the design ([Wireframe Preview](https://xd.adobe.com/view/9f3718f5-67d7-4928-b93e-5461efc72000-ca64/#access_token=eyJhbGciOiJSUzI1NiIsIng1dSI6Imltc19uYTEta2V5LTEuY2VyIn0.eyJpZCI6IjE2MjE0MTI0MTEzNTlfNGQ1ZDVjMDItNDkxOC00YzkwLTkyYzktYjNjMWNjMjhlNjk1X2V3MSIsImNsaWVudF9pZCI6IkNvbWV0V2ViMSIsInVzZXJfaWQiOiIzNDVGQjAwODU2MEE1RDZEN0YwMDAxMDFAQWRvYmVJRCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcyI6Imltcy1uYTEiLCJhYV9pZCI6IjM0NUZCMDA4NTYwQTVENkQ3RjAwMDEwMUBBZG9iZUlEIiwiZmciOiJWT0xUNFlUR1ZMUDU1SFVDQ01aTFJIUUFaWT09PT09PSIsInNpZCI6IjE2MTM4MzY5NjcwNDdfZTYxY2Q5YzktOWQ5YS00ZTBkLTk5ZGEtZDViYzU3YmRmNzg1X3VlMSIsIm1vaSI6IjhmMDg4NmNlIiwiZXhwaXJlc19pbiI6Ijg2NDAwMDAwIiwic2NvcGUiOiIiLCJjcmVhdGVkX2F0IjoiMTYyMTQxMjQxMTM1OSJ9.d17ougvZOlVlJNNnaWP05SfZ7jgerstrydNIv8htrCM20yDQwfbPvkl_7N_UF8_zUMEePhIiPWR_FiwOi5Ga3dj1aCAYwHLKFCKW4nEHs7DsrXYCdvq4ZGAxVAwD3N95QRQPA0Zn5zrG1O97gg4iBFyHCRuSFK77BzUnze2fbvEuI2le9iwGmVG6cBMEb8AOYuYvx9xE5m088kikD09fQVTeF86kxhwKyBfNefBb6VIRGKJSU6-JvB5cpPQLuMjrY8IxgU9kDGPIC5Y-sk70PZv3U-SDqT2GzyhzLof0lkxo8-qN8nTCj1cfemQ4-l-QH3ZUzeHSfwecIXNtMRfoDw&token_type=bearer&expires_in=86399982)) in parallel with the completion of the development phase, with the aim of launching it by the end of June. 

Similarly, our design team has finalised the inception phase for PROM of the 3D assets that will be the starting point for building a 3D crowdfunding platform for film makers.

I take this opportunity to thank everyone for your support and we look forward to continuing this journey together. 

Michele, CPO - Risidio

**Comment by MickM21** [comment]
!m1_complete

**Comment by MickM21** [comment]
We are very happy to report that the first milestone has been successfully completed.

In particular, as announced through the various community channels, on Thursday 13th May we officially launched the application [This is #1](https://thisisnumberone.com/), through press releases from various online publications and social media.

Yesterday, Monday 18th May, we started the auction of the first NFT (created by Chemical X) which will be followed by the auction of the remaining 4 according to the schedule on the website. Obviously, we will continue to update the community on events in real time through our Discord channel.

As for RUMA, we are in the process of finalising the design ([Wireframe Preview](https://xd.adobe.com/view/9f3718f5-67d7-4928-b93e-5461efc72000-ca64/#access_token=eyJhbGciOiJSUzI1NiIsIng1dSI6Imltc19uYTEta2V5LTEuY2VyIn0.eyJpZCI6IjE2MjE0MTI0MTEzNTlfNGQ1ZDVjMDItNDkxOC00YzkwLTkyYzktYjNjMWNjMjhlNjk1X2V3MSIsImNsaWVudF9pZCI6IkNvbWV0V2ViMSIsInVzZXJfaWQiOiIzNDVGQjAwODU2MEE1RDZEN0YwMDAxMDFAQWRvYmVJRCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcyI6Imltcy1uYTEiLCJhYV9pZCI6IjM0NUZCMDA4NTYwQTVENkQ3RjAwMDEwMUBBZG9iZUlEIiwiZmciOiJWT0xUNFlUR1ZMUDU1SFVDQ01aTFJIUUFaWT09PT09PSIsInNpZCI6IjE2MTM4MzY5NjcwNDdfZTYxY2Q5YzktOWQ5YS00ZTBkLTk5ZGEtZDViYzU3YmRmNzg1X3VlMSIsIm1vaSI6IjhmMDg4NmNlIiwiZXhwaXJlc19pbiI6Ijg2NDAwMDAwIiwic2NvcGUiOiIiLCJjcmVhdGVkX2F0IjoiMTYyMTQxMjQxMTM1OSJ9.d17ougvZOlVlJNNnaWP05SfZ7jgerstrydNIv8htrCM20yDQwfbPvkl_7N_UF8_zUMEePhIiPWR_FiwOi5Ga3dj1aCAYwHLKFCKW4nEHs7DsrXYCdvq4ZGAxVAwD3N95QRQPA0Zn5zrG1O97gg4iBFyHCRuSFK77BzUnze2fbvEuI2le9iwGmVG6cBMEb8AOYuYvx9xE5m088kikD09fQVTeF86kxhwKyBfNefBb6VIRGKJSU6-JvB5cpPQLuMjrY8IxgU9kDGPIC5Y-sk70PZv3U-SDqT2GzyhzLof0lkxo8-qN8nTCj1cfemQ4-l-QH3ZUzeHSfwecIXNtMRfoDw&token_type=bearer&expires_in=86399982)) in parallel with the completion of the development phase, with the aim of launching it by the end of June. 

Similarly, our design team has finalised the inception phase for PROM of the 3D assets that will be the starting point for building a 3D crowdfunding platform for film makers.

I take this opportunity to thank everyone for your support and we look forward to continuing this journey together. 

Michele, CPO - Risidio

**Comment by RaffiSapire** [comment]
Thats great, @radicleart!  Is this is complete?

**Comment by radicleart** [comment]
Hi @RaffiSapire, yes this is now complete.

**Comment by harounkola** [comment]
Exciting. Looking forward to working together and also getting a similar grant.

**Comment by radicleart** [comment]
Hi M1  is complete for this! !m1_complete

**Comment by jhammond2012** [comment]
Hi @radicleart can you please comment the m1 complete again?

**Comment by radicleart** [comment]
!m1_complete

**Comment by radicleart** [comment]
!m2_complete

**Comment by radicleart** [comment]
!m3_complete

**Comment by radicleart** [comment]
@RaffiSapire just for completeness the services described in milestones 2 and 3 can be seen on our staging servers...
 - https://ruma.risidio.com/
 - https://prom.risidio.com/

I am currently working on the Stacks Mate grant and will post progress on that grant very soon.

**Comment by RaffiSapire** [comment]
Congratulations on completing this! Would love for you to present at the next demo day if you're up for it.
