### ISSUE TITLE
stacking.club

### ISSUE THREAD

**Issue by aulneau** [stacksgov/Stacks-Grant-Launchpad#88]
**Background**

Greetings everyone!

I run [stacking.club](https://stacking.club), it’s a project I have had a lot of fun building, and am really excited for its potential. For those who don’t know, stacking.club is home to the most up-to-date and detailed data around Stacking, including data for individual stackers and pools. Since the launch on Feb 19, 2021 the site has received at least ~28k unique visitors, with more than ~110k total views. 

This is a grant request for funds to continue the work I have done thus far on stacking.club. The funds will be directed towards costs for hosting and maintaining the site, in addition to my time on building out new features.

Grant amount requested: **$15k USD**

### Project Overview
Currently the primary features on stacking.club are focused around exposing data and metrics around BTC rewards for a given PoX reward address, and mostly focused around stacking transactions for either a pool operator or stackers that have locked enough stacks to become eligible for a reward slot. 

**Pool explorer**
I’d like to take the next phase of work on stacking.club and dedicate my energy to making the pooling data more of a first class citizen. I think there is a lot of potential around making stacking.club act as a kind of pool explorer. The ways in which this might be exposed can be:

- Meta data for pools, such as:
    - Human readable names
    - BNS connections
    - Descriptions
    - External links
- Compare and contrast pools and their use and pros/cons
- More interactive experience around pooling and historical rewards
- Potentially expose non-standard rewards data
    - such as if a pool uses a contract to dispense STX rewards

**Stacking.club as a Stacks app**
Currently, stacking.club is a static web app that simply displays and transforms data for the end user. I think there is a huge positive potential in transforming it to be a stacks app that gives the user an ability to interface more deeply with their stacking related data. Some features I have in mind:

- Stacking.club will become a Stacks app + connect to the Stacks Wallet for Web
- It will use Gaia to enable user-owned data
- Track your own addresses
- Track/favorite other addresses
- Notifications on activity related to your address(es) (privacy focused, needs more research)
- Detailed data for addresses that are pool operators
- Potentially enabling an easier experience for pool operators
- Stacking and pooling directly from within stacking.club

**Improved education**
More educational information around stacking and how to participate:

- Improve the `/learn` page to include a guide, FAQs, and examples
- Link to Hiro resources/guides/faqs
- Add a stacking calculator to see potential rewards based on real, historical data

**Improved API and performance**
The API that I have created which powers the frontend is something that I think can be of use in other ways. Some work I have planned for it:

- I have a [PR open](https://github.com/DefiLlama/DefiLlama-Adapters/pull/112) to add PoX related data to DeFi llama, which will rely on a new Total Value Locked (TVL) endpoint
- Improve performance and reliability
- Potentially open-sourcing or exposing the API for anyone to use
- Potentially Interface with the oracle contracts that pascal has created (make reward data available to contracts)

### Milestones
**M1: More detailed pooling data**
- Users can view pools
- Pools contain more detailed data , such as:
    - Human readable names
    - BNS connections
    - Descriptions
    - External links
- View historical pool data and participation

**M2: Stacks app**
- Users can sign into stacking.club 
- Users can save and track various addresses
- Pool operators can administer their delegates via CRM like functionality

**M3: Misc**
- Updated educational resources
- Stacking calculator
- Improved performance (for api and frontend)
- at least 1 external party will make use of API

### Timeline
I am a full-time employee at Hiro, and as such that is always my priority. I do spend a good amount of time outside of those responsibilities working on and improving stacking.club. I would assume that the buckets above will take a few months in total to complete given the time I have available.

### Cost breakdown
If it works within the context of the grant program, I’d love for $10k upfront and then check in sometime in the next 4-6 weeks for the remainder of the grant. 

Thank you for considering my grant request, please let me know if there are any questions or concerns I can answer.

--- 

**_Future grant: Localization_**
The buckets of features above will likely change the UX and UI of the website a good amount, and once that has stabilized, I’d like to localize the application. After the US, South Korea and countries in Europe are the highest sources of traffic. I think for the first round of internationalization work would include:

- Korean
- Turkish
- Chinese

I’d likely submit a separate grant to fund work on my end and any external contractors that might need to be hired for language services.

**Comment by cuevasm** [comment]
I'm so excited about the future of stacking.club. It's already my favorite website so its exciting to peek ahead at what's next 🚀

**Comment by friedger** [comment]
I support this proposal and I can also see that the [stacking pool registry](https://stacks-pool-registry.pages.dev) will become a part of stacking.club.

**Comment by RaffiSapire** [comment]
Hi there @aulneau this should be broken down into clear milestones, based on features and techincal milestones. Our team will review each milestone to determine whether it is "complete" so subjectivity here is not an issue. Please take a go at that.

**Comment by aulneau** [comment]
> Hi there @aulneau this should be broken down into clear milestones, based on features and techincal milestones. Our team will review each milestone to determine whether it is "complete" so subjectivity here is not an issue. Please take a go at that.

Sure. I've updated the original post to reflect the milestone based system that you require. The work will not happen in this kind of linear manner, however.

**Comment by tycho1212** [comment]
Really cool stuff! The design is 🔥

Minor contribution for the future grant: 
- For the languages I'd suggest dropping Dutch, I live in the Netherlands and it has a [higher English speaking rate than Canada](https://www.reddit.com/r/todayilearned/comments/59tubr/til_a_greater_percentage_of_dutch_people_speak/). German is also not super necessary as the English speaking rate [is also high](https://www.ef.co.uk/epi/), especially among Stacks target audience. I'd have a look at Turkish as there's quite a big Stacks community there that's quite active in their native language!

PS: [Localise](https://lokalise.com/) makes localisation a breeze

**Comment by aulneau** [comment]
> * For the languages I'd suggest dropping Dutch, I live in the Netherlands and it has a [higher English speaking rate than Canada](https://www.reddit.com/r/todayilearned/comments/59tubr/til_a_greater_percentage_of_dutch_people_speak/). German is also not super necessary as the English speaking rate [is also high](https://www.ef.co.uk/epi/), especially among Stacks target audience. I'd have a look at Turkish as there's quite a big Stacks community there that's quite active in their native language!
> 
> PS: [Localise](https://lokalise.com/) makes localisation a breeze

Thank you!!

Yeah, I was thinking that too :) was mostly just throwing out the most visited countries. I think a better revised list to start will be
- Korean
- Turkish
- Chinese

**Comment by 0xngmi** [comment]
I work on DefiLlama and I must say that @aulneau has been very responsive during the listing process, I'd support this grant.

**Comment by RaffiSapire** [comment]
Hi @aulneau , this is approved. If you want to keep as is, we're happy to approve for $11k, $5k for M1, $1k for M2, and $5k for M3. To get this to a $15k grant, we'd love to beef up M2. Here's our suggestion:

M2: admin panel for pool operators. give a way to help pool operators coordinate or list thier users is more CRM like work that is useful. Becomes an onramp for starting a pool. 

Let us know what you think?

**Comment by aulneau** [comment]
> Hi @aulneau , this is approved. If you want to keep as is, we're happy to approve for $11k, $5k for M1, $1k for M2, and $5k for M3. To get this to a $15k grant, we'd love to beef up M2. Here's our suggestion:
> 
> M2: admin panel for pool operators. give a way to help pool operators coordinate or list thier users is more CRM like work that is useful. Becomes an onramp for starting a pool.
> 
> Let us know what you think?

Yay! That sounds good to me, it's something I had planned for, I updated the original M2 to reflect this functionality :)

**Comment by RaffiSapire** [comment]
Please email raffi@stacks.org and i'll get you set up.

**Comment by RaffiSapire** [comment]
Hi @aulneau wanted to check in here and see if you had any updates on M2? Thanks!

**Comment by aulneau** [comment]
> Hi @aulneau wanted to check in here and see if you had any updates on M2? Thanks!

Hi @RaffiSapire ! thanks for checking in -- still hard at work at various elements of each milestone -- they are happening kind of in tandem as they are pretty interrelated. I'm looking to have a beta version out within the next few weeks that includes functionality for pool operators and stackers alike to be able to sign in and get a richer experience, with the possibility of facilitating a few different pool operations, such as payouts etc :)

Will update soon with more details!

**Comment by aulneau** [comment]
> Hey Thomas! Checking in to see if you've got any updates to share. Let us know if you need any further support :).

Hey Jenny! Thanks for checking in -- just wanted to reply to let you know I'll update this thread a bit later this week with progress!

**Comment by jennymith** [comment]
Hey @aulneau, I know that the scope of this grant will be changing now that you're a Resident 🥳. Can you share an update on how you plan to proceed with this work? Will the remainder of milestones be absorbed by your residence work? (In which case, should we close this grant?)

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
