### ISSUE TITLE
jhjh

### ISSUE THREAD

**Issue by ILMpk** [stacksgov/Stacks-Grant-Launchpad#882]

**Comment by stacks-foundation** [comment]
👋 @ILMpk
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by ILMpk** [comment]
o
