### ISSUE TITLE
Smartists - Private Art Studios on the Internet of Value. 

### ISSUE THREAD

**Issue by SmartMirlo** [stacksgov/Stacks-Grant-Launchpad#9]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> **What problems do you aim to solve?** 

Artists and authors who work professionally in the physical world, and own digital files, need to take control of the digital copies they upload to the Internet. They are the owners of such contents although it is very difficult for them to get recognition for the value they bring to the web. So far they still depend on platforms, and it’s time for them to reach independence and open their own studios on the web 3. 

Just before COVID-19, we launched a survey among different kind of artists who told us about their essential problems on the web 2: Lack of privacy, impossibility of selling their art directly, and also the need to build more meaningful communities of followers genuinely interested in their work to make business and exchange valuable experiences [see supporting materials].
Since COVID-19, artists have seen their jobs in the physical world disappear and they need to turn to digital solutions for survival. So many are starting considering using the web, now looking for incomes and not just for promotion. 

Users who own digital valuable contents and users interested in them deserve the chance to connect and exchange value directly in their own terms, as they do in the physical world. Smartists, powered by Blockstack, brings them a solution including legal protection.

> **How does it serve the mission of a user owned internet?**

Smartists can be an understandable example of what a user-owned Internet means for end-users. This DApp is  an opportunity to show how contents in the Internet can be owned by users, showing many users who are content creators the way to the web3.
Being a DApp for end-users, Smartists will also provide visibility to what is possible in terms of privacy and property rights with the BlockstackID, storage and Clarity smart contracts.

## Project Overview

> **What solution are you providing?** 

Smartists is a Decentralized App for artists/authors to make their art works and art work projects available on the Internet in their own terms, as they do in the physical world from their private studios. With this blockchain based solution, powered by Blockstack, we aim to serve artists so they can connect and make transactions directly with their art-users and their colleagues, on the Internet of Value. 

![Smartists](https://user-images.githubusercontent.com/44160828/92375965-25862b80-f102-11ea-95a7-419332711771.jpg)

Smartists is being designed to provide the 3 essential services to self-managed artists: 
A) a networking community for art professionals identifiable with their Blockstack ID; 
B) private studios for project collaboration and on demand art services using Gaia storage; 
C) P2P marketplace using Clarity smart contracts for private sales. 

Moreover, Smartists shall include legal support for confidentiality within the Smartists’ studios, as well as a set of Smart Licenses for artists’ to choose when selling their digital copies.

> **Who will it serve?**

We address authors who want to manage and market the digital files of their artworks as creative assets on the web in their own terms. We are considering:
	Self-managed writers
 	Self-managed visual artists 
	Self-managed musicians
	Self-managed performers
	Self-managed digital editors. 
We like to call these artists “smartists” because they are self-managed and they are open to use smart-contracts to make business with their art works on the Internet of Value.   

We also address artwork-users on the Internet who look for original art works, and want to connect directly with authors/artists. We are considering:
	Private users - art lovers, collectors, etc.
	Independent Professionals - educators, healthcare providers, etc. 
	Business Professionals working in  the Culture and Entertainment Industry - producers, marketers, publishers, collectors, artists managers, etc.
We like to call these users “Creative-users”.

## Scope

> **What are the components or technical specs of the project?** 

Blockstack auth + Blockstack Storage + Firebase + Angular/React UI" In the future, we are even thinking of integrating Clarity contracts with Stacks token as a payment option. 
Note: These are the initial specs and will be upgraded as we progress. 

Moreover, we have designed a legal framework for Self-managed Artists and Art-users to be able to make their private, secure, and profitable deals legally supported. In our “International Smart Licensing Agreements” [ I. S. L. A.] we include general terms applicable to any deal, and some special terms and conditions to be defined for every case by the parties. This legal framework is designed to be easy, fast, and practical to navigate. 

>**What will the final deliverable look like?** 

UX - When entering Smartists, Self-managed artist as well as Art-users with a Blockstack ID will access:

A PROFESSIONAL NETWORK TO CONNECT . Visitors can browse the members list but they can only start connecting after introducing themselves as artists or art users, setting them as members of the community and signing the Confidentiality Agreement. The basic information provided when introducing themselves is only visible by community members, and we warn users that they can always update it with their Blockstack ID… This is how we ensure a members’ list of identifiable Self-managed artists and art-users who are responsible for any future agreement or deal. In such list, visitors will easily find artists from different fields who are ready to work on demand, and/or make deals. They will be able to connect with them as soon as they set themselves as members of Smartists. 

A PRIVATE STUDIO TO REACH AGREEMENTS & MAKE DEALS .  Artists can open a private ‘studio’ once they are members. Then, they can find colleagues from different fields to collaborate in their projects, as well as  offer their services for on demand art works. Private sales of licensed digital copies can also take place in the studio. The usual activities artists can do in their real studios is what we want to bring to the digital world. This explains why we are committed to support them legally. 
In Smartists Online Private Studios, Privacy and Intellectual Property protection are enabled by Blockstack technology, while being legally supported by the terms agreed.

A GALLERY . A common space for community members to showcase and sell their art digital files, as well as a space to help grow the Smartists network.

PRICING - Browsing Smartists as a visitor is free with your Blockstack ID, but if you want to connect you need to become a member, which is also free (but we could introduce a PoHodl in the future). To open a Smartists studio and getting the different services as well as the legal support, artists will pay a fee in STX. We are considering incentives for “Smartists pioneers” and referrals. Including a wallet is something we need to consider sooner than later. 

We have a first prototype that we have been improving with the feedback of four testers. We want to include (A) and (B) in the first mvp, and (C) should come in v2.

> **How will you measure success?**

We are considering ACTIVE USERS as the primary metric, defined in three categories:
· Visitors (all need a Blockstack ID) 
· Community Members (introducing themselves on ‘settings’ & signing the Confidentiality Agreement) 
· Artist opening their studios (completing settings)

A secondary parametric can be the number of links to Smartists on websites, which we could somehow promote.

At this moment, we humbly think that having 100 potential users at the time of mvp launch could be good enough. We leave REVENUE parametric for a much more advanced stage. Before launching, we will also need to set our weekly growth rate goals, and start tracking our progress.

## Budget and Milestones

> **What grant amount are you seeking?** 

So far, the Smartists team members have been working out of our passion for the project. Now, we need to get Smartists to the next level (MVP) and start onboarding our first users while we look for funding in order to grow.. 

$800 Improved UI mock-up and new testing for feedback. 

> **How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.**

35 hours - 3 weeks

10 hours -> Improved UI mock-up 
10 hours -> materials for testing (video, surveys...) + testers
10 hours -> testing (face to face and remote)
5 hours -> analysis and report for improvements to get ready for mvp.

## Team

> **Who is building this? What relevant experience do you bring to this project?** 

**Georgina G.-Mauriño** is the founder and designer. As a senior author, illustrator and digital content creator she is going to be the first user, along with some colleagues of hers. Moreover she has a background in Law studies and brings her experiences in self-managing her intellectual property rights. Georgina is an enthusiast of blockchain technology since 2016 and a Blockstack evangelist since July 2019. 
[LinkedIn profile](https://www.linkedin.com/in/georginagarciamaurino/). 

**Isabel Yagüe Ballester** is our legal advisor. She has helped design, and improve the legal services we offer within the DApp. She is a specialist in compliance, with experience advising in national and international negotiations, transactions, contracts and dispute settlement procedures in different areas including IT & Telecommunications Law, Data Protection, etc.
[LinkedIn profile](https://www.linkedin.com/in/isabelyagueballester/).

**Harini Rajan** is our technical advisor. She has been following and supporting Georgina’s ideation and prototyping process.

> **Are there skills sets you are missing that you are seeking from the community?**

WE ARE LOOKING FOR A DEVELOPING PARTNER!

We are in the process of building a team which can help succeed and grow Smartists. Technical experience as well as business experience are the two skills we are looking for at this moment. Actually, we are looking for an experienced technical partner from Blockstack. to build a strong and more balanced team. Any help to find a good candidate would be welcome.

## Risks

> **What dependencies or obstacles do you anticipate? What contingency plans do you have in place?**

From the technical point of view, we don’t see too many risks at the present stage. Future implementations may come with challenges.

From the business point of view, adoption is our main concern, as we want to make a successful DApp. We know that there is still a lot of work to do in terms of final users’ awareness and education. Nevertheless, we are already building a small community of testers and potential users who might come in handy as examples in the future. We only wonder, how long could this take? Will all the team members be patient enough to keep actively involved? 

For this reason, I am taking action myself, as an author. This 2020-21 course, I intend to build a simple website on the web3 (using Runkod hosting), as well as sharing with my audience my experience as an author embracing web3 with Blockstack DApps. While I set this example, I hope to link that website to my private “Smartists studio” at some point. I think that presenting use cases might be a straightforward way to communicate the final deliverable to potential users, and using Blockstack dapps I also hope to reach at the Blockstack community.

## Community and Supporting Materials

> **Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?**

I, the founder, am not a technical person and I cannot bring here any code commits or previous projects in the ecosystem apart from my initiatives as a Blockstack evangelist. 
Instead, I bring a lot user-experience relevant to this application, as an author and a Blockstacker. 
The design of Smartists is a mission driven journey including: 
- Research, courses and readings, mainly about blockchain technology, Intellectual Property and Licensing.
- Private surveys (using BlockSurvey). See first report: https://app.sigle.io/smartmirlo.id.blockstack/cE2iXWS4wAw3yKKXRQSzA

In the Blockstack community a few members know about Smartists. **Harini Rajan** has been providing invaluable guidance during all the process of shaping the original idea and prototyping. **Louise Ivan** knows about my mission since I joined the community in July 2019 and has been also a great support, including this wonderful heads up in Twitter:  https://twitter.com/blockstackrs/status/1291122933738491904, and his recommendation to join the KERNEL program, a useful learning experience. **Wilson Bright** also provided some good advice. Moreover, I have contacted some founders of DApps in the ecosystem which could collaborate with us providing complementary services. Greg Hart from **Proof of Existence** answered very positively. At this moment, I am considering sharing my plan in the **Business Model Working Group**, where I have been learning a lot in the past months. For Smartists different possibilities are open, especially in terms of incentive mechanisms for adoption and onboarding. I think that sharing my plan there may provide the chance for listening to new ideas and make improvements. On the Discord channel, I have just started sharing a little about Smartists... 
https://discordapp.com/channels/621759717756370964/662205407908855808/728273962450157699
https://discordapp.com/channels/621759717756370964/676458476527943709/738327193909985371

Beyond the Blockstack community, I am bringing awareness about how we are trying to solve the artists’ problems in newsletters to my audience as an author and in a series of **articles on Sigle**: https://app.sigle.io/mirlo.id.blockstack . However, I am also confident that there will be many other opportunities to share Smartists, especially after the job I’ve been doing in Madrid as an evangelist which may open a few doors in the blockchain community here.

I am now building a complete portfolio with all the supporting materials we may need to present if addressing potential investors when the MVP is ready: decentralised business canvas, deck, business plan, video, etc.

**Comment by radicleart** [comment]
Nice project Georgina et al - best of luck!

**Comment by SmartMirlo** [comment]
> Nice project Georgina et al - best of luck!

Thank you, Mike!

**Comment by blocks8** [comment]
**Review Committee Feedback from 9/8/2020: We'd like more information on your proposal.**

Thank you for your application! You have a clear vision of an application that you can bring to the world and we're excited to see your plans.

The full build of the application is a large project, larger than what the grant amount could fund, so we were hoping you could break things down into smaller milestones. Here are two different directions we suggest for an updated proposal:

1. Scope a mock-up of your application as milestone 1 and scope the funding down for that size. By creating a UI mock-up it will help provide context around how Smartists will work within the application, how they can meet their needs, and be the first step towards building out a technical application. Through creation of the mock-up you can showcase: the actions users can do in the MVP; the user flow through the app; get feedback from potential users on the design; scope out what types of functionality is required (ability to upload images, video, etc.)? 

2. Develop the MVP of the Smartist smart contract first. You listed this as part C but work on this type of marketplace smart contract could be useful to the whole ecosystem as code that could be reused in different marketplaces. What would be the mock-up and functionality of this smart contract? Are you able to design the interaction as a milestone 1? Then you could apply for additional funding to develop out the smart contract if the design is clear. 

We're excited to see your app come to life on Blockstack. Although the grant program does not provide direct funding for independent apps, pieces of your application could be useful to the broader ecosystem and would add to a showcase of use cases. Designing what the new ownership of art could look like using the Stacks Blockchain is really interesting. 

If you would like to update your proposal with the above feedback, you may do so as a reply to this comment or edit the original application entry above.

**Comment by SmartMirlo** [comment]
Thank you very much, Brittany and the whole review Committee, for this very useful feedback.
I am now contacting the whole team to make a sounded decision about which of the two suggested directions is best for us at this moment.
I will comment as soon as I can.
Gratefully,

Georgina G.- Mauriño
"There is no end to learning." Robert Schumann

**Comment by SmartMirlo** [comment]
After talking with the team, and considering your suggestions, we agree and are ready to make a few changes to the application.

A UI mock-up for testing (suggestion #1) is already available completely for Phase 1 and needs to be worked for Phase 2 and Phase 3. We have actually been testing this prototype with potential end-users(artist community). Nevertheless, we would like to have the chance to show it to the committee and community for feedback and eventually improve it if necessary.  As suggested we would like to apply for this with 500 $ grants. Duration is 1 week. 

Also, we want to apply for another grant for finishing Phase 1 of Smartists, that includes "Upload the artists/art-users to the platform and allow them to set up their own studio", since the prototype is already ready and tested with artist community people - For this phase to be completed, we will integrate Blockstack Connect and Gaia + front-end react UI. For this grant requested grants are 3000 $. Duration - 8 to 10 weeks. 

For the Smartists smart contract (suggestion #2) further research is needed, and it is beyond our possibilities right now.

**Comment by SmartMirlo** [comment]
Unexpected changes in our team have come up, and we can no longer can commit to the milestones as explained in the application. In such circumstances, we can only apply to the $800 for the UI mock-up (2 to 4 weeks duration, including testing for feedback).

At this moment, we need to find a new developing partner, and any help in our search will be welcome.

I will edit the original application above accordingly.

I am sorry for the timing, and apologize for the inconveniences, but I only got confirmation of these news a few hours ago.

**Comment by RaffiSapire** [comment]
Hi @SmartMirlo thank you for the update, things happen, no worries. My name is Raffi and I'm working with the Foundation on the grants program. We'll need to sync up to discuss whether it makes sense to provide the grant for just the mockup. A couple questions that will help us decide, would it be low-fi or hi-fi, and what are you using, figma or another tool? Also, could you please share previous design work where you've created UI mockups, personas, etc?

**Comment by SmartMirlo** [comment]
Good morning, Raffi, and pleased to meet you.

I had a first prototype on AdobeXD which I was about to bring to Figma (as advised by our first developer) when in the Blockstack community I was recommended to use Webflow as it would be easier to have a version ready to test by actual potential users (I am addressing actual professional artists who are far from technical users). On Webflow I have now a first prototype/semi-functional mock-up which I have tested with four users and even showed confidentially in two private meetings in Kernel. I can privately share a link to the last version, after some improvements following the first tests, but It doesn’t include the marketplace/gallery (this part being a further stage for the mvp we are heading to).

I cannot show you recent works in this field because I have not been working in this for the last 2 years. Designing and building websites has been a side-necessity since 1999 more or less, but never a central part in my career. Nevertheless, I have managed to build and maintain on my own 4 of them, including one integrating e-commerce (this was at www.anotherlookatmusic.com but unfortunately the shop on the page was closed).

As for personas, I wrote the article ["A painter, a musician, a writer and and a teacher"](https://app.sigle.io/mirlo.id.blockstack/Cx6GzUYdurKV1QAzAdNiH) introducing some use-cases/personas based in real ‘self-managed artists’ I know, and I was going to write a similar one with some personas with 'art-users’ profiles.

I hope this answers most of your questions. Anyway, I am always open to talk and provide more information. Moreover, for any technical details Harini Rajan is better placed than me to answer any question as she has been supporting and mentoring me since January. She has actually witnessed all my commitment, and she also knows my technical limitations.

I don't know whether it makes sense to provide the grant for the mock-up. We actually considered this following the suggestion of the Stacks grants committee in the first answer to our application. What was actually in our roadmap and it is crucial for Smartists to become a DApp is to reach the mvp stage (BlockstackAuth and Storage).

I’ll be looking forward to your news.

Thank you,

Mirlo
"Cultivate your inner garden" Voltaire

**Comment by SmartMirlo** [comment]
Dear committee, 
>
After thinking it through, I cannot make a new mock-up just to follow the suggestion of the grant. It was my mistake to ask for it, and I am sorry for that.
>
I am very respectful for the time of all of us, so I think the correct thing to do is to step back and close this issue.
>
May my previous comment, answering Raffi, serve to know each other better.
>
Thank you.

**Comment by blocks8** [comment]
Hi @SmartMirlo, perhaps it's best to get on a call to talk through the best way to scope the proposal. We're excited about what you can showcase to the community. Could you send some time availability that overlaps with EST working hours to grants {at} stacks {dot} org email address. We can discuss further details to determine scope and grant fit.

**Comment by SmartMirlo** [comment]
I just sent the email. Thank you very much, @blocks8.

**Comment by SmartMirlo** [comment]
Just a quick followup, @blocks8 ! I wanted to share with the committee a video of the prototype so you can see. Is this possible? I remain open to talk as you suggested and I hope you received the email. Thank you!
