### ISSUE TITLE
On-chain accounting for Community Stacking Pools

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#91]
**Background**
Users of stacking pools have to trust the pool admin to manage their rewards correctly. Transparency can help to increase the trust. Therefore, income and expenses should be collected on-chain. This will create transparency as well as help to automate stacking pool operation in the future. Friedger Pool and other community stacking pools should benefit from it.

**Project Overview**
The project is about writing a smart contract and a web interface that allows users and pool admins to submit and view tx of stacking pools that payout rewards in stx as well as perform some pool admin tasks. Users and pool admins have the same privileges because the submitted data is verified on-chain.

The project will collaborate and use results from related work by the following projects:
* [decent delegate](https://github.com/hozzjss/cooperative-stacking)
* [stacks-open-oracle](https://github.com/psq/stacks-open-oracle)
* [bitcoin library](https://github.com/jcnelson/clarity-bitcoin)
* [pool tools](https://gitlab.com/riot.ai/clarity-pool-registry)
* [boomboxes](https://explorer.stacks.co/txid/ST314JC8J24YWNVAEJJHQXS5Q4S9DX1FW5Z9DK9NT.boomboxes-v1?chain=testnet)
* [xverse](https://explorer.stacks.co/txid/SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33.xverse-pool-v1?chain=mainnet)
* [stacking.club](https://github.com/stacksgov/Stacks-Grants/issues/88)

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
Components:
* The smart contract will allow users to 
    * submit btc tx for rewards received by the pool's btc reward address
    * submit stx tx for pool admin activities by the pools stx delegatee addresses
    * request stx rewards payouts proportionally to their delegated stacked stxs
    * delegate stx that are immediately locked by the users themselves
    * aggregate commit the pool 50 blocks before the start of the next cycle
* The web app will focus on functionality and reuse design and app architecture of Speed Spend/Pool Registry/Send Many
    * uses `connect` library for tx signing (requires users to use Stacks Wallet for Web)
    * show btc and stx total of the submitted txs
    * provide UI to call the smart contract functions
    * provide UI to allow the smart contract to manage the users' delegation
* User education
   * update pool.friedger.de and include information how to use the smart contract
   * answer questions via email, discord, twitter (and occasionally other social media)

The project will be successful when 
1. users participate in delegated stacking through the smart contract, 
2. the pool contract meets the static stacking minimum (min_increment_ustx) and can join Friedger Pool.
3. rewards are claimed and received by users through the smart contract

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 4000 STX 

M1: Smart contract for submitting btc and stx transactions + web app to view txs (1 week)

M2: Extended smart contract with pool operations + web app (2 week)

M3: Invite pool members to use the contract for the next cycle. (1 week)

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Friedger Müffke,  pool administrator of [Friedger Pool](https://pool.friedger.de),

I am looking for 
* community manager
* testers
* smart contract testers

**Risks**

The project depends on the successful submission of the Stacks Wallet for Web through the Hiro team. The project can only be successful once the wallet is published on the corresponding browser extension sites.

The verification of btc tx and stx tx is not yet well tested in production. It can be too difficult or impossible to do it on-chain. Therefore, M1 focus on this part of the proposal.

**Community and Supporting Materials**
This is continued work for Friedger Pool and related community stacking pools, following #52 and #84

**Comment by friedger** [comment]
Actually, submission and verification of stx transactions are not needed, because all relevant tx happens as part of the contract.

**Comment by RaffiSapire** [comment]
@friedger this is great, but we want to see you complete the existing grants before being approved for any additional grants.
