### ISSUE TITLE
On-chain Accounting for Stacking Pools (Take 2)

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grant-Launchpad#92]
**Background**
Users of stacking pools have to trust the pool admin to manage their rewards correctly. Transparency can help to increase the trust. Therefore, income and expenses should be collected on-chain. This will create transparency as well as help to automate stacking pool operation in the future. This is the next step to make stacking pools more autonomous. Friedger Pool and other community stacking pools should benefit from it.

**Project Overview**
The project is about writing a smart contract and a web interface that allows users and pool admins to submit and view tx of stacking pools that payout rewards in stx as well as perform some pool admin tasks. Users and pool admins have the same privileges because the submitted data is verified on-chain.

The project will collaborate and use results from related work by the following projects:
* [decent delegate](https://github.com/hozzjss/cooperative-stacking)
* [stacks-open-oracle](https://github.com/psq/stacks-open-oracle)
* [bitcoin library](https://github.com/jcnelson/clarity-bitcoin)
* [pool tools](https://gitlab.com/riot.ai/clarity-pool-registry)
* [boomboxes](https://explorer.stacks.co/txid/ST314JC8J24YWNVAEJJHQXS5Q4S9DX1FW5Z9DK9NT.boomboxes-v1?chain=testnet)
* [xverse](https://explorer.stacks.co/txid/SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33.xverse-pool-v1?chain=mainnet)
* [stacking.club](https://github.com/stacksgov/Stacks-Grants/issues/88)

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
Components:
* There will be two smart contracts
    * Auditing contract
        * submit btc tx for rewards received by the pool's btc reward address, the corresponding stx value of the reward will be determined by an oracle, the value is stored both in stx and btc.
        * submit btc tx for btc withdraw from pool's btc reward address, the corresponding stx value of the withdraw will be determined by an oracle, the value is stored both in stx and btc.
    * Admin contract
        * delegate stx that are immediately locked by the users themselves
        * aggregate commit the pool 50 blocks before the start of the next cycle
        * request stx rewards payouts proportionally to their delegated stacked stxs, the total reward amount is retrieved from the auditing contract
* The web app will focus on functionality and reuse design and app architecture of Speed Spend/Pool Registry/Send Many
    * uses `connect` library for tx signing (requires users to use Stacks Wallet for Web)
    * show btc and stx of the submitted txs
    * provide UI to call the smart contract functions
    * provide UI to allow the smart contract to manage the users' delegation
* User education
   * update pool.friedger.de and include information how to use the smart contract
   * answer questions via email, discord, twitter (and occasionally other social media)
* Test on Testnet 
* Operate Friedger Pool until it runs autonomous. This includes customer services, maintaining the website, trading BTC/STX, accounting, legal advice.

The project will be successful when 
1. users participate in delegated stacking through the smart contract in cycle #11.
2. the pool contract meets the static stacking minimum (min_increment_ustx) and can join Friedger Pool's btc reward address.
3. rewards are claimed and received by users through the smart contract.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 8000 STX 

M1: Smart contract for submitting btc transactions + web app to submit and view txs (1 week)
1000 STX development clarity + web
1000 STX operating costs Friedger Pool

M2: Extended smart contract with pool operations + web app + testnet test (2 week)
1500 STX development clarity + web
500 STX community management for testing
2000 STX operating costs Friedger Pool

M3: Invite pool members to use the contract for the next cycle. (1 week)
1000 STX user education
1000 STX operating costs Friedger Pool

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Friedger Müffke,  pool administrator of [Friedger Pool](https://pool.friedger.de),

I have one open grant (https://github.com/stacksgov/Stacks-Grants/issues/84) that only requires a bit of communication with other pool admins over the next weeks.

I am looking for 
* community manager
* testers
* smart contract testers

**Risks**

The project depends on the successful submission of the Stacks Wallet for Web through the Hiro team. The project can only be successful once the wallet is published on the corresponding browser extension sites.

The verification of btc tx is not yet well tested in production. It can be too difficult or impossible to do it on-chain. Therefore, M1 focus on this part of the proposal.

**Community and Supporting Materials**
This is continued work for Friedger Pool and related community stacking pools, following #52 and #84

**Comment by jcnelson** [comment]
Hey @friedger,

I see you're listing the clarity-bitcoin library as a key component.  I haven't had time yet to determine how truly expensive it is to parse and validate Bitcoin transactions on-chain with that code -- the frequent use of `index-of` makes it expensive.  If you end up using it for validating Merkle proofs, you might want to add a method that takes a `tuple` representation of a transaction, and generates its txid by _serializing_ it piecemeal.  You could call the existing parsing code as a read-only method from a Web client to get a `tuple` representation, serialize that representation with `stacks.js`, and then use this new method to (1) derive the txid, and (2) verify that it was included in a Bitcoin block.

The `develop` branch of `stacks-blockchain` contains a version of `clarity-cli` that will output the runtime costs for this and other contracts you use, in order to help you determine how expensive it will be for the audit contract to run.

**Comment by joberding** [comment]
+1 for an accounting feature incorp in the webapp so individual users can automatically track their transactions, base value and rewards across participating pools for taxation purposes. I realize it is beyond the scope of current proposal but thought I would throw it out there.

**Comment by jennymith** [comment]
Hi @friedger, this has been approved. However, please keep us updated on the status of pool admin registrations for #84. If possible, could you please set a deadline within the next couple of weeks to get everyone registered so that we can close out that grant? Thanks! cc: @RaffiSapire for the contract--thank you!

**Comment by friedger** [comment]
This is closed in favor of #121
